Endorphin: DownloadModel Class Reference
DownloadModel Class Reference
#include <downloadmanager.h>
Public Member Functions
DownloadModel (DownloadManager *downloadManager, QObject *parent=nullptr)
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
Qt::ItemFlags flags (const QModelIndex &index) const
QMimeData * mimeData (const QModelIndexList &indexes) const
Private Attributes
DownloadManager * m_downloadManager
Friends
class DownloadManager
Detailed Description
Definition at line 197 of file downloadmanager.h.
Constructor & Destructor Documentation
DownloadModel()
DownloadModel::DownloadModel (DownloadManager * downloadManager, QObject * parent = nullptr)
Definition at line 818 of file downloadmanager.cpp.
     : QAbstractListModel(parent)
     , m_downloadManager(downloadManager)
 {
 }
Member Function Documentation
data()
QVariant DownloadModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Definition at line 824 of file downloadmanager.cpp.
 {
     if (index.row() < 0 || index.row() >= rowCount(index.parent()))
         return QVariant();
     if (role == Qt::ToolTipRole)
         if (!m_downloadManager->m_downloads.at(index.row())->downloadedSuccessfully())
             return m_downloadManager->m_downloads.at(index.row())->downloadInfoLabel->text();
     return QVariant();
 }
References m_downloadManager, DownloadManager::m_downloads, and rowCount().
flags()
Qt::ItemFlags DownloadModel::flags (const QModelIndex & index) const
Definition at line 858 of file downloadmanager.cpp.
 {
     if (index.row() < 0 || index.row() >= rowCount(index.parent()))
         return 0;
     Qt::ItemFlags defaultFlags = QAbstractItemModel::flags(index);
     DownloadItem *item = m_downloadManager->m_downloads.at(index.row());
     if (item->downloadedSuccessfully())
         return defaultFlags | Qt::ItemIsDragEnabled;
     return defaultFlags;
 }
References DownloadItem::downloadedSuccessfully(), m_downloadManager, DownloadManager::m_downloads, and rowCount().
mimeData()
QMimeData * DownloadModel::mimeData (const QModelIndexList & indexes) const
Definition at line 872 of file downloadmanager.cpp.
 {
     QMimeData *mimeData = new QMimeData();
     QList<QUrl> urls;
     foreach (const QModelIndex &index, indexes) {
         if (!index.isValid())
             continue;
         DownloadItem *item = m_downloadManager->m_downloads.at(index.row());
         urls.append(QUrl::fromLocalFile(QFileInfo(item->m_output).absoluteFilePath()));
     }
     mimeData->setUrls(urls);
     return mimeData;
 }
References m_downloadManager, DownloadManager::m_downloads, and DownloadItem::m_output.
removeRows()
bool DownloadModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex())
Definition at line 839 of file downloadmanager.cpp.
 {
     if (parent.isValid())
         return false;
     int lastRow = row + count - 1;
     for (int i = lastRow; i >= row; --i) {
         if (m_downloadManager->m_downloads.at(i)->downloadedSuccessfully()
                 || m_downloadManager->m_downloads.at(i)->tryAgainButton->isEnabled()) {
             beginRemoveRows(parent, i, i);
             m_downloadManager->m_downloads.takeAt(i)->deleteLater();
             endRemoveRows();
         }
     }
     m_downloadManager->m_autoSaver->changeOccurred();
     m_downloadManager->updateItemCount();
     return true;
 }
References AutoSaver::changeOccurred(), DownloadManager::m_autoSaver, m_downloadManager, DownloadManager::m_downloads, and DownloadManager::updateItemCount().
Referenced by DownloadManager::cleanup().
rowCount()
int DownloadModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 834 of file downloadmanager.cpp.
 {
     return (parent.isValid()) ? 0 : m_downloadManager->m_downloads.count();
 }
References m_downloadManager, and DownloadManager::m_downloads.
Referenced by data(), and flags().
Friends And Related Function Documentation
DownloadManager
friend class DownloadManager friend
Definition at line 199 of file downloadmanager.h.
Member Data Documentation
m_downloadManager
DownloadManager* DownloadModel::m_downloadManager private
Definition at line 211 of file downloadmanager.h.
Referenced by data(), flags(), mimeData(), removeRows(), and rowCount().
The documentation for this class was generated from the following files:
src/downloadmanager.h
src/downloadmanager.cpp