Endorphin: BookmarksDialog Class Reference
BookmarksDialog Class Reference
#include <bookmarksdialog.h>
Signals
void openUrl (const QUrl &url, TabWidget::OpenUrlIn tab, const QString &title)
Public Member Functions
BookmarksDialog (QWidget *parent=nullptr, BookmarksManager *manager=nullptr)
~BookmarksDialog ()
Private Slots
void customContextMenuRequested (const QPoint &pos)
void openBookmark (TabWidget::OpenUrlIn tab)
void openBookmark ()
void openInNewTab ()
void openInCurrentTab ()
void editName ()
void editAddress ()
void newFolder ()
Private Member Functions
void expandNodes (BookmarkNode *node)
bool saveExpandedNodes (const QModelIndex &parent)
Private Attributes
BookmarksManager * m_bookmarksManager
BookmarksModel * m_bookmarksModel
TreeSortFilterProxyModel * m_proxyModel
Detailed Description
Definition at line 78 of file bookmarksdialog.h.
Constructor & Destructor Documentation
BookmarksDialog()
BookmarksDialog::BookmarksDialog (QWidget * parent = nullptr, BookmarksManager * manager = nullptr)
Definition at line 74 of file bookmarksdialog.cpp.
     : QDialog(parent)
     , m_bookmarksManager(nullptr)
     , m_bookmarksModel(nullptr)
     , m_proxyModel(nullptr)
 {
     m_bookmarksManager = manager;
     if (!m_bookmarksManager)
         m_bookmarksManager = BrowserApplication::bookmarksManager();
     setupUi(this);
     tree->setUniformRowHeights(true);
     tree->setSelectionBehavior(QAbstractItemView::SelectRows);
     tree->setSelectionMode(QAbstractItemView::ExtendedSelection);
     tree->setTextElideMode(Qt::ElideMiddle);
     m_bookmarksModel = m_bookmarksManager->bookmarksModel();
     m_proxyModel = new TreeSortFilterProxyModel(this);
     m_proxyModel->setFilterKeyColumn(-1);
     connect(search, SIGNAL(textChanged(QString)),
             m_proxyModel, SLOT(setFilterFixedString(QString)));
     connect(removeButton, SIGNAL(clicked()), tree, SLOT(removeSelected()));
     m_proxyModel->setSourceModel(m_bookmarksModel);
     tree->setModel(m_proxyModel);
     tree->setDragDropMode(QAbstractItemView::InternalMove);
     tree->setExpanded(m_proxyModel->index(0, 0), true);
     tree->setAlternatingRowColors(true);
     QFontMetrics fm(font());
     int header = fm.horizontalAdvance(QLatin1Char('m')) * 40;
     tree->header()->resizeSection(0, header);
     tree->header()->setStretchLastSection(true);
     connect(tree, SIGNAL(activated(const QModelIndex&)),
             this, SLOT(openBookmark()));
     tree->setContextMenuPolicy(Qt::CustomContextMenu);
     connect(tree, SIGNAL(customContextMenuRequested(const QPoint &)),
             this, SLOT(customContextMenuRequested(const QPoint &)));
     connect(addFolderButton, SIGNAL(clicked()),
             this, SLOT(newFolder()));
     expandNodes(m_bookmarksManager->bookmarks());
 }
References BookmarksManager::bookmarks(), BrowserApplication::bookmarksManager(), BookmarksManager::bookmarksModel(), customContextMenuRequested(), expandNodes(), m_bookmarksManager, m_bookmarksModel, m_proxyModel, newFolder(), and openBookmark().
~BookmarksDialog()
BookmarksDialog::~BookmarksDialog ()
Definition at line 114 of file bookmarksdialog.cpp.
 {
     if (saveExpandedNodes(tree->rootIndex()))
         m_bookmarksManager->changeExpanded();
 }
References BookmarksManager::changeExpanded(), m_bookmarksManager, and saveExpandedNodes().
Member Function Documentation
customContextMenuRequested
void BookmarksDialog::customContextMenuRequested (const QPoint & pos) private slot
Definition at line 152 of file bookmarksdialog.cpp.
 {
     QMenu menu;
     QModelIndex index = tree->indexAt(pos);
     index = index.sibling(index.row(), 0);
     QModelIndex sourceIndex = m_proxyModel->mapToSource(index);
     const BookmarkNode *node = m_bookmarksModel->node(sourceIndex);
     if (index.isValid() && node->type() != BookmarkNode::Folder) {
         menu.addAction(tr("Open"), this, SLOT(openInCurrentTab()));
         menu.addAction(tr("Open in New Tab"), this, SLOT(openInNewTab()));
         menu.addSeparator();
     }
     menu.addSeparator();
     QAction *renameAction = menu.addAction(tr("Edit Name"), this, SLOT(editName()));
     renameAction->setEnabled(index.flags() & Qt::ItemIsEditable);
     if (index.isValid() && node->type() != BookmarkNode::Folder) {
         menu.addAction(tr("Edit Address"), this, SLOT(editAddress()));
     }
     menu.addSeparator();
     QAction *deleteAction = menu.addAction(tr("Delete"), tree, SLOT(removeSelected()));
     deleteAction->setEnabled(index.flags() & Qt::ItemIsDragEnabled);
     menu.exec(QCursor::pos());
 }
References editAddress(), editName(), BookmarkNode::Folder, m_bookmarksModel, m_proxyModel, BookmarksModel::node(), openInCurrentTab(), openInNewTab(), and BookmarkNode::type().
Referenced by BookmarksDialog().
editAddress
void BookmarksDialog::editAddress () private slot
Definition at line 213 of file bookmarksdialog.cpp.
 {
     QModelIndex idx = tree->currentIndex();
     idx = idx.sibling(idx.row(), 1);
     tree->edit(idx);
 }
Referenced by customContextMenuRequested().
editName
void BookmarksDialog::editName () private slot
Definition at line 206 of file bookmarksdialog.cpp.
 {
     QModelIndex idx = tree->currentIndex();
     idx = idx.sibling(idx.row(), 0);
     tree->edit(idx);
 }
Referenced by customContextMenuRequested().
expandNodes()
void BookmarksDialog::expandNodes (BookmarkNode * node) private
Definition at line 139 of file bookmarksdialog.cpp.
 {
     for (int i = 0; i < node->children().count(); ++i) {
         BookmarkNode *childNode = node->children()[i];
         if (childNode->expanded) {
             QModelIndex idx = m_bookmarksModel->index(childNode);
             idx = m_proxyModel->mapFromSource(idx);
             tree->setExpanded(idx, true);
             expandNodes(childNode);
         }
     }
 }
References BookmarkNode::children(), BookmarkNode::expanded, BookmarksModel::index(), m_bookmarksModel, and m_proxyModel.
Referenced by BookmarksDialog().
newFolder
void BookmarksDialog::newFolder () private slot
Definition at line 220 of file bookmarksdialog.cpp.
 {
     QModelIndex currentIndex = tree->currentIndex();
     QModelIndex idx = currentIndex;
     QModelIndex sourceIndex = m_proxyModel->mapToSource(idx);
     const BookmarkNode *sourceNode = m_bookmarksModel->node(sourceIndex);
     int row = -1; // default: append new folder as last item in selected folder
     if (sourceNode && sourceNode->type() != BookmarkNode::Folder) {
         // if selected item is not a folder, add new folder to parent folder,
         // but direcly below the selected item
         idx = idx.parent();
         row = currentIndex.row() + 1;
     }
     if (!idx.isValid())
         idx = m_proxyModel->index(1, 0); // Select Bookmarks menu as default
     idx = m_proxyModel->mapToSource(idx);
     BookmarkNode *parent = m_bookmarksManager->bookmarksModel()->node(idx);
     BookmarkNode *node = new BookmarkNode(BookmarkNode::Folder);
     node->title = tr("New Folder");
     m_bookmarksManager->addBookmark(parent, node, row);
 }
References BookmarksManager::addBookmark(), BookmarksManager::bookmarksModel(), BookmarkNode::Folder, m_bookmarksManager, m_bookmarksModel, m_proxyModel, BookmarksModel::node(), BookmarkNode::parent(), BookmarkNode::title, and BookmarkNode::type().
Referenced by BookmarksDialog().
openBookmark [1/2]
void BookmarksDialog::openBookmark () private slot
Definition at line 189 of file bookmarksdialog.cpp.
 {
     BrowserApplication::instance()->setEventMouseButtons(qApp->mouseButtons());
     BrowserApplication::instance()->setEventKeyboardModifiers(qApp->keyboardModifiers());
     openBookmark(TabWidget::UserOrCurrent);
 }
References BrowserApplication::instance(), BrowserApplication::setEventKeyboardModifiers(), BrowserApplication::setEventMouseButtons(), and TabWidget::UserOrCurrent.
Referenced by BookmarksDialog(), openInCurrentTab(), and openInNewTab().
openBookmark [2/2]
void BookmarksDialog::openBookmark (TabWidget::OpenUrlIn tab) private slot
Definition at line 176 of file bookmarksdialog.cpp.
 {
     QModelIndex index = tree->currentIndex();
     QModelIndex sourceIndex = m_proxyModel->mapToSource(index);
     const BookmarkNode *node = m_bookmarksModel->node(sourceIndex);
     if (!index.parent().isValid() || !node || node->type() == BookmarkNode::Folder)
         return;
     emit openUrl(
         index.sibling(index.row(), 1).data(BookmarksModel::UrlRole).toUrl(),
         tab,
         index.sibling(index.row(), 0).data(Qt::DisplayRole).toString());
 }
References BookmarkNode::Folder, m_bookmarksModel, m_proxyModel, BookmarksModel::node(), openUrl(), BookmarkNode::type(), and BookmarksModel::UrlRole.
openInCurrentTab
void BookmarksDialog::openInCurrentTab () private slot
Definition at line 196 of file bookmarksdialog.cpp.
 {
     openBookmark(TabWidget::CurrentTab);
 }
References TabWidget::CurrentTab, and openBookmark().
Referenced by customContextMenuRequested().
openInNewTab
void BookmarksDialog::openInNewTab () private slot
Definition at line 201 of file bookmarksdialog.cpp.
 {
     openBookmark(TabWidget::NewTab);
 }
References TabWidget::NewTab, and openBookmark().
Referenced by customContextMenuRequested().
openUrl
void BookmarksDialog::openUrl (const QUrl & url, TabWidget::OpenUrlIn tab, const QString & title) signal
Referenced by openBookmark().
saveExpandedNodes()
bool BookmarksDialog::saveExpandedNodes (const QModelIndex & parent) private
Definition at line 120 of file bookmarksdialog.cpp.
 {
     bool changed = false;
     for (int i = 0; i < m_proxyModel->rowCount(parent); ++i) {
         QModelIndex child = m_proxyModel->index(i, 0, parent);
         QModelIndex sourceIndex = m_proxyModel->mapToSource(child);
         BookmarkNode *childNode = m_bookmarksModel->node(sourceIndex);
         bool wasExpanded = childNode->expanded;
         if (tree->isExpanded(child)) {
             childNode->expanded = true;
             changed |= saveExpandedNodes(child);
         } else {
             childNode->expanded = false;
         }
         changed |= (wasExpanded != childNode->expanded);
     }
     return changed;
 }
References BookmarkNode::expanded, m_bookmarksModel, m_proxyModel, and BookmarksModel::node().
Referenced by ~BookmarksDialog().
Member Data Documentation
m_bookmarksManager
BookmarksManager* BookmarksDialog::m_bookmarksManager private
Definition at line 103 of file bookmarksdialog.h.
Referenced by BookmarksDialog(), newFolder(), and ~BookmarksDialog().
m_bookmarksModel
BookmarksModel* BookmarksDialog::m_bookmarksModel private
Definition at line 104 of file bookmarksdialog.h.
Referenced by BookmarksDialog(), customContextMenuRequested(), expandNodes(), newFolder(), openBookmark(), and saveExpandedNodes().
m_proxyModel
TreeSortFilterProxyModel* BookmarksDialog::m_proxyModel private
Definition at line 105 of file bookmarksdialog.h.
Referenced by BookmarksDialog(), customContextMenuRequested(), expandNodes(), newFolder(), openBookmark(), and saveExpandedNodes().
The documentation for this class was generated from the following files:
src/bookmarks/bookmarksdialog.h
src/bookmarks/bookmarksdialog.cpp