Endorphin: HistoryTreeModel Class Reference
HistoryTreeModel Class Reference
#include <history.h>
Public Member Functions
HistoryTreeModel (QAbstractItemModel *sourceModel, QObject *parent=nullptr)
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
int columnCount (const QModelIndex &parent) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
QModelIndex mapFromSource (const QModelIndex &sourceIndex) const
QModelIndex mapToSource (const QModelIndex &proxyIndex) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &index=QModelIndex()) const
bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Qt::ItemFlags flags (const QModelIndex &index) const
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
void setSourceModel (QAbstractItemModel *sourceModel)
Private Slots
void sourceReset ()
void sourceRowsInserted (const QModelIndex &parent, int start, int end)
void sourceRowsRemoved (const QModelIndex &parent, int start, int end)
Private Member Functions
int sourceDateRow (int row) const
Private Attributes
QList< int > m_sourceRowCache
bool removingDown
Detailed Description
Definition at line 244 of file history.h.
Constructor & Destructor Documentation
HistoryTreeModel()
HistoryTreeModel::HistoryTreeModel (QAbstractItemModel * sourceModel, QObject * parent = nullptr)
Definition at line 732 of file history.cpp.
     : QAbstractProxyModel(parent)
     , removingDown(false)
 {
     setSourceModel(sourceModel);
 }
References setSourceModel().
Member Function Documentation
columnCount()
int HistoryTreeModel::columnCount (const QModelIndex & parent) const
Definition at line 780 of file history.cpp.
 {
     return sourceModel()->columnCount(mapToSource(parent));
 }
References mapToSource(), and parent().
Referenced by HistoryMenuModel::columnCount(), and index().
data()
QVariant HistoryTreeModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Definition at line 744 of file history.cpp.
 {
     switch (role) {
     case Qt::DisplayRole:
     case Qt::EditRole: {
         int start = index.internalId();
         if (start == 0) {
             int offset = sourceDateRow(index.row());
             if (index.column() == 0) {
                 QModelIndex idx = sourceModel()->index(offset, 0);
                 QDate date = idx.data(HistoryModel::DateRole).toDate();
                 if (date == QDate::currentDate())
                     return tr("Earlier Today");
                 return date.toString(QLatin1String("dddd, MMMM d, yyyy"));
             }
             if (index.column() == 1) {
                 return tr("%n item(s)", "", rowCount(index.sibling(index.row(), 0)));
             }
         }
     }
     case Qt::DecorationRole: {
         if (index.column() == 0 && !index.parent().isValid())
             return QIcon(QLatin1String(":graphics/history.png"));
     }
     case HistoryModel::DateRole: {
         if (index.column() == 0 && index.internalId() == 0) {
             int offset = sourceDateRow(index.row());
             QModelIndex idx = sourceModel()->index(offset, 0);
             return idx.data(HistoryModel::DateRole);
         }
     }
     }
     return QAbstractProxyModel::data(index, role);
 }
References HistoryModel::DateRole, index(), rowCount(), and sourceDateRow().
flags()
Qt::ItemFlags HistoryTreeModel::flags (const QModelIndex & index) const
Definition at line 872 of file history.cpp.
 {
     if (!index.isValid())
         return Qt::NoItemFlags;
     return Qt::ItemIsSelectable | Qt::ItemIsEnabled | Qt::ItemIsDragEnabled;
 }
References index().
hasChildren()
bool HistoryTreeModel::hasChildren (const QModelIndex & parent = QModelIndex()) const
Definition at line 864 of file history.cpp.
 {
     QModelIndex grandparent = parent.parent();
     if (!grandparent.isValid())
         return true;
     return false;
 }
References parent().
headerData()
QVariant HistoryTreeModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Definition at line 739 of file history.cpp.
 {
     return sourceModel()->headerData(section, orientation, role);
 }
index()
QModelIndex HistoryTreeModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
Definition at line 844 of file history.cpp.
 {
     if (row < 0
             || column < 0 || column >= columnCount(parent)
             || parent.column() > 0)
         return QModelIndex();
     if (!parent.isValid())
         return createIndex(row, column, (void*) nullptr);
     return createIndex(row, column, parent.row() + 1);
 }
References columnCount(), and parent().
Referenced by HistoryMenuModel::bumpedRows(), data(), flags(), HistoryMenuModel::index(), HistoryMenuModel::mapToSource(), HistoryMenuModel::parent(), parent(), removeRows(), sourceRowsInserted(), and sourceRowsRemoved().
mapFromSource()
QModelIndex HistoryTreeModel::mapFromSource (const QModelIndex & sourceIndex) const
Definition at line 936 of file history.cpp.
 {
     if (!sourceIndex.isValid())
         return QModelIndex();
     if (m_sourceRowCache.isEmpty())
         rowCount(QModelIndex());
     QList<int>::iterator it;
     it = std::lower_bound(m_sourceRowCache.begin(), m_sourceRowCache.end(), sourceIndex.row());
     if (*it != sourceIndex.row())
         --it;
     int dateRow = qMax(0, it - m_sourceRowCache.begin());
     int row = sourceIndex.row() - m_sourceRowCache.at(dateRow);
     return createIndex(row, sourceIndex.column(), dateRow + 1);
 }
References m_sourceRowCache, and rowCount().
Referenced by HistoryMenuModel::mapToSource(), HistoryMenuModel::parent(), and sourceRowsInserted().
mapToSource()
QModelIndex HistoryTreeModel::mapToSource (const QModelIndex & proxyIndex) const
Definition at line 835 of file history.cpp.
 {
     int offset = proxyIndex.internalId();
     if (offset == 0)
         return QModelIndex();
     int startDateRow = sourceDateRow(offset - 1);
     return sourceModel()->index(startDateRow + proxyIndex.row(), proxyIndex.column());
 }
References sourceDateRow().
Referenced by columnCount(), HistoryMenuModel::index(), HistoryMenuModel::mapFromSource(), and HistoryMenuModel::parent().
parent()
QModelIndex HistoryTreeModel::parent (const QModelIndex & index = QModelIndex()) const
Definition at line 856 of file history.cpp.
 {
     int offset = index.internalId();
     if (offset == 0 || !index.isValid())
         return QModelIndex();
     return createIndex(offset - 1, 0, (void*) nullptr);
 }
References index().
Referenced by columnCount(), hasChildren(), index(), removeRows(), rowCount(), sourceRowsInserted(), and sourceRowsRemoved().
removeRows()
bool HistoryTreeModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex())
Definition at line 953 of file history.cpp.
 {
     if (row < 0 || count <= 0 || row + count > rowCount(parent))
         return false;
     removingDown = true;
     if (parent.isValid() && rowCount(parent) == count - row)
         beginRemoveRows(QModelIndex(), parent.row(), parent.row());
     else
         beginRemoveRows(parent, row, row + count - 1);
     if (parent.isValid()) {
         // removing pages
         int offset = sourceDateRow(parent.row());
         return sourceModel()->removeRows(offset + row, count);
     } else {
         // removing whole dates
         for (int i = row + count - 1; i >= row; --i) {
             QModelIndex dateParent = index(i, 0);
             int offset = sourceDateRow(dateParent.row());
             if (!sourceModel()->removeRows(offset, rowCount(dateParent)))
                 return false;
         }
     }
     return true;
 }
References index(), parent(), removingDown, rowCount(), and sourceDateRow().
rowCount()
int HistoryTreeModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 785 of file history.cpp.
 {
     if (parent.internalId() != 0
             || parent.column() > 0
             || !sourceModel())
         return 0;
     // row count OF dates
     if (!parent.isValid()) {
         if (!m_sourceRowCache.isEmpty())
             return m_sourceRowCache.count();
         QDate currentDate;
         int rows = 0;
         int totalRows = sourceModel()->rowCount();
         for (int i = 0; i < totalRows; ++i) {
             QDate rowDate = sourceModel()->index(i, 0).data(HistoryModel::DateRole).toDate();
             if (rowDate != currentDate) {
                 m_sourceRowCache.append(i);
                 currentDate = rowDate;
                 ++rows;
             }
         }
         Q_ASSERT(m_sourceRowCache.count() == rows);
         return rows;
     }
     // row count FOR a date
     int start = sourceDateRow(parent.row());
     int end = sourceDateRow(parent.row() + 1);
     return (end - start);
 }
References HistoryModel::DateRole, m_sourceRowCache, parent(), and sourceDateRow().
Referenced by HistoryMenuModel::bumpedRows(), data(), mapFromSource(), removeRows(), sourceDateRow(), sourceRowsInserted(), and sourceRowsRemoved().
setSourceModel()
void HistoryTreeModel::setSourceModel (QAbstractItemModel * sourceModel)
Definition at line 879 of file history.cpp.
 {
     beginResetModel();
     if (sourceModel()) {
         disconnect(sourceModel(), SIGNAL(modelReset()), this, SLOT(sourceReset()));
         disconnect(sourceModel(), SIGNAL(layoutChanged()), this, SLOT(sourceReset()));
         disconnect(sourceModel(), SIGNAL(rowsInserted(const QModelIndex &, int, int)),
                    this, SLOT(sourceRowsInserted(const QModelIndex &, int, int)));
         disconnect(sourceModel(), SIGNAL(rowsRemoved(const QModelIndex &, int, int)),
                    this, SLOT(sourceRowsRemoved(const QModelIndex &, int, int)));
     }
     QAbstractProxyModel::setSourceModel(newSourceModel);
     if (newSourceModel) {
         connect(sourceModel(), SIGNAL(modelReset()), this, SLOT(sourceReset()));
         connect(sourceModel(), SIGNAL(layoutChanged()), this, SLOT(sourceReset()));
         connect(sourceModel(), SIGNAL(rowsInserted(const QModelIndex &, int, int)),
                 this, SLOT(sourceRowsInserted(const QModelIndex &, int, int)));
         connect(sourceModel(), SIGNAL(rowsRemoved(const QModelIndex &, int, int)),
                 this, SLOT(sourceRowsRemoved(const QModelIndex &, int, int)));
     }
     endResetModel();
 }
References sourceReset(), sourceRowsInserted(), and sourceRowsRemoved().
Referenced by HistoryTreeModel().
sourceDateRow()
int HistoryTreeModel::sourceDateRow (int row) const private
Definition at line 819 of file history.cpp.
 {
     if (row <= 0)
         return 0;
     if (m_sourceRowCache.isEmpty())
         rowCount(QModelIndex());
     if (row >= m_sourceRowCache.count()) {
         if (!sourceModel())
             return 0;
         return sourceModel()->rowCount();
     }
     return m_sourceRowCache.at(row);
 }
References m_sourceRowCache, and rowCount().
Referenced by data(), mapToSource(), removeRows(), and rowCount().
sourceReset
void HistoryTreeModel::sourceReset () private slot
Definition at line 906 of file history.cpp.
 {
     beginResetModel();
     m_sourceRowCache.clear();
     endResetModel();
 }
References m_sourceRowCache.
Referenced by setSourceModel().
sourceRowsInserted
void HistoryTreeModel::sourceRowsInserted (const QModelIndex & parent, int start, int end) private slot
Definition at line 913 of file history.cpp.
 {
     Q_UNUSED(parent); // Avoid warnings when compiling release
     Q_ASSERT(!parent.isValid());
     if (start != 0 || start != end) {
         beginResetModel();
         m_sourceRowCache.clear();
         endResetModel();
         return;
     }
     m_sourceRowCache.clear();
     QModelIndex treeIndex = mapFromSource(sourceModel()->index(start, 0));
     QModelIndex treeParent = treeIndex.parent();
     if (rowCount(treeParent) == 1) {
         beginInsertRows(QModelIndex(), 0, 0);
         endInsertRows();
     } else {
         beginInsertRows(treeParent, treeIndex.row(), treeIndex.row());
         endInsertRows();
     }
 }
References index(), m_sourceRowCache, mapFromSource(), parent(), and rowCount().
Referenced by setSourceModel().
sourceRowsRemoved
void HistoryTreeModel::sourceRowsRemoved (const QModelIndex & parent, int start, int end) private slot
Definition at line 979 of file history.cpp.
 {
     if (!removingDown) {
         beginResetModel();
         m_sourceRowCache.clear();
         endResetModel();
         return;
     }
     Q_UNUSED(parent); // Avoid warnings when compiling release
     Q_ASSERT(!parent.isValid());
     if (!m_sourceRowCache.isEmpty())
         for (int i = end; i >= start;) {
             QList<int>::iterator it;
             it = std::lower_bound(m_sourceRowCache.begin(), m_sourceRowCache.end(), i);
             if (*it != i)
                 --it;
             int row = qMax(0, it - m_sourceRowCache.begin());
             int offset = m_sourceRowCache[row];
             QModelIndex dateParent = index(row, 0);
             // If we can remove all the rows in the date do that and skip over them
             int rc = rowCount(dateParent);
             if (i - rc + 1 == offset && start <= i - rc + 1) {
                 m_sourceRowCache.removeAt(row);
                 i -= rc + 1;
             } else {
                 ++row;
                 --i;
             }
             for (int j = row; j < m_sourceRowCache.count(); ++j)
                 --m_sourceRowCache[j];
         }
     if (removingDown) {
         endRemoveRows();
         removingDown = false;
     }
 }
References index(), m_sourceRowCache, parent(), removingDown, and rowCount().
Referenced by setSourceModel().
Member Data Documentation
m_sourceRowCache
QList<int> HistoryTreeModel::m_sourceRowCache mutable private
Definition at line 271 of file history.h.
Referenced by mapFromSource(), rowCount(), sourceDateRow(), sourceReset(), sourceRowsInserted(), and sourceRowsRemoved().
removingDown
bool HistoryTreeModel::removingDown private
Definition at line 272 of file history.h.
Referenced by removeRows(), and sourceRowsRemoved().
The documentation for this class was generated from the following files:
src/history/history.h
src/history/history.cpp