Endorphin: ModelToolBar Class Reference
ModelToolBar Class Reference
#include <modeltoolbar.h>
Signals
void activated (const QModelIndex &index)
Public Member Functions
ModelToolBar (QWidget *parent=nullptr)
ModelToolBar (const QString &title, QWidget *parent=nullptr)
void setModel (QAbstractItemModel *model)
QAbstractItemModel * model () const
void setRootIndex (const QModelIndex &index)
QModelIndex rootIndex () const
Static Public Member Functions
static QModelIndex index (QAction *action)
Protected Slots
void build ()
Protected Member Functions
virtual ModelMenu * createMenu ()
bool eventFilter (QObject *object, QEvent *event)
void hideEvent (QHideEvent *event)
void showEvent (QShowEvent *event)
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
void mouseMoveEvent (QMouseEvent *event)
Private Attributes
QAbstractItemModel * m_model
QPersistentModelIndex m_rootIndex
QPoint m_dragStartPos
Detailed Description
Definition at line 31 of file modeltoolbar.h.
Constructor & Destructor Documentation
ModelToolBar() [1/2]
ModelToolBar::ModelToolBar (QWidget * parent = nullptr)
Definition at line 34 of file modeltoolbar.cpp.
     : QToolBar(parent)
     , m_model(nullptr)
 {
     if (isVisible())
         build();
     setAcceptDrops(true);
 }
References build().
ModelToolBar() [2/2]
ModelToolBar::ModelToolBar (const QString & title, QWidget * parent = nullptr)
Definition at line 44 of file modeltoolbar.cpp.
     : QToolBar(title, parent)
     , m_model(nullptr)
 {
     if (isVisible())
         build();
     setAcceptDrops(true);
 }
References build().
Member Function Documentation
activated
void ModelToolBar::activated (const QModelIndex & index) signal
Referenced by BookmarksToolBar::BookmarksToolBar(), and eventFilter().
build
void ModelToolBar::build () protected slot
Definition at line 96 of file modeltoolbar.cpp.
 {
     Q_ASSERT(m_model);
     clear();
     for (int i = 0; i < m_model->rowCount(m_rootIndex); ++i) {
         QModelIndex index = m_model->index(i, 0, m_rootIndex);
         QVariant variant;
         variant.setValue(index);
         QString title = index.data(Qt::DisplayRole).toString();
         QIcon icon = qvariant_cast<QIcon>(index.data(Qt::DecorationRole));
         bool hasChildren = m_model->hasChildren(index);
         QAction *action = addAction(icon, title);
         action->setData(variant);
         QWidget *actionWidget = widgetForAction(action);
         QToolButton *button = qobject_cast<QToolButton*>(actionWidget);
         Q_ASSERT(button);
         button->installEventFilter(this);
         if (hasChildren) {
             ModelMenu *menu = createMenu();
             menu->setModel(m_model);
             menu->setRootIndex(index);
             action->setMenu(menu);
             button->setPopupMode(QToolButton::InstantPopup);
             button->setArrowType(Qt::DownArrow);
         }
     }
 }
References createMenu(), index(), m_model, m_rootIndex, ModelMenu::setModel(), and ModelMenu::setRootIndex().
Referenced by ModelToolBar(), setModel(), and showEvent().
createMenu()
ModelMenu * ModelToolBar::createMenu () protected virtual
Reimplemented in BookmarksToolBar.
Definition at line 143 of file modeltoolbar.cpp.
 {
     return new ModelMenu(this);
 }
Referenced by build().
dragEnterEvent()
void ModelToolBar::dragEnterEvent (QDragEnterEvent * event) protected
Definition at line 177 of file modeltoolbar.cpp.
 {
     if (!m_model) {
         QToolBar::dragEnterEvent(event);
         return;
     }
     QStringList mimeTypes = m_model->mimeTypes();
     foreach (const QString &mimeType, mimeTypes) {
         if (event->mimeData()->hasFormat(mimeType))
             event->acceptProposedAction();
     }
     QToolBar::dragEnterEvent(event);
 }
References m_model.
dropEvent()
void ModelToolBar::dropEvent (QDropEvent * event) protected
Definition at line 206 of file modeltoolbar.cpp.
 {
     if (!m_model) {
         QToolBar::dropEvent(event);
         return;
     }
     int row;
     QAction *action = actionAt(mapFromGlobal(QCursor::pos()));
     QModelIndex index;
     QModelIndex parentIndex = m_rootIndex;
     if (!action) {
         row = m_model->rowCount(m_rootIndex);
     } else {
         index = this->index(action);
         Q_ASSERT(index.isValid());
         row = index.row();
         if (m_model->hasChildren(index))
             parentIndex = index;
     }
     event->acceptProposedAction();
     m_model->dropMimeData(event->mimeData(), event->dropAction(), row, 0, parentIndex);
     QToolBar::dropEvent(event);
 }
References index(), m_model, and m_rootIndex.
eventFilter()
bool ModelToolBar::eventFilter (QObject * object, QEvent * event) protected
Definition at line 148 of file modeltoolbar.cpp.
 {
     if (event->type() == QEvent::MouseButtonRelease) {
         QToolButton *button = static_cast<QToolButton*>(object);
         Q_ASSERT(button);
         QMouseEvent *mouseEvent = static_cast<QMouseEvent*>(event);
 #ifndef NO_BROWSERAPPLICATION
         BrowserApplication::instance()->setEventMouseButtons(mouseEvent->button());
         BrowserApplication::instance()->setEventKeyboardModifiers(mouseEvent->modifiers());
 #endif
         QAction *action = button->defaultAction();
         Q_ASSERT(action);
         QModelIndex index = this->index(action);
         Q_ASSERT(this->index(action).isValid());
         emit activated(index);
     } else if (event->type() == QEvent::MouseButtonPress) {
         Q_ASSERT(static_cast<QToolButton*>(object));
         QMouseEvent *mouseEvent = static_cast<QMouseEvent*>(event);
         if (mouseEvent->buttons() & Qt::LeftButton)
             m_dragStartPos = mapFromGlobal(mouseEvent->globalPos());
     }
     return false;
 }
References activated(), index(), BrowserApplication::instance(), m_dragStartPos, BrowserApplication::setEventKeyboardModifiers(), and BrowserApplication::setEventMouseButtons().
hideEvent()
void ModelToolBar::hideEvent (QHideEvent * event) protected
Definition at line 193 of file modeltoolbar.cpp.
 {
     clear();
     QToolBar::hideEvent(event);
 }
index()
QModelIndex ModelToolBar::index (QAction * action) static
Definition at line 130 of file modeltoolbar.cpp.
 {
     if (!action)
         return QModelIndex();
     QVariant variant = action->data();
     if (!variant.canConvert<QModelIndex>())
         return QModelIndex();
     QModelIndex index = qvariant_cast<QModelIndex>(variant);
     return index;
 }
Referenced by BookmarksToolBar::bookmarkActivated(), build(), dropEvent(), eventFilter(), mouseMoveEvent(), BookmarksToolBar::openBookmark(), BookmarksToolBar::openBookmarkInCurrentTab(), BookmarksToolBar::openBookmarkInNewTab(), BookmarksToolBar::removeBookmark(), and setRootIndex().
model()
QAbstractItemModel * ModelToolBar::model () const
Definition at line 81 of file modeltoolbar.cpp.
 {
     return m_model;
 }
References m_model.
Referenced by BookmarksToolBar::BookmarksToolBar(), and setModel().
mouseMoveEvent()
void ModelToolBar::mouseMoveEvent (QMouseEvent * event) protected
Definition at line 233 of file modeltoolbar.cpp.
 {
     if (!m_model) {
         QToolBar::mouseMoveEvent(event);
         return;
     }
     if (!(event->buttons() & Qt::LeftButton)) {
         QToolBar::mouseMoveEvent(event);
         return;
     }
     int manhattanLength = (event->pos() - m_dragStartPos).manhattanLength();
     if (manhattanLength <= QApplication::startDragDistance()) {
         QToolBar::mouseMoveEvent(event);
         return;
     }
     QAction *action = actionAt(m_dragStartPos);
     if (!action) {
         QToolBar::mouseMoveEvent(event);
         return;
     }
     QPersistentModelIndex index = this->index(action);
     Q_ASSERT(index.isValid());
     QDrag *drag = new QDrag(this);
     drag->setMimeData(m_model->mimeData(QModelIndexList() << index));
     QRect actionRect = actionGeometry(action);
     drag->setPixmap(this->grab(actionRect));
     if (drag->exec() == Qt::MoveAction)
         m_model->removeRow(index.row(), m_rootIndex);
 }
References index(), m_dragStartPos, m_model, and m_rootIndex.
rootIndex()
QModelIndex ModelToolBar::rootIndex () const
Definition at line 91 of file modeltoolbar.cpp.
 {
     return m_rootIndex;
 }
References m_rootIndex.
Referenced by BookmarksToolBar::newBookmark(), BookmarksToolBar::newFolder(), and BookmarksToolBar::removeBookmark().
setModel()
void ModelToolBar::setModel (QAbstractItemModel * model)
Definition at line 54 of file modeltoolbar.cpp.
 {
     if (m_model) {
         disconnect(m_model, SIGNAL(modelReset()),
                    this, SLOT(build()));
         disconnect(m_model, SIGNAL(rowsInserted(const QModelIndex &, int, int)),
                    this, SLOT(build()));
         disconnect(m_model, SIGNAL(rowsRemoved(const QModelIndex &, int, int)),
                    this, SLOT(build()));
         disconnect(m_model, SIGNAL(dataChanged(const QModelIndex &, const QModelIndex &)),
                    this, SLOT(build()));
     }
     m_model = model;
     if (m_model) {
         connect(m_model, SIGNAL(modelReset()),
                 this, SLOT(build()));
         connect(m_model, SIGNAL(rowsInserted(const QModelIndex &, int, int)),
                 this, SLOT(build()));
         connect(m_model, SIGNAL(rowsRemoved(const QModelIndex &, int, int)),
                 this, SLOT(build()));
         connect(m_model, SIGNAL(dataChanged(const QModelIndex &, const QModelIndex &)),
                 this, SLOT(build()));
     }
 }
References build(), m_model, and model().
Referenced by BookmarksToolBar::BookmarksToolBar().
setRootIndex()
void ModelToolBar::setRootIndex (const QModelIndex & index)
Definition at line 86 of file modeltoolbar.cpp.
 {
     m_rootIndex = index;
 }
References index(), and m_rootIndex.
Referenced by BookmarksToolBar::BookmarksToolBar().
showEvent()
void ModelToolBar::showEvent (QShowEvent * event) protected
Definition at line 199 of file modeltoolbar.cpp.
 {
     if (actions().isEmpty())
         build();
     QToolBar::showEvent(event);
 }
References build().
Member Data Documentation
m_dragStartPos
QPoint ModelToolBar::m_dragStartPos private
Definition at line 67 of file modeltoolbar.h.
Referenced by eventFilter(), and mouseMoveEvent().
m_model
QAbstractItemModel* ModelToolBar::m_model private
Definition at line 65 of file modeltoolbar.h.
Referenced by build(), dragEnterEvent(), dropEvent(), model(), mouseMoveEvent(), and setModel().
m_rootIndex
QPersistentModelIndex ModelToolBar::m_rootIndex private
Definition at line 66 of file modeltoolbar.h.
Referenced by build(), dropEvent(), mouseMoveEvent(), rootIndex(), and setRootIndex().
The documentation for this class was generated from the following files:
src/modeltoolbar.h
src/modeltoolbar.cpp