Endorphin: OpenSearchEngineAction Class Reference
OpenSearchEngineAction Class Reference
#include <opensearchengineaction.h>
Public Member Functions
OpenSearchEngineAction (OpenSearchEngine *engine, QObject *parent=nullptr)
Private Slots
void imageChanged ()
Private Attributes
OpenSearchEngine * m_engine
Detailed Description
Definition at line 26 of file opensearchengineaction.h.
Constructor & Destructor Documentation
OpenSearchEngineAction()
OpenSearchEngineAction::OpenSearchEngineAction (OpenSearchEngine * engine, QObject * parent = nullptr)
Definition at line 26 of file opensearchengineaction.cpp.
     : QAction(parent)
     , m_engine(engine)
 {
     if (!engine->networkAccessManager())
         engine->setNetworkAccessManager(new QNetworkAccessManager());
     setText(engine->name());
     imageChanged();
     connect(engine, SIGNAL(imageChanged()), this, SLOT(imageChanged()));
 }
References imageChanged(), OpenSearchEngine::name, OpenSearchEngine::networkAccessManager, and OpenSearchEngine::setNetworkAccessManager().
Member Function Documentation
imageChanged
void OpenSearchEngineAction::imageChanged () private slot
Definition at line 38 of file opensearchengineaction.cpp.
 {
     QImage image = m_engine->image();
     if (image.isNull())
         setIcon(BrowserApplication::icon(m_engine->imageUrl()));
     else
         setIcon(QIcon(QPixmap::fromImage(image)));
 }
References BrowserApplication::icon(), OpenSearchEngine::image(), OpenSearchEngine::imageUrl, and m_engine.
Referenced by OpenSearchEngineAction().
Member Data Documentation
m_engine
OpenSearchEngine* OpenSearchEngineAction::m_engine private
Definition at line 37 of file opensearchengineaction.h.
Referenced by imageChanged().
The documentation for this class was generated from the following files:
src/opensearch/opensearchengineaction.h
src/opensearch/opensearchengineaction.cpp