Endorphin: ModelMenu Class Reference
ModelMenu Class Reference
#include <modelmenu.h>
Signals
void activated (const QModelIndex &index)
Public Member Functions
ModelMenu (QWidget *parent=nullptr)
void setModel (QAbstractItemModel *model)
QAbstractItemModel * model () const
void setMaxRows (int max)
int maxRows () const
void setFirstSeparator (int offset)
int firstSeparator () const
void setRootIndex (const QModelIndex &index)
QModelIndex rootIndex () const
void setStatusBarTextRole (int role)
int statusBarTextRole () const
void setSeparatorRole (int role)
int separatorRole () const
QAction * makeAction (const QIcon &icon, const QString &text, QObject *parent)
QModelIndex index (QAction *action)
Protected Member Functions
virtual bool prePopulated ()
virtual void postPopulated ()
virtual ModelMenu * createBaseMenu ()
void createMenu (const QModelIndex &parent, int max, QMenu *parentMenu=nullptr, QMenu *menu=nullptr)
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
Private Slots
void aboutToShow ()
void actionTriggered (QAction *action)
Private Member Functions
QAction * makeAction (const QModelIndex &index)
Private Attributes
int m_maxRows
int m_firstSeparator
int m_maxWidth
int m_statusBarTextRole
int m_separatorRole
QAbstractItemModel * m_model
QPersistentModelIndex m_root
QPoint m_dragStartPos
Detailed Description
Definition at line 71 of file modelmenu.h.
Constructor & Destructor Documentation
ModelMenu()
ModelMenu::ModelMenu (QWidget * parent = nullptr)
Definition at line 80 of file modelmenu.cpp.
     : QMenu(parent)
     , m_maxRows(-1)
     , m_firstSeparator(-1)
     , m_maxWidth(-1)
     , m_statusBarTextRole(0)
     , m_separatorRole(0)
     , m_model(nullptr)
 {
     setAcceptDrops(true);
     connect(this, SIGNAL(aboutToShow()), this, SLOT(aboutToShow()));
     connect(this, SIGNAL(triggered(QAction*)), this, SLOT(actionTriggered(QAction*)));
 }
References aboutToShow(), and actionTriggered().
Referenced by createBaseMenu().
Member Function Documentation
aboutToShow
void ModelMenu::aboutToShow () private slot
Definition at line 165 of file modelmenu.cpp.
 {
     clear();
     if (prePopulated())
         addSeparator();
     int max = m_maxRows;
     if (max != -1)
         max += m_firstSeparator;
     createMenu(m_root, max, this, this);
     postPopulated();
 }
Referenced by ModelMenu(), and mouseMoveEvent().
actionTriggered
void ModelMenu::actionTriggered (QAction * action) private slot
Definition at line 248 of file modelmenu.cpp.
 {
     QModelIndex idx = index(action);
     if (idx.isValid())
         emit activated(idx);
 }
References activated(), and index().
Referenced by createMenu(), and ModelMenu().
activated
void ModelMenu::activated (const QModelIndex & index) signal
Referenced by actionTriggered().
createBaseMenu()
ModelMenu * ModelMenu::createBaseMenu () protected virtual
Reimplemented in BookmarksMenu.
Definition at line 178 of file modelmenu.cpp.
 {
     return new ModelMenu(this);
 }
References ModelMenu().
Referenced by createMenu().
createMenu()
void ModelMenu::createMenu (const QModelIndex & parent, int max, QMenu * parentMenu = nullptr, QMenu * menu = nullptr) protected
Definition at line 183 of file modelmenu.cpp.
 {
     if (!menu) {
         QVariant v;
         v.setValue(parent);
         QString title = parent.data().toString();
         ModelMenu *modelMenu = createBaseMenu();
         // triggered goes all the way up the menu structure
         disconnect(modelMenu, SIGNAL(triggered(QAction*)),
                    modelMenu, SLOT(actionTriggered(QAction*)));
         modelMenu->setTitle(title);
         QIcon icon = qvariant_cast<QIcon>(parent.data(Qt::DecorationRole));
         modelMenu->setIcon(icon);
         parentMenu->addMenu(modelMenu)->setData(v);
         modelMenu->setRootIndex(parent);
         modelMenu->setModel(m_model);
         return;
     }
     if (!m_model)
         return;
     int end = m_model->rowCount(parent);
     if (max != -1)
         end = qMin(max, end);
     for (int i = 0; i < end; ++i) {
         QModelIndex idx = m_model->index(i, 0, parent);
         if (m_model->hasChildren(idx)) {
             createMenu(idx, -1, menu);
         } else {
             if (m_separatorRole != 0
                     && idx.data(m_separatorRole).toBool())
                 addSeparator();
             else
                 menu->addAction(makeAction(idx));
         }
         if (menu == this && i == m_firstSeparator - 1)
             addSeparator();
     }
 }
References actionTriggered(), createBaseMenu(), m_firstSeparator, m_model, m_separatorRole, makeAction(), setModel(), and setRootIndex().
Referenced by BookmarksMenuBarMenu::prePopulated().
dragEnterEvent()
void ModelMenu::dragEnterEvent (QDragEnterEvent * event) protected
Definition at line 266 of file modelmenu.cpp.
 {
     if (!m_model) {
         QMenu::dragEnterEvent(event);
         return;
     }
     QStringList mimeTypes = m_model->mimeTypes();
     foreach (const QString &mimeType, mimeTypes) {
         if (event->mimeData()->hasFormat(mimeType))
             event->acceptProposedAction();
     }
     QMenu::dragEnterEvent(event);
 }
References m_model.
dropEvent()
void ModelMenu::dropEvent (QDropEvent * event) protected
Definition at line 282 of file modelmenu.cpp.
 {
     if (!m_model) {
         QMenu::dropEvent(event);
         return;
     }
     int row;
     QAction *action = actionAt(mapFromGlobal(QCursor::pos()));
     QModelIndex index;
     QModelIndex parentIndex = m_root;
     if (!action) {
         row = m_model->rowCount(m_root);
     } else {
         index = this->index(action);
         Q_ASSERT(index.isValid());
         row = index.row();
         if (m_model->hasChildren(index))
             parentIndex = index;
     }
     event->acceptProposedAction();
     m_model->dropMimeData(event->mimeData(), event->dropAction(), row, 0, parentIndex);
     QMenu::dropEvent(event);
 }
References index(), m_model, and m_root.
firstSeparator()
int ModelMenu::firstSeparator () const
Definition at line 129 of file modelmenu.cpp.
 {
     return m_firstSeparator;
 }
References m_firstSeparator.
index()
QModelIndex ModelMenu::index (QAction * action)
Definition at line 255 of file modelmenu.cpp.
 {
     if (!action)
         return QModelIndex();
     QVariant variant = action->data();
     if (!variant.canConvert<QModelIndex>())
         return QModelIndex();
     return qvariant_cast<QModelIndex>(variant);
 }
Referenced by actionTriggered(), BookmarksMenu::activated(), HistoryMenu::activated(), dropEvent(), makeAction(), mouseMoveEvent(), and setRootIndex().
makeAction() [1/2]
QAction * ModelMenu::makeAction (const QIcon & icon, const QString & text, QObject * parent)
Definition at line 239 of file modelmenu.cpp.
 {
     QFontMetrics fm(font());
     if (-1 == m_maxWidth)
         m_maxWidth = fm.horizontalAdvance(QLatin1Char('m')) * 30;
     QString smallText = fm.elidedText(text, Qt::ElideMiddle, m_maxWidth);
     return new QAction(icon, smallText, parent);
 }
References m_maxWidth.
Referenced by createMenu(), and makeAction().
makeAction() [2/2]
QAction * ModelMenu::makeAction (const QModelIndex & index) private
Definition at line 227 of file modelmenu.cpp.
 {
     QIcon icon = qvariant_cast<QIcon>(index.data(Qt::DecorationRole));
     QAction *action = makeAction(icon, index.data().toString(), this);
     action->setStatusTip(index.data(m_statusBarTextRole).toString());
     QVariant v;
     v.setValue(index);
     action->setData(v);
     return action;
 }
References index(), m_statusBarTextRole, and makeAction().
maxRows()
int ModelMenu::maxRows () const
Definition at line 119 of file modelmenu.cpp.
 {
     return m_maxRows;
 }
References m_maxRows.
model()
QAbstractItemModel * ModelMenu::model () const
Definition at line 109 of file modelmenu.cpp.
 {
     return m_model;
 }
References m_model.
Referenced by setModel().
mouseMoveEvent()
void ModelMenu::mouseMoveEvent (QMouseEvent * event) protected
Definition at line 325 of file modelmenu.cpp.
 {
     int manhattanLength = (event->pos() - m_dragStartPos).manhattanLength();
     if (manhattanLength <= QApplication::startDragDistance()) {
         QMenu::mouseMoveEvent(event);
         return;
     }
     if (!(event->buttons() & Qt::LeftButton)) {
         QMenu::mouseMoveEvent(event);
         return;
     }
     QAction *action = actionAt(m_dragStartPos);
     QModelIndex idx = index(action);
     if (!idx.isValid()) {
         QMenu::mouseMoveEvent(event);
         return;
     }
     QDrag *drag = new QDrag(this);
     drag->setMimeData(m_model->mimeData((QModelIndexList() << idx)));
     QRect actionRect = actionGeometry(action);
     drag->setPixmap(this->grab(actionRect));
     if (drag->exec() == Qt::MoveAction) {
         m_model->removeRow(idx.row(), m_root);
         QWidget *target = static_cast<QWidget*>(drag->target());
         if (!this->isAncestorOf(target))
             close();
         else
             aboutToShow();
     }
 }
References aboutToShow(), index(), m_dragStartPos, m_model, and m_root.
mousePressEvent()
void ModelMenu::mousePressEvent (QMouseEvent * event) protected
Definition at line 309 of file modelmenu.cpp.
 {
     if (event->button() == Qt::LeftButton)
         m_dragStartPos = event->pos();
     QMenu::mousePressEvent(event);
 }
References m_dragStartPos.
mouseReleaseEvent()
void ModelMenu::mouseReleaseEvent (QMouseEvent * event) protected
Definition at line 317 of file modelmenu.cpp.
 {
     BrowserApplication::instance()->setEventMouseButtons(event->button());
     BrowserApplication::instance()->setEventKeyboardModifiers(event->modifiers());
     QMenu::mouseReleaseEvent(event);
 }
References BrowserApplication::instance(), BrowserApplication::setEventKeyboardModifiers(), and BrowserApplication::setEventMouseButtons().
postPopulated()
void ModelMenu::postPopulated () protected virtual
Reimplemented in HistoryMenu, and BookmarksMenu.
Definition at line 100 of file modelmenu.cpp.
 {
 }
prePopulated()
bool ModelMenu::prePopulated () protected virtual
Reimplemented in HistoryMenu, and BookmarksMenuBarMenu.
Definition at line 95 of file modelmenu.cpp.
 {
     return false;
 }
rootIndex()
QModelIndex ModelMenu::rootIndex () const
Definition at line 139 of file modelmenu.cpp.
 {
     return m_root;
 }
References m_root.
Referenced by BookmarksMenu::openAll(), and BookmarksMenu::postPopulated().
separatorRole()
int ModelMenu::separatorRole () const
Definition at line 159 of file modelmenu.cpp.
 {
     return m_separatorRole;
 }
References m_separatorRole.
setFirstSeparator()
void ModelMenu::setFirstSeparator (int offset)
Definition at line 124 of file modelmenu.cpp.
 {
     m_firstSeparator = offset;
 }
References m_firstSeparator.
Referenced by HistoryMenu::prePopulated().
setMaxRows()
void ModelMenu::setMaxRows (int max)
Definition at line 114 of file modelmenu.cpp.
 {
     m_maxRows = max;
 }
References m_maxRows.
Referenced by HistoryMenu::HistoryMenu().
setModel()
void ModelMenu::setModel (QAbstractItemModel * model)
Definition at line 104 of file modelmenu.cpp.
 {
     m_model = model;
 }
References m_model, and model().
Referenced by ModelToolBar::build(), createMenu(), BookmarksMenuBarMenu::prePopulated(), and HistoryMenu::prePopulated().
setRootIndex()
void ModelMenu::setRootIndex (const QModelIndex & index)
Definition at line 134 of file modelmenu.cpp.
 {
     m_root = index;
 }
References index(), and m_root.
Referenced by ModelToolBar::build(), createMenu(), and BookmarksMenuBarMenu::prePopulated().
setSeparatorRole()
void ModelMenu::setSeparatorRole (int role)
Definition at line 154 of file modelmenu.cpp.
 {
     m_separatorRole = role;
 }
References m_separatorRole.
Referenced by BookmarksMenu::BookmarksMenu().
setStatusBarTextRole()
void ModelMenu::setStatusBarTextRole (int role)
Definition at line 144 of file modelmenu.cpp.
 {
     m_statusBarTextRole = role;
 }
References m_statusBarTextRole.
Referenced by BookmarksMenu::BookmarksMenu(), and HistoryMenu::HistoryMenu().
statusBarTextRole()
int ModelMenu::statusBarTextRole () const
Definition at line 149 of file modelmenu.cpp.
 {
     return m_statusBarTextRole;
 }
References m_statusBarTextRole.
Member Data Documentation
m_dragStartPos
QPoint ModelMenu::m_dragStartPos private
Definition at line 176 of file modelmenu.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_firstSeparator
int ModelMenu::m_firstSeparator private
Definition at line 170 of file modelmenu.h.
Referenced by createMenu(), firstSeparator(), and setFirstSeparator().
m_maxRows
int ModelMenu::m_maxRows private
Definition at line 169 of file modelmenu.h.
Referenced by maxRows(), and setMaxRows().
m_maxWidth
int ModelMenu::m_maxWidth private
Definition at line 171 of file modelmenu.h.
Referenced by makeAction().
m_model
QAbstractItemModel* ModelMenu::m_model private
Definition at line 174 of file modelmenu.h.
Referenced by createMenu(), dragEnterEvent(), dropEvent(), model(), mouseMoveEvent(), and setModel().
m_root
QPersistentModelIndex ModelMenu::m_root private
Definition at line 175 of file modelmenu.h.
Referenced by dropEvent(), mouseMoveEvent(), rootIndex(), and setRootIndex().
m_separatorRole
int ModelMenu::m_separatorRole private
Definition at line 173 of file modelmenu.h.
Referenced by createMenu(), separatorRole(), and setSeparatorRole().
m_statusBarTextRole
int ModelMenu::m_statusBarTextRole private
Definition at line 172 of file modelmenu.h.
Referenced by makeAction(), setStatusBarTextRole(), and statusBarTextRole().
The documentation for this class was generated from the following files:
src/modelmenu.h
src/modelmenu.cpp