Endorphin: AutoSaver Class Reference
AutoSaver Class Reference
#include <autosaver.h>
Public Slots
void changeOccurred ()
Public Member Functions
AutoSaver (QObject *parent)
~AutoSaver ()
void saveIfNeccessary ()
Protected Member Functions
void timerEvent (QTimerEvent *event)
Private Attributes
QBasicTimer m_timer
QElapsedTimer m_firstChange
Detailed Description
Definition at line 75 of file autosaver.h.
Constructor & Destructor Documentation
AutoSaver()
AutoSaver::AutoSaver (QObject * parent)
Definition at line 74 of file autosaver.cpp.
                                     : QObject(parent)
 {
     Q_ASSERT(parent);
 }
~AutoSaver()
AutoSaver::~AutoSaver ()
Definition at line 79 of file autosaver.cpp.
 {
     if (m_timer.isActive()) {
         qWarning() << "AutoSaver: still active when destroyed, changes not saved.";
         if (parent() && parent()->metaObject())
             qWarning() << parent() << parent()->metaObject()->className() << "should call saveIfNeccessary";
     }
 }
References m_timer.
Member Function Documentation
changeOccurred
void AutoSaver::changeOccurred () slot
Definition at line 88 of file autosaver.cpp.
 {
     if (!m_firstChange.isValid())
         m_firstChange.start();
     if (m_firstChange.elapsed() > MAXWAIT) {
         saveIfNeccessary();
     } else {
         m_timer.start(AUTOSAVE_IN, this);
     }
 }
References AUTOSAVE_IN, m_firstChange, m_timer, MAXWAIT, and saveIfNeccessary().
Referenced by BookmarksManager::changeExpanded(), DownloadManager::cleanup(), ToolbarSearch::clear(), HistoryManager::clear(), HistoryManager::load(), DownloadModel::removeRows(), ToolbarSearch::searchNow(), HistoryManager::setDaysToExpire(), HistoryManager::setHistory(), DownloadManager::setRemovePolicy(), HistoryManager::updateHistoryEntry(), BrowserMainWindow::viewBookmarksBar(), BrowserMainWindow::viewMenuBar(), BrowserMainWindow::viewStatusbar(), BrowserMainWindow::viewToolbar(), BrowserMainWindow::~BrowserMainWindow(), and DownloadManager::~DownloadManager().
saveIfNeccessary()
void AutoSaver::saveIfNeccessary ()
Definition at line 109 of file autosaver.cpp.
 {
     if (!m_timer.isActive())
         return;
     m_timer.stop();
     m_firstChange = QElapsedTimer();
     if (!QMetaObject::invokeMethod(parent(), "save", Qt::DirectConnection)) {
         qWarning() << "AutoSaver: error invoking slot save() on parent";
     }
 }
References m_firstChange, and m_timer.
Referenced by changeOccurred(), HistoryManager::clear(), BrowserApplication::newMainWindow(), timerEvent(), BookmarksManager::~BookmarksManager(), BrowserMainWindow::~BrowserMainWindow(), DownloadManager::~DownloadManager(), HistoryManager::~HistoryManager(), OpenSearchManager::~OpenSearchManager(), and ToolbarSearch::~ToolbarSearch().
timerEvent()
void AutoSaver::timerEvent (QTimerEvent * event) protected
Definition at line 100 of file autosaver.cpp.
 {
     if (event->timerId() == m_timer.timerId()) {
         saveIfNeccessary();
     } else {
         QObject::timerEvent(event);
     }
 }
References m_timer, and saveIfNeccessary().
Member Data Documentation
m_firstChange
QElapsedTimer AutoSaver::m_firstChange private
Definition at line 134 of file autosaver.h.
Referenced by changeOccurred(), and saveIfNeccessary().
m_timer
QBasicTimer AutoSaver::m_timer private
Definition at line 133 of file autosaver.h.
Referenced by changeOccurred(), saveIfNeccessary(), timerEvent(), and ~AutoSaver().
The documentation for this class was generated from the following files:
src/autosaver.h
src/autosaver.cpp