Endorphin: WebView Class Reference
WebView Class Reference
#include <webview.h>
Public Slots
void zoomIn ()
void zoomOut ()
void resetZoom ()
void applyZoom ()
Signals
void search (const QUrl &searchUrl, TabWidget::OpenUrlIn openIn)
void notifyRanJavaScript ()
void devToolsRequested (QWebEnginePage *source)
Public Member Functions
WebView (QWidget *parent=nullptr)
WebPage * webPage () const
void loadSettings ()
void keyReleaseEvent (QKeyEvent *event)
void focusOutEvent (QFocusEvent *event)
void loadUrl (const QUrl &url, const QString &title=QString())
QUrl url () const
QString lastStatusBarText () const
int progress () const
TabWidget * tabWidget () const
void ranJavaScript ()
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void contextMenuEvent (QContextMenuEvent *event)
void wheelEvent (QWheelEvent *event)
void resizeEvent (QResizeEvent *event)
void dragEnterEvent (QDragEnterEvent *event)
void dragMoveEvent (QDragMoveEvent *event)
void dropEvent (QDropEvent *event)
void keyPressEvent (QKeyEvent *event)
Private Slots
void setProgress (int progress)
void loadFinished ()
void setStatusBarText (const QString &string)
void downloadRequested (const QNetworkRequest &request)
void openActionUrlInNewTab ()
void openActionUrlInNewWindow ()
void downloadLinkToDisk ()
void copyLinkToClipboard ()
void openImageInNewWindow ()
void downloadImageToDisk ()
void copyImageToClipboard ()
void copyImageLocationToClipboard ()
void bookmarkLink ()
void searchRequested (QAction *action)
Private Member Functions
int levelForZoom (int zoom)
void onFeaturePermissionRequested (const QUrl &securityOrigin, QWebEnginePage::Feature)
Private Attributes
QString m_statusBarText
QUrl m_initialUrl
int m_progress
int m_currentZoom
QList< int > m_zoomLevels
WebPage * m_page
Detailed Description
Definition at line 77 of file webview.h.
Constructor & Destructor Documentation
WebView()
WebView::WebView (QWidget * parent = nullptr)
Definition at line 149 of file webview.cpp.
     : QWebEngineView(parent)
     , m_progress(0)
     , m_currentZoom(100)
     , m_page(new WebPage(this))
 //    , m_enableAccessKeys(true)
 //    , m_accessKeysPressed(false)
 {
     setPage(m_page);
     connect(page(), &WebPage::featurePermissionRequested, this, &WebView::onFeaturePermissionRequested);
     QPalette p;
     connect(this, SIGNAL(loadProgress(int)),
             this, SLOT(setProgress(int)));
     connect(this, SIGNAL(loadFinished(bool)),
             this, SLOT(loadFinished()));
     connect(page(), SIGNAL(aboutToLoadUrl(const QUrl &)),
             this, SIGNAL(urlChanged(const QUrl &)));
     connect(page(), SIGNAL(downloadRequested(const QNetworkRequest &)),
             this, SLOT(downloadRequested(const QNetworkRequest &)));
     connect(BrowserApplication::instance(), SIGNAL(zoomTextOnlyChanged(bool)),
             this, SLOT(applyZoom()));
 //    page()->setForwardUnsupportedContent(true);
     setAcceptDrops(true);
     // the zoom values (in percent) are chosen to be like in Mozilla Firefox 3
     m_zoomLevels << 30 << 50 << 67 << 80 << 90;
     m_zoomLevels << 100;
     m_zoomLevels << 110 << 120 << 133 << 150 << 170 << 200 << 240 << 300;
     /*
         connect(m_page, SIGNAL(loadStarted()),
                 this, SLOT(hideAccessKeys()));
         connect(m_page, SIGNAL(scrollRequested(int, int, const QRect &)),
                 this, SLOT(hideAccessKeys()));
     */
     loadSettings();
 }
References applyZoom(), downloadRequested(), BrowserApplication::instance(), loadFinished(), loadSettings(), m_page, m_zoomLevels, onFeaturePermissionRequested(), and setProgress().
Member Function Documentation
applyZoom
void WebView::applyZoom () slot
Definition at line 521 of file webview.cpp.
 {
     setZoomFactor(qreal(m_currentZoom) / 100.0);
 }
References m_currentZoom.
Referenced by resetZoom(), WebView(), wheelEvent(), zoomIn(), and zoomOut().
bookmarkLink
void WebView::bookmarkLink () private slot
Definition at line 374 of file webview.cpp.
 {
     if (QAction *action = qobject_cast<QAction*>(sender())) {
         AddBookmarkDialog dialog;
         dialog.setUrl(QString::fromUtf8(action->data().toUrl().toEncoded()));
         dialog.exec();
     }
 }
References AddBookmarkDialog::setUrl().
Referenced by contextMenuEvent().
contextMenuEvent()
void WebView::contextMenuEvent (QContextMenuEvent * event) protected
Definition at line 210 of file webview.cpp.
 {
     QMenu *menu = new QMenu(this);
     if (!page()->contextMenuData().linkUrl().isEmpty()) {
         QAction *newWindowAction = menu->addAction(tr("Open in New &Window"), this, SLOT(openActionUrlInNewWindow()));
         newWindowAction->setData(page()->contextMenuData().linkUrl());
         QAction *newTabAction = menu->addAction(tr("Open in New &Tab"), this, SLOT(openActionUrlInNewTab()));
         newTabAction->setData(page()->contextMenuData().linkUrl());
         menu->addSeparator();
         menu->addAction(tr("Save Lin&k"), this, SLOT(downloadLinkToDisk()));
         menu->addAction(tr("&Bookmark This Link"), this, SLOT(bookmarkLink()))->setData(page()->contextMenuData().linkUrl());
         menu->addSeparator();
         if (!page()->selectedText().isEmpty())
             menu->addAction(pageAction(QWebEnginePage::Copy));
         menu->addAction(tr("&Copy Link Location"), this, SLOT(copyLinkToClipboard()));
     }
     if (page()->contextMenuData().mediaType() == QWebEngineContextMenuData::MediaTypeImage) {
         if (!menu->isEmpty())
             menu->addSeparator();
         QAction *newWindowAction = menu->addAction(tr("Open Image in New &Window"), this, SLOT(openActionUrlInNewWindow()));
         newWindowAction->setData(page()->contextMenuData().mediaUrl());
         QAction *newTabAction = menu->addAction(tr("Open Image in New &Tab"), this, SLOT(openActionUrlInNewTab()));
         newTabAction->setData(page()->contextMenuData().mediaUrl());
         menu->addSeparator();
         menu->addAction(tr("&Save Image"), this, SLOT(downloadImageToDisk()));
         menu->addAction(tr("&Copy Image"), this, SLOT(copyImageToClipboard()));
         menu->addAction(tr("C&opy Image Location"), this, SLOT(copyImageLocationToClipboard()))->setData(page()->contextMenuData().mediaUrl().toString());
     }
     if (!page()->selectedText().isEmpty()) {
         if (menu->isEmpty()) {
             menu->addAction(pageAction(QWebEnginePage::Copy));
         } else {
             menu->addSeparator();
         }
         QMenu *searchMenu = menu->addMenu(tr("Search with..."));
         QList<QString> list = ToolbarSearch::openSearchManager()->allEnginesNames();
         for (int i = 0; i < list.count(); ++i) {
             QString name = list.at(i);
             OpenSearchEngine *engine = ToolbarSearch::openSearchManager()->engine(name);
             QAction *action = new OpenSearchEngineAction(engine, searchMenu);
             searchMenu->addAction(action);
             action->setData(name);
         }
         connect(searchMenu, SIGNAL(triggered(QAction *)), this, SLOT(searchRequested(QAction *)));
     }
     /*
         QWebElement element = r.element();
         if (!element.isNull()
             && element.tagName().toLower() == QLatin1String("input")
             && element.attribute(QLatin1String("type"), QLatin1String("text")) == QLatin1String("text")) {
             if (menu->isEmpty()) {
                 menu->addAction(pageAction(QWebEnginePage::Copy));
             } else {
                 menu->addSeparator();
             }
             QVariant variant;
             variant.setValue(element);
             menu->addAction(tr("Add to the toolbar search"), this, SLOT(addSearchEngine()))->setData(variant);
         }
     */
     if (menu->isEmpty()) {
         delete menu;
         menu = page()->createStandardContextMenu();
     }
     QAction *action = new QAction(menu);
     action->setText("Inspect Element");
     connect(action, &QAction::triggered, [this]() { emit devToolsRequested(page()); });
     menu->addAction(action);
     if (!menu->isEmpty()) {
         if (BrowserMainWindow::parentWindow(tabWidget())->menuBar()->isHidden()) {
             menu->addSeparator();
             menu->addAction(BrowserMainWindow::parentWindow(tabWidget())->showMenuBarAction());
         }
         menu->exec(mapToGlobal(event->pos()));
         delete menu;
         return;
     }
     delete menu;
     QWebEngineView::contextMenuEvent(event);
 }
References OpenSearchManager::allEnginesNames(), bookmarkLink(), copyImageLocationToClipboard(), copyImageToClipboard(), copyLinkToClipboard(), devToolsRequested(), downloadImageToDisk(), downloadLinkToDisk(), OpenSearchManager::engine(), openActionUrlInNewTab(), openActionUrlInNewWindow(), ToolbarSearch::openSearchManager(), BrowserMainWindow::parentWindow(), searchRequested(), BrowserMainWindow::showMenuBarAction(), and tabWidget().
copyImageLocationToClipboard
void WebView::copyImageLocationToClipboard () private slot
Definition at line 367 of file webview.cpp.
 {
     if (QAction *action = qobject_cast<QAction*>(sender())) {
         BrowserApplication::clipboard()->setText(action->data().toString());
     }
 }
Referenced by contextMenuEvent().
copyImageToClipboard
void WebView::copyImageToClipboard () private slot
Definition at line 362 of file webview.cpp.
 {
     pageAction(QWebEnginePage::CopyImageToClipboard)->trigger();
 }
Referenced by contextMenuEvent().
copyLinkToClipboard
void WebView::copyLinkToClipboard () private slot
Definition at line 331 of file webview.cpp.
 {
     pageAction(QWebEnginePage::CopyLinkToClipboard)->trigger();
 }
Referenced by contextMenuEvent().
devToolsRequested
void WebView::devToolsRequested (QWebEnginePage * source) signal
Referenced by contextMenuEvent(), and TabWidget::makeNewTab().
downloadImageToDisk
void WebView::downloadImageToDisk () private slot
Definition at line 357 of file webview.cpp.
 {
     pageAction(QWebEnginePage::DownloadImageToDisk)->trigger();
 }
Referenced by contextMenuEvent().
downloadLinkToDisk
void WebView::downloadLinkToDisk () private slot
Definition at line 326 of file webview.cpp.
 {
     pageAction(QWebEnginePage::DownloadLinkToDisk)->trigger();
 }
Referenced by contextMenuEvent().
downloadRequested
void WebView::downloadRequested (const QNetworkRequest & request) private slot
Definition at line 688 of file webview.cpp.
 {
     BrowserApplication::downloadManager()->download(request);
 }
References DownloadManager::download(), and BrowserApplication::downloadManager().
Referenced by WebView().
dragEnterEvent()
void WebView::dragEnterEvent (QDragEnterEvent * event) protected
Definition at line 627 of file webview.cpp.
 {
     event->acceptProposedAction();
 }
dragMoveEvent()
void WebView::dragMoveEvent (QDragMoveEvent * event) protected
Definition at line 632 of file webview.cpp.
 {
     event->ignore();
     if (event->source() != this) {
         if (!event->mimeData()->urls().isEmpty()) {
             event->acceptProposedAction();
         } else {
             QUrl url(event->mimeData()->text());
             if (url.isValid())
                 event->acceptProposedAction();
         }
     }
     if (!event->isAccepted()) {
         QWebEngineView::dragMoveEvent(event);
     }
 }
References url().
dropEvent()
void WebView::dropEvent (QDropEvent * event) protected
Definition at line 649 of file webview.cpp.
 {
     QWebEngineView::dropEvent(event);
     if (!event->isAccepted()
             && event->source() != this
             && event->possibleActions() & Qt::CopyAction) {
         QUrl url;
         if (!event->mimeData()->urls().isEmpty())
             url = event->mimeData()->urls().first();
         if (!url.isValid())
             url = event->mimeData()->text();
         if (url.isValid()) {
             loadUrl(url);
             event->acceptProposedAction();
         }
     }
 }
References loadUrl(), and url().
focusOutEvent()
void WebView::focusOutEvent (QFocusEvent * event)
Definition at line 737 of file webview.cpp.
 {
     /*
         if (m_accessKeysPressed) {
             hideAccessKeys();
             m_accessKeysPressed = false;
         }
     */
     QWebEngineView::focusOutEvent(event);
 }
keyPressEvent()
void WebView::keyPressEvent (QKeyEvent * event) protected
Definition at line 693 of file webview.cpp.
 {
     /*
     if (m_enableAccessKeys) {
         m_accessKeysPressed = (event->modifiers() == Qt::ControlModifier
                                && event->key() == Qt::Key_Control);
         if (!m_accessKeysPressed) {
             if (checkForAccessKey(event)) {
                 hideAccessKeys();
                 event->accept();
                 return;
             }
             hideAccessKeys();
         } else {
             QTimer::singleShot(300, this, SLOT(accessKeyShortcut()));
         }
     }
     */
     QWebEngineView::keyPressEvent(event);
 }
keyReleaseEvent()
void WebView::keyReleaseEvent (QKeyEvent * event)
Definition at line 728 of file webview.cpp.
 {
     /*
         if (m_enableAccessKeys)
             m_accessKeysPressed = event->key() == Qt::Key_Control;
     */
     QWebEngineView::keyReleaseEvent(event);
 }
lastStatusBarText()
QString WebView::lastStatusBarText () const
Definition at line 595 of file webview.cpp.
 {
     return m_statusBarText;
 }
References m_statusBarText.
Referenced by TabWidget::currentChanged().
levelForZoom()
int WebView::levelForZoom (int zoom) private
Definition at line 498 of file webview.cpp.
 {
     int i;
     i = m_zoomLevels.indexOf(zoom);
     if (i >= 0)
         return i;
     for (i = 0 ; i < m_zoomLevels.count(); ++i)
         if (zoom <= m_zoomLevels[i])
             break;
     if (i == m_zoomLevels.count())
         return i - 1;
     if (i == 0)
         return i;
     if (zoom - m_zoomLevels[i-1] > m_zoomLevels[i] - zoom)
         return i;
     else
         return i-1;
 }
References m_zoomLevels.
Referenced by zoomIn(), and zoomOut().
loadFinished
void WebView::loadFinished () private slot
Definition at line 550 of file webview.cpp.
 {
     if (100 != m_progress) {
         qWarning() << "Received finished signal while progress is still:" << progress()
                    << "Url:" << url();
     }
     m_progress = 0;
 }
References m_progress, progress(), and url().
Referenced by WebView().
loadSettings()
void WebView::loadSettings ()
Definition at line 186 of file webview.cpp.
 {
     /*
     QSettings settings;
     settings.beginGroup(QLatin1String("WebView"));
     m_enableAccessKeys = settings.value(QLatin1String("enableAccessKeys"), m_enableAccessKeys).toBool();
     if (!m_enableAccessKeys)
         hideAccessKeys();
     */
     m_page->loadSettings();
 }
References WebPage::loadSettings(), and m_page.
Referenced by TabWidget::loadSettings(), and WebView().
loadUrl()
void WebView::loadUrl (const QUrl & url, const QString & title = QString())
Definition at line 559 of file webview.cpp.
 {
     if (url.scheme() == QLatin1String("javascript")) {
         QString scriptSource = QUrl::fromPercentEncoding(url.toString(Q_FLAGS(QUrl::TolerantMode|QUrl::RemoveScheme)).toLatin1());
         QEventLoop loop;
         QObject::connect(this, SIGNAL(notifyRanJavaScript()), &loop, SLOT(quit()));
         page()->runJavaScript(scriptSource, [this](const QVariant &v)
         {
             this->ranJavaScript();
         });
         loop.exec();
         return;
     }
     m_initialUrl = url;
     if (!title.isEmpty())
         emit titleChanged(tr("Loading..."));
     else
         emit titleChanged(title);
     QUrl oldurl = QUrl(url.toString());
     QUrl newurl = QUrl(url.toString());
     if(newurl.toString().startsWith(QLatin1String("endorphin://"))) {
         QString url_tmp = newurl.toString().mid(12);
         newurl = QUrl(QLatin1String("qrc:/") + url_tmp);
         QString urlstr = newurl.toString();
         if(!urlstr.endsWith(QLatin1String(".html"))) {
             newurl = QUrl(urlstr + QLatin1String(".html"));
         }
     }
     load(newurl);
 }
References m_initialUrl, notifyRanJavaScript(), ranJavaScript(), and url().
Referenced by TabWidget::cloneTab(), dropEvent(), TabWidget::loadUrl(), mouseReleaseEvent(), and TabWidget::restoreState().
mousePressEvent()
void WebView::mousePressEvent (QMouseEvent * event) protected
Definition at line 609 of file webview.cpp.
 {
     BrowserApplication::instance()->setEventMouseButtons(event->buttons());
     BrowserApplication::instance()->setEventKeyboardModifiers(event->modifiers());
     switch (event->button()) {
     case Qt::XButton1:
         pageAction(WebPage::Back)->trigger();
         break;
     case Qt::XButton2:
         pageAction(WebPage::Forward)->trigger();
         break;
     default:
         QWebEngineView::mousePressEvent(event);
         break;
     }
 }
References BrowserApplication::instance(), BrowserApplication::setEventKeyboardModifiers(), and BrowserApplication::setEventMouseButtons().
mouseReleaseEvent()
void WebView::mouseReleaseEvent (QMouseEvent * event) protected
Definition at line 668 of file webview.cpp.
 {
     const bool isAccepted = event->isAccepted();
     m_page->event(event);
     if (!event->isAccepted()
             && (BrowserApplication::instance()->eventMouseButtons() & Qt::MidButton)) {
         QUrl url(QApplication::clipboard()->text(QClipboard::Selection));
         if (!url.isEmpty() && url.isValid() && !url.scheme().isEmpty()) {
             BrowserApplication::instance()->setEventMouseButtons(Qt::NoButton);
             loadUrl(url);
         }
     }
     event->setAccepted(isAccepted);
 }
References BrowserApplication::eventMouseButtons(), BrowserApplication::instance(), loadUrl(), m_page, BrowserApplication::setEventMouseButtons(), and url().
notifyRanJavaScript
void WebView::notifyRanJavaScript () signal
Referenced by loadUrl(), and ranJavaScript().
onFeaturePermissionRequested()
void WebView::onFeaturePermissionRequested (const QUrl & securityOrigin, QWebEnginePage::Feature feature) private
Definition at line 891 of file webview.cpp.
 {
     PermissionBar *permissionBar = new PermissionBar(this);
     connect(permissionBar, &PermissionBar::featurePermissionProvided, page(), &QWebEnginePage::setFeaturePermission);
     // Discard the bar on new loads (if we navigate away or reload).
     connect(page(), &QWebEnginePage::loadStarted, permissionBar, &QObject::deleteLater);
     permissionBar->requestPermission(securityOrigin, feature);
 }
References PermissionBar::featurePermissionProvided(), and PermissionBar::requestPermission().
Referenced by WebView().
openActionUrlInNewTab
void WebView::openActionUrlInNewTab () private slot
Definition at line 336 of file webview.cpp.
 {
     if (QAction *action = qobject_cast<QAction*>(sender())) {
         QWebEnginePage *page = tabWidget()->getView(TabWidget::NewNotSelectedTab, this)->page();
         page->load(action->data().toUrl());
     }
 }
References TabWidget::getView(), TabWidget::NewNotSelectedTab, and tabWidget().
Referenced by contextMenuEvent().
openActionUrlInNewWindow
void WebView::openActionUrlInNewWindow () private slot
Definition at line 344 of file webview.cpp.
 {
     if (QAction *action = qobject_cast<QAction*>(sender())) {
         QWebEnginePage *page = tabWidget()->getView(TabWidget::NewWindow, this)->page();
         page->load(action->data().toUrl());
     }
 }
References TabWidget::getView(), TabWidget::NewWindow, and tabWidget().
Referenced by contextMenuEvent().
openImageInNewWindow
void WebView::openImageInNewWindow () private slot
Definition at line 352 of file webview.cpp.
 {
     //pageAction(QWebEnginePage::OpenImageInNewWindow)->trigger();
 }
progress()
int WebView::progress () const inline
Definition at line 96 of file webview.h.
{
         return m_progress;
     }
References m_progress.
Referenced by TabWidget::currentChanged(), loadFinished(), and setProgress().
ranJavaScript()
void WebView::ranJavaScript ()
Definition at line 590 of file webview.cpp.
 {
     emit notifyRanJavaScript();
 }
References notifyRanJavaScript().
Referenced by loadUrl().
resetZoom
void WebView::resetZoom () slot
Definition at line 544 of file webview.cpp.
 {
     m_currentZoom = 100;
     applyZoom();
 }
References applyZoom(), and m_currentZoom.
Referenced by BrowserMainWindow::zoomNormal().
resizeEvent()
void WebView::resizeEvent (QResizeEvent * event) protected
Definition at line 314 of file webview.cpp.
 {
     /*
         int offset = event->size().height() - event->oldSize().height();
         int currentValue = page()->mainFrame()->scrollBarValue(Qt::Vertical);
         setUpdatesEnabled(false);
         page()->mainFrame()->setScrollBarValue(Qt::Vertical, currentValue - offset);
         setUpdatesEnabled(true);
     */
     QWebEngineView::resizeEvent(event);
 }
search
void WebView::search (const QUrl & searchUrl, TabWidget::OpenUrlIn openIn) signal
Referenced by searchRequested().
searchRequested
void WebView::searchRequested (QAction * action) private slot
Definition at line 383 of file webview.cpp.
 {
     QString searchText = page()->selectedText();
     if (searchText.isEmpty())
         return;
     QVariant index = action->data();
     if (index.canConvert<QString>()) {
         OpenSearchEngine *engine = ToolbarSearch::openSearchManager()->engine(index.toString());
         emit search(engine->searchUrl(searchText), TabWidget::NewSelectedTab);
     }
 }
References OpenSearchManager::engine(), TabWidget::NewSelectedTab, ToolbarSearch::openSearchManager(), search(), and OpenSearchEngine::searchUrl().
Referenced by contextMenuEvent().
setProgress
void WebView::setProgress (int progress) private slot
Definition at line 493 of file webview.cpp.
 {
     m_progress = progress;
 }
References m_progress, and progress().
Referenced by WebView().
setStatusBarText
void WebView::setStatusBarText (const QString & string) private slot
Definition at line 683 of file webview.cpp.
 {
     m_statusBarText = string;
 }
References m_statusBarText.
tabWidget()
TabWidget * WebView::tabWidget () const
Definition at line 199 of file webview.cpp.
 {
     QObject *widget = this->parent();
     while (widget) {
         if (TabWidget *tw = qobject_cast<TabWidget*>(widget))
             return tw;
         widget = widget->parent();
     }
     return nullptr;
 }
Referenced by contextMenuEvent(), openActionUrlInNewTab(), and openActionUrlInNewWindow().
url()
QUrl WebView::url () const
Definition at line 600 of file webview.cpp.
 {
     QUrl url = QWebEngineView::url();
     if (!url.isEmpty())
         return url;
     return m_initialUrl;
 }
References m_initialUrl.
Referenced by BrowserMainWindow::addBookmark(), TabWidget::bookmarkTabs(), TabWidget::cloneTab(), TabWidget::closeTab(), TabWidget::currentChanged(), dragMoveEvent(), dropEvent(), loadFinished(), loadUrl(), LocationBarSiteIcon::mouseMoveEvent(), mouseReleaseEvent(), TabWidget::restoreState(), SettingsDialog::setHomeToCurrentPage(), BrowserMainWindow::viewPageSource(), TabWidget::webViewIconChanged(), LocationBarSiteIcon::webViewSiteIconChanged(), and TabWidget::webViewTitleChanged().
webPage()
WebPage* WebView::webPage () const inline
Definition at line 83 of file webview.h.
{
         return m_page;
     }
References m_page.
wheelEvent()
void WebView::wheelEvent (QWheelEvent * event) protected
Definition at line 301 of file webview.cpp.
 {
     if (event->modifiers() & Qt::ControlModifier) {
         int numDegrees = event->delta() / 8;
         int numSteps = numDegrees / 15;
         m_currentZoom = m_currentZoom + numSteps * 10;
         applyZoom();
         event->accept();
         return;
     }
     QWebEngineView::wheelEvent(event);
 }
References applyZoom(), and m_currentZoom.
zoomIn
void WebView::zoomIn () slot
Definition at line 526 of file webview.cpp.
 {
     int i = levelForZoom(m_currentZoom);
     if (i < m_zoomLevels.count() - 1)
         m_currentZoom = m_zoomLevels[i + 1];
     applyZoom();
 }
References applyZoom(), levelForZoom(), m_currentZoom, and m_zoomLevels.
Referenced by BrowserMainWindow::zoomIn().
zoomOut
void WebView::zoomOut () slot
Definition at line 535 of file webview.cpp.
 {
     int i = levelForZoom(m_currentZoom);
     if (i > 0)
         m_currentZoom = m_zoomLevels[i - 1];
     applyZoom();
 }
References applyZoom(), levelForZoom(), m_currentZoom, and m_zoomLevels.
Referenced by BrowserMainWindow::zoomOut().
Member Data Documentation
m_currentZoom
int WebView::m_currentZoom private
Definition at line 150 of file webview.h.
Referenced by applyZoom(), resetZoom(), wheelEvent(), zoomIn(), and zoomOut().
m_initialUrl
QUrl WebView::m_initialUrl private
Definition at line 148 of file webview.h.
Referenced by loadUrl(), and url().
m_page
WebPage* WebView::m_page private
Definition at line 152 of file webview.h.
Referenced by loadSettings(), mouseReleaseEvent(), webPage(), and WebView().
m_progress
int WebView::m_progress private
Definition at line 149 of file webview.h.
Referenced by loadFinished(), progress(), and setProgress().
m_statusBarText
QString WebView::m_statusBarText private
Definition at line 147 of file webview.h.
Referenced by lastStatusBarText(), and setStatusBarText().
m_zoomLevels
QList<int> WebView::m_zoomLevels private
Definition at line 151 of file webview.h.
Referenced by levelForZoom(), WebView(), zoomIn(), and zoomOut().
The documentation for this class was generated from the following files:
src/webview.h
src/webview.cpp