Endorphin: SingleApplication Class Reference
SingleApplication Class Reference
#include <singleapplication.h>
Signals
void messageReceived (QLocalSocket *socket)
Public Member Functions
SingleApplication (int &argc, char **argv)
bool sendMessage (const QByteArray &message, int waitMsecsForReply=0)
bool startSingleServer ()
bool isRunning () const
Private Slots
void newConnection ()
Private Member Functions
QString serverName () const
Private Attributes
QLocalServer * m_localServer
Detailed Description
Definition at line 40 of file singleapplication.h.
Constructor & Destructor Documentation
SingleApplication()
SingleApplication::SingleApplication (int & argc, char ** argv)
Copyright (c) 2008-2009, Aaron Dewes
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Endorphin nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS `‘AS IS’' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 45 of file singleapplication.cpp.
     : QApplication(argc, argv)
     , m_localServer(nullptr)
 {
 }
Member Function Documentation
isRunning()
bool SingleApplication::isRunning () const
Definition at line 122 of file singleapplication.cpp.
 {
     return (nullptr != m_localServer);
 }
References m_localServer.
Referenced by main().
messageReceived
void SingleApplication::messageReceived (QLocalSocket * socket) signal
Referenced by newConnection(), and sendMessage().
newConnection
void SingleApplication::newConnection () private slot
Definition at line 127 of file singleapplication.cpp.
 {
     QLocalSocket *socket = m_localServer->nextPendingConnection();
     if (!socket)
         return;
     socket->waitForReadyRead();
     emit messageReceived(socket);
     delete socket;
 }
References m_localServer, and messageReceived().
Referenced by startSingleServer().
sendMessage()
bool SingleApplication::sendMessage (const QByteArray & message, int waitMsecsForReply = 0)
Definition at line 51 of file singleapplication.cpp.
 {
 #ifdef SINGALAPPLICATION_DEBUG
     qDebug() << "SingleApplication::" << __FUNCTION__ << message << waitMsecsForReply;
 #endif
     QLocalSocket socket;
     socket.connectToServer(serverName());
     if (!socket.waitForConnected(500))
         return false;
     socket.write(message);
     socket.flush();
     socket.waitForBytesWritten();
     bool success = true;
     if (socket.error() != QLocalSocket::UnknownSocketError) {
 #ifdef SINGALAPPLICATION_DEBUG
         qDebug() << "SingleApplication::" << __FUNCTION__ << socket.errorString();
 #endif
         success = false;
     }
     if (success) {
         socket.waitForReadyRead(waitMsecsForReply);
         if (socket.bytesAvailable() > 0)
             emit messageReceived(&socket);
     }
     return success;
 }
References messageReceived(), and serverName().
Referenced by BrowserApplication::BrowserApplication().
serverName()
QString SingleApplication::serverName () const private
Definition at line 137 of file singleapplication.cpp.
 {
     QString serverName = QCoreApplication::applicationName();
     Q_ASSERT(!serverName.isEmpty());
 #ifdef Q_WS_QWS
     serverName += QLatin1String("_qws");
 #endif
 #ifndef Q_OS_WIN
     serverName += QString(QLatin1String("_%1_%2")).arg(getuid()).arg(getgid());
 #else
     static QString login;
     if (login.isEmpty()) {
         QT_WA({
             wchar_t buffer[256];
             DWORD bufferSize = sizeof(buffer) / sizeof(wchar_t) - 1;
             GetUserNameW(buffer, &bufferSize);
             login = QString::fromUtf16((ushort*)buffer);
         },
         {
             char buffer[256];
             DWORD bufferSize = sizeof(buffer) / sizeof(char) - 1;
             GetUserNameA(buffer, &bufferSize);
             login = QString::fromLocal8Bit(buffer);
         });
     }
     serverName += QString::fromAscii("_%1").arg(login);
 #endif
     return serverName;
 }
Referenced by sendMessage(), and startSingleServer().
startSingleServer()
bool SingleApplication::startSingleServer ()
Definition at line 78 of file singleapplication.cpp.
 {
     if (m_localServer)
         return false;
     m_localServer = new QLocalServer(this);
     connect(m_localServer, SIGNAL(newConnection()),
             this, SLOT(newConnection()));
     bool success = false;
     if (!m_localServer->listen(serverName())) {
         if (QAbstractSocket::AddressInUseError == m_localServer->serverError()) {
             // cleanup from a segfaulted server
 #ifdef Q_OS_UNIX
             QString fullServerName = QDir::tempPath() + QLatin1String("/") + serverName();
             if (QFile::exists(fullServerName))
                 QFile::remove(fullServerName);
 #endif
             if (m_localServer->listen(serverName())) {
                 success = true;
             }
         }
         if (!success) {
             qWarning() << "SingleApplication: Unable to listen:" << m_localServer->errorString();
         }
     } else {
         success = true;
     }
     if (success) {
 #ifdef Q_OS_UNIX
         QFile file(m_localServer->fullServerName());
         if (!file.setPermissions(QFile::ReadUser | QFile::WriteUser))
             qWarning() << "SingleApplication: Unable to set permissions on:"
                        << file.fileName() << file.errorString();
 #endif
     }
     if (!success) {
         delete m_localServer;
         m_localServer = nullptr;
     }
     return success;
 }
References m_localServer, newConnection(), and serverName().
Referenced by BrowserApplication::BrowserApplication().
Member Data Documentation
m_localServer
QLocalServer* SingleApplication::m_localServer private
Definition at line 59 of file singleapplication.h.
Referenced by isRunning(), newConnection(), and startSingleServer().
The documentation for this class was generated from the following files:
src/utils/singleapplication.h
src/utils/singleapplication.cpp