Endorphin: TabBar Class Reference
TabBar Class Reference
#include <tabbar.h>
Signals
void newTab ()
void cloneTab (int index)
void closeTab (int index)
void closeOtherTabs (int index)
void reloadTab (int index)
void reloadAllTabs ()
void loadUrl (const QUrl &url, TabWidget::OpenUrlIn tab)
Public Member Functions
TabBar (QWidget *parent=nullptr)
bool showTabBarWhenOneTab () const
void setShowTabBarWhenOneTab (bool enabled)
QAction * viewTabBarAction () const
QTabBar::ButtonPosition freeSide ()
Protected Member Functions
void mouseDoubleClickEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
QSize tabSizeHint (int index) const
void tabInserted (int position)
void tabRemoved (int position)
Private Slots
void selectTabAction ()
void cloneTab ()
void closeTab ()
void closeOtherTabs ()
void reloadTab ()
void contextMenuRequested (const QPoint &position)
void updateViewToolBarAction ()
void viewTabBar ()
Private Member Functions
void updateVisibility ()
Private Attributes
QPoint m_dragStartPos
QAction * m_viewTabBarAction
bool m_showTabBarWhenOneTab
Friends
class TabWidget
Detailed Description
Definition at line 73 of file tabbar.h.
Constructor & Destructor Documentation
TabBar()
TabBar::TabBar (QWidget * parent = nullptr)
Definition at line 90 of file tabbar.cpp.
     : QTabBar(parent)
     , m_viewTabBarAction(nullptr)
     , m_showTabBarWhenOneTab(true)
 {
     setContextMenuPolicy(Qt::CustomContextMenu);
     setAcceptDrops(true);
     setElideMode(Qt::ElideRight);
     setUsesScrollButtons(true);
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)),
             this, SLOT(contextMenuRequested(const QPoint &)));
     QString alt = QLatin1String("Ctrl+%1");
     for (int i = 0; i < 9; ++i) {
         int key = i + 1;
         TabShortcut *tabShortCut = new TabShortcut(i, alt.arg(key), this);
         connect(tabShortCut, SIGNAL(activated()), this, SLOT(selectTabAction()));
     }
     m_viewTabBarAction = new QAction(this);
     updateViewToolBarAction();
     connect(m_viewTabBarAction, SIGNAL(triggered()),
             this, SLOT(viewTabBar()));
     setMovable(true);
 }
References contextMenuRequested(), m_viewTabBarAction, selectTabAction(), updateViewToolBarAction(), and viewTabBar().
Member Function Documentation
cloneTab [1/2]
void TabBar::cloneTab () private slot
Definition at line 198 of file tabbar.cpp.
 {
     if (QAction *action = qobject_cast<QAction*>(sender())) {
         int index = action->data().toInt();
         emit cloneTab(index);
     }
 }
Referenced by contextMenuRequested().
cloneTab [2/2]
void TabBar::cloneTab (int index) signal
closeOtherTabs [1/2]
void TabBar::closeOtherTabs () private slot
Definition at line 214 of file tabbar.cpp.
 {
     if (QAction *action = qobject_cast<QAction*>(sender())) {
         int index = action->data().toInt();
         emit closeOtherTabs(index);
     }
 }
Referenced by contextMenuRequested().
closeOtherTabs [2/2]
void TabBar::closeOtherTabs (int index) signal
closeTab [1/2]
void TabBar::closeTab () private slot
Definition at line 206 of file tabbar.cpp.
 {
     if (QAction *action = qobject_cast<QAction*>(sender())) {
         int index = action->data().toInt();
         emit closeTab(index);
     }
 }
Referenced by contextMenuRequested(), and mouseReleaseEvent().
closeTab [2/2]
void TabBar::closeTab (int index) signal
contextMenuRequested
void TabBar::contextMenuRequested (const QPoint & position) private slot
Definition at line 160 of file tabbar.cpp.
 {
     QMenu menu;
     TabWidget *tabWidget = qobject_cast<TabWidget*>(parentWidget());
     if (!tabWidget)
         return;
     menu.addAction(tabWidget->newTabAction());
     int index = tabAt(position);
     if (-1 != index) {
         QAction *action = menu.addAction(tr("Duplicate Tab"),
                                          this, SLOT(cloneTab()));
         action->setData(index);
         menu.addSeparator();
         action = menu.addAction(tr("&Close Tab"),
                                 this, SLOT(closeTab()), QKeySequence::Close);
         action->setData(index);
         action = menu.addAction(tr("Close &Other Tabs"),
                                 this, SLOT(closeOtherTabs()));
         action->setData(index);
         menu.addSeparator();
         action = menu.addAction(tr("Reload Tab"),
                                 this, SLOT(reloadTab()), QKeySequence::Refresh);
         action->setData(index);
     } else {
         menu.addSeparator();
     }
     menu.addAction(tr("Reload All Tabs"), this, SIGNAL(reloadAllTabs()));
     menu.addSeparator();
     menu.addAction(tabWidget->bookmarkTabsAction());
     menu.exec(QCursor::pos());
 }
References TabWidget::bookmarkTabsAction(), cloneTab(), closeOtherTabs(), closeTab(), TabWidget::newTabAction(), reloadAllTabs(), and reloadTab().
Referenced by TabBar().
dragEnterEvent()
void TabBar::dragEnterEvent (QDragEnterEvent * event) protected
Definition at line 280 of file tabbar.cpp.
 {
     const QMimeData *mimeData = event->mimeData();
     if (mimeData->hasUrls() || mimeData->hasText())
         event->acceptProposedAction();
     QTabBar::dragEnterEvent(event);
 }
dropEvent()
void TabBar::dropEvent (QDropEvent * event) protected
Definition at line 289 of file tabbar.cpp.
 {
     const QMimeData *mimeData = event->mimeData();
     QUrl url;
     if (mimeData->hasUrls())
         url = mimeData->urls().at(0);
     else if (mimeData->hasText())
         url = QUrl::fromEncoded(mimeData->text().toUtf8());
     if (!url.isEmpty() && url.isValid()) {
         event->acceptProposedAction();
         int index = tabAt(event->pos());
         if (-1 != index) {
             setCurrentIndex(index);
             emit loadUrl(url, TabWidget::CurrentTab);
         } else {
             emit loadUrl(url, TabWidget::NewSelectedTab);
         }
     }
     QTabBar::dropEvent(event);
 }
References TabWidget::CurrentTab, loadUrl(), and TabWidget::NewSelectedTab.
freeSide()
QTabBar::ButtonPosition TabBar::freeSide ()
Definition at line 133 of file tabbar.cpp.
 {
     QTabBar::ButtonPosition side = (QTabBar::ButtonPosition)style()->styleHint(QStyle::SH_TabBar_CloseButtonPosition, nullptr, this);
     side = (side == QTabBar::LeftSide) ? QTabBar::RightSide : QTabBar::LeftSide;
     return side;
 }
Referenced by TabWidget::animationLabel(), and TabWidget::webViewLoadFinished().
loadUrl
void TabBar::loadUrl (const QUrl & url, TabWidget::OpenUrlIn tab) signal
Referenced by dropEvent(), and mouseReleaseEvent().
mouseDoubleClickEvent()
void TabBar::mouseDoubleClickEvent (QMouseEvent * event) protected
Definition at line 222 of file tabbar.cpp.
 {
     if (event->button() == Qt::LeftButton
             && tabAt(event->pos()) == -1) {
         emit newTab();
         return;
     }
     QTabBar::mouseDoubleClickEvent(event);
 }
References newTab().
mouseMoveEvent()
void TabBar::mouseMoveEvent (QMouseEvent * event) protected
Definition at line 256 of file tabbar.cpp.
 {
     if (event->buttons() == Qt::LeftButton) {
         int diffX = event->pos().x() - m_dragStartPos.x();
         int diffY = event->pos().y() - m_dragStartPos.y();
         if ((event->pos() - m_dragStartPos).manhattanLength() > QApplication::startDragDistance()
                 && diffX < 3 && diffX > -3
                 && diffY < -10) {
             QDrag *drag = new QDrag(this);
             QMimeData *mimeData = new QMimeData;
             QList<QUrl> urls;
             int index = tabAt(event->pos());
             QUrl url = tabData(index).toUrl();
             urls.append(url);
             mimeData->setUrls(urls);
             mimeData->setText(tabText(index));
             mimeData->setData(QLatin1String("action"), "tab-reordering");
             drag->setMimeData(mimeData);
             drag->exec();
         }
     }
     QTabBar::mouseMoveEvent(event);
 }
References m_dragStartPos.
mousePressEvent()
void TabBar::mousePressEvent (QMouseEvent * event) protected
Definition at line 249 of file tabbar.cpp.
 {
     if (event->button() == Qt::LeftButton)
         m_dragStartPos = event->pos();
     QTabBar::mousePressEvent(event);
 }
References m_dragStartPos.
mouseReleaseEvent()
void TabBar::mouseReleaseEvent (QMouseEvent * event) protected
Definition at line 232 of file tabbar.cpp.
 {
     if (event->button() == Qt::MidButton) {
         int index = tabAt(event->pos());
         if (index != -1) {
             emit closeTab(index);
             return;
         } else {
             QUrl url(QApplication::clipboard()->text(QClipboard::Selection));
             if (!url.isEmpty() && url.isValid() && !url.scheme().isEmpty())
                 emit loadUrl(url, TabWidget::NewTab);
         }
     }
     QTabBar::mouseReleaseEvent(event);
 }
References closeTab(), loadUrl(), and TabWidget::NewTab.
newTab
void TabBar::newTab () signal
Referenced by mouseDoubleClickEvent().
reloadAllTabs
void TabBar::reloadAllTabs () signal
Referenced by contextMenuRequested().
reloadTab [1/2]
void TabBar::reloadTab () private slot
Definition at line 319 of file tabbar.cpp.
 {
     if (QAction *action = qobject_cast<QAction*>(sender())) {
         int index = action->data().toInt();
         emit reloadTab(index);
     }
 }
Referenced by contextMenuRequested().
reloadTab [2/2]
void TabBar::reloadTab (int index) signal
selectTabAction
void TabBar::selectTabAction () private slot
Definition at line 154 of file tabbar.cpp.
 {
     int index = qobject_cast<TabShortcut*>(sender())->tab();
     setCurrentIndex(index);
 }
Referenced by TabBar().
setShowTabBarWhenOneTab()
void TabBar::setShowTabBarWhenOneTab (bool enabled)
Definition at line 122 of file tabbar.cpp.
 {
     m_showTabBarWhenOneTab = enabled;
     updateVisibility();
 }
References m_showTabBarWhenOneTab, and updateVisibility().
Referenced by BrowserMainWindow::restoreState(), and viewTabBar().
showTabBarWhenOneTab()
bool TabBar::showTabBarWhenOneTab () const
Definition at line 117 of file tabbar.cpp.
 {
     return m_showTabBarWhenOneTab;
 }
References m_showTabBarWhenOneTab.
Referenced by BrowserMainWindow::saveState(), updateViewToolBarAction(), and viewTabBar().
tabInserted()
void TabBar::tabInserted (int position) protected
Definition at line 327 of file tabbar.cpp.
 {
     Q_UNUSED(position);
     updateVisibility();
 }
References updateVisibility().
tabRemoved()
void TabBar::tabRemoved (int position) protected
Definition at line 333 of file tabbar.cpp.
 {
     Q_UNUSED(position);
     updateVisibility();
 }
References updateVisibility().
tabSizeHint()
QSize TabBar::tabSizeHint (int index) const protected
Definition at line 312 of file tabbar.cpp.
 {
     QSize sizeHint = QTabBar::tabSizeHint(index);
     QFontMetrics fm = fontMetrics();
     return sizeHint.boundedTo(QSize(fm.horizontalAdvance(QLatin1Char('M')) * 18, sizeHint.height()));
 }
updateViewToolBarAction
void TabBar::updateViewToolBarAction () private slot
Definition at line 140 of file tabbar.cpp.
 {
     bool show = showTabBarWhenOneTab();
     if (count() > 1)
         show = true;
     m_viewTabBarAction->setText(!show ? tr("Show Tab Bar") : tr("Hide Tab Bar"));
 }
References m_viewTabBarAction, and showTabBarWhenOneTab().
Referenced by TabWidget::retranslate(), TabBar(), updateVisibility(), and viewTabBar().
updateVisibility()
void TabBar::updateVisibility () private
Definition at line 339 of file tabbar.cpp.
 {
     setVisible((count()) > 1 || m_showTabBarWhenOneTab);
     bool enabled = (count() == 1);
     if (m_viewTabBarAction->isEnabled() != enabled)
         m_viewTabBarAction->setEnabled(enabled);
     updateViewToolBarAction();
 }
References m_showTabBarWhenOneTab, m_viewTabBarAction, and updateViewToolBarAction().
Referenced by setShowTabBarWhenOneTab(), tabInserted(), and tabRemoved().
viewTabBar
void TabBar::viewTabBar () private slot
Definition at line 148 of file tabbar.cpp.
 {
     setShowTabBarWhenOneTab(!showTabBarWhenOneTab());
     updateViewToolBarAction();
 }
References setShowTabBarWhenOneTab(), showTabBarWhenOneTab(), and updateViewToolBarAction().
Referenced by TabBar().
viewTabBarAction()
QAction * TabBar::viewTabBarAction () const
Definition at line 128 of file tabbar.cpp.
 {
     return m_viewTabBarAction;
 }
References m_viewTabBarAction.
Referenced by BrowserMainWindow::setupMenu().
Friends And Related Function Documentation
TabWidget
friend class TabWidget friend
Definition at line 158 of file tabbar.h.
Member Data Documentation
m_dragStartPos
QPoint TabBar::m_dragStartPos private
Definition at line 160 of file tabbar.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_showTabBarWhenOneTab
bool TabBar::m_showTabBarWhenOneTab private
Definition at line 162 of file tabbar.h.
Referenced by setShowTabBarWhenOneTab(), showTabBarWhenOneTab(), and updateVisibility().
m_viewTabBarAction
QAction* TabBar::m_viewTabBarAction private
Definition at line 161 of file tabbar.h.
Referenced by TabBar(), updateViewToolBarAction(), updateVisibility(), and viewTabBarAction().
The documentation for this class was generated from the following files:
src/tabbar.h
src/tabbar.cpp