Endorphin: BookmarksMenu Class Reference
BookmarksMenu Class Reference
#include <bookmarksmenu.h>
Signals
void openUrl (const QUrl &url, const QString &title)
void openUrl (const QUrl &url, TabWidget::OpenUrlIn tab, const QString &title)
Signals inherited from ModelMenu
void activated (const QModelIndex &index)
Public Member Functions
BookmarksMenu (QWidget *parent=nullptr)
Public Member Functions inherited from ModelMenu
ModelMenu (QWidget *parent=nullptr)
void setModel (QAbstractItemModel *model)
QAbstractItemModel * model () const
void setMaxRows (int max)
int maxRows () const
void setFirstSeparator (int offset)
int firstSeparator () const
void setRootIndex (const QModelIndex &index)
QModelIndex rootIndex () const
void setStatusBarTextRole (int role)
int statusBarTextRole () const
void setSeparatorRole (int role)
int separatorRole () const
QAction * makeAction (const QIcon &icon, const QString &text, QObject *parent)
QModelIndex index (QAction *action)
Protected Member Functions
void postPopulated ()
ModelMenu * createBaseMenu ()
Protected Member Functions inherited from ModelMenu
virtual bool prePopulated ()
void createMenu (const QModelIndex &parent, int max, QMenu *parentMenu=nullptr, QMenu *menu=nullptr)
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
Private Slots
void openAll ()
void activated (const QModelIndex &index)
Detailed Description
Definition at line 76 of file bookmarksmenu.h.
Constructor & Destructor Documentation
BookmarksMenu()
BookmarksMenu::BookmarksMenu (QWidget * parent = nullptr)
Definition at line 76 of file bookmarksmenu.cpp.
     : ModelMenu(parent)
 {
     connect(this, SIGNAL(activated(const QModelIndex &)),
             this, SLOT(activated(const QModelIndex &)));
     setStatusBarTextRole(BookmarksModel::UrlStringRole);
     setSeparatorRole(BookmarksModel::SeparatorRole);
 }
References activated(), BookmarksModel::SeparatorRole, ModelMenu::setSeparatorRole(), ModelMenu::setStatusBarTextRole(), and BookmarksModel::UrlStringRole.
Referenced by createBaseMenu().
Member Function Documentation
activated
void BookmarksMenu::activated (const QModelIndex & index) private slot
Definition at line 93 of file bookmarksmenu.cpp.
 {
     emit openUrl(index.data(BookmarksModel::UrlRole).toUrl(),
                  index.data(Qt::DisplayRole).toString());
 }
References ModelMenu::index(), openUrl(), and BookmarksModel::UrlRole.
Referenced by BookmarksMenu().
createBaseMenu()
ModelMenu * BookmarksMenu::createBaseMenu () protected virtual
Reimplemented from ModelMenu.
Definition at line 85 of file bookmarksmenu.cpp.
 {
     BookmarksMenu *menu = new BookmarksMenu(this);
     connect(menu, SIGNAL(openUrl(const QUrl&, TabWidget::OpenUrlIn, const QString&)),
             this, SIGNAL(openUrl(const QUrl&, TabWidget::OpenUrlIn, const QString&)));
     return menu;
 }
References BookmarksMenu(), and openUrl().
openAll
void BookmarksMenu::openAll () private slot
Definition at line 126 of file bookmarksmenu.cpp.
 {
     ModelMenu *menu = qobject_cast<ModelMenu*>(sender()->parent());
     if (!menu)
         return;
     QModelIndex parent = menu->rootIndex();
     if (!parent.isValid())
         return;
     for (int i = 0; i < parent.model()->rowCount(parent); ++i) {
         QModelIndex child = parent.model()->index(i, 0, parent);
         if (child.data(BookmarksModel::TypeRole) != BookmarkNode::Bookmark)
             continue;
         TabWidget::OpenUrlIn tab;
         tab = (i == 0) ? TabWidget::CurrentTab : TabWidget::NewTab;
         emit openUrl(child.data(BookmarksModel::UrlRole).toUrl(),
                      tab,
                      child.data(Qt::DisplayRole).toString());
     }
 }
References BookmarkNode::Bookmark, TabWidget::CurrentTab, TabWidget::NewTab, openUrl(), ModelMenu::rootIndex(), BookmarksModel::TypeRole, and BookmarksModel::UrlRole.
Referenced by postPopulated().
openUrl [1/2]
void BookmarksMenu::openUrl (const QUrl & url, const QString & title) signal
Referenced by activated(), createBaseMenu(), and openAll().
openUrl [2/2]
void BookmarksMenu::openUrl (const QUrl & url, TabWidget::OpenUrlIn tab, const QString & title) signal
postPopulated()
void BookmarksMenu::postPopulated () protected virtual
Reimplemented from ModelMenu.
Definition at line 99 of file bookmarksmenu.cpp.
 {
     if (isEmpty())
         return;
     QModelIndex parent = rootIndex();
     bool hasBookmarks = false;
     for (int i = 0; i < parent.model()->rowCount(parent); ++i) {
         QModelIndex child = parent.model()->index(i, 0, parent);
         if (child.data(BookmarksModel::TypeRole) == BookmarkNode::Bookmark) {
             hasBookmarks = true;
             break;
         }
     }
     if (!hasBookmarks)
         return;
     addSeparator();
     QAction *action = addAction(tr("Open in Tabs"));
     connect(action, SIGNAL(triggered()),
             this, SLOT(openAll()));
 }
References BookmarkNode::Bookmark, openAll(), ModelMenu::rootIndex(), and BookmarksModel::TypeRole.
The documentation for this class was generated from the following files:
src/bookmarks/bookmarksmenu.h
src/bookmarks/bookmarksmenu.cpp