Endorphin: HistoryDialog Class Reference
HistoryDialog Class Reference
#include <history.h>
Signals
void openUrl (const QUrl &url, const QString &title)
Public Member Functions
HistoryDialog (QWidget *parent=nullptr, HistoryManager *history=nullptr)
Private Slots
void customContextMenuRequested (const QPoint &pos)
void open ()
void copy ()
Detailed Description
Definition at line 279 of file history.h.
Constructor & Destructor Documentation
HistoryDialog()
HistoryDialog::HistoryDialog (QWidget * parent = nullptr, HistoryManager * history = nullptr)
Definition at line 416 of file history.cpp.
                                                                         : QDialog(parent)
 {
     HistoryManager *history = setHistory;
     if (!history)
         history = BrowserApplication::historyManager();
     setupUi(this);
     tree->setUniformRowHeights(true);
     tree->setSelectionBehavior(QAbstractItemView::SelectRows);
     tree->setSelectionMode(QAbstractItemView::ExtendedSelection);
     tree->setTextElideMode(Qt::ElideMiddle);
     QAbstractItemModel *model = history->historyTreeModel();
     TreeSortFilterProxyModel *proxyModel = new TreeSortFilterProxyModel(this);
     proxyModel->setSortRole(HistoryModel::DateTimeRole);
     proxyModel->setFilterKeyColumn(-1);
     connect(search, SIGNAL(textChanged(QString)),
             proxyModel, SLOT(setFilterFixedString(QString)));
     connect(removeButton, SIGNAL(clicked()), tree, SLOT(removeSelected()));
     connect(removeAllButton, SIGNAL(clicked()), history, SLOT(clear()));
     proxyModel->setSourceModel(model);
     tree->setModel(proxyModel);
     tree->setExpanded(proxyModel->index(0, 0), true);
     tree->setAlternatingRowColors(true);
     QFontMetrics fm(font());
     int header = fm.horizontalAdvance(QLatin1Char('m')) * 40;
     tree->header()->resizeSection(0, header);
     tree->header()->setStretchLastSection(true);
     connect(tree, SIGNAL(activated(const QModelIndex&)),
             this, SLOT(open()));
     tree->setContextMenuPolicy(Qt::CustomContextMenu);
     connect(tree, SIGNAL(customContextMenuRequested(const QPoint &)),
             this, SLOT(customContextMenuRequested(const QPoint &)));
 }
References customContextMenuRequested(), HistoryModel::DateTimeRole, BrowserApplication::historyManager(), HistoryManager::historyTreeModel(), and open().
Member Function Documentation
copy
void HistoryDialog::copy () private slot
Definition at line 474 of file history.cpp.
 {
     QModelIndex index = tree->currentIndex();
     if (!index.parent().isValid())
         return;
     QString url = index.data(HistoryModel::UrlStringRole).toString();
     QClipboard *clipboard = QApplication::clipboard();
     clipboard->setText(url);
 }
References HistoryModel::UrlStringRole.
Referenced by customContextMenuRequested().
customContextMenuRequested
void HistoryDialog::customContextMenuRequested (const QPoint & pos) private slot
Definition at line 449 of file history.cpp.
 {
     QMenu menu;
     QModelIndex index = tree->indexAt(pos);
     index = index.sibling(index.row(), 0);
     if (index.isValid() && !tree->model()->hasChildren(index)) {
         menu.addAction(tr("Open"), this, SLOT(open()));
         menu.addSeparator();
         menu.addAction(tr("Copy"), this, SLOT(copy()));
     }
     menu.addAction(tr("Delete"), tree, SLOT(removeSelected()));
     menu.exec(QCursor::pos());
 }
References copy(), and open().
Referenced by HistoryDialog().
open
void HistoryDialog::open () private slot
Definition at line 463 of file history.cpp.
 {
     QModelIndex index = tree->currentIndex();
     if (!index.parent().isValid())
         return;
     BrowserApplication::instance()->setEventMouseButtons(qApp->mouseButtons());
     BrowserApplication::instance()->setEventKeyboardModifiers(qApp->keyboardModifiers());
     emit openUrl(index.data(HistoryModel::UrlRole).toUrl(),
                  index.data(HistoryModel::TitleRole).toString());
 }
References BrowserApplication::instance(), openUrl(), BrowserApplication::setEventKeyboardModifiers(), BrowserApplication::setEventMouseButtons(), HistoryModel::TitleRole, and HistoryModel::UrlRole.
Referenced by customContextMenuRequested(), and HistoryDialog().
openUrl
void HistoryDialog::openUrl (const QUrl & url, const QString & title) signal
Referenced by open().
The documentation for this class was generated from the following files:
src/history/history.h
src/history/history.cpp