Endorphin: LocationBarSiteIcon Class Reference
LocationBarSiteIcon Class Reference
#include <locationbarsiteicon.h>
Public Member Functions
LocationBarSiteIcon (QWidget *parent=nullptr)
void setWebView (WebView *webView)
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
Private Slots
void webViewSiteIconChanged ()
Private Attributes
WebView * m_webView
QPoint m_dragStartPos
Detailed Description
Definition at line 26 of file locationbarsiteicon.h.
Constructor & Destructor Documentation
LocationBarSiteIcon()
LocationBarSiteIcon::LocationBarSiteIcon (QWidget * parent = nullptr)
Definition at line 30 of file locationbarsiteicon.cpp.
     : QLabel(parent)
     , m_webView(nullptr)
 {
     resize(QSize(16, 16));
     webViewSiteIconChanged();
     setCursor(Qt::ArrowCursor);
     show();
 }
References webViewSiteIconChanged().
Member Function Documentation
mouseMoveEvent()
void LocationBarSiteIcon::mouseMoveEvent (QMouseEvent * event) protected
Definition at line 64 of file locationbarsiteicon.cpp.
 {
     if (event->buttons() == Qt::LeftButton
             && (event->pos() - m_dragStartPos).manhattanLength() > QApplication::startDragDistance()
             && m_webView) {
         QDrag *drag = new QDrag(this);
         QMimeData *mimeData = new QMimeData;
         QString title = m_webView->title();
         if (title.isEmpty())
             title = QString::fromUtf8(m_webView->url().toEncoded());
         mimeData->setText(title);
         QList<QUrl> urls;
         urls.append(m_webView->url());
         mimeData->setUrls(urls);
         const QPixmap *p = pixmap();
         if (p)
             drag->setPixmap(*p);
         drag->setMimeData(mimeData);
         drag->exec();
     }
 }
References m_dragStartPos, m_webView, and WebView::url().
mousePressEvent()
void LocationBarSiteIcon::mousePressEvent (QMouseEvent * event) protected
Definition at line 57 of file locationbarsiteicon.cpp.
 {
     if (event->button() == Qt::LeftButton)
         m_dragStartPos = event->pos();
     QLabel::mousePressEvent(event);
 }
References m_dragStartPos.
setWebView()
void LocationBarSiteIcon::setWebView (WebView * webView)
Definition at line 40 of file locationbarsiteicon.cpp.
 {
     m_webView = webView;
     connect(webView, SIGNAL(loadFinished(bool)),
             this, SLOT(webViewSiteIconChanged()));
     connect(webView, SIGNAL(iconChanged(QIcon)),
             this, SLOT(webViewSiteIconChanged()));
 }
References m_webView, and webViewSiteIconChanged().
Referenced by LocationBar::setWebView().
webViewSiteIconChanged
void LocationBarSiteIcon::webViewSiteIconChanged () private slot
Definition at line 49 of file locationbarsiteicon.cpp.
 {
     QUrl url;
     if (m_webView)
         url = m_webView->url();
     setPixmap(BrowserApplication::instance()->icon(url).pixmap(16, 16));
 }
References BrowserApplication::instance(), m_webView, and WebView::url().
Referenced by LocationBarSiteIcon(), and setWebView().
Member Data Documentation
m_dragStartPos
QPoint LocationBarSiteIcon::m_dragStartPos private
Definition at line 43 of file locationbarsiteicon.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_webView
WebView* LocationBarSiteIcon::m_webView private
Definition at line 42 of file locationbarsiteicon.h.
Referenced by mouseMoveEvent(), setWebView(), and webViewSiteIconChanged().
The documentation for this class was generated from the following files:
src/locationbar/locationbarsiteicon.h
src/locationbar/locationbarsiteicon.cpp