Endorphin: HistoryMenu Class Reference
HistoryMenu Class Reference
#include <history.h>
Signals
void openUrl (const QUrl &url, const QString &title)
Signals inherited from ModelMenu
void activated (const QModelIndex &index)
Public Member Functions
HistoryMenu (QWidget *parent=nullptr)
void setInitialActions (QList< QAction * > actions)
Public Member Functions inherited from ModelMenu
ModelMenu (QWidget *parent=nullptr)
void setModel (QAbstractItemModel *model)
QAbstractItemModel * model () const
void setMaxRows (int max)
int maxRows () const
void setFirstSeparator (int offset)
int firstSeparator () const
void setRootIndex (const QModelIndex &index)
QModelIndex rootIndex () const
void setStatusBarTextRole (int role)
int statusBarTextRole () const
void setSeparatorRole (int role)
int separatorRole () const
QAction * makeAction (const QIcon &icon, const QString &text, QObject *parent)
QModelIndex index (QAction *action)
Protected Member Functions
bool prePopulated ()
void postPopulated ()
Protected Member Functions inherited from ModelMenu
virtual ModelMenu * createBaseMenu ()
void createMenu (const QModelIndex &parent, int max, QMenu *parentMenu=nullptr, QMenu *menu=nullptr)
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
Private Slots
void activated (const QModelIndex &index)
void showHistoryDialog ()
void clearHistoryDialog ()
Private Attributes
HistoryManager * m_history
HistoryMenuModel * m_historyMenuModel
QList< QAction * > m_initialActions
Detailed Description
Definition at line 214 of file history.h.
Constructor & Destructor Documentation
HistoryMenu()
HistoryMenu::HistoryMenu (QWidget * parent = nullptr)
Definition at line 341 of file history.cpp.
     : ModelMenu(parent)
     , m_history(nullptr)
     , m_historyMenuModel(nullptr)
 {
     setMaxRows(7);
     connect(this, SIGNAL(activated(const QModelIndex &)),
             this, SLOT(activated(const QModelIndex &)));
     setStatusBarTextRole(HistoryModel::UrlStringRole);
 }
References activated(), ModelMenu::setMaxRows(), ModelMenu::setStatusBarTextRole(), and HistoryModel::UrlStringRole.
Member Function Documentation
activated
void HistoryMenu::activated (const QModelIndex & index) private slot
Definition at line 352 of file history.cpp.
 {
     emit openUrl(index.data(HistoryModel::UrlRole).toUrl(),
                  index.data(HistoryModel::TitleRole).toString());
 }
References ModelMenu::index(), openUrl(), HistoryModel::TitleRole, and HistoryModel::UrlRole.
Referenced by HistoryMenu().
clearHistoryDialog
void HistoryMenu::clearHistoryDialog () private slot
Definition at line 401 of file history.cpp.
 {
     if (m_history && QMessageBox::question(nullptr, tr("Clear History"), tr("Do you want to clear the history?"),
                                            QMessageBox::Yes | QMessageBox::No, QMessageBox::No) == QMessageBox::Yes) {
         m_history->clear();
     }
 }
References HistoryManager::clear(), and m_history.
Referenced by postPopulated().
openUrl
void HistoryMenu::openUrl (const QUrl & url, const QString & title) signal
Referenced by activated(), and showHistoryDialog().
postPopulated()
void HistoryMenu::postPopulated () protected virtual
Reimplemented from ModelMenu.
Definition at line 375 of file history.cpp.
 {
     if (m_history->history().count() > 0)
         addSeparator();
     QAction *showAllAction = new QAction(tr("Show All History"), this);
 #if !defined(Q_WS_MAC)
     showAllAction->setShortcut(QKeySequence(Qt::CTRL | Qt::Key_H));
 #endif
     connect(showAllAction, SIGNAL(triggered()), this, SLOT(showHistoryDialog()));
     addAction(showAllAction);
     QAction *clearAction = new QAction(tr("Clear History..."), this);
     connect(clearAction, SIGNAL(triggered()), this, SLOT(clearHistoryDialog()));
     addAction(clearAction);
 }
References clearHistoryDialog(), HistoryManager::history(), m_history, and showHistoryDialog().
prePopulated()
bool HistoryMenu::prePopulated () protected virtual
Reimplemented from ModelMenu.
Definition at line 358 of file history.cpp.
 {
     if (!m_history) {
         m_history = BrowserApplication::historyManager();
         m_historyMenuModel = new HistoryMenuModel(m_history->historyTreeModel(), this);
         setModel(m_historyMenuModel);
     }
     // initial actions
     for (int i = 0; i < m_initialActions.count(); ++i)
         addAction(m_initialActions.at(i));
     if (!m_initialActions.isEmpty())
         addSeparator();
     setFirstSeparator(m_historyMenuModel->bumpedRows());
     return false;
 }
References HistoryMenuModel::bumpedRows(), BrowserApplication::historyManager(), HistoryManager::historyTreeModel(), m_history, m_historyMenuModel, m_initialActions, ModelMenu::setFirstSeparator(), and ModelMenu::setModel().
setInitialActions()
void HistoryMenu::setInitialActions (QList< QAction * > actions)
Definition at line 409 of file history.cpp.
 {
     m_initialActions = actions;
     for (int i = 0; i < m_initialActions.count(); ++i)
         addAction(m_initialActions.at(i));
 }
References m_initialActions.
Referenced by BrowserMainWindow::setupMenu().
showHistoryDialog
void HistoryMenu::showHistoryDialog () private slot
Definition at line 392 of file history.cpp.
 {
     HistoryDialog *dialog = new HistoryDialog(this);
     dialog->setAttribute(Qt::WA_DeleteOnClose);
     connect(dialog, SIGNAL(openUrl(const QUrl&, const QString &)),
             this, SIGNAL(openUrl(const QUrl&, const QString &)));
     dialog->show();
 }
References openUrl().
Referenced by postPopulated().
Member Data Documentation
m_history
HistoryManager* HistoryMenu::m_history private
Definition at line 235 of file history.h.
Referenced by clearHistoryDialog(), postPopulated(), and prePopulated().
m_historyMenuModel
HistoryMenuModel* HistoryMenu::m_historyMenuModel private
Definition at line 236 of file history.h.
Referenced by prePopulated().
m_initialActions
QList<QAction*> HistoryMenu::m_initialActions private
Definition at line 237 of file history.h.
Referenced by prePopulated(), and setInitialActions().
The documentation for this class was generated from the following files:
src/history/history.h
src/history/history.cpp