Endorphin: PlainTextEditSearch Class Reference
PlainTextEditSearch Class Reference
#include <plaintexteditsearch.h>
Public Slots
void findNext ()
void findPrevious ()
Public Slots inherited from SearchBar
void animateHide ()
void clear ()
void showFind ()
virtual void findNext ()=0
virtual void findPrevious ()=0
Public Member Functions
PlainTextEditSearch (QPlainTextEdit *plainTextEdit, QWidget *parent=nullptr)
Public Member Functions inherited from SearchBar
SearchBar (QWidget *parent=nullptr)
void setSearchObject (QObject *object)
QObject * searchObject () const
Private Member Functions
void find (QTextDocument::FindFlags flags)
Private Attributes
QPlainTextEdit * m_edit
QString m_lastSearchTerm
Additional Inherited Members
Protected Member Functions inherited from SearchBar
void resizeEvent (QResizeEvent *event)
Protected Attributes inherited from SearchBar
Ui_SearchBanner ui
Detailed Description
Definition at line 28 of file plaintexteditsearch.h.
Constructor & Destructor Documentation
PlainTextEditSearch()
PlainTextEditSearch::PlainTextEditSearch (QPlainTextEdit * plainTextEdit, QWidget * parent = nullptr)
Definition at line 25 of file plaintexteditsearch.cpp.
     : SearchBar(parent)
     , m_edit(plainTextEdit)
 {
     setSearchObject(plainTextEdit);
 }
References SearchBar::setSearchObject().
Member Function Documentation
find()
void PlainTextEditSearch::find (QTextDocument::FindFlags flags) private
Definition at line 42 of file plaintexteditsearch.cpp.
 {
     QString searchString = ui.searchLineEdit->text();
     if (!m_edit || searchString.isEmpty())
         return;
     if (searchString != m_lastSearchTerm) {
         QTextCursor cursor = m_edit->textCursor();
         cursor.setPosition(cursor.selectionStart());
         cursor.clearSelection();
         m_edit->setTextCursor(cursor);
         m_lastSearchTerm = searchString;
     }
     QString infoString;
     if (!m_edit->find(searchString, flags)) {
         /* no support for wrapping so we set the cursor to start */
         QTextCursor cursor = m_edit->textCursor();
         m_edit->moveCursor(QTextCursor::Start);
         /* ...search again from the beginning */
         if (!m_edit->find(searchString,flags)) {
             /* and if there's still nothing, we revert the cursor */
             infoString = tr("Not Found");
             cursor.clearSelection();
             m_edit->setTextCursor(cursor);
         }
     }
     ui.searchInfo->setText(infoString);
 }
References m_edit, m_lastSearchTerm, and SearchBar::ui.
Referenced by findNext(), and findPrevious().
findNext
void PlainTextEditSearch::findNext () slot
Definition at line 32 of file plaintexteditsearch.cpp.
 {
     find(0);
 }
References find().
findPrevious
void PlainTextEditSearch::findPrevious () slot
Definition at line 37 of file plaintexteditsearch.cpp.
 {
     find(QTextDocument::FindBackward);
 }
References find().
Member Data Documentation
m_edit
QPlainTextEdit* PlainTextEditSearch::m_edit private
Definition at line 41 of file plaintexteditsearch.h.
Referenced by find().
m_lastSearchTerm
QString PlainTextEditSearch::m_lastSearchTerm private
Definition at line 42 of file plaintexteditsearch.h.
Referenced by find().
The documentation for this class was generated from the following files:
src/plaintexteditsearch.h
src/plaintexteditsearch.cpp