Endorphin: LocationBar Class Reference
LocationBar Class Reference
#include <locationbar.h>
Public Member Functions
LocationBar (QWidget *parent=nullptr)
void setWebView (WebView *webView)
WebView * webView () const
Public Member Functions inherited from LineEdit
LineEdit (QWidget *parent=nullptr)
LineEdit (const QString &contents, QWidget *parent=nullptr)
void addWidget (QWidget *widget, WidgetPosition position)
void removeWidget (QWidget *widget)
void setWidgetSpacing (int spacing)
int widgetSpacing () const
int textMargin (WidgetPosition position) const
QString inactiveText () const
void setInactiveText (const QString &text)
void paintEvent (QPaintEvent *event)
Protected Member Functions
void paintEvent (QPaintEvent *event)
void focusOutEvent (QFocusEvent *event)
void mouseDoubleClickEvent (QMouseEvent *event)
void keyPressEvent (QKeyEvent *event)
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
Protected Member Functions inherited from LineEdit
void resizeEvent (QResizeEvent *event)
bool event (QEvent *event)
Private Slots
void webViewUrlChanged (const QUrl &url)
Private Attributes
QPointer< WebView > m_webView
LocationBarSiteIcon * m_siteIcon
PrivacyIndicator * m_privacyIndicator
Additional Inherited Members
Public Types inherited from LineEdit
enum WidgetPosition { LeftSide, RightSide }
Protected Slots inherited from LineEdit
void updateTextMargins ()
Properties inherited from LineEdit
QString inactiveText
Detailed Description
Definition at line 31 of file locationbar.h.
Constructor & Destructor Documentation
LocationBar()
LocationBar::LocationBar (QWidget * parent = nullptr)
Definition at line 37 of file locationbar.cpp.
     : LineEdit(parent)
     , m_webView(nullptr)
     , m_siteIcon(nullptr)
     , m_privacyIndicator(nullptr)
 {
     // Urls are always LeftToRight
     setLayoutDirection(Qt::LeftToRight);
     setUpdatesEnabled(false);
     // site icon on the left
     m_siteIcon = new LocationBarSiteIcon(this);
     addWidget(m_siteIcon, LeftSide);
     // privacy indicator at rightmost position
     m_privacyIndicator = new PrivacyIndicator(this);
     addWidget(m_privacyIndicator, RightSide);
     // clear button on the right
     ClearButton *m_clearButton = new ClearButton(this);
     connect(m_clearButton, SIGNAL(clicked()),
             this, SLOT(clear()));
     connect(this, SIGNAL(textChanged(const QString&)),
             m_clearButton, SLOT(textChanged(const QString&)));
     addWidget(m_clearButton, RightSide);
     updateTextMargins();
     setUpdatesEnabled(true);
 }
References LineEdit::addWidget(), LineEdit::LeftSide, m_privacyIndicator, m_siteIcon, LineEdit::RightSide, and LineEdit::updateTextMargins().
Member Function Documentation
dragEnterEvent()
void LocationBar::dragEnterEvent (QDragEnterEvent * event) protected
Definition at line 180 of file locationbar.cpp.
 {
     const QMimeData *mimeData = event->mimeData();
     if (mimeData->hasUrls() || mimeData->hasText())
         event->acceptProposedAction();
     LineEdit::dragEnterEvent(event);
 }
References LineEdit::event().
dropEvent()
void LocationBar::dropEvent (QDropEvent * event) protected
Definition at line 189 of file locationbar.cpp.
 {
     const QMimeData *mimeData = event->mimeData();
     QUrl url;
     if (mimeData->hasUrls())
         url = mimeData->urls().at(0);
     else if (mimeData->hasText())
         url = QUrl::fromEncoded(mimeData->text().toUtf8(), QUrl::TolerantMode);
     if (url.isEmpty() || !url.isValid()) {
         LineEdit::dropEvent(event);
         return;
     }
     setText(QString::fromUtf8(url.toEncoded()));
     selectAll();
     event->acceptProposedAction();
 }
References LineEdit::event().
focusOutEvent()
void LocationBar::focusOutEvent (QFocusEvent * event) protected
Definition at line 135 of file locationbar.cpp.
 {
     if (text().isEmpty() && m_webView)
         webViewUrlChanged(m_webView->url());
     QLineEdit::focusOutEvent(event);
 }
References LineEdit::event(), m_webView, and webViewUrlChanged().
keyPressEvent()
void LocationBar::keyPressEvent (QKeyEvent * event) protected
Definition at line 150 of file locationbar.cpp.
 {
     if (event->key() == Qt::Key_Escape && m_webView) {
         setText(QString::fromUtf8(m_webView->url().toEncoded()));
         selectAll();
         return;
     }
     QString currentText = text().trimmed();
     if ((event->key() == Qt::Key_Enter || event->key() == Qt::Key_Return)
             && !currentText.startsWith(QLatin1String("http://"), Qt::CaseInsensitive)) {
         QString append;
         if (event->modifiers() == Qt::ControlModifier)
             append = QLatin1String(".com");
         else if (event->modifiers() == (Qt::ControlModifier | Qt::ShiftModifier))
             append = QLatin1String(".org");
         else if (event->modifiers() == Qt::ShiftModifier)
             append = QLatin1String(".net");
         QUrl url(QLatin1String("http://") + currentText);
         QString host = url.host();
         if (!host.endsWith(append, Qt::CaseInsensitive)) {
             host += append;
             url.setHost(host);
             setText(url.toString());
         }
     }
     LineEdit::keyPressEvent(event);
 }
References LineEdit::event(), and m_webView.
mouseDoubleClickEvent()
void LocationBar::mouseDoubleClickEvent (QMouseEvent * event) protected
Definition at line 142 of file locationbar.cpp.
 {
     if (event->button() == Qt::LeftButton)
         selectAll();
     else
         QLineEdit::mouseDoubleClickEvent(event);
 }
References LineEdit::event().
paintEvent()
void LocationBar::paintEvent (QPaintEvent * event) protected
Definition at line 103 of file locationbar.cpp.
 {
     QPalette p = palette();
     QColor defaultBaseColor = QApplication::palette().color(QPalette::Base);
     QColor backgroundColor = defaultBaseColor;
     if (m_webView && m_webView->url().scheme() == QLatin1String("https")
             && p.color(QPalette::Text).value() < 128) {
         QColor lightYellow(248, 248, 210);
         backgroundColor = lightYellow;
     }
     // set the progress bar
     if (m_webView) {
         int progress = m_webView->progress();
         if (progress == 0) {
             p.setBrush(QPalette::Base, backgroundColor);
         } else {
             QColor loadingColor = QColor(116, 192, 250);
             if (p.color(QPalette::Text).value() >= 128)
                 loadingColor = defaultBaseColor.darker(200);
             QLinearGradient gradient(0, 0, width(), 0);
             gradient.setColorAt(0, loadingColor);
             gradient.setColorAt(((double)progress)/100, backgroundColor);
             p.setBrush(QPalette::Base, gradient);
         }
         setPalette(p);
     }
     LineEdit::paintEvent(event);
 }
References LineEdit::event(), m_webView, and LineEdit::paintEvent().
setWebView()
void LocationBar::setWebView (WebView * webView)
Definition at line 67 of file locationbar.cpp.
 {
     Q_ASSERT(webView);
     m_webView = webView;
     m_siteIcon->setWebView(webView);
     connect(webView, SIGNAL(urlChanged(const QUrl &)),
             this, SLOT(webViewUrlChanged(const QUrl &)));
     connect(webView, SIGNAL(loadProgress(int)),
             this, SLOT(update()));
 }
References m_siteIcon, m_webView, LocationBarSiteIcon::setWebView(), webView(), and webViewUrlChanged().
webView()
WebView * LocationBar::webView () const
Definition at line 78 of file locationbar.cpp.
 {
     return m_webView;
 }
References m_webView.
Referenced by setWebView().
webViewUrlChanged
void LocationBar::webViewUrlChanged (const QUrl & url) private slot
Definition at line 83 of file locationbar.cpp.
 {
     if (hasFocus())
         return;
     if(!url.toString().startsWith(QString("qrc:/"))) {
         setText(QString::fromUtf8(url.toEncoded()));
     } else {
         QUrl newurl = QUrl(url.toString());
         QString url_tmp = newurl.toString().mid(5);
         newurl = QUrl(QLatin1String("endorphin://") + url_tmp);
         QString urlstr = newurl.toString();
         if(urlstr.endsWith(QLatin1String(".html"))) {
             urlstr.chop(5);
             newurl = QUrl(urlstr);
         }
         setText(QString::fromUtf8(newurl.toEncoded()));
     }
     setCursorPosition(0);
 }
Referenced by focusOutEvent(), and setWebView().
Member Data Documentation
m_privacyIndicator
PrivacyIndicator* LocationBar::m_privacyIndicator private
Definition at line 55 of file locationbar.h.
Referenced by LocationBar().
m_siteIcon
LocationBarSiteIcon* LocationBar::m_siteIcon private
Definition at line 54 of file locationbar.h.
Referenced by LocationBar(), and setWebView().
m_webView
QPointer<WebView> LocationBar::m_webView private
Definition at line 52 of file locationbar.h.
Referenced by focusOutEvent(), keyPressEvent(), paintEvent(), setWebView(), and webView().
The documentation for this class was generated from the following files:
src/locationbar/locationbar.h
src/locationbar/locationbar.cpp