Endorphin: HistoryManager Class Reference
HistoryManager Class Reference
#include <historymanager.h>
Public Slots
void clear ()
void loadSettings ()
Signals
void historyCleared ()
void historyGoingToChange ()
void historyReset ()
void entryAdded (const HistoryEntry &item)
void entryRemoved (const HistoryEntry &item)
void entryUpdated (int offset)
Public Member Functions
HistoryManager (QObject *parent=nullptr)
~HistoryManager ()
bool historyContains (const QString &url) const
void addHistoryEntry (const QString &url)
void updateHistoryEntry (const QUrl &url, const QString &title)
void removeHistoryEntry (const QUrl &url, const QString &title=QString())
int daysToExpire () const
void setDaysToExpire (int limit)
QList< HistoryEntry > history () const
void setHistory (const QList< HistoryEntry > &history, bool loadedAndSorted=false)
HistoryModel * historyModel () const
HistoryFilterModel * historyFilterModel () const
HistoryTreeModel * historyTreeModel () const
QString dataFilePath (const QString &fileName)
Protected Member Functions
void prependHistoryEntry (const HistoryEntry &item)
void removeHistoryEntry (const HistoryEntry &item)
Properties
int daysToExpire
Private Slots
void save ()
void checkForExpired ()
Private Member Functions
void load ()
QString atomicString (const QString &string)
void startFrecencyTimer ()
Private Attributes
AutoSaver * m_saveTimer
int m_daysToExpire
QTimer m_expiredTimer
QHash< QString, int > m_atomicStringHash
QList< HistoryEntry > m_history
QString m_lastSavedUrl
HistoryModel * m_historyModel
HistoryFilterModel * m_historyFilterModel
HistoryTreeModel * m_historyTreeModel
Detailed Description
Definition at line 99 of file historymanager.h.
Constructor & Destructor Documentation
HistoryManager()
HistoryManager::HistoryManager (QObject * parent = nullptr)
Definition at line 104 of file historymanager.cpp.
     : QObject(parent)
     , m_saveTimer(new AutoSaver(this))
     , m_daysToExpire(30)
     , m_historyModel(nullptr)
     , m_historyFilterModel(nullptr)
     , m_historyTreeModel(nullptr)
 {
     m_expiredTimer.setSingleShot(true);
     connect(&m_expiredTimer, SIGNAL(timeout()),
             this, SLOT(checkForExpired()));
     connect(this, SIGNAL(entryAdded(const HistoryEntry &)),
             m_saveTimer, SLOT(changeOccurred()));
     connect(this, SIGNAL(entryRemoved(const HistoryEntry &)),
             m_saveTimer, SLOT(changeOccurred()));
     load();
     m_historyModel = new HistoryModel(this, this);
     m_historyFilterModel = new HistoryFilterModel(m_historyModel, this);
     m_historyTreeModel = new HistoryTreeModel(m_historyFilterModel, this);
 }
References checkForExpired(), entryAdded(), entryRemoved(), load(), m_expiredTimer, m_historyFilterModel, m_historyModel, m_historyTreeModel, and m_saveTimer.
~HistoryManager()
HistoryManager::~HistoryManager ()
Definition at line 126 of file historymanager.cpp.
 {
     // remove history items on application exit
     if (m_daysToExpire == -2)
         clear();
     m_saveTimer->saveIfNeccessary();
 }
References clear(), m_daysToExpire, m_saveTimer, and AutoSaver::saveIfNeccessary().
Member Function Documentation
addHistoryEntry()
void HistoryManager::addHistoryEntry (const QString & url)
Definition at line 144 of file historymanager.cpp.
 {
     QUrl cleanUrl(url);
     cleanUrl.setPassword(QString());
     cleanUrl.setHost(cleanUrl.host().toLower());
     HistoryEntry item(atomicString(cleanUrl.toString()), QDateTime::currentDateTime());
     prependHistoryEntry(item);
 }
References atomicString(), and prependHistoryEntry().
atomicString()
QString HistoryManager::atomicString (const QString & string) private
Definition at line 363 of file historymanager.cpp.
{
     QHash<QString, int>::const_iterator it = m_atomicStringHash.constFind(string);
     if (it == m_atomicStringHash.constEnd()) {
         QHash<QString, int>::iterator insertedIterator = m_atomicStringHash.insert(string, 0);
         return insertedIterator.key();
     }
     return it.key();
 }
References m_atomicStringHash.
Referenced by addHistoryEntry(), load(), and updateHistoryEntry().
checkForExpired
void HistoryManager::checkForExpired () private slot
Definition at line 188 of file historymanager.cpp.
 {
     if (m_daysToExpire < 0 || m_history.isEmpty())
         return;
     QDateTime now = QDateTime::currentDateTime();
     int nextTimeout = 0;
     while (!m_history.isEmpty()) {
         QDateTime checkForExpired = m_history.last().dateTime;
         checkForExpired.setDate(checkForExpired.date().addDays(m_daysToExpire));
         if (now.daysTo(checkForExpired) > 7) {
             // check at most in a week to prevent int overflows on the timer
             nextTimeout = 7 * 86400;
         } else {
             nextTimeout = now.secsTo(checkForExpired);
         }
         if (nextTimeout > 0)
             break;
         HistoryEntry item = m_history.takeLast();
         // remove from saved file also
         m_lastSavedUrl.clear();
         emit entryRemoved(item);
     }
     if (nextTimeout > 0)
         m_expiredTimer.start(nextTimeout * 1000);
 }
References entryRemoved(), m_daysToExpire, m_expiredTimer, m_history, and m_lastSavedUrl.
Referenced by HistoryManager(), prependHistoryEntry(), setDaysToExpire(), and setHistory().
clear
void HistoryManager::clear () slot
Definition at line 277 of file historymanager.cpp.
 {
     emit historyGoingToChange();
     m_history.clear();
     m_atomicStringHash.clear();
     m_lastSavedUrl.clear();
     m_saveTimer->changeOccurred();
     m_saveTimer->saveIfNeccessary();
     emit historyReset();
     emit historyCleared();
 }
References AutoSaver::changeOccurred(), historyCleared(), historyGoingToChange(), historyReset(), m_atomicStringHash, m_history, m_lastSavedUrl, m_saveTimer, and AutoSaver::saveIfNeccessary().
Referenced by ClearPrivateData::accept(), HistoryMenu::clearHistoryDialog(), and ~HistoryManager().
dataFilePath()
QString HistoryManager::dataFilePath (const QString & fileName)
Definition at line 80 of file historymanager.cpp.
 {
     QString directory = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation) + "/data/Endorphin";
     if (!QFile::exists(directory)) {
         QDir dir;
         dir.mkpath(directory);
     }
     return directory + QLatin1String("/") + fileName;
 }
Referenced by load(), and save().
daysToExpire()
int HistoryManager::daysToExpire () const
Definition at line 263 of file historymanager.cpp.
 {
     return m_daysToExpire;
 }
References m_daysToExpire.
entryAdded
void HistoryManager::entryAdded (const HistoryEntry & item) signal
Referenced by HistoryManager(), and prependHistoryEntry().
entryRemoved
void HistoryManager::entryRemoved (const HistoryEntry & item) signal
Referenced by checkForExpired(), HistoryManager(), and removeHistoryEntry().
entryUpdated
void HistoryManager::entryUpdated (int offset) signal
Referenced by updateHistoryEntry().
history()
QList< HistoryEntry > HistoryManager::history () const
Definition at line 134 of file historymanager.cpp.
 {
     return m_history;
 }
References m_history.
Referenced by HistoryModel::data(), HistoryMenu::postPopulated(), HistoryModel::removeRows(), HistoryModel::rowCount(), and setHistory().
historyCleared
void HistoryManager::historyCleared () signal
Referenced by clear().
historyContains()
bool HistoryManager::historyContains (const QString & url) const
Definition at line 139 of file historymanager.cpp.
 {
     return m_historyFilterModel->historyContains(url);
 }
References HistoryFilterModel::historyContains(), and m_historyFilterModel.
historyFilterModel()
HistoryFilterModel * HistoryManager::historyFilterModel () const
Definition at line 178 of file historymanager.cpp.
 {
     return m_historyFilterModel;
 }
References m_historyFilterModel.
historyGoingToChange
void HistoryManager::historyGoingToChange () signal
Referenced by clear(), and setHistory().
historyModel()
HistoryModel * HistoryManager::historyModel () const
Definition at line 173 of file historymanager.cpp.
 {
     return m_historyModel;
 }
References m_historyModel.
historyReset
void HistoryManager::historyReset () signal
Referenced by clear(), and setHistory().
historyTreeModel()
HistoryTreeModel * HistoryManager::historyTreeModel () const
Definition at line 183 of file historymanager.cpp.
 {
     return m_historyTreeModel;
 }
References m_historyTreeModel.
Referenced by HistoryDialog::HistoryDialog(), and HistoryMenu::prePopulated().
load()
void HistoryManager::load () private
Definition at line 297 of file historymanager.cpp.
 {
     loadSettings();
     QFile historyFile(HistoryManager::dataFilePath(QLatin1String("history")));
     if (!historyFile.exists())
         return;
     if (!historyFile.open(QFile::ReadOnly)) {
         qWarning() << "Unable to open history file" << historyFile.fileName();
         return;
     }
     QList<HistoryEntry> list;
     QDataStream in(&historyFile);
     // Double check that the history file is sorted as it is read in
     bool needToSort = false;
     HistoryEntry lastInsertedItem;
     QByteArray data;
     QDataStream stream;
     QBuffer buffer;
     QString string;
     stream.setDevice(&buffer);
     while (!historyFile.atEnd()) {
         in >> data;
         buffer.close();
         buffer.setBuffer(&data);
         buffer.open(QIODevice::ReadOnly);
         quint32 ver;
         stream >> ver;
         if (ver != HISTORY_VERSION)
             continue;
         HistoryEntry item;
         stream >> string;
         item.url = atomicString(string);
         stream >> item.dateTime;
         stream >> string;
         item.title = atomicString(string);
         if (!item.dateTime.isValid())
             continue;
         if (item == lastInsertedItem) {
             if (lastInsertedItem.title.isEmpty() && !list.isEmpty())
                 list[0].title = item.title;
             continue;
         }
         if (!needToSort && !list.isEmpty() && lastInsertedItem < item)
             needToSort = true;
         list.prepend(item);
         lastInsertedItem = item;
     }
     if (needToSort)
         std::sort(list.begin(), list.end());
     setHistory(list, true);
     // If we had to sort re-write the whole history sorted
     if (needToSort) {
         m_lastSavedUrl.clear();
         m_saveTimer->changeOccurred();
     }
 }
References atomicString(), AutoSaver::changeOccurred(), dataFilePath(), HistoryEntry::dateTime, HISTORY_VERSION, loadSettings(), m_lastSavedUrl, m_saveTimer, setHistory(), HistoryEntry::title, and HistoryEntry::url.
Referenced by HistoryManager().
loadSettings
void HistoryManager::loadSettings () slot
Definition at line 289 of file historymanager.cpp.
 {
     // load settings
     QSettings settings;
     settings.beginGroup(QLatin1String("history"));
     m_daysToExpire = settings.value(QLatin1String("historyLimit"), 30).toInt();
 }
References m_daysToExpire.
Referenced by load(), and SettingsDialog::saveToSettings().
prependHistoryEntry()
void HistoryManager::prependHistoryEntry (const HistoryEntry & item) protected
Definition at line 217 of file historymanager.cpp.
 {
     /*
     QWebEngineSettings *globalSettings = QWebEngineSettings::globalSettings();
     if (globalSettings->testAttribute(QWebEngineSettings::PrivateBrowsingEnabled))
         return;
     */
     m_history.prepend(item);
     emit entryAdded(item);
     if (m_history.count() == 1)
         checkForExpired();
 }
References checkForExpired(), entryAdded(), and m_history.
Referenced by addHistoryEntry().
removeHistoryEntry() [1/2]
void HistoryManager::removeHistoryEntry (const HistoryEntry & item) protected
Definition at line 245 of file historymanager.cpp.
 {
     m_lastSavedUrl.clear();
     m_history.removeOne(item);
     emit entryRemoved(item);
 }
References entryRemoved(), m_history, and m_lastSavedUrl.
removeHistoryEntry() [2/2]
void HistoryManager::removeHistoryEntry (const QUrl & url, const QString & title = QString())
Definition at line 252 of file historymanager.cpp.
 {
     for (int i = 0; i < m_history.count(); ++i) {
         if (url == m_history.at(i).url
                 && (title.isEmpty() || title == m_history.at(i).title)) {
             removeHistoryEntry(m_history.at(i));
             break;
         }
     }
 }
References m_history.
save
void HistoryManager::save () private slot
Definition at line 372 of file historymanager.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("history"));
     settings.setValue(QLatin1String("historyLimit"), m_daysToExpire);
     bool saveAll = m_lastSavedUrl.isEmpty();
     int first = m_history.count() - 1;
     if (!saveAll) {
         // find the first one to save
         for (int i = 0; i < m_history.count(); ++i) {
             if (m_history.at(i).url == m_lastSavedUrl) {
                 first = i - 1;
                 break;
             }
         }
     }
     if (first == m_history.count() - 1)
         saveAll = true;
     QFile historyFile(HistoryManager::dataFilePath(QLatin1String("history")));
     // When saving everything use a temporary file to prevent possible data loss.
     QTemporaryFile tempFile;
     tempFile.setAutoRemove(false);
     bool open = false;
     if (saveAll) {
         open = tempFile.open();
     } else {
         open = historyFile.open(QFile::Append);
     }
     if (!open) {
         qWarning() << "Unable to open history file for saving"
                    << (saveAll ? tempFile.fileName() : historyFile.fileName());
         return;
     }
     QDataStream out(saveAll ? &tempFile : &historyFile);
     for (int i = first; i >= 0; --i) {
         QByteArray data;
         QDataStream stream(&data, QIODevice::WriteOnly);
         HistoryEntry item = m_history.at(i);
         stream << HISTORY_VERSION << item.url << item.dateTime << item.title;
         out << data;
     }
     tempFile.close();
     if (saveAll) {
         if (historyFile.exists() && !historyFile.remove())
             qWarning() << "History: error removing old history." << historyFile.errorString();
         if (!tempFile.copy(historyFile.fileName()))
             qWarning() << "History: error moving new history over old." << tempFile.errorString() << historyFile.fileName();
         if (!tempFile.remove())
             qWarning() << "History: error deleting temporary file." << tempFile.errorString() << tempFile.fileName();
     }
     m_lastSavedUrl = m_history.value(0).url;
 }
References dataFilePath(), HistoryEntry::dateTime, HISTORY_VERSION, m_daysToExpire, m_history, m_lastSavedUrl, HistoryEntry::title, and HistoryEntry::url.
setDaysToExpire()
void HistoryManager::setDaysToExpire (int limit)
Definition at line 268 of file historymanager.cpp.
 {
     if (m_daysToExpire == limit)
         return;
     m_daysToExpire = limit;
     checkForExpired();
     m_saveTimer->changeOccurred();
 }
References AutoSaver::changeOccurred(), checkForExpired(), m_daysToExpire, and m_saveTimer.
setHistory()
void HistoryManager::setHistory (const QList< HistoryEntry > & history, bool loadedAndSorted = false)
Definition at line 153 of file historymanager.cpp.
 {
     emit historyGoingToChange();
     m_history = history;
     // verify that it is sorted by date
     if (!loadedAndSorted)
         std::sort(m_history.begin(), m_history.end());
     checkForExpired();
     if (loadedAndSorted) {
         m_lastSavedUrl = m_history.value(0).url;
     } else {
         m_lastSavedUrl.clear();
         m_saveTimer->changeOccurred();
     }
     emit historyReset();
 }
References AutoSaver::changeOccurred(), checkForExpired(), history(), historyGoingToChange(), historyReset(), m_history, m_lastSavedUrl, and m_saveTimer.
Referenced by load(), and HistoryModel::removeRows().
startFrecencyTimer()
void HistoryManager::startFrecencyTimer () private
updateHistoryEntry()
void HistoryManager::updateHistoryEntry (const QUrl & url, const QString & title)
Definition at line 231 of file historymanager.cpp.
 {
     for (int i = 0; i < m_history.count(); ++i) {
         if (url == m_history.at(i).url) {
             m_history[i].title = atomicString(title);
             m_saveTimer->changeOccurred();
             if (m_lastSavedUrl.isEmpty())
                 m_lastSavedUrl = m_history.at(i).url;
             emit entryUpdated(i);
             break;
         }
     }
 }
References atomicString(), AutoSaver::changeOccurred(), entryUpdated(), m_history, m_lastSavedUrl, and m_saveTimer.
Referenced by TabWidget::webViewTitleChanged().
Member Data Documentation
m_atomicStringHash
QHash<QString, int> HistoryManager::m_atomicStringHash private
Definition at line 154 of file historymanager.h.
Referenced by atomicString(), and clear().
m_daysToExpire
int HistoryManager::m_daysToExpire private
Definition at line 152 of file historymanager.h.
Referenced by checkForExpired(), daysToExpire(), loadSettings(), save(), setDaysToExpire(), and ~HistoryManager().
m_expiredTimer
QTimer HistoryManager::m_expiredTimer private
Definition at line 153 of file historymanager.h.
Referenced by checkForExpired(), and HistoryManager().
m_history
QList<HistoryEntry> HistoryManager::m_history private
Definition at line 155 of file historymanager.h.
Referenced by checkForExpired(), clear(), history(), prependHistoryEntry(), removeHistoryEntry(), save(), setHistory(), and updateHistoryEntry().
m_historyFilterModel
HistoryFilterModel* HistoryManager::m_historyFilterModel private
Definition at line 159 of file historymanager.h.
Referenced by historyContains(), historyFilterModel(), and HistoryManager().
m_historyModel
HistoryModel* HistoryManager::m_historyModel private
Definition at line 158 of file historymanager.h.
Referenced by HistoryManager(), and historyModel().
m_historyTreeModel
HistoryTreeModel* HistoryManager::m_historyTreeModel private
Definition at line 160 of file historymanager.h.
Referenced by HistoryManager(), and historyTreeModel().
m_lastSavedUrl
QString HistoryManager::m_lastSavedUrl private
Definition at line 156 of file historymanager.h.
Referenced by checkForExpired(), clear(), load(), removeHistoryEntry(), save(), setHistory(), and updateHistoryEntry().
m_saveTimer
AutoSaver* HistoryManager::m_saveTimer private
Definition at line 151 of file historymanager.h.
Referenced by clear(), HistoryManager(), load(), setDaysToExpire(), setHistory(), updateHistoryEntry(), and ~HistoryManager().
Property Documentation
daysToExpire
int HistoryManager::daysToExpire read write
Definition at line 133 of file historymanager.h.
The documentation for this class was generated from the following files:
src/history/historymanager.h
src/history/historymanager.cpp