Endorphin: AcceptLanguageDialog Class Reference
AcceptLanguageDialog Class Reference
#include <acceptlanguagedialog.h>
Public Member Functions
AcceptLanguageDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=nullptr)
void accept ()
Static Public Member Functions
static QByteArray httpString (const QStringList &list)
static QStringList defaultAcceptList ()
Private Slots
void load ()
void save ()
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
void moveLanguageUp ()
void moveLanguageDown ()
void removeLanguage ()
void addLanguage ()
Static Private Member Functions
static QStringList expand (const QLocale::Language language)
Private Attributes
QStringListModel m_allLanguagesModel
QStringListModel m_model
Detailed Description
Definition at line 28 of file acceptlanguagedialog.h.
Constructor & Destructor Documentation
AcceptLanguageDialog()
AcceptLanguageDialog::AcceptLanguageDialog (QWidget * parent = nullptr, Qt::WindowFlags flags = nullptr)
Definition at line 28 of file acceptlanguagedialog.cpp.
     : QDialog(parent, flags)
 {
     setupUi(this);
     connect(addButton, SIGNAL(clicked()), this, SLOT(addLanguage()));
     connect(removeButton, SIGNAL(clicked()), this, SLOT(removeLanguage()));
     connect(moveUpButton, SIGNAL(clicked()), this, SLOT(moveLanguageUp()));
     connect(moveDownButton, SIGNAL(clicked()), this, SLOT(moveLanguageDown()));
     listView->setModel(&m_model);
     connect(listView->selectionModel(), SIGNAL(currentChanged(const QModelIndex &, const QModelIndex &)),
             this, SLOT(currentChanged(const QModelIndex &, const QModelIndex &)));
     load();
     QStringList allLanguages;
     for (int i = 1 + (int)QLocale::C; i <= (int)QLocale::LastLanguage; ++i)
         allLanguages += expand(QLocale::Language(i));
     m_allLanguagesModel.setStringList(allLanguages);
     addComboBox->setModel(&m_allLanguagesModel);
 }
References addLanguage(), currentChanged(), expand(), load(), m_allLanguagesModel, m_model, moveLanguageDown(), moveLanguageUp(), and removeLanguage().
Member Function Documentation
accept()
void AcceptLanguageDialog::accept ()
Definition at line 88 of file acceptlanguagedialog.cpp.
 {
     save();
     QDialog::accept();
 }
References save().
addLanguage
void AcceptLanguageDialog::addLanguage () private slot
Definition at line 162 of file acceptlanguagedialog.cpp.
 {
     QString text = addComboBox->currentText();
     if (m_model.stringList().contains(text))
         return;
     m_model.insertRow(m_model.rowCount());
     m_model.setData(m_model.index(m_model.rowCount() - 1), text);
 }
References m_model.
Referenced by AcceptLanguageDialog().
currentChanged
void AcceptLanguageDialog::currentChanged (const QModelIndex & current, const QModelIndex & previous) private slot
Definition at line 71 of file acceptlanguagedialog.cpp.
 {
     Q_UNUSED(previous);
     removeButton->setEnabled(current.isValid());
     int row = current.row();
     moveUpButton->setEnabled(row > 0);
     moveDownButton->setEnabled(row != -1 && row < m_model.rowCount() - 1);
 }
References m_model.
Referenced by AcceptLanguageDialog().
defaultAcceptList()
QStringList AcceptLanguageDialog::defaultAcceptList () static
Definition at line 80 of file acceptlanguagedialog.cpp.
 {
     QString currentLanguage = BrowserApplication::instance()->languageManager()->currentLanguage();
     if (currentLanguage.isEmpty())
         return QStringList();
     return expand(QLocale(currentLanguage).language());
 }
References LanguageManager::currentLanguage, expand(), BrowserApplication::instance(), and BrowserApplication::languageManager().
Referenced by load(), and save().
expand()
QStringList AcceptLanguageDialog::expand (const QLocale::Language language) static private
Definition at line 48 of file acceptlanguagedialog.cpp.
 {
     QStringList allLanguages;
     QList<QLocale::Country> countries = QLocale::countriesForLanguage(language);
     for (int j = 0; j < countries.size(); ++j) {
         QString languageString;
         if (countries.count() == 1) {
             languageString = QString(QLatin1String("%1 [%2]"))
                              .arg(QLocale::languageToString(language))
                              .arg(QLocale(language).name().split(QLatin1Char('_')).at(0));
         } else {
             languageString = QString(QLatin1String("%1/%2 [%3]"))
                              .arg(QLocale::languageToString(language))
                              .arg(QLocale::countryToString(countries.at(j)))
                              .arg(QLocale(language, countries.at(j)).name().split(QLatin1Char('_')).join(QLatin1String("-")).toLower());
         }
         if (!allLanguages.contains(languageString))
             allLanguages.append(languageString);
     }
     return allLanguages;
 }
Referenced by AcceptLanguageDialog(), and defaultAcceptList().
httpString()
QByteArray AcceptLanguageDialog::httpString (const QStringList & list) static
Definition at line 117 of file acceptlanguagedialog.cpp.
 {
     QStringList processed;
     qreal qvalue = 1.0;
     foreach (const QString &string, list) {
         int leftBracket = string.indexOf(QLatin1Char('['));
         int rightBracket = string.indexOf(QLatin1Char(']'));
         QString tag = string.mid(leftBracket + 1, rightBracket - leftBracket - 1);
         if (processed.isEmpty()) {
             processed << tag;
         } else {
             processed << QString(QLatin1String("%1; %2")).arg(tag).arg(QString::number(qvalue, 'f', 1));
         }
         if (qvalue > .1)
             qvalue -= .1;
     }
     return processed.join(QLatin1String(", ")).toLatin1();
 }
load
void AcceptLanguageDialog::load () private slot
Definition at line 94 of file acceptlanguagedialog.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("network"));
     m_model.setStringList(settings.value(QLatin1String("acceptLanguages"), defaultAcceptList()).toStringList());
 }
References defaultAcceptList(), and m_model.
Referenced by AcceptLanguageDialog().
moveLanguageDown
void AcceptLanguageDialog::moveLanguageDown () private slot
Definition at line 146 of file acceptlanguagedialog.cpp.
 {
     int currentRow = listView->currentIndex().row();
     QString item = listView->currentIndex().data().toString();
     m_model.removeRow(currentRow);
     m_model.insertRows(currentRow + 1, 1);
     m_model.setData(m_model.index(currentRow + 1), item);
     listView->setCurrentIndex(m_model.index(currentRow + 1));
 }
References m_model.
Referenced by AcceptLanguageDialog().
moveLanguageUp
void AcceptLanguageDialog::moveLanguageUp () private slot
Definition at line 136 of file acceptlanguagedialog.cpp.
 {
     int currentRow = listView->currentIndex().row();
     QString item = listView->currentIndex().data().toString();
     m_model.removeRow(currentRow);
     m_model.insertRows(currentRow - 1, 1);
     m_model.setData(m_model.index(currentRow - 1), item);
     listView->setCurrentIndex(m_model.index(currentRow + 1));
 }
References m_model.
Referenced by AcceptLanguageDialog().
removeLanguage
void AcceptLanguageDialog::removeLanguage () private slot
Definition at line 156 of file acceptlanguagedialog.cpp.
 {
     int currentRow = listView->currentIndex().row();
     m_model.removeRow(currentRow);
 }
References m_model.
Referenced by AcceptLanguageDialog().
save
void AcceptLanguageDialog::save () private slot
Definition at line 101 of file acceptlanguagedialog.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("network"));
     QStringList result = m_model.stringList();
     if (result == defaultAcceptList() || result.isEmpty())
         settings.remove(QLatin1String("acceptLanguages"));
     else
         settings.setValue(QLatin1String("acceptLanguages"), result);
 }
References defaultAcceptList(), and m_model.
Referenced by accept().
Member Data Documentation
m_allLanguagesModel
QStringListModel AcceptLanguageDialog::m_allLanguagesModel private
Definition at line 50 of file acceptlanguagedialog.h.
Referenced by AcceptLanguageDialog().
m_model
QStringListModel AcceptLanguageDialog::m_model private
Definition at line 51 of file acceptlanguagedialog.h.
Referenced by AcceptLanguageDialog(), addLanguage(), currentChanged(), load(), moveLanguageDown(), moveLanguageUp(), removeLanguage(), and save().
The documentation for this class was generated from the following files:
src/acceptlanguagedialog.h
src/acceptlanguagedialog.cpp