Endorphin: AddBookmarkDialog Class Reference
AddBookmarkDialog Class Reference
#include <addbookmarkdialog.h>
Public Member Functions
AddBookmarkDialog (QWidget *parent=nullptr, BookmarksManager *bookmarksManager=nullptr)
void setUrl (const QString &url)
QString url () const
void setTitle (const QString &title)
QString title () const
void setCurrentIndex (const QModelIndex &index)
QModelIndex currentIndex () const
void setFolder (bool addFolder)
bool isFolder () const
BookmarkNode * addedNode () const
Private Slots
void accept ()
Private Attributes
QTreeView * m_treeView
BookmarksManager * m_bookmarksManager
BookmarkNode * m_addedNode
AddBookmarkProxyModel * m_proxyModel
bool m_addFolder
Detailed Description
Definition at line 86 of file addbookmarkdialog.h.
Constructor & Destructor Documentation
AddBookmarkDialog()
AddBookmarkDialog::AddBookmarkDialog (QWidget * parent = nullptr, BookmarksManager * bookmarksManager = nullptr)
Definition at line 96 of file addbookmarkdialog.cpp.
     : QDialog(parent)
     , m_bookmarksManager(bookmarksManager)
     , m_addedNode(nullptr)
     , m_proxyModel(nullptr)
     , m_addFolder(false)
 {
     setWindowFlags(Qt::Sheet);
     setupUi(this);
     if (!m_bookmarksManager)
 #ifndef NO_BROWSERAPPLICATION
         m_bookmarksManager = BrowserApplication::bookmarksManager();
 #else
     #ifdef FOR_AUTOTEST
         m_bookmarksManager = tst_AddBookmarkDialog::bookmarksManager();
     #else
         #error "Nothing provides a bookmarksmanager"
     #endif
 #endif
     m_proxyModel = new AddBookmarkProxyModel(this);
     BookmarksModel *model = m_bookmarksManager->bookmarksModel();
     m_proxyModel->setSourceModel(model);
     m_treeView = new QTreeView(this);
     m_treeView->setModel(m_proxyModel);
     m_treeView->expandAll();
     m_treeView->header()->setStretchLastSection(true);
     m_treeView->header()->hide();
     m_treeView->setItemsExpandable(false);
     m_treeView->setRootIsDecorated(false);
     m_treeView->setIndentation(10);
     m_treeView->show();
     location->setModel(m_proxyModel);
     location->setView(m_treeView);
     address->setInactiveText(tr("Url"));
     name->setInactiveText(tr("Title"));
     resize(sizeHint());
 }
References BrowserApplication::bookmarksManager(), BookmarksManager::bookmarksModel(), m_bookmarksManager, m_proxyModel, and m_treeView.
Member Function Documentation
accept
void AddBookmarkDialog::accept () private slot
Definition at line 204 of file addbookmarkdialog.cpp.
 {
     if ((!m_addFolder && address->text().isEmpty()) || name->text().isEmpty()) {
         QDialog::accept();
         return;
     }
     QModelIndex index = currentIndex();
     if (!index.isValid())
         index = m_bookmarksManager->bookmarksModel()->index(0, 0);
     BookmarkNode *parent = m_bookmarksManager->bookmarksModel()->node(index);
     BookmarkNode::Type type = (m_addFolder) ? BookmarkNode::Folder : BookmarkNode::Bookmark;
     BookmarkNode *bookmark = new BookmarkNode(type);
     bookmark->title = name->text();
     if (!m_addFolder)
         bookmark->url = address->text();
     m_bookmarksManager->addBookmark(parent, bookmark);
     m_addedNode = bookmark;
     QDialog::accept();
 }
References BookmarksManager::addBookmark(), BookmarkNode::Bookmark, BookmarksManager::bookmarksModel(), currentIndex(), BookmarkNode::Folder, BookmarksModel::index(), m_addedNode, m_addFolder, m_bookmarksManager, BookmarksModel::node(), BookmarkNode::title, and BookmarkNode::url.
addedNode()
BookmarkNode * AddBookmarkDialog::addedNode () const
Definition at line 199 of file addbookmarkdialog.cpp.
 {
     return m_addedNode;
 }
References m_addedNode.
Referenced by TabWidget::bookmarkTabs().
currentIndex()
QModelIndex AddBookmarkDialog::currentIndex () const
Definition at line 172 of file addbookmarkdialog.cpp.
 {
     QModelIndex index = location->view()->currentIndex();
     index = m_proxyModel->mapToSource(index);
     return index;
 }
References m_proxyModel.
Referenced by accept().
isFolder()
bool AddBookmarkDialog::isFolder () const
Definition at line 194 of file addbookmarkdialog.cpp.
 {
     return m_addFolder;
 }
References m_addFolder.
setCurrentIndex()
void AddBookmarkDialog::setCurrentIndex (const QModelIndex & index)
Definition at line 162 of file addbookmarkdialog.cpp.
 {
     if (!index.isValid())
         return;
     QModelIndex proxyIndex = m_proxyModel->mapFromSource(index);
     m_treeView->setCurrentIndex(proxyIndex);
     location->setCurrentIndex(proxyIndex.row());
 }
References m_proxyModel, and m_treeView.
Referenced by BrowserMainWindow::addBookmark(), BrowserMainWindow::addBookmarkFolder(), BookmarksToolBar::newBookmark(), and BookmarksToolBar::newFolder().
setFolder()
void AddBookmarkDialog::setFolder (bool addFolder)
Definition at line 179 of file addbookmarkdialog.cpp.
 {
     m_addFolder = addFolder;
     if (addFolder) {
         setWindowTitle(tr("Add Folder"));
         address->setVisible(false);
     } else {
         setWindowTitle(tr("Add Bookmark"));
         address->setVisible(true);
     }
     resize(sizeHint());
 }
References m_addFolder.
Referenced by BrowserMainWindow::addBookmarkFolder(), TabWidget::bookmarkTabs(), and BookmarksToolBar::newFolder().
setTitle()
void AddBookmarkDialog::setTitle (const QString & title)
Definition at line 152 of file addbookmarkdialog.cpp.
 {
     name->setText(title);
 }
References title().
Referenced by BrowserMainWindow::addBookmark(), and TabWidget::bookmarkTabs().
setUrl()
void AddBookmarkDialog::setUrl (const QString & url)
Definition at line 140 of file addbookmarkdialog.cpp.
 {
     address->setText(url);
     address->setVisible(url.isEmpty());
     resize(sizeHint());
 }
References url().
Referenced by BrowserMainWindow::addBookmark(), and WebView::bookmarkLink().
title()
QString AddBookmarkDialog::title () const
Definition at line 157 of file addbookmarkdialog.cpp.
 {
     return name->text();
 }
Referenced by setTitle().
url()
QString AddBookmarkDialog::url () const
Definition at line 147 of file addbookmarkdialog.cpp.
 {
     return address->text();
 }
Referenced by setUrl().
Member Data Documentation
m_addedNode
BookmarkNode* AddBookmarkDialog::m_addedNode private
Definition at line 113 of file addbookmarkdialog.h.
Referenced by accept(), and addedNode().
m_addFolder
bool AddBookmarkDialog::m_addFolder private
Definition at line 115 of file addbookmarkdialog.h.
Referenced by accept(), isFolder(), and setFolder().
m_bookmarksManager
BookmarksManager* AddBookmarkDialog::m_bookmarksManager private
Definition at line 112 of file addbookmarkdialog.h.
Referenced by accept(), and AddBookmarkDialog().
m_proxyModel
AddBookmarkProxyModel* AddBookmarkDialog::m_proxyModel private
Definition at line 114 of file addbookmarkdialog.h.
Referenced by AddBookmarkDialog(), currentIndex(), and setCurrentIndex().
m_treeView
QTreeView* AddBookmarkDialog::m_treeView private
Definition at line 111 of file addbookmarkdialog.h.
Referenced by AddBookmarkDialog(), and setCurrentIndex().
The documentation for this class was generated from the following files:
src/bookmarks/addbookmarkdialog.h
src/bookmarks/addbookmarkdialog.cpp