Endorphin: BookmarkNode Class Reference
BookmarkNode Class Reference
#include <bookmarknode.h>
Public Types
enum Type { Root, Folder, Bookmark, Separator }
Public Member Functions
BookmarkNode (Type type=Root, BookmarkNode *parent=nullptr)
~BookmarkNode ()
bool operator== (const BookmarkNode &other) const
Type type () const
void setType (Type type)
QList< BookmarkNode * > children () const
BookmarkNode * parent () const
void add (BookmarkNode *child, int offset=-1)
void remove (BookmarkNode *child)
Public Attributes
QString url
QString title
QString desc
bool expanded
Private Attributes
BookmarkNode * m_parent
Type m_type
QList< BookmarkNode * > m_children
Detailed Description
Definition at line 69 of file bookmarknode.h.
Member Enumeration Documentation
Type
enum BookmarkNode::Type
Enumerator
Root
Folder
Bookmark
Separator
Definition at line 113 of file bookmarknode.h.
Constructor & Destructor Documentation
BookmarkNode()
BookmarkNode::BookmarkNode (BookmarkNode::Type type = Root, BookmarkNode * parent = nullptr)
Definition at line 65 of file bookmarknode.cpp.
                                                                       :
     expanded(false)
     , m_parent(parent)
     , m_type(type)
 {
     if (parent)
         parent->add(this);
 }
References add(), and parent().
~BookmarkNode()
BookmarkNode::~BookmarkNode ()
Definition at line 74 of file bookmarknode.cpp.
 {
     if (m_parent)
         m_parent->remove(this);
     for (int i = m_children.count() -1; i >= 0; --i)
         delete m_children[i];
     m_parent = nullptr;
     m_type = BookmarkNode::Root;
 }
References m_children, m_parent, m_type, remove(), and Root.
Member Function Documentation
add()
void BookmarkNode::add (BookmarkNode * child, int offset = -1)
Definition at line 120 of file bookmarknode.cpp.
 {
     if (!child)
         return;
     if (m_type == BookmarkNode::Bookmark)
         return;
     Q_ASSERT(child->m_type != Root);
     if (child->m_parent)
         child->m_parent->remove(child);
     child->m_parent = this;
     if (-1 == offset)
         offset = m_children.size();
     m_children.insert(offset, child);
 }
References Bookmark, m_children, m_parent, m_type, remove(), and Root.
Referenced by BookmarkNode(), BookmarksManager::load(), and RemoveBookmarksCommand::undo().
children()
QList< BookmarkNode * > BookmarkNode::children () const
Definition at line 110 of file bookmarknode.cpp.
 {
     return m_children;
 }
References m_children.
Referenced by BookmarksModel::dropMimeData(), BookmarksModel::entryAdded(), BookmarksDialog::expandNodes(), BookmarksModel::index(), BookmarksManager::load(), BookmarksModel::parent(), BookmarksManager::removeBookmark(), BookmarksModel::removeRows(), BookmarksModel::rowCount(), XbelWriter::write(), and XbelWriter::writeItem().
operator==()
bool BookmarkNode::operator== (const BookmarkNode & other) const
Definition at line 84 of file bookmarknode.cpp.
 {
     if (url != other.url
             || title != other.title
             || desc != other.desc
             || expanded != other.expanded
             || m_type != other.m_type
             || m_children.count() != other.m_children.count())
         return false;
     for (int i = 0; i < m_children.count(); ++i)
         if (!((*(m_children[i])) == (*(other.m_children[i]))))
             return false;
     return true;
 }
References desc, expanded, m_children, m_type, title, and url.
parent()
BookmarkNode * BookmarkNode::parent () const
Definition at line 115 of file bookmarknode.cpp.
 {
     return m_parent;
 }
References m_parent.
Referenced by BookmarkNode(), BookmarksModel::entryAdded(), BookmarksModel::index(), BookmarksDialog::newFolder(), BookmarksModel::parent(), BookmarksManager::removeBookmark(), and RemoveBookmarksCommand::~RemoveBookmarksCommand().
remove()
void BookmarkNode::remove (BookmarkNode * child)
Definition at line 135 of file bookmarknode.cpp.
 {
     if (!child)
         return;
     child->m_parent = nullptr;
     m_children.removeAll(child);
 }
References m_children, and m_parent.
Referenced by add(), BookmarksModel::dropMimeData(), BookmarksManager::load(), RemoveBookmarksCommand::redo(), and ~BookmarkNode().
setType()
void BookmarkNode::setType (Type type)
Definition at line 105 of file bookmarknode.cpp.
 {
     m_type = type;
 }
References m_type, and type().
Referenced by BookmarksManager::importBookmarks().
type()
BookmarkNode::Type BookmarkNode::type () const
Definition at line 100 of file bookmarknode.cpp.
 {
     return m_type;
 }
References m_type.
Referenced by BookmarksDialog::customContextMenuRequested(), BookmarksModel::data(), BookmarksModel::flags(), BookmarksModel::hasChildren(), BookmarksManager::load(), BookmarksDialog::newFolder(), BookmarksDialog::openBookmark(), setType(), XbelWriter::write(), and XbelWriter::writeItem().
Member Data Documentation
desc
QString BookmarkNode::desc
Definition at line 134 of file bookmarknode.h.
Referenced by operator==(), XbelReader::readDescription(), and XbelWriter::writeItem().
expanded
bool BookmarkNode::expanded
Definition at line 135 of file bookmarknode.h.
Referenced by BookmarksDialog::expandNodes(), operator==(), XbelReader::readFolder(), BookmarksDialog::saveExpandedNodes(), and XbelWriter::writeItem().
m_children
QList<BookmarkNode*> BookmarkNode::m_children private
Definition at line 140 of file bookmarknode.h.
Referenced by add(), children(), operator==(), remove(), and ~BookmarkNode().
m_parent
BookmarkNode* BookmarkNode::m_parent private
Definition at line 138 of file bookmarknode.h.
Referenced by add(), parent(), remove(), and ~BookmarkNode().
m_type
Type BookmarkNode::m_type private
Definition at line 139 of file bookmarknode.h.
Referenced by add(), operator==(), setType(), type(), and ~BookmarkNode().
title
QString BookmarkNode::title
Definition at line 133 of file bookmarknode.h.
Referenced by AddBookmarkDialog::accept(), TabWidget::bookmarkTabs(), ChangeBookmarkCommand::ChangeBookmarkCommand(), BookmarksModel::data(), BookmarksModel::dropMimeData(), BookmarksManager::importBookmarks(), BookmarksManager::load(), BookmarksDialog::newFolder(), operator==(), XbelReader::readBookmarkNode(), XbelReader::readTitle(), ChangeBookmarkCommand::redo(), BookmarksManager::retranslate(), BookmarksManager::save(), ChangeBookmarkCommand::undo(), and XbelWriter::writeItem().
url
QString BookmarkNode::url
Definition at line 132 of file bookmarknode.h.
Referenced by AddBookmarkDialog::accept(), TabWidget::bookmarkTabs(), ChangeBookmarkCommand::ChangeBookmarkCommand(), BookmarksModel::data(), BookmarksModel::dropMimeData(), operator==(), XbelReader::readBookmarkNode(), ChangeBookmarkCommand::redo(), ChangeBookmarkCommand::undo(), and XbelWriter::writeItem().
The documentation for this class was generated from the following files:
src/bookmarks/bookmarknode.h
src/bookmarks/bookmarknode.cpp