Endorphin: OpenSearchDialog Class Reference
OpenSearchDialog Class Reference
#include <opensearchdialog.h>
Public Member Functions
OpenSearchDialog (QWidget *parent=nullptr)
Protected Slots
void addButtonClicked ()
void deleteButtonClicked ()
void restoreButtonClicked ()
Private Attributes
OpenSearchEngineModel * m_model
Detailed Description
Definition at line 30 of file opensearchdialog.h.
Constructor & Destructor Documentation
OpenSearchDialog()
OpenSearchDialog::OpenSearchDialog (QWidget * parent = nullptr)
Definition at line 31 of file opensearchdialog.cpp.
     : QDialog(parent)
     , m_model(nullptr)
 {
     setModal(true);
     setupUi(this);
     m_model = new OpenSearchEngineModel(ToolbarSearch::openSearchManager(), this);
     m_tableView->setModel(m_model);
     m_tableView->horizontalHeader()->resizeSection(0, 200);
     m_tableView->horizontalHeader()->setStretchLastSection(true);
     m_tableView->verticalHeader()->hide();
     m_tableView->verticalHeader()->setDefaultSectionSize(1.2 * fontMetrics().height());
     m_tableView->setSelectionBehavior(QAbstractItemView::SelectRows);
     m_tableView->setShowGrid(false);
     m_tableView->setAlternatingRowColors(true);
     connect(m_closeButton, SIGNAL(clicked()),
             this, SLOT(close()));
     connect(m_addButton, SIGNAL(clicked()),
             this, SLOT(addButtonClicked()));
     connect(m_deleteButton, SIGNAL(clicked()),
             this, SLOT(deleteButtonClicked()));
     connect(m_restoreButton, SIGNAL(clicked()),
             this, SLOT(restoreButtonClicked()));
 }
References addButtonClicked(), deleteButtonClicked(), m_model, ToolbarSearch::openSearchManager(), and restoreButtonClicked().
Member Function Documentation
addButtonClicked
void OpenSearchDialog::addButtonClicked () protected slot
Definition at line 58 of file opensearchdialog.cpp.
 {
     QStringList fileNames = QFileDialog::getOpenFileNames(this,
                             tr("Open File"),
                             QString(),
                             tr("OpenSearch") + QLatin1String(" (*.xml)"));
     foreach (const QString &fileName, fileNames) {
         if (!ToolbarSearch::openSearchManager()->addEngine(fileName)) {
             QMessageBox::critical(this, tr("Error"),
                                   tr("%1 is not a valid OpenSearch 1.1 description or is already on your list.").arg(fileName));
         }
     }
 }
References ToolbarSearch::openSearchManager().
Referenced by OpenSearchDialog().
deleteButtonClicked
void OpenSearchDialog::deleteButtonClicked () protected slot
Definition at line 73 of file opensearchdialog.cpp.
 {
     if (m_tableView->model()->rowCount() == 1) {
         QMessageBox::critical(this, tr("Error"),
                               tr("You must have at least one search engine in here."));
         return;
     }
     m_tableView->removeSelected();
 }
Referenced by OpenSearchDialog().
restoreButtonClicked
void OpenSearchDialog::restoreButtonClicked () protected slot
Definition at line 84 of file opensearchdialog.cpp.
 {
     ToolbarSearch::openSearchManager()->restoreDefaults();
 }
References ToolbarSearch::openSearchManager(), and OpenSearchManager::restoreDefaults().
Referenced by OpenSearchDialog().
Member Data Documentation
m_model
OpenSearchEngineModel* OpenSearchDialog::m_model private
Definition at line 43 of file opensearchdialog.h.
Referenced by OpenSearchDialog().
The documentation for this class was generated from the following files:
src/opensearch/opensearchdialog.h
src/opensearch/opensearchdialog.cpp