Endorphin: HistoryCompleter Class Reference
HistoryCompleter Class Reference
#include <historycompleter.h>
Public Member Functions
HistoryCompleter (QObject *parent=nullptr)
HistoryCompleter (QAbstractItemModel *model, QObject *parent=nullptr)
virtual QString pathFromIndex (const QModelIndex &index) const
virtual QStringList splitPath (const QString &path) const
Protected Member Functions
bool eventFilter (QObject *obj, QEvent *event)
Private Slots
void updateFilter ()
Private Member Functions
void init ()
Private Attributes
QString m_searchString
QTimer m_filterTimer
Detailed Description
Definition at line 84 of file historycompleter.h.
Constructor & Destructor Documentation
HistoryCompleter() [1/2]
HistoryCompleter::HistoryCompleter (QObject * parent = nullptr)
Definition at line 167 of file historycompleter.cpp.
     : QCompleter(parent)
 {
     init();
 }
References init().
HistoryCompleter() [2/2]
HistoryCompleter::HistoryCompleter (QAbstractItemModel * model, QObject * parent = nullptr)
Definition at line 173 of file historycompleter.cpp.
     : QCompleter(m, parent)
 {
     init();
 }
References init().
Member Function Documentation
eventFilter()
bool HistoryCompleter::eventFilter (QObject * obj, QEvent * event) protected
Definition at line 229 of file historycompleter.cpp.
 {
     if (event->type() == QEvent::KeyPress && popup()->isVisible()) {
         QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
         if (keyEvent->key() == Qt::Key_Tab) {
             QKeyEvent *newEvent = new QKeyEvent(QEvent::KeyPress,
                                                 Qt::Key_Down,
                                                 keyEvent->modifiers(),
                                                 QString());
             if (!QCompleter::eventFilter(obj, newEvent))
                 obj->event(newEvent);
             return true;
         } else if (keyEvent->key() == Qt::Key_Backtab) {
             QKeyEvent *newEvent = new QKeyEvent(QEvent::KeyPress,
                                                 Qt::Key_Up,
                                                 keyEvent->modifiers(),
                                                 keyEvent->text(),
                                                 keyEvent->isAutoRepeat(),
                                                 keyEvent->count());
             if (!QCompleter::eventFilter(obj, newEvent))
                 obj->event(newEvent);
             return true;
         } else if (keyEvent->key() == Qt::Key_Escape) {
             popup()->hide();
         }
     }
     return QCompleter::eventFilter(obj, event);
 }
init()
void HistoryCompleter::init () private
Definition at line 179 of file historycompleter.cpp.
 {
     setPopup(new HistoryCompletionView());
     // we want to complete against our own faked role
     setCompletionRole(HistoryCompletionModel::HistoryCompletionRole);
     // and since we fake our completion role, we can take
     // advantage of the sorted-model optimizations in QCompleter
     setCaseSensitivity(Qt::CaseSensitive);
     setModelSorting(QCompleter::CaseSensitivelySortedModel);
     m_filterTimer.setSingleShot(true);
     connect(&m_filterTimer, SIGNAL(timeout()), this, SLOT(updateFilter()));
 }
References HistoryCompletionModel::HistoryCompletionRole, m_filterTimer, and updateFilter().
Referenced by HistoryCompleter().
pathFromIndex()
QString HistoryCompleter::pathFromIndex (const QModelIndex & index) const virtual
Definition at line 195 of file historycompleter.cpp.
 {
     // we want to return the actual url from the history for the
     // data the QCompleter finally returns
     return model()->data(index, HistoryModel::UrlStringRole).toString();
 }
References HistoryModel::UrlStringRole.
splitPath()
QStringList HistoryCompleter::splitPath (const QString & path) const virtual
Definition at line 202 of file historycompleter.cpp.
 {
     if (path == m_searchString)
         return QStringList() << QLatin1String("a");
     // queue an update to our search string
     // We will wait a bit so that if the user is quickly typing,
     // we don't try to complete until they pause.
     if (m_filterTimer.isActive())
         m_filterTimer.stop();
     m_filterTimer.start(150);
     // if the previous search results are not a superset of
     // the current search results, tell the model that it is not valid yet
     if (!path.startsWith(m_searchString)) {
         HistoryCompletionModel *completionModel = qobject_cast<HistoryCompletionModel*>(model());
         Q_ASSERT(completionModel);
         completionModel->setValid(false);
     }
     m_searchString = path;
     // the actual filtering is done by the HistoryCompletionModel; we just
     // return a short dummy here so that QCompleter thinks we match everything
     return QStringList() << QLatin1String("a");
 }
References m_filterTimer, m_searchString, and HistoryCompletionModel::setValid().
updateFilter
void HistoryCompleter::updateFilter () private slot
Definition at line 260 of file historycompleter.cpp.
 {
     HistoryCompletionModel *completionModel = qobject_cast<HistoryCompletionModel*>(model());
     Q_ASSERT(completionModel);
     // tell the HistoryCompletionModel about the new search string
     completionModel->setSearchString(m_searchString);
     // sort the model
     completionModel->sort(0);
     // mark it valid
     completionModel->setValid(true);
     // and now update the QCompleter widget, but only if the user is still
     // typing a url
     if (widget() && widget()->hasFocus())
         complete();
 }
References m_searchString, HistoryCompletionModel::setSearchString(), and HistoryCompletionModel::setValid().
Referenced by init().
Member Data Documentation
m_filterTimer
QTimer HistoryCompleter::m_filterTimer mutable private
Definition at line 104 of file historycompleter.h.
Referenced by init(), and splitPath().
m_searchString
QString HistoryCompleter::m_searchString mutable private
Definition at line 103 of file historycompleter.h.
Referenced by splitPath(), and updateFilter().
The documentation for this class was generated from the following files:
src/history/historycompleter.h
src/history/historycompleter.cpp