Endorphin: BookmarksToolBar Class Reference
BookmarksToolBar Class Reference
#include <bookmarkstoolbar.h>
Signals
void openUrl (const QUrl &url, const QString &title)
void openUrl (const QUrl &url, TabWidget::OpenUrlIn tab, const QString &title)
Signals inherited from ModelToolBar
void activated (const QModelIndex &index)
Public Member Functions
BookmarksToolBar (BookmarksModel *model, QWidget *parent=nullptr)
Public Member Functions inherited from ModelToolBar
ModelToolBar (QWidget *parent=nullptr)
ModelToolBar (const QString &title, QWidget *parent=nullptr)
void setModel (QAbstractItemModel *model)
QAbstractItemModel * model () const
void setRootIndex (const QModelIndex &index)
QModelIndex rootIndex () const
Protected Slots
void openBookmark ()
void openBookmarkInCurrentTab ()
void openBookmarkInNewTab ()
void removeBookmark ()
void newBookmark ()
void newFolder ()
void bookmarkActivated (const QModelIndex &)
Protected Slots inherited from ModelToolBar
void build ()
Protected Member Functions
virtual ModelMenu * createMenu ()
Protected Member Functions inherited from ModelToolBar
bool eventFilter (QObject *object, QEvent *event)
void hideEvent (QHideEvent *event)
void showEvent (QShowEvent *event)
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
void mouseMoveEvent (QMouseEvent *event)
Private Slots
void contextMenuRequested (const QPoint &position)
Private Attributes
BookmarksModel * m_bookmarksModel
QPoint m_dragStartPosition
Additional Inherited Members
Static Public Member Functions inherited from ModelToolBar
static QModelIndex index (QAction *action)
Detailed Description
Definition at line 33 of file bookmarkstoolbar.h.
Constructor & Destructor Documentation
BookmarksToolBar()
BookmarksToolBar::BookmarksToolBar (BookmarksModel * model, QWidget * parent = nullptr)
Definition at line 39 of file bookmarkstoolbar.cpp.
     : ModelToolBar(parent)
     , m_bookmarksModel(model)
 {
     setModel(model);
 #ifndef NO_BROWSERAPPLICATION
     setRootIndex(model->index(BrowserApplication::bookmarksManager()->toolbar()));
 #else
     #ifdef FOR_AUTOTEST
     setRootIndex(model->index(tst_AddBookmarkDialog::bookmarksManager()->toolbar()));
     #else
         #error "Nothing provides a bookmarksmanager"
     #endif
 #endif
     setContextMenuPolicy(Qt::CustomContextMenu);
     connect(this, SIGNAL(customContextMenuRequested(const QPoint &)),
             this, SLOT(contextMenuRequested(const QPoint &)));
     connect(this, SIGNAL(activated(const QModelIndex &)),
             this, SLOT(bookmarkActivated(const QModelIndex &)));
     setHidden(true);
     setToolButtonStyle(Qt::ToolButtonTextOnly);
 }
References ModelToolBar::activated(), bookmarkActivated(), BrowserApplication::bookmarksManager(), contextMenuRequested(), ModelToolBar::model(), ModelToolBar::setModel(), ModelToolBar::setRootIndex(), and BookmarksManager::toolbar().
Member Function Documentation
bookmarkActivated
void BookmarksToolBar::bookmarkActivated (const QModelIndex & index) protected slot
Definition at line 99 of file bookmarkstoolbar.cpp.
 {
     Q_ASSERT(index.isValid());
     emit openUrl(
         index.data(BookmarksModel::UrlRole).toUrl(),
         index.data(Qt::DisplayRole).toString());
 }
References ModelToolBar::index(), openUrl(), and BookmarksModel::UrlRole.
Referenced by BookmarksToolBar().
contextMenuRequested
void BookmarksToolBar::contextMenuRequested (const QPoint & position) private slot
Definition at line 65 of file bookmarkstoolbar.cpp.
 {
     QAction *action = actionAt(position);
     QMenu menu;
     if (action) {
         QVariant variant = action->data();
         Q_ASSERT(variant.canConvert<QModelIndex>());
         QAction *menuAction = nullptr;
         if (!action->menu()) {
             menuAction = menu.addAction(tr("Open"), this, SLOT(openBookmarkInCurrentTab()));
             menuAction->setData(variant);
             menuAction = menu.addAction(tr("Open in New &Tab"), this, SLOT(openBookmarkInNewTab()));
             menuAction->setData(variant);
             menu.addSeparator();
         }
         menuAction = menu.addAction(tr("Remove"), this, SLOT(removeBookmark()));
         menuAction->setData(variant);
         menu.addSeparator();
     }
     menu.addAction(tr("Add Bookmark..."), this, SLOT(newBookmark()));
     menu.addAction(tr("Add Folder..."), this, SLOT(newFolder()));
     menu.exec(QCursor::pos());
 }
References newBookmark(), newFolder(), openBookmarkInCurrentTab(), openBookmarkInNewTab(), and removeBookmark().
Referenced by BookmarksToolBar().
createMenu()
ModelMenu * BookmarksToolBar::createMenu () protected virtual
Reimplemented from ModelToolBar.
Definition at line 159 of file bookmarkstoolbar.cpp.
 {
     BookmarksMenu *menu = new BookmarksMenu(this);
     connect(menu, SIGNAL(openUrl(const QUrl&, const QString&)),
             this, SIGNAL(openUrl(const QUrl&, const QString&)));
     connect(menu, SIGNAL(openUrl(const QUrl&, TabWidget::OpenUrlIn, const QString &)),
             this, SIGNAL(openUrl(const QUrl&, TabWidget::OpenUrlIn, const QString &)));
     return menu;
 }
References openUrl().
newBookmark
void BookmarksToolBar::newBookmark () protected slot
Definition at line 144 of file bookmarkstoolbar.cpp.
 {
     AddBookmarkDialog dialog;
     dialog.setCurrentIndex(rootIndex());
     dialog.exec();
 }
References ModelToolBar::rootIndex(), and AddBookmarkDialog::setCurrentIndex().
Referenced by contextMenuRequested().
newFolder
void BookmarksToolBar::newFolder () protected slot
Definition at line 151 of file bookmarkstoolbar.cpp.
 {
     AddBookmarkDialog dialog;
     dialog.setCurrentIndex(rootIndex());
     dialog.setFolder(true);
     dialog.exec();
 }
References ModelToolBar::rootIndex(), AddBookmarkDialog::setCurrentIndex(), and AddBookmarkDialog::setFolder().
Referenced by contextMenuRequested().
openBookmark
void BookmarksToolBar::openBookmark () protected slot
Definition at line 108 of file bookmarkstoolbar.cpp.
 {
     QModelIndex index = ModelToolBar::index(qobject_cast<QAction*>(sender()));
     emit openUrl(
         index.data(BookmarksModel::UrlRole).toUrl(),
         index.data(Qt::DisplayRole).toString());
 }
References ModelToolBar::index(), openUrl(), and BookmarksModel::UrlRole.
openBookmarkInCurrentTab
void BookmarksToolBar::openBookmarkInCurrentTab () protected slot
Definition at line 117 of file bookmarkstoolbar.cpp.
 {
     QModelIndex index = ModelToolBar::index(qobject_cast<QAction*>(sender()));
     emit openUrl(
         index.data(BookmarksModel::UrlRole).toUrl(),
         TabWidget::CurrentTab,
         index.data(Qt::DisplayRole).toString());
 }
References TabWidget::CurrentTab, ModelToolBar::index(), openUrl(), and BookmarksModel::UrlRole.
Referenced by contextMenuRequested().
openBookmarkInNewTab
void BookmarksToolBar::openBookmarkInNewTab () protected slot
Definition at line 127 of file bookmarkstoolbar.cpp.
 {
     QModelIndex index = ModelToolBar::index(qobject_cast<QAction*>(sender()));
     emit openUrl(
         index.data(BookmarksModel::UrlRole).toUrl(),
         TabWidget::NewTab,
         index.data(Qt::DisplayRole).toString());
 }
References ModelToolBar::index(), TabWidget::NewTab, openUrl(), and BookmarksModel::UrlRole.
Referenced by contextMenuRequested().
openUrl [1/2]
void BookmarksToolBar::openUrl (const QUrl & url, const QString & title) signal
Referenced by bookmarkActivated(), createMenu(), openBookmark(), openBookmarkInCurrentTab(), and openBookmarkInNewTab().
openUrl [2/2]
void BookmarksToolBar::openUrl (const QUrl & url, TabWidget::OpenUrlIn tab, const QString & title) signal
removeBookmark
void BookmarksToolBar::removeBookmark () protected slot
Definition at line 137 of file bookmarkstoolbar.cpp.
 {
     QModelIndex index = ModelToolBar::index(qobject_cast<QAction*>(sender()));
     m_bookmarksModel->removeRow(index.row(), rootIndex());
 }
References ModelToolBar::index(), m_bookmarksModel, and ModelToolBar::rootIndex().
Referenced by contextMenuRequested().
Member Data Documentation
m_bookmarksModel
BookmarksModel* BookmarksToolBar::m_bookmarksModel private
Definition at line 60 of file bookmarkstoolbar.h.
Referenced by removeBookmark().
m_dragStartPosition
QPoint BookmarksToolBar::m_dragStartPosition private
Definition at line 62 of file bookmarkstoolbar.h.
The documentation for this class was generated from the following files:
src/bookmarks/bookmarkstoolbar.h
src/bookmarks/bookmarkstoolbar.cpp