Endorphin: TabWidget Class Reference
TabWidget Class Reference
#include <tabwidget.h>
Public Types
enum OpenUrlIn {
NewWindow, NewSelectedTab, NewNotSelectedTab, CurrentTab,
UserOrCurrent, NewTab = NewNotSelectedTab
}
Public Slots
void loadString (const QString &string, OpenUrlIn tab=CurrentTab)
void loadUrlFromUser (const QUrl &url, const QString &title=QString())
void loadUrl (const QUrl &url, TabWidget::OpenUrlIn tab=CurrentTab, const QString &title=QString())
void createTab (const QByteArray &historyState, TabWidget::OpenUrlIn tab=CurrentTab)
void newTab ()
void cloneTab (int index=-1)
void closeTab (int index=-1)
void closeOtherTabs (int index)
void reloadTab (int index=-1)
void reloadAllTabs ()
void nextTab ()
void previousTab ()
void bookmarkTabs ()
Signals
void tabsChanged ()
void lastTabClosed ()
void setCurrentTitle (const QString &url)
void showStatusBarMessage (const QString &message)
void linkHovered (const QString &link)
void loadProgress (int progress)
void geometryChangeRequested (const QRect &geometry)
void printRequested (QWebEnginePage *page)
void devToolsRequested (QWebEnginePage *source)
Public Member Functions
TabWidget (QWidget *parent=nullptr)
void loadSettings ()
TabBar * tabBar ()
void clear ()
void addWebAction (QAction *action, QWebEnginePage::WebAction webAction)
QAction * newTabAction () const
QAction * closeTabAction () const
QAction * bookmarkTabsAction () const
QAction * recentlyClosedTabsAction () const
QAction * nextTabAction () const
QAction * previousTabAction () const
QWidget * locationBarStack () const
QLineEdit * currentLocationBar () const
WebView * currentWebView () const
WebView * webView (int index) const
WebViewSearch * webViewSearch (int index) const
QLineEdit * locationBar (int index) const
int webViewIndex (WebView *webView) const
WebView * makeNewTab (bool makeCurrent=false)
QByteArray saveState () const
bool restoreState (const QByteArray &state)
WebView * getView (OpenUrlIn tab, WebView *currentView)
Static Public Member Functions
static OpenUrlIn modifyWithUserBehavior (OpenUrlIn tab)
Protected Member Functions
void changeEvent (QEvent *event)
Private Slots
void currentChanged (int index)
void openLastTab ()
void aboutToShowRecentTabsMenu ()
void aboutToShowRecentTriggeredAction (QAction *action)
void webViewLoadStarted ()
void webViewLoadProgress (int progress)
void webViewLoadFinished (bool ok)
void webViewIconChanged ()
void webViewTitleChanged (const QString &title)
void webViewUrlChanged (const QUrl &url)
void lineEditReturnPressed ()
void windowCloseRequested ()
void moveTab (int fromIndex, int toIndex)
void geometryChangeRequestedCheck (const QRect &geometry)
void historyCleared ()
Private Member Functions
QLabel * animationLabel (int index, bool addMovie)
void retranslate ()
Static Private Member Functions
static QUrl guessUrlFromString (const QString &url)
Private Attributes
QAction * m_recentlyClosedTabsAction
QAction * m_newTabAction
QAction * m_closeTabAction
QAction * m_bookmarkTabsAction
QAction * m_nextTabAction
QAction * m_previousTabAction
QMenu * m_recentlyClosedTabsMenu
QList< QUrl > m_recentlyClosedTabs
QList< QByteArray > m_recentlyClosedTabsHistory
QList< WebActionMapper * > m_actions
QCompleter * m_lineEditCompleter
QStackedWidget * m_locationBars
TabBar * m_tabBar
QToolButton * addTabButton
QToolButton * closeTabButton
Static Private Attributes
static const int m_recentlyClosedTabsSize = 10
Detailed Description
TabWidget that contains WebViews and a stack widget of associated line edits.
Connects up the current tab's signals to this class's signal and uses WebActionMapper to proxy the actions.
Definition at line 92 of file tabwidget.h.
Member Enumeration Documentation
OpenUrlIn
enum TabWidget::OpenUrlIn
Enumerator
NewWindow
NewSelectedTab
NewNotSelectedTab
CurrentTab
UserOrCurrent
NewTab
Definition at line 111 of file tabwidget.h.
                    {
         NewWindow,
         NewSelectedTab,
         NewNotSelectedTab,
         CurrentTab,
         UserOrCurrent,
         NewTab = NewNotSelectedTab
     };
Constructor & Destructor Documentation
TabWidget()
TabWidget::TabWidget (QWidget * parent = nullptr)
Definition at line 101 of file tabwidget.cpp.
     : QTabWidget(parent)
     , m_recentlyClosedTabsAction(nullptr)
     , m_newTabAction(nullptr)
     , m_closeTabAction(nullptr)
     , m_bookmarkTabsAction(nullptr)
     , m_nextTabAction(nullptr)
     , m_previousTabAction(nullptr)
     , m_recentlyClosedTabsMenu(nullptr)
     , m_lineEditCompleter(nullptr)
     , m_locationBars(nullptr)
     , m_tabBar(new TabBar(this))
     , addTabButton(nullptr)
     , closeTabButton(nullptr)
 {
     setElideMode(Qt::ElideRight);
     new QShortcut(QKeySequence(Qt::CTRL | Qt::SHIFT | Qt::Key_T), this, SLOT(openLastTab()));
     new QShortcut(QKeySequence::Undo, this, SLOT(openLastTab()));
     connect(m_tabBar, SIGNAL(loadUrl(const QUrl&, TabWidget::OpenUrlIn)),
             this, SLOT(loadUrl(const QUrl&, TabWidget::OpenUrlIn)));
     connect(m_tabBar, SIGNAL(newTab()), this, SLOT(newTab()));
     connect(m_tabBar, SIGNAL(closeTab(int)), this, SLOT(closeTab(int)));
     connect(m_tabBar, SIGNAL(cloneTab(int)), this, SLOT(cloneTab(int)));
     connect(m_tabBar, SIGNAL(closeOtherTabs(int)), this, SLOT(closeOtherTabs(int)));
     connect(m_tabBar, SIGNAL(reloadTab(int)), this, SLOT(reloadTab(int)));
     connect(m_tabBar, SIGNAL(reloadAllTabs()), this, SLOT(reloadAllTabs()));
     setTabBar(m_tabBar);
     setDocumentMode(true);
     connect(m_tabBar, SIGNAL(tabMoved(int, int)),
             this, SLOT(moveTab(int, int)));
     // Actions
     m_newTabAction = new QAction(this);
     m_newTabAction->setShortcuts(QKeySequence::AddTab);
     connect(m_newTabAction, SIGNAL(triggered()), this, SLOT(newTab()));
     m_closeTabAction = new QAction(this);
     m_closeTabAction->setShortcuts(QKeySequence::Close);
     m_closeTabAction->setIcon(QIcon(QLatin1String(":graphics/closetab.png")));
 #if !defined(Q_WS_X11)
     m_closeTabAction->setIconVisibleInMenu(false);
 #endif
     connect(m_closeTabAction, SIGNAL(triggered()), this, SLOT(closeTab()));
     m_bookmarkTabsAction = new QAction(this);
     connect(m_bookmarkTabsAction, SIGNAL(triggered()), this, SLOT(bookmarkTabs()));
     m_newTabAction->setIcon(QIcon(QLatin1String(":graphics/addtab.png")));
 #if !defined(Q_WS_X11)
     m_newTabAction->setIconVisibleInMenu(false);
 #endif
     m_nextTabAction = new QAction(this);
     connect(m_nextTabAction, SIGNAL(triggered()), this, SLOT(nextTab()));
     m_previousTabAction = new QAction(this);
     connect(m_previousTabAction, SIGNAL(triggered()), this, SLOT(previousTab()));
 #if defined(Q_WS_X11)
     m_previousTabAction->setIcon(QIcon::fromTheme(QLatin1String("go-previous")));
     m_nextTabAction->setIcon(QIcon::fromTheme(QLatin1String("go-next")));
 #endif
     m_recentlyClosedTabsMenu = new QMenu(this);
     connect(m_recentlyClosedTabsMenu, SIGNAL(aboutToShow()),
             this, SLOT(aboutToShowRecentTabsMenu()));
     connect(m_recentlyClosedTabsMenu, SIGNAL(triggered(QAction *)),
             this, SLOT(aboutToShowRecentTriggeredAction(QAction *)));
     m_recentlyClosedTabsAction = new QAction(this);
     m_recentlyClosedTabsAction->setMenu(m_recentlyClosedTabsMenu);
     m_recentlyClosedTabsAction->setEnabled(false);
 #ifndef Q_WS_MAC // can't seem to figure out the background color :(
     addTabButton = new QToolButton(this);
     addTabButton->setDefaultAction(m_newTabAction);
     addTabButton->setAutoRaise(true);
     addTabButton->setToolButtonStyle(Qt::ToolButtonIconOnly);
     addTabButton->setIconSize(QSize(50, 100));
 #endif
     connect(m_tabBar, SIGNAL(tabCloseRequested(int)),
             this, SLOT(closeTab(int)));
     connect(this, SIGNAL(currentChanged(int)),
             this, SLOT(currentChanged(int)));
     m_locationBars = new QStackedWidget(this);
     connect(BrowserApplication::historyManager(), SIGNAL(historyCleared()),
             this, SLOT(historyCleared()));
     // Initialize Actions' labels
     retranslate();
     loadSettings();
 }
References aboutToShowRecentTabsMenu(), aboutToShowRecentTriggeredAction(), addTabButton, bookmarkTabs(), cloneTab(), closeOtherTabs(), closeTab(), currentChanged(), historyCleared(), BrowserApplication::historyManager(), loadSettings(), loadUrl(), m_bookmarkTabsAction, m_closeTabAction, m_locationBars, m_newTabAction, m_nextTabAction, m_previousTabAction, m_recentlyClosedTabsAction, m_recentlyClosedTabsMenu, m_tabBar, moveTab(), newTab(), nextTab(), openLastTab(), previousTab(), reloadAllTabs(), reloadTab(), and retranslate().
Member Function Documentation
aboutToShowRecentTabsMenu
void TabWidget::aboutToShowRecentTabsMenu () private slot
Definition at line 709 of file tabwidget.cpp.
 {
     m_recentlyClosedTabsMenu->clear();
     for (int i = 0; i < m_recentlyClosedTabs.count(); ++i) {
         QAction *action = new QAction(m_recentlyClosedTabsMenu);
         action->setData(m_recentlyClosedTabsHistory.at(i));
         QIcon icon = BrowserApplication::instance()->icon(m_recentlyClosedTabs.at(i));
         action->setIcon(icon);
         action->setText(m_recentlyClosedTabs.at(i).toString());
         m_recentlyClosedTabsMenu->addAction(action);
     }
 }
References BrowserApplication::icon(), BrowserApplication::instance(), m_recentlyClosedTabs, m_recentlyClosedTabsHistory, and m_recentlyClosedTabsMenu.
Referenced by TabWidget().
aboutToShowRecentTriggeredAction
void TabWidget::aboutToShowRecentTriggeredAction (QAction * action) private slot
Definition at line 722 of file tabwidget.cpp.
 {
     if (!action)
         return;
     QByteArray historyState = action->data().toByteArray();
     createTab(historyState, NewTab);
 }
References createTab(), and NewTab.
Referenced by TabWidget().
addWebAction()
void TabWidget::addWebAction (QAction * action, QWebEnginePage::WebAction webAction)
Definition at line 236 of file tabwidget.cpp.
 {
     if (!action)
         return;
     m_actions.append(new WebActionMapper(action, webAction, this));
 }
References m_actions.
Referenced by BrowserMainWindow::setupMenu().
animationLabel()
QLabel * TabWidget::animationLabel (int index, bool addMovie) private
Definition at line 578 of file tabwidget.cpp.
 {
     if (-1 == index)
         return nullptr;
     QTabBar::ButtonPosition side = m_tabBar->freeSide();
     QLabel *loadingAnimation = qobject_cast<QLabel*>(m_tabBar->tabButton(index, side));
     if (!loadingAnimation) {
         loadingAnimation = new QLabel(this);
     }
     if (addMovie && !loadingAnimation->movie()) {
         QMovie *movie = new QMovie(QLatin1String(":graphics/loading.gif"), QByteArray(), loadingAnimation);
         movie->setSpeed(50);
         loadingAnimation->setMovie(movie);
         movie->start();
     }
     m_tabBar->setTabButton(index, side, nullptr);
     m_tabBar->setTabButton(index, side, loadingAnimation);
     return loadingAnimation;
 }
References TabBar::freeSide(), and m_tabBar.
Referenced by webViewIconChanged(), webViewLoadFinished(), and webViewLoadStarted().
bookmarkTabs
void TabWidget::bookmarkTabs () slot
Definition at line 449 of file tabwidget.cpp.
 {
     AddBookmarkDialog dialog;
     dialog.setFolder(true);
     dialog.setTitle(tr("Saved Tabs"));
     dialog.exec();
     BookmarkNode *folder = dialog.addedNode();
     if (!folder)
         return;
     for (int i = 0; i < count(); ++i) {
         WebView *tab = webView(i);
         if (!tab)
             continue;
         QString title = tab->title();
         QString url = QString::fromUtf8(tab->url().toEncoded());
         BookmarkNode *bookmark = new BookmarkNode(BookmarkNode::Bookmark);
         bookmark->url = url;
         bookmark->title = title;
         BrowserApplication::bookmarksManager()->addBookmark(folder, bookmark);
     }
 }
References BookmarksManager::addBookmark(), AddBookmarkDialog::addedNode(), BookmarkNode::Bookmark, BrowserApplication::bookmarksManager(), AddBookmarkDialog::setFolder(), AddBookmarkDialog::setTitle(), BookmarkNode::title, WebView::url(), BookmarkNode::url, and webView().
Referenced by TabWidget().
bookmarkTabsAction()
QAction * TabWidget::bookmarkTabsAction () const
Definition at line 289 of file tabwidget.cpp.
 {
     return m_bookmarkTabsAction;
 }
References m_bookmarkTabsAction.
Referenced by TabBar::contextMenuRequested().
changeEvent()
void TabWidget::changeEvent (QEvent * event) protected
Definition at line 756 of file tabwidget.cpp.
 {
     if (event->type() == QEvent::LanguageChange)
         retranslate();
     QTabWidget::changeEvent(event);
 }
References retranslate().
clear()
void TabWidget::clear ()
Definition at line 203 of file tabwidget.cpp.
 {
     // clear the recently closed tabs
     m_recentlyClosedTabs.clear();
     m_recentlyClosedTabsAction->setEnabled(false);
     // clear the line edit history
     for (int i = 0; i < m_locationBars->count(); ++i) {
         QLineEdit *qLineEdit = locationBar(i);
         qLineEdit->setText(qLineEdit->text());
         webViewSearch(i)->clear();
     }
 }
References SearchBar::clear(), locationBar(), m_locationBars, m_recentlyClosedTabs, m_recentlyClosedTabsAction, and webViewSearch().
Referenced by BrowserMainWindow::privacyChanged().
cloneTab
void TabWidget::cloneTab (int index = -1) slot
Definition at line 513 of file tabwidget.cpp.
 {
     if (index < 0)
         index = currentIndex();
     if (index < 0 || index >= count())
         return;
     QUrl url = webView(index)->url();
     WebView *tab = makeNewTab();
     tab->loadUrl(url);
 }
References WebView::loadUrl(), makeNewTab(), WebView::url(), and webView().
Referenced by TabWidget().
closeOtherTabs
void TabWidget::closeOtherTabs (int index) slot
Definition at line 502 of file tabwidget.cpp.
 {
     if (-1 == index)
         return;
     for (int i = count() - 1; i > index; --i)
         closeTab(i);
     for (int i = index - 1; i >= 0; --i)
         closeTab(i);
 }
References closeTab().
Referenced by TabWidget().
closeTab
void TabWidget::closeTab (int index = -1) slot
Definition at line 525 of file tabwidget.cpp.
 {
     if (index < 0)
         index = currentIndex();
     if (index < 0 || index >= count())
         return;
     bool hasFocus = false;
     WebView *tab = webView(index);
     if (tab && !tab->url().isEmpty()) {
         /*
         if (tab->isModified()) {
             QMessageBox closeConfirmation(tab);
             closeConfirmation.setWindowFlags(Qt::Sheet);
             closeConfirmation.setWindowTitle(tr("Do you really want to close this page?"));
             closeConfirmation.setInformativeText(tr("You have modified this page and when closing it you would lose the modification.\n"
                                                     "Do you really want to close this page?\n"));
             closeConfirmation.setIcon(QMessageBox::Question);
             closeConfirmation.addButton(QMessageBox::Yes);
             closeConfirmation.addButton(QMessageBox::No);
             closeConfirmation.setEscapeButton(QMessageBox::No);
             if (closeConfirmation.exec() == QMessageBox::No)
                 return;
         }
         */
         hasFocus = tab->hasFocus();
         m_recentlyClosedTabsAction->setEnabled(true);
         m_recentlyClosedTabs.prepend(tab->url());
         QByteArray tabHistory;
         QDataStream tabHistoryStream(&tabHistory, QIODevice::WriteOnly);
         tabHistoryStream << *tab->history();
         m_recentlyClosedTabsHistory.prepend(tabHistory);
         if (m_recentlyClosedTabs.size() >= TabWidget::m_recentlyClosedTabsSize)
             m_recentlyClosedTabs.removeLast();
     }
     QWidget *lineEdit = m_locationBars->widget(index);
     m_locationBars->removeWidget(lineEdit);
     lineEdit->deleteLater();
     QWidget *webViewWithSearch = widget(index);
     removeTab(index);
     webViewWithSearch->setParent(nullptr);
     webViewWithSearch->deleteLater();
     emit tabsChanged();
     if (hasFocus && count() > 0 && currentWebView())
         currentWebView()->setFocus();
     if (count() == 0)
         emit lastTabClosed();
 }
References currentWebView(), lastTabClosed(), m_locationBars, m_recentlyClosedTabs, m_recentlyClosedTabsAction, m_recentlyClosedTabsHistory, m_recentlyClosedTabsSize, tabsChanged(), WebView::url(), and webView().
Referenced by closeOtherTabs(), TabWidget(), and windowCloseRequested().
closeTabAction()
QAction * TabWidget::closeTabAction () const
Definition at line 284 of file tabwidget.cpp.
 {
     return m_closeTabAction;
 }
References m_closeTabAction.
Referenced by BrowserMainWindow::setupMenu().
createTab
void TabWidget::createTab (const QByteArray & historyState, TabWidget::OpenUrlIn tab = CurrentTab) slot
Definition at line 1046 of file tabwidget.cpp.
 {
     if (WebView *webView = getView(tab, currentWebView())) {
         QDataStream historyStream(historyState);
         historyStream >> *webView->history();
     }
 }
References currentWebView(), getView(), and webView().
Referenced by aboutToShowRecentTriggeredAction(), openLastTab(), and restoreState().
currentChanged
void TabWidget::currentChanged (int index) private slot
Definition at line 243 of file tabwidget.cpp.
 {
     WebView *webView = this->webView(index);
     if (!webView)
         return;
     Q_ASSERT(m_locationBars->count() == count());
     WebView *oldWebView = this->webView(m_locationBars->currentIndex());
     if (oldWebView) {
         disconnect(oldWebView->page(), SIGNAL(linkHovered(const QString&)),
                    this, SIGNAL(linkHovered(const QString&)));
         disconnect(oldWebView, SIGNAL(loadProgress(int)),
                    this, SIGNAL(loadProgress(int)));
     }
     connect(webView->page(), SIGNAL(linkHovered(const QString&)),
             this, SIGNAL(linkHovered(const QString&)));
     connect(webView, SIGNAL(loadProgress(int)),
             this, SIGNAL(loadProgress(int)));
     for (int i = 0; i < m_actions.count(); ++i) {
         WebActionMapper *mapper = m_actions[i];
         mapper->updateCurrent(webView->page());
     }
     emit setCurrentTitle(webView->title());
     m_locationBars->setCurrentIndex(index);
     emit loadProgress(webView->progress());
     emit showStatusBarMessage(webView->lastStatusBarText());
     if (webView->url().isEmpty() && webView->hasFocus()) {
         m_locationBars->currentWidget()->setFocus();
     } else if (!webView->url().isEmpty()) {
         webView->setFocus();
     }
 }
References WebView::lastStatusBarText(), linkHovered(), loadProgress(), m_actions, m_locationBars, WebView::progress(), setCurrentTitle(), showStatusBarMessage(), WebActionMapper::updateCurrent(), WebView::url(), and webView().
Referenced by makeNewTab(), and TabWidget().
currentLocationBar()
QLineEdit * TabWidget::currentLocationBar () const
Definition at line 314 of file tabwidget.cpp.
 {
     return locationBar(m_locationBars->currentIndex());
 }
References locationBar(), and m_locationBars.
Referenced by BrowserMainWindow::BrowserMainWindow(), BrowserMainWindow::selectLineEdit(), and BrowserMainWindow::swapFocus().
currentWebView()
WebView * TabWidget::currentWebView () const
Definition at line 319 of file tabwidget.cpp.
 {
     return webView(currentIndex());
 }
References webView().
Referenced by closeTab(), createTab(), BrowserMainWindow::currentTab(), lineEditReturnPressed(), loadUrl(), and restoreState().
devToolsRequested
void TabWidget::devToolsRequested (QWebEnginePage * source) signal
Referenced by BrowserMainWindow::BrowserMainWindow(), and makeNewTab().
geometryChangeRequested
void TabWidget::geometryChangeRequested (const QRect & geometry) signal
Referenced by geometryChangeRequestedCheck(), and makeNewTab().
geometryChangeRequestedCheck
void TabWidget::geometryChangeRequestedCheck (const QRect & geometry) private slot
Definition at line 434 of file tabwidget.cpp.
 {
     if (count() == 1)
         emit geometryChangeRequested(geometry);
 }
References geometryChangeRequested().
Referenced by makeNewTab().
getView()
WebView * TabWidget::getView (OpenUrlIn tab, WebView * currentView)
Definition at line 910 of file tabwidget.cpp.
 {
     WebView *webView = nullptr;
     switch (tab) {
     case NewWindow: {
 #ifdef USERMODIFIEDBEHAVIOR_DEBUG
         qDebug() << __FUNCTION__ << "NewWindow";
 #endif
         BrowserMainWindow *newMainWindow = BrowserApplication::instance()->newMainWindow();
         webView = newMainWindow->currentTab();
         webView->setFocus();
         break;
     }
     case NewSelectedTab: {
 #ifdef USERMODIFIEDBEHAVIOR_DEBUG
         qDebug() << __FUNCTION__ << "NewSelectedTab";
 #endif
         webView = makeNewTab(true);
         webView->setFocus();
         break;
     }
     case NewNotSelectedTab: {
 #ifdef USERMODIFIEDBEHAVIOR_DEBUG
         qDebug() << __FUNCTION__ << "NewNotSelectedTab";
 #endif
         webView = makeNewTab(false);
         break;
     }
     case CurrentTab:
     default:
 #ifdef USERMODIFIEDBEHAVIOR_DEBUG
         qDebug() << __FUNCTION__ << "CurrentTab";
 #endif
         webView = currentView;
         if (!webView)
             return nullptr;
         webView->setFocus();
         break;
     }
     return webView;
 }
References BrowserMainWindow::currentTab(), CurrentTab, BrowserApplication::instance(), makeNewTab(), BrowserApplication::newMainWindow(), NewNotSelectedTab, NewSelectedTab, NewWindow, and webView().
Referenced by WebPage::acceptNavigationRequest(), createTab(), WebPage::createWindow(), loadUrl(), WebView::openActionUrlInNewTab(), WebView::openActionUrlInNewWindow(), and restoreState().
guessUrlFromString()
QUrl TabWidget::guessUrlFromString (const QString & url) static private
Definition at line 777 of file tabwidget.cpp.
 {
     OpenSearchManager *manager = ToolbarSearch::openSearchManager();
     QUrl url = manager->convertKeywordSearchToUrl(string);
     if (url.isValid())
         return url;
     url = QUrl::fromUserInput(string);
     if (url.scheme() == QLatin1String("about")
             && url.path() == QLatin1String("home"))
         url = QUrl(QLatin1String("https://endorphinbrowser.github.io/newTab/0.13.0-preview1/"));
     // QUrl::isValid() is too much tolerant.
     // We actually want to check if the url conforms to the RFC, which QUrl::isValid() doesn't state.
     if (!url.scheme().isEmpty() && (!url.host().isEmpty() || !url.path().isEmpty()))
         return url;
     QSettings settings;
     settings.beginGroup(QLatin1String("urlloading"));
     bool search = settings.value(QLatin1String("searchEngineFallback"), false).toBool();
     if (search) {
         url = ToolbarSearch::openSearchManager()->currentEngine()->searchUrl(string.trimmed());
     } else {
         QString urlString = QLatin1String("http://") + string.trimmed();
         url = QUrl::fromEncoded(urlString.toUtf8(), QUrl::TolerantMode);
     }
     return url;
 }
References OpenSearchManager::convertKeywordSearchToUrl(), OpenSearchManager::currentEngine(), ToolbarSearch::openSearchManager(), and OpenSearchEngine::searchUrl().
Referenced by loadString().
historyCleared
void TabWidget::historyCleared () private slot
Definition at line 197 of file tabwidget.cpp.
 {
     m_recentlyClosedTabs.clear();
     m_recentlyClosedTabsAction->setEnabled(false);
 }
References m_recentlyClosedTabs, and m_recentlyClosedTabsAction.
Referenced by TabWidget().
lastTabClosed
void TabWidget::lastTabClosed () signal
Referenced by closeTab().
lineEditReturnPressed
void TabWidget::lineEditReturnPressed () private slot
Definition at line 474 of file tabwidget.cpp.
 {
     if (QLineEdit *lineEdit = qobject_cast<QLineEdit*>(sender())) {
         OpenUrlIn tab = CurrentTab;
         if (qApp->keyboardModifiers() == Qt::AltModifier)
             tab = NewSelectedTab;
         loadString(lineEdit->text(), tab);
         if (m_locationBars->currentWidget() == lineEdit)
             currentWebView()->setFocus();
     }
 }
References CurrentTab, currentWebView(), loadString(), m_locationBars, and NewSelectedTab.
Referenced by makeNewTab().
linkHovered
void TabWidget::linkHovered (const QString & link) signal
Referenced by currentChanged().
loadProgress
void TabWidget::loadProgress (int progress) signal
Referenced by currentChanged(), and makeNewTab().
loadSettings()
void TabWidget::loadSettings ()
Definition at line 820 of file tabwidget.cpp.
 {
     for (int i = 0; i < count(); ++i) {
         WebView *v = webView(i);
         if (v && v->page())
             v->loadSettings();
     }
     QSettings settings;
     settings.beginGroup(QLatin1String("tabs"));
     bool newTabButtonInRightCorner = settings.value(QLatin1String("newTabButtonInRightCorner"), true).toBool();
 #ifndef Q_WS_MAC
     setCornerWidget(addTabButton, newTabButtonInRightCorner ? Qt::TopRightCorner : Qt::TopLeftCorner);
     addTabButton->show();
 #endif
     bool oneCloseButton = settings.value(QLatin1String("oneCloseButton"), false).toBool();
     if (oneCloseButton) {
         if (!closeTabButton) {
             closeTabButton = new QToolButton(this);
             closeTabButton->setDefaultAction(m_closeTabAction);
             closeTabButton->setAutoRaise(true);
             closeTabButton->setToolButtonStyle(Qt::ToolButtonIconOnly);
         }
         setCornerWidget(closeTabButton, newTabButtonInRightCorner ? Qt::TopLeftCorner : Qt::TopRightCorner);
         closeTabButton->setVisible(oneCloseButton);
     } else {
         setCornerWidget(nullptr, newTabButtonInRightCorner ? Qt::TopLeftCorner : Qt::TopRightCorner);
     }
     m_tabBar->setTabsClosable(!oneCloseButton);
 }
References addTabButton, closeTabButton, WebView::loadSettings(), m_closeTabAction, m_tabBar, and webView().
Referenced by SettingsDialog::saveToSettings(), and TabWidget().
loadString
void TabWidget::loadString (const QString & string, OpenUrlIn tab = CurrentTab) slot
Definition at line 768 of file tabwidget.cpp.
 {
     if (string.isEmpty())
         return;
     QUrl url = guessUrlFromString(string);
     loadUrl(url, tab);
 }
References guessUrlFromString(), and loadUrl().
Referenced by BrowserMainWindow::goHome(), lineEditReturnPressed(), makeNewTab(), BrowserApplication::messageReceived(), and BrowserApplication::postLaunch().
loadUrl
void TabWidget::loadUrl (const QUrl & url, TabWidget::OpenUrlIn tab = CurrentTab, const QString & title = QString()) slot
Definition at line 889 of file tabwidget.cpp.
 {
     if (tab == UserOrCurrent) {
         loadUrlFromUser(url, title);
         return;
     }
     if (!url.isValid())
         return;
     WebView *webView = getView(tab, currentWebView());
     if (webView) {
         int index = webViewIndex(webView);
         if (index != -1)
             locationBar(index)->setText(QString::fromUtf8(url.toEncoded()));
         webView->loadUrl(url, title);
     }
 }
References currentWebView(), getView(), WebView::loadUrl(), loadUrlFromUser(), locationBar(), UserOrCurrent, webView(), and webViewIndex().
Referenced by BrowserMainWindow::fileOpen(), loadString(), loadUrlFromUser(), makeNewTab(), BrowserApplication::openUrl(), and TabWidget().
loadUrlFromUser
void TabWidget::loadUrlFromUser (const QUrl & url, const QString & title = QString()) slot
Definition at line 815 of file tabwidget.cpp.
 {
     loadUrl(url, modifyWithUserBehavior(CurrentTab), title);
 }
References CurrentTab, loadUrl(), and modifyWithUserBehavior().
Referenced by loadUrl().
locationBar()
QLineEdit * TabWidget::locationBar (int index) const
Definition at line 324 of file tabwidget.cpp.
 {
     return qobject_cast<LocationBar*>(m_locationBars->widget(index));
 }
References m_locationBars.
Referenced by clear(), currentLocationBar(), loadUrl(), and makeNewTab().
locationBarStack()
QWidget * TabWidget::locationBarStack () const
Definition at line 309 of file tabwidget.cpp.
 {
     return m_locationBars;
 }
References m_locationBars.
Referenced by BrowserMainWindow::setupToolBar().
makeNewTab()
WebView * TabWidget::makeNewTab (bool makeCurrent = false)
Definition at line 364 of file tabwidget.cpp.
 {
     // line edit
     LocationBar *locationBar = new LocationBar;
     if (!m_lineEditCompleter) {
         HistoryCompletionModel *completionModel = new HistoryCompletionModel(this);
         completionModel->setSourceModel(BrowserApplication::historyManager()->historyFilterModel());
         m_lineEditCompleter = new HistoryCompleter(completionModel, this);
         connect(m_lineEditCompleter, SIGNAL(activated(const QString &)),
                 this, SLOT(loadString(const QString &)));
         // Should this be in Qt by default?
         QAbstractItemView *popup = m_lineEditCompleter->popup();
         QListView *listView = qobject_cast<QListView*>(popup);
         if (listView) {
             // Urls are always LeftToRight
             listView->setLayoutDirection(Qt::LeftToRight);
             listView->setUniformItemSizes(true);
         }
     }
     locationBar->setCompleter(m_lineEditCompleter);
     connect(locationBar, SIGNAL(returnPressed()), this, SLOT(lineEditReturnPressed()));
     m_locationBars->addWidget(locationBar);
     m_locationBars->setSizePolicy(locationBar->sizePolicy());
 #ifndef AUTOTESTS
     QWidget::setTabOrder(locationBar, BrowserMainWindow::parentWindow(this)->findChild<ToolbarSearch*>());
 #endif
     // webview
     WebView *webView = new WebView;
     locationBar->setWebView(webView);
     connect(webView, SIGNAL(loadStarted()),
             this, SLOT(webViewLoadStarted()));
     connect(webView, SIGNAL(loadProgress(int)),
             this, SLOT(webViewLoadProgress(int)));
     connect(webView, SIGNAL(loadFinished(bool)),
             this, SLOT(webViewLoadFinished(bool)));
     connect(webView, SIGNAL(iconChanged(QIcon)),
             this, SLOT(webViewIconChanged()));
     connect(webView, SIGNAL(titleChanged(const QString &)),
             this, SLOT(webViewTitleChanged(const QString &)));
     connect(webView, SIGNAL(urlChanged(const QUrl &)),
             this, SLOT(webViewUrlChanged(const QUrl &)));
     connect(webView, SIGNAL(search(const QUrl&, TabWidget::OpenUrlIn)),
             this, SLOT(loadUrl(const QUrl&, TabWidget::OpenUrlIn)));
     connect(webView->page(), SIGNAL(windowCloseRequested()),
             this, SLOT(windowCloseRequested()));
     connect(webView->page(), SIGNAL(printRequested(Q)),
             this, SIGNAL(printRequested(webView->page())));
     connect(webView->page(), SIGNAL(geometryChangeRequested(const QRect &)),
             this, SLOT(geometryChangeRequestedCheck(const QRect &)));
     connect(webView, &WebView::devToolsRequested, this, &TabWidget::devToolsRequested);
     WebViewWithSearch *webViewWithSearch = new WebViewWithSearch(webView, this);
     addTab(webViewWithSearch, tr("Untitled"));
     if (makeCurrent)
         setCurrentWidget(webViewWithSearch);
     // webview actions
     for (int i = 0; i < m_actions.count(); ++i) {
         WebActionMapper *mapper = m_actions[i];
         mapper->addChild(webView->page()->action(mapper->webAction()));
     }
     if (count() == 1)
         currentChanged(currentIndex());
     emit tabsChanged();
     return webView;
 }
References WebActionMapper::addChild(), currentChanged(), WebView::devToolsRequested(), devToolsRequested(), geometryChangeRequested(), geometryChangeRequestedCheck(), BrowserApplication::historyManager(), lineEditReturnPressed(), loadProgress(), loadString(), loadUrl(), locationBar(), m_actions, m_lineEditCompleter, m_locationBars, BrowserMainWindow::parentWindow(), printRequested(), tabsChanged(), WebActionMapper::webAction(), webView(), webViewIconChanged(), webViewLoadFinished(), webViewLoadProgress(), webViewLoadStarted(), webViewTitleChanged(), webViewUrlChanged(), and windowCloseRequested().
Referenced by cloneTab(), getView(), BrowserMainWindow::lastTabClosed(), and newTab().
modifyWithUserBehavior()
TabWidget::OpenUrlIn TabWidget::modifyWithUserBehavior (OpenUrlIn tab) static
Definition at line 859 of file tabwidget.cpp.
{
     Qt::KeyboardModifiers modifiers = BrowserApplication::instance()->eventKeyboardModifiers();
     Qt::MouseButtons buttons = BrowserApplication::instance()->eventMouseButtons();
 #ifdef USERMODIFIEDBEHAVIOR_DEBUG
     qDebug() << __FUNCTION__ << "start" << modifiers << buttons << tab;
 #endif
     if (modifiers & Qt::ControlModifier || buttons == Qt::MidButton) {
         if (modifiers & Qt::AltModifier) {
             tab = NewWindow;
         } else {
             QSettings settings;
             settings.beginGroup(QLatin1String("tabs"));
             bool select = settings.value(QLatin1String("selectNewTabs"), false).toBool();
             if (modifiers & Qt::ShiftModifier)
                 tab = !select ? NewSelectedTab : NewNotSelectedTab;
             else
                 tab = select ? NewSelectedTab : NewNotSelectedTab;
         }
     }
 #ifdef USERMODIFIEDBEHAVIOR_DEBUG
     qDebug() << __FUNCTION__ << "end" << modifiers << buttons << tab;
 #endif
     BrowserApplication::instance()->setEventKeyboardModifiers(nullptr);
     BrowserApplication::instance()->setEventMouseButtons(Qt::NoButton);
     return tab;
 }
References BrowserApplication::eventKeyboardModifiers(), BrowserApplication::eventMouseButtons(), BrowserApplication::instance(), NewNotSelectedTab, NewSelectedTab, NewWindow, BrowserApplication::setEventKeyboardModifiers(), and BrowserApplication::setEventMouseButtons().
Referenced by WebPage::acceptNavigationRequest(), WebPage::createWindow(), and loadUrlFromUser().
moveTab
void TabWidget::moveTab (int fromIndex, int toIndex) private slot
Definition at line 229 of file tabwidget.cpp.
 {
     QWidget *lineEdit = m_locationBars->widget(fromIndex);
     m_locationBars->removeWidget(lineEdit);
     m_locationBars->insertWidget(toIndex, lineEdit);
 }
References m_locationBars.
Referenced by TabWidget().
newTab
void TabWidget::newTab () slot
Definition at line 359 of file tabwidget.cpp.
 {
     makeNewTab(true);
 }
References makeNewTab().
Referenced by BrowserMainWindow::BrowserMainWindow(), BrowserMainWindow::closeEvent(), and TabWidget().
newTabAction()
QAction * TabWidget::newTabAction () const
Definition at line 279 of file tabwidget.cpp.
 {
     return m_newTabAction;
 }
References m_newTabAction.
Referenced by TabBar::contextMenuRequested(), and BrowserMainWindow::setupMenu().
nextTab
void TabWidget::nextTab () slot
Definition at line 955 of file tabwidget.cpp.
 {
     int next = currentIndex() + 1;
     if (next == count())
         next = 0;
     setCurrentIndex(next);
 }
Referenced by TabWidget().
nextTabAction()
QAction * TabWidget::nextTabAction () const
Definition at line 299 of file tabwidget.cpp.
 {
     return m_nextTabAction;
 }
References m_nextTabAction.
Referenced by BrowserMainWindow::aboutToShowWindowMenu().
openLastTab
void TabWidget::openLastTab () private slot
Definition at line 699 of file tabwidget.cpp.
 {
     if (m_recentlyClosedTabs.isEmpty())
         return;
     QUrl url = m_recentlyClosedTabs.takeFirst();
     QByteArray historyState = m_recentlyClosedTabsHistory.takeFirst();
     createTab(historyState, NewTab);
     m_recentlyClosedTabsAction->setEnabled(!m_recentlyClosedTabs.isEmpty());
 }
References createTab(), m_recentlyClosedTabs, m_recentlyClosedTabsAction, m_recentlyClosedTabsHistory, and NewTab.
Referenced by TabWidget().
previousTab
void TabWidget::previousTab () slot
Definition at line 963 of file tabwidget.cpp.
 {
     int next = currentIndex() - 1;
     if (next < 0)
         next = count() - 1;
     setCurrentIndex(next);
 }
Referenced by TabWidget().
previousTabAction()
QAction * TabWidget::previousTabAction () const
Definition at line 304 of file tabwidget.cpp.
 {
     return m_previousTabAction;
 }
References m_previousTabAction.
Referenced by BrowserMainWindow::aboutToShowWindowMenu().
printRequested
void TabWidget::printRequested (QWebEnginePage * page) signal
Referenced by makeNewTab().
recentlyClosedTabsAction()
QAction * TabWidget::recentlyClosedTabsAction () const
Definition at line 294 of file tabwidget.cpp.
 {
     return m_recentlyClosedTabsAction;
 }
References m_recentlyClosedTabsAction.
Referenced by BrowserMainWindow::setupMenu().
reloadAllTabs
void TabWidget::reloadAllTabs () slot
Definition at line 440 of file tabwidget.cpp.
 {
     for (int i = 0; i < count(); ++i) {
         if (WebView *tab = webView(i)) {
             tab->reload();
         }
     }
 }
References webView().
Referenced by TabWidget().
reloadTab
void TabWidget::reloadTab (int index = -1) slot
Definition at line 217 of file tabwidget.cpp.
 {
     if (index < 0)
         index = currentIndex();
     if (index < 0 || index >= count())
         return;
     if (WebView *tab = webView(index)) {
         tab->reload();
     }
 }
References webView().
Referenced by TabWidget().
restoreState()
bool TabWidget::restoreState (const QByteArray & state)
Definition at line 1007 of file tabwidget.cpp.
 {
     int version = 1;
     QByteArray sd = state;
     QDataStream stream(&sd, QIODevice::ReadOnly);
     if (stream.atEnd())
         return false;
     qint32 marker;
     qint32 v;
     stream >> marker;
     stream >> v;
     if (marker != TabWidgetMagic || v != version)
         return false;
     QStringList openTabs;
     stream >> openTabs;
     int currentTab;
     stream >> currentTab;
     setCurrentIndex(currentTab);
     QList<QByteArray> tabHistory;
     stream >> tabHistory;
     for (int i = 0; i < openTabs.count(); ++i) {
         QUrl url = QUrl::fromEncoded(openTabs.at(i).toUtf8());
         TabWidget::OpenUrlIn tab = i == 0 && currentWebView()->url() == QUrl() ? CurrentTab : NewTab;
         QByteArray historyState = tabHistory.value(i);
         if (!historyState.isEmpty()) {
             createTab(historyState, tab);
         } else {
             if (WebView *webView = getView(tab, currentWebView()))
                 webView->loadUrl(url);
         }
     }
     return true;
 }
References createTab(), CurrentTab, currentWebView(), getView(), WebView::loadUrl(), NewTab, TabWidgetMagic, WebView::url(), and webView().
Referenced by BrowserMainWindow::restoreState().
retranslate()
void TabWidget::retranslate () private
Definition at line 731 of file tabwidget.cpp.
 {
     m_nextTabAction->setText(tr("Show Next Tab"));
     QList<QKeySequence> shortcuts;
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_BraceRight));
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_PageDown));
     shortcuts.append(tr("Ctrl-]"));
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_Less));
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_Tab));
     m_nextTabAction->setShortcuts(shortcuts);
     m_previousTabAction->setText(tr("Show Previous Tab"));
     shortcuts.clear();
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_BraceLeft));
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_PageUp));
     shortcuts.append(tr("Ctrl-["));
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_Greater));
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::SHIFT | Qt::Key_Tab));
     m_previousTabAction->setShortcuts(shortcuts);
     m_recentlyClosedTabsAction->setText(tr("Recently Closed Tabs"));
     m_newTabAction->setText(tr("New &Tab"));
     m_closeTabAction->setText(tr("&Close Tab"));
     m_bookmarkTabsAction->setText(tr("Bookmark All Tabs"));
     m_tabBar->updateViewToolBarAction();
 }
References m_bookmarkTabsAction, m_closeTabAction, m_newTabAction, m_nextTabAction, m_previousTabAction, m_recentlyClosedTabsAction, m_tabBar, and TabBar::updateViewToolBarAction().
Referenced by changeEvent(), and TabWidget().
saveState()
QByteArray TabWidget::saveState () const
Definition at line 973 of file tabwidget.cpp.
 {
     int version = 1;
     QByteArray data;
     QDataStream stream(&data, QIODevice::WriteOnly);
     stream << qint32(TabWidgetMagic);
     stream << qint32(version);
     QStringList tabs;
     QList<QByteArray> tabsHistory;
     for (int i = 0; i < count(); ++i) {
         if (WebView *tab = webView(i)) {
             tabs.append(QString::fromUtf8(tab->url().toEncoded()));
             if (tab->history()->count() != 0) {
                 QByteArray tabHistory;
                 QDataStream tabHistoryStream(&tabHistory, QIODevice::WriteOnly);
                 tabHistoryStream << *tab->history();
                 tabsHistory.append(tabHistory);
             } else {
                 tabsHistory << QByteArray();
             }
         } else {
             tabs.append(QString());
             tabsHistory.append(QByteArray());
         }
     }
     stream << tabs;
     stream << currentIndex();
     stream << tabsHistory;
     return data;
 }
References TabWidgetMagic, and webView().
Referenced by BrowserMainWindow::saveState().
setCurrentTitle
void TabWidget::setCurrentTitle (const QString & url) signal
Referenced by currentChanged(), and webViewTitleChanged().
showStatusBarMessage
void TabWidget::showStatusBarMessage (const QString & message) signal
Referenced by currentChanged(), webViewLoadFinished(), webViewLoadProgress(), and webViewLoadStarted().
tabBar()
TabBar* TabWidget::tabBar () inline
Definition at line 123 of file tabwidget.h.
                      {
         return m_tabBar;
     }
References m_tabBar.
Referenced by BrowserMainWindow::restoreState(), BrowserMainWindow::saveState(), and BrowserMainWindow::setupMenu().
tabsChanged
void TabWidget::tabsChanged () signal
Referenced by closeTab(), makeNewTab(), and webViewUrlChanged().
webView()
WebView * TabWidget::webView (int index) const
Definition at line 329 of file tabwidget.cpp.
 {
     QWidget *widget = this->widget(index);
     if (WebViewWithSearch *webViewWithSearch = qobject_cast<WebViewWithSearch*>(widget)) {
         return webViewWithSearch->m_webView;
     }
     return nullptr;
 }
Referenced by bookmarkTabs(), cloneTab(), closeTab(), createTab(), currentChanged(), currentWebView(), getView(), loadSettings(), loadUrl(), makeNewTab(), reloadAllTabs(), reloadTab(), restoreState(), BrowserMainWindow::runScriptOnOpenViews(), saveState(), webViewIconChanged(), webViewIndex(), webViewLoadFinished(), webViewLoadProgress(), webViewLoadStarted(), webViewTitleChanged(), webViewUrlChanged(), and windowCloseRequested().
webViewIconChanged
void TabWidget::webViewIconChanged () private slot
Definition at line 656 of file tabwidget.cpp.
 {
     WebView *webView = qobject_cast<WebView*>(sender());
     int index = webViewIndex(webView);
     if (-1 != index) {
 #if !defined(Q_WS_MAC)
         QIcon icon = BrowserApplication::instance()->icon(webView->url());
         QLabel *label = animationLabel(index, false);
         QMovie *movie = label->movie();
         delete movie;
         label->setMovie(nullptr);
         label->setPixmap(icon.pixmap(16, 16));
 #endif
     }
 }
References animationLabel(), BrowserApplication::icon(), BrowserApplication::instance(), WebView::url(), webView(), and webViewIndex().
Referenced by makeNewTab(), and webViewLoadFinished().
webViewIndex()
int TabWidget::webViewIndex (WebView * webView) const
Definition at line 347 of file tabwidget.cpp.
 {
     for (int i = 0; i < count(); ++i) {
         QWidget *widget = this->widget(i);
         if (WebViewWithSearch *webViewWithSearch = qobject_cast<WebViewWithSearch*>(widget)) {
             if (webViewWithSearch->m_webView == webView)
                 return i;
         }
     }
     return -1;
 }
References webView().
Referenced by loadUrl(), webViewIconChanged(), webViewLoadFinished(), webViewLoadProgress(), webViewLoadStarted(), webViewTitleChanged(), webViewUrlChanged(), and windowCloseRequested().
webViewLoadFinished
void TabWidget::webViewLoadFinished (bool ok) private slot
Definition at line 630 of file tabwidget.cpp.
 {
     WebView *webView = qobject_cast<WebView*>(sender());
     int index = webViewIndex(webView);
     if (-1 != index) {
         QLabel *label = animationLabel(index, true);
         if (label->movie())
             label->movie()->stop();
 #if defined(Q_WS_MAC)
         QTabBar::ButtonPosition side = m_tabBar->freeSide();
         m_tabBar->setTabButton(index, side, 0);
         delete label;
 #endif
     }
     webViewIconChanged();
     if (index != currentIndex())
         return;
     if (ok)
         emit showStatusBarMessage(tr("Finished loading"));
     else
         emit showStatusBarMessage(tr("Failed to load"));
 }
References animationLabel(), TabBar::freeSide(), m_tabBar, showStatusBarMessage(), webView(), webViewIconChanged(), and webViewIndex().
Referenced by makeNewTab().
webViewLoadProgress
void TabWidget::webViewLoadProgress (int progress) private slot
Definition at line 614 of file tabwidget.cpp.
 {
     WebView *webView = qobject_cast<WebView*>(sender());
     int index = webViewIndex(webView);
     if (index != currentIndex()
             || index < 0)
         return;
     //double totalBytes = (double) webView->webPage()->totalBytes() / 1024;
     //QString message = tr("Loading %1% (%2 %3)...").arg(progress).arg(totalBytes, 0, 'f', 2).arg(QLatin1String("kB"));
     QString message = tr("Loading ...");
     emit showStatusBarMessage(message);
 }
References showStatusBarMessage(), webView(), and webViewIndex().
Referenced by makeNewTab().
webViewLoadStarted
void TabWidget::webViewLoadStarted () private slot
Definition at line 598 of file tabwidget.cpp.
 {
     WebView *webView = qobject_cast<WebView*>(sender());
     int index = webViewIndex(webView);
     if (-1 != index) {
         QLabel *label = animationLabel(index, true);
         if (label->movie())
             label->movie()->start();
     }
     if (index != currentIndex())
         return;
     emit showStatusBarMessage(tr("Loading..."));
 }
References animationLabel(), showStatusBarMessage(), webView(), and webViewIndex().
Referenced by makeNewTab().
webViewSearch()
WebViewSearch * TabWidget::webViewSearch (int index) const
Definition at line 338 of file tabwidget.cpp.
 {
     QWidget *widget = this->widget(index);
     if (WebViewWithSearch *webViewWithSearch = qobject_cast<WebViewWithSearch*>(widget)) {
         return webViewWithSearch->m_webViewSearch;
     }
     return nullptr;
 }
Referenced by clear(), BrowserMainWindow::editFind(), BrowserMainWindow::editFindNext(), and BrowserMainWindow::editFindPrevious().
webViewTitleChanged
void TabWidget::webViewTitleChanged (const QString & title) private slot
Definition at line 672 of file tabwidget.cpp.
 {
     WebView *webView = qobject_cast<WebView*>(sender());
     int index = webViewIndex(webView);
     if (-1 == index)
         return;
     QString tabTitle = title;
     if (title.isEmpty())
         tabTitle = QString::fromUtf8(webView->url().toEncoded());
     tabTitle.replace(QLatin1Char('&'), QLatin1String("&&"));
     setTabText(index, tabTitle);
     setTabToolTip(index, tabTitle);
     if (currentIndex() == index)
         emit setCurrentTitle(title);
     BrowserApplication::historyManager()->updateHistoryEntry(webView->url(), title);
 }
References BrowserApplication::historyManager(), setCurrentTitle(), HistoryManager::updateHistoryEntry(), WebView::url(), webView(), and webViewIndex().
Referenced by makeNewTab().
webViewUrlChanged
void TabWidget::webViewUrlChanged (const QUrl & url) private slot
Definition at line 689 of file tabwidget.cpp.
 {
     WebView *webView = qobject_cast<WebView*>(sender());
     int index = webViewIndex(webView);
     if (-1 == index)
         return;
     m_tabBar->setTabData(index, url);
     emit tabsChanged();
 }
References m_tabBar, tabsChanged(), webView(), and webViewIndex().
Referenced by makeNewTab().
windowCloseRequested
void TabWidget::windowCloseRequested () private slot
Definition at line 487 of file tabwidget.cpp.
 {
     WebPage *webPage = qobject_cast<WebPage*>(sender());
     if (!webPage)
         return;
     WebView *webView = qobject_cast<WebView*>(webPage->view());
     int index = webViewIndex(webView);
     if (index >= 0) {
         if (count() == 1)
             BrowserMainWindow::parentWindow(this)->close();
         else
             closeTab(index);
     }
 }
References closeTab(), BrowserMainWindow::parentWindow(), webView(), and webViewIndex().
Referenced by makeNewTab().
Member Data Documentation
addTabButton
QToolButton* TabWidget::addTabButton private
Definition at line 207 of file tabwidget.h.
Referenced by loadSettings(), and TabWidget().
closeTabButton
QToolButton* TabWidget::closeTabButton private
Definition at line 208 of file tabwidget.h.
Referenced by loadSettings().
m_actions
QList<WebActionMapper*> TabWidget::m_actions private
Definition at line 202 of file tabwidget.h.
Referenced by addWebAction(), currentChanged(), and makeNewTab().
m_bookmarkTabsAction
QAction* TabWidget::m_bookmarkTabsAction private
Definition at line 194 of file tabwidget.h.
Referenced by bookmarkTabsAction(), retranslate(), and TabWidget().
m_closeTabAction
QAction* TabWidget::m_closeTabAction private
Definition at line 193 of file tabwidget.h.
Referenced by closeTabAction(), loadSettings(), retranslate(), and TabWidget().
m_lineEditCompleter
QCompleter* TabWidget::m_lineEditCompleter private
Definition at line 204 of file tabwidget.h.
Referenced by makeNewTab().
m_locationBars
QStackedWidget* TabWidget::m_locationBars private
Definition at line 205 of file tabwidget.h.
Referenced by clear(), closeTab(), currentChanged(), currentLocationBar(), lineEditReturnPressed(), locationBar(), locationBarStack(), makeNewTab(), moveTab(), and TabWidget().
m_newTabAction
QAction* TabWidget::m_newTabAction private
Definition at line 192 of file tabwidget.h.
Referenced by newTabAction(), retranslate(), and TabWidget().
m_nextTabAction
QAction* TabWidget::m_nextTabAction private
Definition at line 195 of file tabwidget.h.
Referenced by nextTabAction(), retranslate(), and TabWidget().
m_previousTabAction
QAction* TabWidget::m_previousTabAction private
Definition at line 196 of file tabwidget.h.
Referenced by previousTabAction(), retranslate(), and TabWidget().
m_recentlyClosedTabs
QList<QUrl> TabWidget::m_recentlyClosedTabs private
Definition at line 200 of file tabwidget.h.
Referenced by aboutToShowRecentTabsMenu(), clear(), closeTab(), historyCleared(), and openLastTab().
m_recentlyClosedTabsAction
QAction* TabWidget::m_recentlyClosedTabsAction private
Definition at line 191 of file tabwidget.h.
Referenced by clear(), closeTab(), historyCleared(), openLastTab(), recentlyClosedTabsAction(), retranslate(), and TabWidget().
m_recentlyClosedTabsHistory
QList<QByteArray> TabWidget::m_recentlyClosedTabsHistory private
Definition at line 201 of file tabwidget.h.
Referenced by aboutToShowRecentTabsMenu(), closeTab(), and openLastTab().
m_recentlyClosedTabsMenu
QMenu* TabWidget::m_recentlyClosedTabsMenu private
Definition at line 198 of file tabwidget.h.
Referenced by aboutToShowRecentTabsMenu(), and TabWidget().
m_recentlyClosedTabsSize
const int TabWidget::m_recentlyClosedTabsSize = 10 static private
Definition at line 199 of file tabwidget.h.
Referenced by closeTab().
m_tabBar
TabBar* TabWidget::m_tabBar private
Definition at line 206 of file tabwidget.h.
Referenced by animationLabel(), loadSettings(), retranslate(), tabBar(), TabWidget(), webViewLoadFinished(), and webViewUrlChanged().
The documentation for this class was generated from the following files:
src/tabwidget.h
src/tabwidget.cpp