Endorphin: ClearPrivateData Class Reference
ClearPrivateData Class Reference
#include <clearprivatedata.h>
Public Slots
void accept ()
Public Member Functions
ClearPrivateData (QWidget *parent=nullptr)
Private Attributes
QCheckBox * m_browsingHistory
QCheckBox * m_downloadHistory
QCheckBox * m_searchHistory
QCheckBox * m_cookies
QCheckBox * m_cache
QCheckBox * m_favIcons
Detailed Description
Definition at line 27 of file clearprivatedata.h.
Constructor & Destructor Documentation
ClearPrivateData()
ClearPrivateData::ClearPrivateData (QWidget * parent = nullptr)
Definition at line 38 of file clearprivatedata.cpp.
     : QDialog(parent, Qt::WindowTitleHint | Qt::WindowSystemMenuHint)
 {
     setWindowTitle(tr("Clear Private Data"));
     QVBoxLayout *layout = new QVBoxLayout();
     layout->addWidget(new QLabel(tr("Clear the following items:")));
     QSettings settings;
     settings.beginGroup(QLatin1String("clearprivatedata"));
     m_browsingHistory = new QCheckBox(tr("&Browsing History"));
     m_browsingHistory->setChecked(settings.value(QLatin1String("browsingHistory"), true).toBool());
     layout->addWidget(m_browsingHistory);
     m_downloadHistory = new QCheckBox(tr("&Download History"));
     m_downloadHistory->setChecked(settings.value(QLatin1String("downloadHistory"), true).toBool());
     layout->addWidget(m_downloadHistory);
     m_searchHistory = new QCheckBox(tr("&Search History"));
     m_searchHistory->setChecked(settings.value(QLatin1String("searchHistory"), true).toBool());
     layout->addWidget(m_searchHistory);
     m_favIcons = new QCheckBox(tr("Website &Icons"));
     m_favIcons->setChecked(settings.value(QLatin1String("favIcons"), true).toBool());
     layout->addWidget(m_favIcons);
     settings.endGroup();
     QPushButton *acceptButton = new QPushButton(tr("Clear &Private Data"));
     acceptButton->setDefault(true);
     QPushButton *rejectButton = new QPushButton(tr("&Cancel"));
     QDialogButtonBox *buttonBox = new QDialogButtonBox;
     buttonBox->addButton(acceptButton, QDialogButtonBox::AcceptRole);
     buttonBox->addButton(rejectButton, QDialogButtonBox::RejectRole);
     connect(buttonBox, SIGNAL(accepted()), this, SLOT(accept()));
     connect(buttonBox, SIGNAL(rejected()), this, SLOT(reject()));
     layout->addWidget(buttonBox);
     setLayout(layout);
     acceptButton->setFocus(Qt::OtherFocusReason);
 }
References accept(), m_browsingHistory, m_downloadHistory, m_favIcons, and m_searchHistory.
Member Function Documentation
accept
void ClearPrivateData::accept () slot
Definition at line 81 of file clearprivatedata.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("clearprivatedata"));
     settings.setValue(QLatin1String("browsingHistory"), m_browsingHistory->isChecked());
     settings.setValue(QLatin1String("downloadHistory"), m_downloadHistory->isChecked());
     settings.setValue(QLatin1String("searchHistory"), m_searchHistory->isChecked());
     settings.setValue(QLatin1String("cache"), m_cache->isChecked());
     settings.setValue(QLatin1String("favIcons"), m_favIcons->isChecked());
     settings.endGroup();
     if (m_browsingHistory->isChecked()) {
         BrowserApplication::historyManager()->clear();
     }
     if (m_downloadHistory->isChecked()) {
         BrowserApplication::downloadManager()->cleanup();
         BrowserApplication::downloadManager()->hide();
     }
     if (m_searchHistory->isChecked()) {
         QList<BrowserMainWindow*> mainWindows = BrowserApplication::instance()->mainWindows();
         for (int i = 0; i < mainWindows.count(); ++i) {
             mainWindows.at(i)->toolbarSearch()->setText(QString());
         }
     }
     if (m_favIcons->isChecked()) {
         //QWebEngineSettings::clearIconDatabase();
     }
     QDialog::accept();
 }
References DownloadManager::cleanup(), HistoryManager::clear(), BrowserApplication::downloadManager(), BrowserApplication::historyManager(), BrowserApplication::instance(), m_browsingHistory, m_cache, m_downloadHistory, m_favIcons, m_searchHistory, and BrowserApplication::mainWindows().
Referenced by ClearPrivateData().
Member Data Documentation
m_browsingHistory
QCheckBox* ClearPrivateData::m_browsingHistory private
Definition at line 38 of file clearprivatedata.h.
Referenced by accept(), and ClearPrivateData().
m_cache
QCheckBox* ClearPrivateData::m_cache private
Definition at line 42 of file clearprivatedata.h.
Referenced by accept().
m_cookies
QCheckBox* ClearPrivateData::m_cookies private
Definition at line 41 of file clearprivatedata.h.
m_downloadHistory
QCheckBox* ClearPrivateData::m_downloadHistory private
Definition at line 39 of file clearprivatedata.h.
Referenced by accept(), and ClearPrivateData().
m_favIcons
QCheckBox* ClearPrivateData::m_favIcons private
Definition at line 43 of file clearprivatedata.h.
Referenced by accept(), and ClearPrivateData().
m_searchHistory
QCheckBox* ClearPrivateData::m_searchHistory private
Definition at line 40 of file clearprivatedata.h.
Referenced by accept(), and ClearPrivateData().
The documentation for this class was generated from the following files:
src/clearprivatedata.h
src/clearprivatedata.cpp