Endorphin: HistoryFilterModel Class Reference
HistoryFilterModel Class Reference
#include <history.h>
Classes
struct HistoryData
Public Types
enum Roles { FrecencyRole = HistoryModel::MaxRole + 1, MaxRole = FrecencyRole }
Public Member Functions
HistoryFilterModel (QAbstractItemModel *sourceModel, QObject *parent=nullptr)
bool historyContains (const QString &url) const
int historyLocation (const QString &url) const
QModelIndex mapFromSource (const QModelIndex &sourceIndex) const
QModelIndex mapToSource (const QModelIndex &proxyIndex) const
void setSourceModel (QAbstractItemModel *sourceModel)
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
int columnCount (const QModelIndex &parent=QModelIndex()) const
QModelIndex index (int, int, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &index=QModelIndex()) const
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
void recalculateFrecencies ()
Private Slots
void sourceReset ()
void sourceDataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
void sourceRowsInserted (const QModelIndex &parent, int start, int end)
void sourceRowsRemoved (const QModelIndex &, int, int)
void refreshFrecencies ()
Private Member Functions
void load () const
void startFrecencyTimer ()
int frecencyScore (const QModelIndex &sourceIndex) const
Private Attributes
QTimer m_frecencyTimer
QString m_lastSavedUrl
QList< HistoryData > m_filteredRows
QHash< QString, int > m_historyHash
bool m_loaded
QDateTime m_scaleTime
Detailed Description
Proxy model that will remove any duplicate entries. Both m_sourceRow and m_historyHash store their offsets not from the front of the list, but as offsets from the back.
Definition at line 112 of file history.h.
Member Enumeration Documentation
Roles
enum HistoryFilterModel::Roles
Enumerator
FrecencyRole
MaxRole
Definition at line 123 of file history.h.
                {
         FrecencyRole = HistoryModel::MaxRole + 1,
         MaxRole = FrecencyRole
     };
Constructor & Destructor Documentation
HistoryFilterModel()
HistoryFilterModel::HistoryFilterModel (QAbstractItemModel * sourceModel, QObject * parent = nullptr)
Definition at line 485 of file history.cpp.
     : QAbstractProxyModel(parent)
     , m_loaded(false)
 {
     m_frecencyTimer.setSingleShot(true);
     connect(&m_frecencyTimer, SIGNAL(timeout()),
             this, SLOT(refreshFrecencies()));
     setSourceModel(sourceModel);
     startFrecencyTimer();
 }
References m_frecencyTimer, refreshFrecencies(), setSourceModel(), and startFrecencyTimer().
Member Function Documentation
columnCount()
int HistoryFilterModel::columnCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 584 of file history.cpp.
 {
     return (parent.isValid()) ? 0 : 2;
 }
References parent().
Referenced by index().
data()
QVariant HistoryFilterModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Definition at line 519 of file history.cpp.
 {
     if (role == FrecencyRole && index.isValid()) {
         return m_filteredRows[index.row()].frecency;
     }
     return QAbstractProxyModel::data(index, role);
 }
References FrecencyRole, index(), and m_filteredRows.
frecencyScore()
int HistoryFilterModel::frecencyScore (const QModelIndex & sourceIndex) const private
Definition at line 712 of file history.cpp.
 {
     QDateTime loadTime = sourceModel()->data(sourceIndex, HistoryModel::DateTimeRole).toDateTime();
     int days = loadTime.daysTo(m_scaleTime);
     if (days <= 1) {
         return 100;
     } else if (days < 5) { // within the last 4 days
         return 90;
     } else if (days < 15) { // within the last two weeks
         return 70;
     } else if (days < 31) { // within the last month
         return 50;
     } else if (days < 91) { // within the last 3 months
         return 30;
     }
     return 10;
 }
References HistoryModel::DateTimeRole, and m_scaleTime.
Referenced by load(), and sourceRowsInserted().
headerData()
QVariant HistoryFilterModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Definition at line 559 of file history.cpp.
 {
     return sourceModel()->headerData(section, orientation, role);
 }
historyContains()
bool HistoryFilterModel::historyContains (const QString & url) const inline
Definition at line 119 of file history.h.
         { load(); return m_historyHash.contains(url); }
References load(), and m_historyHash.
Referenced by HistoryManager::historyContains().
historyLocation()
int HistoryFilterModel::historyLocation (const QString & url) const
Definition at line 510 of file history.cpp.
 {
     load();
     if (!m_historyHash.contains(url))
         return 0;
     return sourceModel()->rowCount() - m_historyHash.value(url);
 }
References load(), and m_historyHash.
index()
QModelIndex HistoryFilterModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
Definition at line 614 of file history.cpp.
 {
     load();
     if (row < 0 || row >= rowCount(parent)
             || column < 0 || column >= columnCount(parent))
         return QModelIndex();
     return createIndex(row, column, m_filteredRows[row].tailOffset);
 }
References columnCount(), load(), m_filteredRows, parent(), and rowCount().
Referenced by data().
load()
void HistoryFilterModel::load () const private
Definition at line 629 of file history.cpp.
 {
     if (m_loaded)
         return;
     m_filteredRows.clear();
     m_historyHash.clear();
     m_historyHash.reserve(sourceModel()->rowCount());
     m_scaleTime = QDateTime::currentDateTime();
     for (int i = 0; i < sourceModel()->rowCount(); ++i) {
         QModelIndex idx = sourceModel()->index(i, 0);
         QString url = idx.data(HistoryModel::UrlStringRole).toString();
         if (!m_historyHash.contains(url)) {
             int sourceOffset = sourceModel()->rowCount() - i;
             m_filteredRows.append(HistoryData(sourceOffset, frecencyScore(idx)));
             m_historyHash.insert(url, sourceOffset);
         } else {
             // we already know about this url: just increment its frecency score
             QList<HistoryData>::iterator pos = std::lower_bound(m_filteredRows.begin(),
                                                m_filteredRows.end(), HistoryData(m_historyHash[url], -1));
             Q_ASSERT(pos != m_filteredRows.end());
             pos->frecency += frecencyScore(idx);
         }
     }
     m_loaded = true;
 }
References frecencyScore(), m_filteredRows, m_historyHash, m_loaded, m_scaleTime, rowCount(), and HistoryModel::UrlStringRole.
Referenced by historyContains(), historyLocation(), index(), mapFromSource(), mapToSource(), and rowCount().
mapFromSource()
QModelIndex HistoryFilterModel::mapFromSource (const QModelIndex & sourceIndex) const
Definition at line 596 of file history.cpp.
 {
     load();
     QString url = sourceIndex.data(HistoryModel::UrlStringRole).toString();
     if (!m_historyHash.contains(url))
         return QModelIndex();
     int sourceOffset = sourceModel()->rowCount() - sourceIndex.row();
     QList<HistoryData>::iterator pos = std::lower_bound(m_filteredRows.begin(),
                                        m_filteredRows.end(), HistoryData(sourceOffset, -1));
     if (pos == m_filteredRows.end())
         return QModelIndex();
     return createIndex(pos - m_filteredRows.begin(), sourceIndex.column(), sourceOffset);
 }
References load(), m_filteredRows, m_historyHash, and HistoryModel::UrlStringRole.
Referenced by sourceDataChanged().
mapToSource()
QModelIndex HistoryFilterModel::mapToSource (const QModelIndex & proxyIndex) const
Definition at line 589 of file history.cpp.
 {
     load();
     int sourceRow = sourceModel()->rowCount() - proxyIndex.internalId();
     return sourceModel()->index(sourceRow, proxyIndex.column());
 }
References load().
parent()
QModelIndex HistoryFilterModel::parent (const QModelIndex & index = QModelIndex()) const
Definition at line 624 of file history.cpp.
 {
     return QModelIndex();
 }
Referenced by columnCount(), index(), removeRows(), rowCount(), and sourceRowsInserted().
recalculateFrecencies()
void HistoryFilterModel::recalculateFrecencies ()
Definition at line 564 of file history.cpp.
 {
     sourceReset();
 }
References sourceReset().
Referenced by refreshFrecencies().
refreshFrecencies
void HistoryFilterModel::refreshFrecencies () private slot
Definition at line 497 of file history.cpp.
 {
     recalculateFrecencies();
     startFrecencyTimer();
 }
References recalculateFrecencies(), and startFrecencyTimer().
Referenced by HistoryFilterModel().
removeRows()
bool HistoryFilterModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex())
Definition at line 692 of file history.cpp.
 {
     if (row < 0 || count <= 0 || row + count > rowCount(parent) || parent.isValid())
         return false;
     beginResetModel();
     int lastRow = row + count - 1;
     disconnect(sourceModel(), SIGNAL(rowsRemoved(const QModelIndex &, int, int)),
                this, SLOT(sourceRowsRemoved(const QModelIndex &, int, int)));
     beginRemoveRows(parent, row, lastRow);
     int start = sourceModel()->rowCount() - m_filteredRows[row].tailOffset;
     int end = sourceModel()->rowCount() - m_filteredRows[lastRow].tailOffset;
     sourceModel()->removeRows(start, end - start + 1);
     endRemoveRows();
     connect(sourceModel(), SIGNAL(rowsRemoved(const QModelIndex &, int, int)),
             this, SLOT(sourceRowsRemoved(const QModelIndex &, int, int)));
     m_loaded = false;
     endResetModel();
     return true;
 }
References m_filteredRows, m_loaded, parent(), rowCount(), and sourceRowsRemoved().
rowCount()
int HistoryFilterModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 576 of file history.cpp.
 {
     load();
     if (parent.isValid())
         return 0;
     return m_historyHash.count();
 }
References load(), m_historyHash, and parent().
Referenced by index(), load(), removeRows(), and sourceRowsInserted().
setSourceModel()
void HistoryFilterModel::setSourceModel (QAbstractItemModel * sourceModel)
Definition at line 528 of file history.cpp.
 {
     if (sourceModel()) {
         disconnect(sourceModel(), SIGNAL(modelReset()), this, SLOT(sourceReset()));
         disconnect(sourceModel(), SIGNAL(dataChanged(const QModelIndex &, const QModelIndex &)),
                    this, SLOT(dataChanged(const QModelIndex &, const QModelIndex &)));
         disconnect(sourceModel(), SIGNAL(rowsInserted(const QModelIndex &, int, int)),
                    this, SLOT(sourceRowsInserted(const QModelIndex &, int, int)));
         disconnect(sourceModel(), SIGNAL(rowsRemoved(const QModelIndex &, int, int)),
                    this, SLOT(sourceRowsRemoved(const QModelIndex &, int, int)));
     }
     QAbstractProxyModel::setSourceModel(newSourceModel);
     if (sourceModel()) {
         m_loaded = false;
         connect(sourceModel(), SIGNAL(modelReset()), this, SLOT(sourceReset()));
         connect(sourceModel(), SIGNAL(dataChanged(const QModelIndex &, const QModelIndex &)),
                 this, SLOT(sourceDataChanged(const QModelIndex &, const QModelIndex &)));
         connect(sourceModel(), SIGNAL(rowsInserted(const QModelIndex &, int, int)),
                 this, SLOT(sourceRowsInserted(const QModelIndex &, int, int)));
         connect(sourceModel(), SIGNAL(rowsRemoved(const QModelIndex &, int, int)),
                 this, SLOT(sourceRowsRemoved(const QModelIndex &, int, int)));
     }
 }
References m_loaded, sourceDataChanged(), sourceReset(), sourceRowsInserted(), and sourceRowsRemoved().
Referenced by HistoryFilterModel().
sourceDataChanged
void HistoryFilterModel::sourceDataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) private slot
Definition at line 554 of file history.cpp.
 {
     emit dataChanged(mapFromSource(topLeft), mapFromSource(bottomRight));
 }
References mapFromSource().
Referenced by setSourceModel().
sourceReset
void HistoryFilterModel::sourceReset () private slot
Definition at line 569 of file history.cpp.
 {
     beginResetModel();
     m_loaded = false;
     endResetModel();
 }
References m_loaded.
Referenced by recalculateFrecencies(), setSourceModel(), and sourceRowsRemoved().
sourceRowsInserted
void HistoryFilterModel::sourceRowsInserted (const QModelIndex & parent, int start, int end) private slot
Definition at line 655 of file history.cpp.
 {
     Q_ASSERT(start == end && start == 0);
     Q_UNUSED(end);
     if (!m_loaded)
         return;
     QModelIndex idx = sourceModel()->index(start, 0, parent);
     QString url = idx.data(HistoryModel::UrlStringRole).toString();
     int currentFrecency = 0;
     if (m_historyHash.contains(url)) {
         QList<HistoryData>::iterator pos = std::lower_bound(m_filteredRows.begin(),
                                            m_filteredRows.end(), HistoryData(m_historyHash[url], -1));
         Q_ASSERT(pos != m_filteredRows.end());
         int realRow = pos - m_filteredRows.begin();
         currentFrecency = pos->frecency;
         beginRemoveRows(QModelIndex(), realRow, realRow);
         m_filteredRows.erase(pos);
         m_historyHash.remove(url);
         endRemoveRows();
     }
     beginInsertRows(QModelIndex(), 0, 0);
     m_filteredRows.insert(0, HistoryData(sourceModel()->rowCount(), frecencyScore(idx) + currentFrecency));
     m_historyHash.insert(url, sourceModel()->rowCount());
     endInsertRows();
 }
References frecencyScore(), m_filteredRows, m_historyHash, m_loaded, parent(), rowCount(), and HistoryModel::UrlStringRole.
Referenced by setSourceModel().
sourceRowsRemoved
void HistoryFilterModel::sourceRowsRemoved (const QModelIndex & , int start, int end) private slot
Definition at line 681 of file history.cpp.
 {
     Q_UNUSED(start);
     Q_UNUSED(end);
     sourceReset();
 }
References sourceReset().
Referenced by removeRows(), and setSourceModel().
startFrecencyTimer()
void HistoryFilterModel::startFrecencyTimer () private
Definition at line 503 of file history.cpp.
 {
     // schedule us to recalculate the frecencies once per day, at 3:00 am (aka 03h00)
     QDateTime tomorrow(QDate::currentDate().addDays(1), QTime(3, 00));
     m_frecencyTimer.start(QDateTime::currentDateTime().secsTo(tomorrow)*1000);
 }
References m_frecencyTimer.
Referenced by HistoryFilterModel(), and refreshFrecencies().
Member Data Documentation
m_filteredRows
QList<HistoryData> HistoryFilterModel::m_filteredRows mutable private
Definition at line 175 of file history.h.
Referenced by data(), index(), load(), mapFromSource(), removeRows(), and sourceRowsInserted().
m_frecencyTimer
QTimer HistoryFilterModel::m_frecencyTimer private
Definition at line 152 of file history.h.
Referenced by HistoryFilterModel(), and startFrecencyTimer().
m_historyHash
QHash<QString, int> HistoryFilterModel::m_historyHash mutable private
Definition at line 176 of file history.h.
Referenced by historyContains(), historyLocation(), load(), mapFromSource(), rowCount(), and sourceRowsInserted().
m_lastSavedUrl
QString HistoryFilterModel::m_lastSavedUrl private
Definition at line 153 of file history.h.
m_loaded
bool HistoryFilterModel::m_loaded mutable private
Definition at line 177 of file history.h.
Referenced by load(), removeRows(), setSourceModel(), sourceReset(), and sourceRowsInserted().
m_scaleTime
QDateTime HistoryFilterModel::m_scaleTime mutable private
Definition at line 178 of file history.h.
Referenced by frecencyScore(), and load().
The documentation for this class was generated from the following files:
src/history/history.h
src/history/history.cpp