Endorphin: BrowserApplication Class Reference
BrowserApplication Class Reference
#include <browserapplication.h>
Public Slots
BrowserMainWindow * newMainWindow ()
bool restoreLastSession ()
void quitBrowser ()
static void setZoomTextOnly (bool textOnly)
void askDesktopToOpenUrl (const QUrl &url)
Signals
void zoomTextOnlyChanged (bool textOnly)
void privacyChanged (bool isPrivate)
Signals inherited from SingleApplication
void messageReceived (QLocalSocket *socket)
Public Member Functions
BrowserApplication (int &argc, char **argv)
~BrowserApplication ()
void loadSettings ()
BrowserMainWindow * mainWindow ()
QList< BrowserMainWindow * > mainWindows ()
bool allowToCloseWindow (BrowserMainWindow *window)
void saveSession ()
bool canRestoreSession () const
Qt::MouseButtons eventMouseButtons () const
Qt::KeyboardModifiers eventKeyboardModifiers () const
void setEventMouseButtons (Qt::MouseButtons buttons)
void setEventKeyboardModifiers (Qt::KeyboardModifiers modifiers)
Public Member Functions inherited from SingleApplication
SingleApplication (int &argc, char **argv)
bool sendMessage (const QByteArray &message, int waitMsecsForReply=0)
bool startSingleServer ()
bool isRunning () const
Static Public Member Functions
static BrowserApplication * instance ()
static QIcon icon (const QUrl &url)
static HistoryManager * historyManager ()
static DownloadManager * downloadManager ()
static BookmarksManager * bookmarksManager ()
static LanguageManager * languageManager ()
static QString installedDataDirectory ()
static QString dataFilePath (const QString &fileName)
static bool zoomTextOnly ()
static bool isPrivate ()
static void setPrivate (bool isPrivate)
Private Slots
void retranslate ()
void messageReceived (QLocalSocket *socket)
void postLaunch ()
void openUrl (const QUrl &url)
Private Member Functions
QString parseArgumentUrl (const QString &string) const
void clean ()
Private Attributes
QList< QPointer< BrowserMainWindow > > m_mainWindows
QByteArray m_lastSession
bool quitting
Qt::MouseButtons m_eventMouseButtons
Qt::KeyboardModifiers m_eventKeyboardModifiers
QUrl m_lastAskedUrl
QDateTime m_lastAskedUrlDateTime
Static Private Attributes
static HistoryManager * s_historyManager = nullptr
static DownloadManager * s_downloadManager = nullptr
static BookmarksManager * s_bookmarksManager = nullptr
static LanguageManager * s_languageManager = nullptr
Detailed Description
Definition at line 78 of file browserapplication.h.
Constructor & Destructor Documentation
BrowserApplication()
BrowserApplication::BrowserApplication (int & argc, char ** argv)
Definition at line 183 of file browserapplication.cpp.
     : SingleApplication(argc, argv)
     , quitting(false)
 {
     QCoreApplication::setOrganizationDomain(QLatin1String("EndorphinBrowser.github.io/"));
     QCoreApplication::setApplicationName(QLatin1String("Endorphin"));
     QCoreApplication::setApplicationVersion(QLatin1String("0.12.1"
 #ifdef GITVERSION
                                             " (Git: " GITCHANGENUMBER " " GITVERSION ")"
 #endif
                                                          ));
 #ifndef AUTOTESTS
     connect(this, SIGNAL(messageReceived(QLocalSocket *)),
             this, SLOT(messageReceived(QLocalSocket *)));
     QStringList args = QCoreApplication::arguments();
     if (args.count() > 1) {
         QString message = parseArgumentUrl(args.last());
         sendMessage(message.toUtf8());
     }
     // If we could connect to another Endorphin then exit
     QString message = QString(QLatin1String("endorphin://getwinid"));
     if (sendMessage(message.toUtf8(), 500))
         return;
 #ifdef BROWSERAPPLICATION_DEBUG
     qDebug() << "BrowserApplication::" << __FUNCTION__ << "I am the only endorphin";
 #endif
     // not sure what else to do...
     if (!startSingleServer())
         return;
 #endif
 #if defined(Q_WS_MAC)
     QApplication::setQuitOnLastWindowClosed(false);
 #else
     QApplication::setQuitOnLastWindowClosed(true);
 #endif
     QDesktopServices::setUrlHandler(QLatin1String("http"), this, "openUrl");
     // Until QtWebkit defaults to 16
     QWebEngineSettings::globalSettings()->setFontSize(QWebEngineSettings::DefaultFontSize, 16);
     QWebEngineSettings::globalSettings()->setFontSize(QWebEngineSettings::DefaultFixedFontSize, 16);
     QSettings settings;
     settings.beginGroup(QLatin1String("sessions"));
     m_lastSession = settings.value(QLatin1String("lastSession")).toByteArray();
     settings.endGroup();
 #if defined(Q_WS_MAC)
     connect(this, SIGNAL(lastWindowClosed()),
             this, SLOT(lastWindowClosed()));
 #endif
     // setting this in the postLaunch actually takes a lot more time
     // because the event has to be propagated to everyone.
     setWindowIcon(QIcon(QLatin1String(":128x128/endorphin.png")));
 #ifndef AUTOTESTS
     QTimer::singleShot(0, this, SLOT(postLaunch()));
 #endif
     languageManager();
 }
References languageManager(), m_lastSession, messageReceived(), parseArgumentUrl(), postLaunch(), SingleApplication::sendMessage(), and SingleApplication::startSingleServer().
~BrowserApplication()
BrowserApplication::~BrowserApplication ()
Definition at line 250 of file browserapplication.cpp.
 {
     quitting = true;
     delete s_downloadManager;
     qDeleteAll(m_mainWindows);
     delete s_bookmarksManager;
     delete s_languageManager;
     delete s_historyManager;
 }
References m_mainWindows, quitting, s_bookmarksManager, s_downloadManager, s_historyManager, and s_languageManager.
Member Function Documentation
allowToCloseWindow()
bool BrowserApplication::allowToCloseWindow (BrowserMainWindow * window)
Definition at line 486 of file browserapplication.cpp.
 {
     Q_UNUSED(window)
     if (mainWindows().count() > 1)
         return true;
     if (s_downloadManager)
         return downloadManager()->allowQuit();
     return true;
 }
References DownloadManager::allowQuit(), downloadManager(), mainWindows(), and s_downloadManager.
askDesktopToOpenUrl
void BrowserApplication::askDesktopToOpenUrl (const QUrl & url) slot
Definition at line 622 of file browserapplication.cpp.
 {
     m_lastAskedUrl = url;
     m_lastAskedUrlDateTime = QDateTime::currentDateTime();
     QDesktopServices::openUrl(url);
 }
References m_lastAskedUrl, and m_lastAskedUrlDateTime.
Referenced by WebPage::acceptNavigationRequest().
bookmarksManager()
BookmarksManager * BrowserApplication::bookmarksManager () static
Definition at line 679 of file browserapplication.cpp.
 {
     if (!s_bookmarksManager)
         s_bookmarksManager = new BookmarksManager;
     return s_bookmarksManager;
 }
References s_bookmarksManager.
Referenced by BrowserMainWindow::addBookmark(), AddBookmarkDialog::AddBookmarkDialog(), BrowserMainWindow::addBookmarkFolder(), BookmarksDialog::BookmarksDialog(), BookmarksToolBar::BookmarksToolBar(), TabWidget::bookmarkTabs(), BrowserMainWindow::BrowserMainWindow(), BookmarksMenuBarMenu::prePopulated(), retranslate(), and BrowserMainWindow::setupMenu().
canRestoreSession()
bool BrowserApplication::canRestoreSession () const
Definition at line 543 of file browserapplication.cpp.
 {
     return !m_lastSession.isEmpty();
 }
References m_lastSession.
clean()
void BrowserApplication::clean () private
Definition at line 498 of file browserapplication.cpp.
 {
     // cleanup any deleted main windows first
     for (int i = m_mainWindows.count() - 1; i >= 0; --i)
         if (m_mainWindows.at(i).isNull())
             m_mainWindows.removeAt(i);
 }
References m_mainWindows.
Referenced by mainWindow(), mainWindows(), quitBrowser(), and saveSession().
dataFilePath()
QString BrowserApplication::dataFilePath (const QString & fileName) static
Definition at line 727 of file browserapplication.cpp.
 {
     QString directory = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation) + "/data/Endorphin";
     if (directory.isEmpty())
         directory = QDir::homePath() + QLatin1String("/.") + QCoreApplication::applicationName();
     if (!QFile::exists(directory)) {
         QDir dir;
         dir.mkpath(directory);
     }
     return directory + QLatin1String("/") + fileName;
 }
Referenced by languageManager().
downloadManager()
DownloadManager * BrowserApplication::downloadManager () static
Definition at line 665 of file browserapplication.cpp.
 {
     if (!s_downloadManager)
         s_downloadManager = new DownloadManager();
     return s_downloadManager;
 }
References s_downloadManager.
Referenced by ClearPrivateData::accept(), allowToCloseWindow(), BrowserMainWindow::downloadManager(), WebView::downloadRequested(), BrowserMainWindow::fileSaveAs(), DownloadItem::getFileName(), and quitBrowser().
eventKeyboardModifiers()
Qt::KeyboardModifiers BrowserApplication::eventKeyboardModifiers () const
Definition at line 774 of file browserapplication.cpp.
 {
     return m_eventKeyboardModifiers;
 }
References m_eventKeyboardModifiers.
Referenced by TabWidget::modifyWithUserBehavior().
eventMouseButtons()
Qt::MouseButtons BrowserApplication::eventMouseButtons () const
Definition at line 769 of file browserapplication.cpp.
 {
     return m_eventMouseButtons;
 }
References m_eventMouseButtons.
Referenced by TabWidget::modifyWithUserBehavior(), and WebView::mouseReleaseEvent().
historyManager()
HistoryManager * BrowserApplication::historyManager () static
Definition at line 672 of file browserapplication.cpp.
 {
     if (!s_historyManager)
         s_historyManager = new HistoryManager();
     return s_historyManager;
 }
References s_historyManager.
Referenced by ClearPrivateData::accept(), HistoryDialog::HistoryDialog(), TabWidget::makeNewTab(), postLaunch(), HistoryMenu::prePopulated(), SettingsDialog::saveToSettings(), TabWidget::TabWidget(), and TabWidget::webViewTitleChanged().
icon()
QIcon BrowserApplication::icon (const QUrl & url) static
Definition at line 699 of file browserapplication.cpp.
 {
     /*
     QIcon icon = QWebSettings::iconForUrl(url);
     if (!icon.isNull())
         return icon.pixmap(16, 16);
     if (icon.isNull()) {
         QPixmap pixmap = QWebSettings::webGraphic(QWebSettings::DefaultFrameIconGraphic);
         if (pixmap.isNull()) {
             pixmap = QPixmap(QLatin1String(":graphics/defaulticon.png"));
             QWebSettings::setWebGraphic(QWebSettings::DefaultFrameIconGraphic, pixmap);
         }
         return pixmap;
     }
     return icon;
     */
     return QPixmap(":graphics/defaulticon.png");
 }
Referenced by BrowserMainWindow::aboutToShowBackMenu(), BrowserMainWindow::aboutToShowForwardMenu(), TabWidget::aboutToShowRecentTabsMenu(), ClearButton::ClearButton(), OpenSearchEngineModel::data(), BookmarksModel::data(), HistoryModel::data(), OpenSearchEngineAction::imageChanged(), and TabWidget::webViewIconChanged().
installedDataDirectory()
QString BrowserApplication::installedDataDirectory () static
Definition at line 718 of file browserapplication.cpp.
 {
 #if defined(Q_WS_X11)
     return QLatin1String(PKGDATADIR);
 #else
     return qApp->applicationDirPath();
 #endif
 }
Referenced by languageManager().
instance()
BrowserApplication * BrowserApplication::instance () static
Definition at line 270 of file browserapplication.cpp.
 {
     return (static_cast<BrowserApplication*>(QCoreApplication::instance()));
 }
Referenced by BrowserMainWindow::aboutToShowBackMenu(), BrowserMainWindow::aboutToShowForwardMenu(), TabWidget::aboutToShowRecentTabsMenu(), BrowserMainWindow::aboutToShowWindowMenu(), ClearPrivateData::accept(), WebPage::acceptNavigationRequest(), BrowserMainWindow::closeEvent(), BookmarksModel::data(), HistoryModel::data(), AcceptLanguageDialog::defaultAcceptList(), ModelToolBar::eventFilter(), BrowserMainWindow::fileNew(), TabWidget::getView(), TabWidget::modifyWithUserBehavior(), PrivacyIndicator::mousePressEvent(), WebView::mousePressEvent(), WebView::mouseReleaseEvent(), ModelMenu::mouseReleaseEvent(), HistoryDialog::open(), BookmarksDialog::openBookmark(), BrowserMainWindow::parentWindow(), PrivacyIndicator::PrivacyIndicator(), BrowserMainWindow::save(), SettingsDialog::saveToSettings(), BrowserMainWindow::setupMenu(), setZoomTextOnly(), BrowserMainWindow::showWindow(), WebView::WebView(), TabWidget::webViewIconChanged(), and LocationBarSiteIcon::webViewSiteIconChanged().
isPrivate()
bool BrowserApplication::isPrivate () static
Definition at line 757 of file browserapplication.cpp.
 {
     //return QWebEngineSettings::globalSettings()->testAttribute(QWebEngineSettings::PrivateBrowsingEnabled);
     return false;
 }
Referenced by BrowserMainWindow::BrowserMainWindow(), PrivacyIndicator::PrivacyIndicator(), and BrowserMainWindow::privateBrowsing().
languageManager()
LanguageManager * BrowserApplication::languageManager () static
Definition at line 686 of file browserapplication.cpp.
 {
     if (!s_languageManager) {
         s_languageManager = new LanguageManager();
         s_languageManager->addLocaleDirectory(dataFilePath(QLatin1String("locale")));
         s_languageManager->addLocaleDirectory(qApp->applicationDirPath() + QLatin1String("/src/.qm/locale"));
         s_languageManager->addLocaleDirectory(installedDataDirectory() + QLatin1String("/locale"));
         s_languageManager->loadLanguageFromSettings();
         connect(s_languageManager, SIGNAL(languageChanged(const QString &)),
                 qApp, SLOT(retranslate()));
     }
     return s_languageManager;
 }
References LanguageManager::addLocaleDirectory(), dataFilePath(), installedDataDirectory(), LanguageManager::loadLanguageFromSettings(), retranslate(), and s_languageManager.
Referenced by BrowserApplication(), AcceptLanguageDialog::defaultAcceptList(), and BrowserMainWindow::setupMenu().
loadSettings()
void BrowserApplication::loadSettings ()
Definition at line 437 of file browserapplication.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("websettings"));
     QWebEngineSettings *defaultSettings = QWebEngineSettings::globalSettings();
     QWebEngineProfile *defaultProfile = QWebEngineProfile::defaultProfile();
     QString standardFontFamily = defaultSettings->fontFamily(QWebEngineSettings::StandardFont);
     int standardFontSize = defaultSettings->fontSize(QWebEngineSettings::DefaultFontSize);
     QFont standardFont = QFont(standardFontFamily, standardFontSize);
     standardFont = settings.value(QLatin1String("standardFont"), standardFont).value<QFont>();
     defaultSettings->setFontFamily(QWebEngineSettings::StandardFont, standardFont.family());
     defaultSettings->setFontSize(QWebEngineSettings::DefaultFontSize, standardFont.pointSize());
     int minimumFontSize = settings.value(QLatin1String("minimumFontSize"),
                                          defaultSettings->fontSize(QWebEngineSettings::MinimumFontSize)).toInt();
     defaultSettings->setFontSize(QWebEngineSettings::MinimumFontSize, minimumFontSize);
     QString fixedFontFamily = defaultSettings->fontFamily(QWebEngineSettings::FixedFont);
     int fixedFontSize = defaultSettings->fontSize(QWebEngineSettings::DefaultFixedFontSize);
     QFont fixedFont = QFont(fixedFontFamily, fixedFontSize);
     fixedFont = settings.value(QLatin1String("fixedFont"), fixedFont).value<QFont>();
     defaultSettings->setFontFamily(QWebEngineSettings::FixedFont, fixedFont.family());
     defaultSettings->setFontSize(QWebEngineSettings::DefaultFixedFontSize, fixedFont.pointSize());
     defaultSettings->setAttribute(QWebEngineSettings::JavascriptCanOpenWindows, !(settings.value(QLatin1String("blockPopupWindows"), true).toBool()));
     defaultSettings->setAttribute(QWebEngineSettings::JavascriptEnabled, settings.value(QLatin1String("enableJavascript"), true).toBool());
     defaultSettings->setAttribute(QWebEngineSettings::AutoLoadImages, settings.value(QLatin1String("enableImages"), true).toBool());
     defaultSettings->setAttribute(QWebEngineSettings::LocalStorageEnabled, settings.value(QLatin1String("enableLocalStorage"), true).toBool());
     //defaultSettings->setAttribute(QWebEngineSettings::DeveloperExtrasEnabled, settings.value(QLatin1String("enableInspector"), false).toBool());
     defaultSettings->setAttribute(QWebEngineSettings::DnsPrefetchEnabled, true);
     QString css = settings.value(QLatin1String("userStyleSheet")).toString();
     setUserStyleSheet(defaultProfile, css, mainWindow());
 //    int maximumPagesInCache = settings.value(QLatin1String("maximumPagesInCache"), 3).toInt();
 //    QWebEngineSettings::globalSettings()->setMaximumPagesInCache(maximumPagesInCache);
     settings.endGroup();
 }
References mainWindow(), and setUserStyleSheet().
Referenced by postLaunch(), and SettingsDialog::saveToSettings().
mainWindow()
BrowserMainWindow * BrowserApplication::mainWindow ()
Definition at line 648 of file browserapplication.cpp.
 {
     clean();
     BrowserMainWindow *activeWindow = nullptr;
     if (m_mainWindows.isEmpty()) {
         activeWindow = newMainWindow();
     } else {
         activeWindow = qobject_cast<BrowserMainWindow*>(QApplication::activeWindow());
         if (!activeWindow)
             activeWindow = m_mainWindows[0];
     }
     return activeWindow;
 }
References clean(), m_mainWindows, and newMainWindow().
Referenced by loadSettings(), messageReceived(), newMainWindow(), openUrl(), BrowserMainWindow::parentWindow(), postLaunch(), quitBrowser(), and restoreLastSession().
mainWindows()
QList< BrowserMainWindow * > BrowserApplication::mainWindows ()
Definition at line 477 of file browserapplication.cpp.
 {
     clean();
     QList<BrowserMainWindow*> list;
     for (int i = 0; i < m_mainWindows.count(); ++i)
         list.append(m_mainWindows.at(i));
     return list;
 }
References clean(), and m_mainWindows.
Referenced by BrowserMainWindow::aboutToShowWindowMenu(), ClearPrivateData::accept(), allowToCloseWindow(), SettingsDialog::saveToSettings(), and BrowserMainWindow::showWindow().
messageReceived
void BrowserApplication::messageReceived (QLocalSocket * socket) private slot
Definition at line 291 of file browserapplication.cpp.
 {
     QString message;
     QTextStream stream(socket);
     stream >> message;
 #ifdef BROWSERAPPLICATION_DEBUG
     qDebug() << "BrowserApplication::" << __FUNCTION__ << message;
 #endif
     if (message.isEmpty())
         return;
     // Got a normal url
     if (!message.startsWith(QLatin1String("endorphin://"))) {
         QSettings settings;
         settings.beginGroup(QLatin1String("tabs"));
         TabWidget::OpenUrlIn tab = TabWidget::OpenUrlIn(settings.value(QLatin1String("openLinksFromAppsIn"), TabWidget::NewSelectedTab).toInt());
         settings.endGroup();
         if (QUrl(message) == m_lastAskedUrl
                 && m_lastAskedUrlDateTime.addSecs(10) > QDateTime::currentDateTime()) {
             qWarning() << "Possible recursive openUrl called, ignoring url:" << m_lastAskedUrl;
             return;
         }
         mainWindow()->tabWidget()->loadString(message, tab);
         return;
     } else {
         if (message.startsWith(QLatin1String("endorphin://getwinid"))) {
 #ifdef Q_OS_WIN
             QString winid = QString(QLatin1String("%1")).arg((qlonglong)mainWindow()->winId());
 #else
             mainWindow()->show();
             mainWindow()->setFocus();
             mainWindow()->raise();
             mainWindow()->activateWindow();
             alert(mainWindow());
             QString winid;
 #endif
 #ifdef BROWSERAPPLICATION_DEBUG
             qDebug() << "BrowserApplication::" << __FUNCTION__ << "sending win id" << winid << mainWindow()->winId();
 #endif
             QString message = QLatin1String("endorphin://winid/") + winid;
             socket->write(message.toUtf8());
             socket->waitForBytesWritten();
             return;
         }
         if (message.startsWith(QLatin1String("endorphin://winid"))) {
             QString winid = message.mid(21);
 #ifdef BROWSERAPPLICATION_DEBUG
             qDebug() << "BrowserApplication::" << __FUNCTION__ << "got win id:" << winid;
 #endif
 #ifdef Q_OS_WIN
             WId wid = (WId)winid.toLongLong();
             SetForegroundWindow(wid);
 #endif
             return;
         }
         QSettings settings;
         settings.beginGroup(QLatin1String("tabs"));
         TabWidget::OpenUrlIn tab = TabWidget::OpenUrlIn(settings.value(QLatin1String("openLinksFromAppsIn"), TabWidget::NewSelectedTab).toInt());
         settings.endGroup();
         if (QUrl(message) == m_lastAskedUrl
                 && m_lastAskedUrlDateTime.addSecs(10) > QDateTime::currentDateTime()) {
             qWarning() << "Possible recursive openUrl called, ignoring url:" << m_lastAskedUrl;
             return;
         }
         mainWindow()->tabWidget()->loadString(message, tab);
         return;
     }
 }
References TabWidget::loadString(), m_lastAskedUrl, m_lastAskedUrlDateTime, mainWindow(), TabWidget::NewSelectedTab, and BrowserMainWindow::tabWidget().
Referenced by BrowserApplication().
newMainWindow
BrowserMainWindow * BrowserApplication::newMainWindow () slot
Definition at line 636 of file browserapplication.cpp.
 {
     if (!m_mainWindows.isEmpty())
         mainWindow()->m_autoSaver->saveIfNeccessary();
     BrowserMainWindow *browser = new BrowserMainWindow();
     m_mainWindows.prepend(browser);
     connect(this, SIGNAL(privacyChanged(bool)),
             browser, SLOT(privacyChanged(bool)));
     browser->show();
     return browser;
 }
References BrowserMainWindow::m_autoSaver, m_mainWindows, mainWindow(), privacyChanged(), and AutoSaver::saveIfNeccessary().
Referenced by BrowserMainWindow::fileNew(), TabWidget::getView(), main(), mainWindow(), and restoreLastSession().
openUrl
void BrowserApplication::openUrl (const QUrl & url) private slot
Definition at line 629 of file browserapplication.cpp.
 {
     setEventMouseButtons(mouseButtons());
     setEventKeyboardModifiers(keyboardModifiers());
     mainWindow()->tabWidget()->loadUrl(url);
 }
References TabWidget::loadUrl(), mainWindow(), setEventKeyboardModifiers(), setEventMouseButtons(), and BrowserMainWindow::tabWidget().
parseArgumentUrl()
QString BrowserApplication::parseArgumentUrl (const QString & string) const private
Definition at line 282 of file browserapplication.cpp.
 {
     if (QFile::exists(string)) {
         QFileInfo info(string);
         return info.canonicalFilePath();
     }
     return string;
 }
Referenced by BrowserApplication(), and postLaunch().
postLaunch
void BrowserApplication::postLaunch () private slot
Any actions that can be delayed until the window is visible
Definition at line 393 of file browserapplication.cpp.
 {
     QString directory = QStandardPaths::writableLocation(QStandardPaths::CacheLocation);
     if (directory.isEmpty())
         directory = QDir::homePath() + QLatin1String("/.") + QCoreApplication::applicationName();
     // QWebEngineSettings::setIconDatabasePath(directory);
     loadSettings();
     // newMainWindow() needs to be called in main() for this to happen
     if (m_mainWindows.count() > 0) {
         QSettings settings;
         settings.beginGroup(QLatin1String("MainWindow"));
         int startup = settings.value(QLatin1String("startupBehavior")).toInt();
         QStringList args = QCoreApplication::arguments();
         if (args.count() > 1) {
             QString argumentUrl = parseArgumentUrl(args.last());
             switch (startup) {
             case 2: {
                 restoreLastSession();
                 mainWindow()->tabWidget()->loadString(argumentUrl, TabWidget::NewSelectedTab);
                 break;
             }
             default:
                 mainWindow()->tabWidget()->loadString(argumentUrl);
                 break;
             }
         } else {
             switch (startup) {
             case 0:
                 mainWindow()->goHome();
                 break;
             case 1:
                 break;
             case 2:
                 restoreLastSession();
                 break;
             }
         }
     }
     BrowserApplication::historyManager();
 }
References BrowserMainWindow::goHome(), historyManager(), loadSettings(), TabWidget::loadString(), m_mainWindows, mainWindow(), TabWidget::NewSelectedTab, parseArgumentUrl(), restoreLastSession(), and BrowserMainWindow::tabWidget().
Referenced by BrowserApplication().
privacyChanged
void BrowserApplication::privacyChanged (bool isPrivate) signal
Referenced by newMainWindow().
quitBrowser
void BrowserApplication::quitBrowser () slot
Definition at line 361 of file browserapplication.cpp.
 {
     if (s_downloadManager && !downloadManager()->allowQuit())
         return;
     if (QSettings().value(QLatin1String("tabs/confirmClosingMultipleTabs"), true).toBool()) {
         clean();
         int tabCount = 0;
         for (int i = 0; i < m_mainWindows.count(); ++i) {
             tabCount += m_mainWindows.at(i)->tabWidget()->count();
         }
         if (tabCount > 1) {
             QWidget *widget = mainWindow();
             QApplication::alert(widget);
             int ret = QMessageBox::warning(widget, QString(),
                                            tr("There are %1 windows and %2 tabs open\n"
                                               "Do you want to quit anyway?").arg(m_mainWindows.count()).arg(tabCount),
                                            QMessageBox::Yes | QMessageBox::No,
                                            QMessageBox::No);
             if (ret == QMessageBox::No)
                 return;
         }
     }
     saveSession();
     exit(0);
 }
References clean(), downloadManager(), m_mainWindows, mainWindow(), s_downloadManager, and saveSession().
restoreLastSession
bool BrowserApplication::restoreLastSession () slot
Definition at line 548 of file browserapplication.cpp.
 {
     {
         QSettings settings;
         settings.beginGroup(QLatin1String("MainWindow"));
         if (settings.value(QLatin1String("restoring"), false).toBool()) {
             QMessageBox::StandardButton result = QMessageBox::question(nullptr, tr("Restore failed"),
                                                  tr("Endorphin crashed while trying to restore this session.  Should I try again?"), QMessageBox::Yes | QMessageBox::No);
             if (result == QMessageBox::No)
                 return false;
         }
         // saveSession will be called by an AutoSaver timer from the set tabs
         // and in saveSession we will reset this flag back to false
         settings.setValue(QLatin1String("restoring"), true);
     }
     int version = 2;
     QList<QByteArray> windows;
     QBuffer buffer(&m_lastSession);
     QDataStream stream(&buffer);
     buffer.open(QIODevice::ReadOnly);
     qint32 marker;
     qint32 v;
     stream >> marker;
     stream >> v;
     if (marker != BrowserApplicationMagic || v != version)
         return false;
     qint32 windowCount;
     stream >> windowCount;
     for (qint32 i = 0; i < windowCount; ++i) {
         QByteArray windowState;
         stream >> windowState;
         windows.append(windowState);
     }
     for (int i = 0; i < windows.count(); ++i) {
         BrowserMainWindow *newWindow = nullptr;
         if (i == 0 && m_mainWindows.count() >= 1) {
             newWindow = mainWindow();
         } else {
             newWindow = newMainWindow();
         }
         newWindow->restoreState(windows.at(i));
     }
     return true;
 }
References BrowserApplicationMagic, m_lastSession, m_mainWindows, mainWindow(), newMainWindow(), and BrowserMainWindow::restoreState().
Referenced by postLaunch().
retranslate
void BrowserApplication::retranslate () private slot
Definition at line 275 of file browserapplication.cpp.
 {
     bookmarksManager()->retranslate();
 }
References bookmarksManager(), and BookmarksManager::retranslate().
Referenced by languageManager().
saveSession()
void BrowserApplication::saveSession ()
Definition at line 508 of file browserapplication.cpp.
 {
     if (quitting)
         return;
     QSettings settings;
     settings.beginGroup(QLatin1String("MainWindow"));
     settings.setValue(QLatin1String("restoring"), false);
     settings.endGroup();
     /*
         QWebEngineSettings *globalSettings = QWebEngineSettings::globalSettings();
         if (globalSettings->testAttribute(QWebEngineSettings::PrivateBrowsingEnabled))
             return;
     */
     clean();
     settings.beginGroup(QLatin1String("sessions"));
     int version = 2;
     QByteArray data;
     QBuffer buffer(&data);
     QDataStream stream(&buffer);
     buffer.open(QIODevice::WriteOnly);
     stream << qint32(BrowserApplicationMagic);
     stream << qint32(version);
     stream << qint32(m_mainWindows.count());
     for (int i = 0; i < m_mainWindows.count(); ++i)
         stream << m_mainWindows.at(i)->saveState();
     settings.setValue(QLatin1String("lastSession"), data);
     settings.endGroup();
 }
References BrowserApplicationMagic, clean(), m_mainWindows, and quitting.
Referenced by quitBrowser(), and BrowserMainWindow::save().
setEventKeyboardModifiers()
void BrowserApplication::setEventKeyboardModifiers (Qt::KeyboardModifiers modifiers)
Definition at line 784 of file browserapplication.cpp.
 {
     m_eventKeyboardModifiers = modifiers;
 }
References m_eventKeyboardModifiers.
Referenced by ModelToolBar::eventFilter(), TabWidget::modifyWithUserBehavior(), WebView::mousePressEvent(), ModelMenu::mouseReleaseEvent(), HistoryDialog::open(), BookmarksDialog::openBookmark(), and openUrl().
setEventMouseButtons()
void BrowserApplication::setEventMouseButtons (Qt::MouseButtons buttons)
Definition at line 779 of file browserapplication.cpp.
 {
     m_eventMouseButtons = buttons;
 }
References m_eventMouseButtons.
Referenced by ModelToolBar::eventFilter(), TabWidget::modifyWithUserBehavior(), WebView::mousePressEvent(), WebView::mouseReleaseEvent(), ModelMenu::mouseReleaseEvent(), HistoryDialog::open(), BookmarksDialog::openBookmark(), and openUrl().
setPrivate()
void BrowserApplication::setPrivate (bool isPrivate) static
Definition at line 763 of file browserapplication.cpp.
 {
     //QWebEngineSettings::globalSettings()->setAttribute(QWebEngineSettings::PrivateBrowsingEnabled, isPrivate);
     //emit instance()->privacyChanged(isPrivate);
 }
Referenced by PrivacyIndicator::mousePressEvent(), and BrowserMainWindow::privateBrowsing().
setZoomTextOnly
void BrowserApplication::setZoomTextOnly (bool textOnly) static slot
Definition at line 748 of file browserapplication.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("WebEngine"));
     settings.setValue(QLatin1String("zoomTextOnly"), textOnly);
     settings.endGroup();
     emit instance()->zoomTextOnlyChanged(textOnly);
 }
References instance(), and zoomTextOnlyChanged().
zoomTextOnly()
bool BrowserApplication::zoomTextOnly () static
Definition at line 739 of file browserapplication.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("WebEngine"));
     bool textOnly = settings.value(QLatin1String("zoomTextOnly")).toBool();
     settings.endGroup();
     return textOnly;
 }
zoomTextOnlyChanged
void BrowserApplication::zoomTextOnlyChanged (bool textOnly) signal
Referenced by setZoomTextOnly().
Member Data Documentation
m_eventKeyboardModifiers
Qt::KeyboardModifiers BrowserApplication::m_eventKeyboardModifiers private
Definition at line 155 of file browserapplication.h.
Referenced by eventKeyboardModifiers(), and setEventKeyboardModifiers().
m_eventMouseButtons
Qt::MouseButtons BrowserApplication::m_eventMouseButtons private
Definition at line 154 of file browserapplication.h.
Referenced by eventMouseButtons(), and setEventMouseButtons().
m_lastAskedUrl
QUrl BrowserApplication::m_lastAskedUrl private
Definition at line 157 of file browserapplication.h.
Referenced by askDesktopToOpenUrl(), and messageReceived().
m_lastAskedUrlDateTime
QDateTime BrowserApplication::m_lastAskedUrlDateTime private
Definition at line 158 of file browserapplication.h.
Referenced by askDesktopToOpenUrl(), and messageReceived().
m_lastSession
QByteArray BrowserApplication::m_lastSession private
Definition at line 151 of file browserapplication.h.
Referenced by BrowserApplication(), canRestoreSession(), and restoreLastSession().
m_mainWindows
QList<QPointer<BrowserMainWindow> > BrowserApplication::m_mainWindows private
Definition at line 150 of file browserapplication.h.
Referenced by clean(), mainWindow(), mainWindows(), newMainWindow(), postLaunch(), quitBrowser(), restoreLastSession(), saveSession(), and ~BrowserApplication().
quitting
bool BrowserApplication::quitting private
Definition at line 152 of file browserapplication.h.
Referenced by saveSession(), and ~BrowserApplication().
s_bookmarksManager
BookmarksManager * BrowserApplication::s_bookmarksManager = nullptr static private
Definition at line 147 of file browserapplication.h.
Referenced by bookmarksManager(), and ~BrowserApplication().
s_downloadManager
DownloadManager * BrowserApplication::s_downloadManager = nullptr static private
Definition at line 146 of file browserapplication.h.
Referenced by allowToCloseWindow(), downloadManager(), quitBrowser(), and ~BrowserApplication().
s_historyManager
HistoryManager * BrowserApplication::s_historyManager = nullptr static private
Definition at line 145 of file browserapplication.h.
Referenced by historyManager(), and ~BrowserApplication().
s_languageManager
LanguageManager * BrowserApplication::s_languageManager = nullptr static private
Definition at line 148 of file browserapplication.h.
Referenced by languageManager(), and ~BrowserApplication().
The documentation for this class was generated from the following files:
src/browserapplication.h
src/browserapplication.cpp