Endorphin: SettingsDialog Class Reference
SettingsDialog Class Reference
#include <settings.h>
Public Member Functions
SettingsDialog (QWidget *parent=nullptr)
void accept ()
Private Slots
void loadDefaults ()
void loadFromSettings ()
void saveToSettings ()
void setHomeToCurrentPage ()
void chooseDownloadDirectory ()
void chooseDownloadProgram ()
void chooseFont ()
void chooseFixedFont ()
void chooseAcceptLanguage ()
void chooseStyleSheet ()
Private Attributes
QFont m_standardFont
QFont m_fixedFont
bool m_cacheEnabled
Detailed Description
Definition at line 69 of file settings.h.
Constructor & Destructor Documentation
SettingsDialog()
SettingsDialog::SettingsDialog (QWidget * parent = nullptr)
Definition at line 81 of file settings.cpp.
     : QDialog(parent)
     , m_cacheEnabled(false)
 {
     setupUi(this);
     connect(setHomeToCurrentPageButton, SIGNAL(clicked()), this, SLOT(setHomeToCurrentPage()));
     connect(standardFontButton, SIGNAL(clicked()), this, SLOT(chooseFont()));
     connect(fixedFontButton, SIGNAL(clicked()), this, SLOT(chooseFixedFont()));
     connect(languageButton, SIGNAL(clicked()), this, SLOT(chooseAcceptLanguage()));
     connect(downloadDirectoryButton, SIGNAL(clicked()), this, SLOT(chooseDownloadDirectory()));
     connect(externalDownloadBrowse, SIGNAL(clicked()), this, SLOT(chooseDownloadProgram()));
     connect(styleSheetBrowseButton, SIGNAL(clicked()), this, SLOT(chooseStyleSheet()));
     loadDefaults();
     loadFromSettings();
 }
References chooseAcceptLanguage(), chooseDownloadDirectory(), chooseDownloadProgram(), chooseFixedFont(), chooseFont(), chooseStyleSheet(), loadDefaults(), loadFromSettings(), and setHomeToCurrentPage().
Member Function Documentation
accept()
void SettingsDialog::accept ()
Definition at line 345 of file settings.cpp.
 {
     saveToSettings();
     QDialog::accept();
 }
References saveToSettings().
chooseAcceptLanguage
void SettingsDialog::chooseAcceptLanguage () private slot
Definition at line 393 of file settings.cpp.
 {
     AcceptLanguageDialog dialog;
     dialog.exec();
 }
Referenced by SettingsDialog().
chooseDownloadDirectory
void SettingsDialog::chooseDownloadDirectory () private slot
Definition at line 351 of file settings.cpp.
 {
     QString fileName = QFileDialog::getExistingDirectory(this, tr("Choose Directory"), downloadsLocation->text());
     downloadsLocation->setText(fileName);
 }
Referenced by SettingsDialog().
chooseDownloadProgram
void SettingsDialog::chooseDownloadProgram () private slot
Definition at line 357 of file settings.cpp.
 {
     QString fileName = QFileDialog::getOpenFileName(this, tr("Choose Program"), externalDownloadPath->text());
     if (fileName.contains(QLatin1Char(' ')))
         fileName = QString(QLatin1String("\"%1\"")).arg(fileName);
     externalDownloadPath->setText(fileName);
 }
Referenced by SettingsDialog().
chooseFixedFont
void SettingsDialog::chooseFixedFont () private slot
Definition at line 375 of file settings.cpp.
 {
     bool ok;
     QFont font = QFontDialog::getFont(&ok, m_fixedFont, this);
     if (ok) {
         m_fixedFont = font;
         fixedLabel->setText(QString(QLatin1String("%1 %2")).arg(font.family()).arg(font.pointSize()));
     }
 }
References m_fixedFont.
Referenced by SettingsDialog().
chooseFont
void SettingsDialog::chooseFont () private slot
Definition at line 365 of file settings.cpp.
 {
     bool ok;
     QFont font = QFontDialog::getFont(&ok, m_standardFont, this);
     if (ok) {
         m_standardFont = font;
         standardLabel->setText(QString(QLatin1String("%1 %2")).arg(font.family()).arg(font.pointSize()));
     }
 }
References m_standardFont.
Referenced by SettingsDialog().
chooseStyleSheet
void SettingsDialog::chooseStyleSheet () private slot
Definition at line 399 of file settings.cpp.
 {
     QUrl url = QUrl::fromEncoded(userStyleSheet->text().toUtf8());
     QString fileName = QFileDialog::getOpenFileName(this, tr("Choose CSS File"), url.toLocalFile());
     userStyleSheet->setText(QString::fromUtf8(QUrl::fromLocalFile(fileName).toEncoded()));
 }
Referenced by SettingsDialog().
loadDefaults
void SettingsDialog::loadDefaults () private slot
Definition at line 98 of file settings.cpp.
 {
     QWebEngineSettings *defaultSettings = QWebEngineSettings::globalSettings();
     QString standardFontFamily = defaultSettings->fontFamily(QWebEngineSettings::StandardFont);
     int standardFontSize = defaultSettings->fontSize(QWebEngineSettings::DefaultFontSize);
     m_standardFont = QFont(standardFontFamily, standardFontSize);
     standardLabel->setText(QString(QLatin1String("%1 %2")).arg(m_standardFont.family()).arg(m_standardFont.pointSize()));
     QString fixedFontFamily = defaultSettings->fontFamily(QWebEngineSettings::FixedFont);
     int fixedFontSize = defaultSettings->fontSize(QWebEngineSettings::DefaultFixedFontSize);
     m_fixedFont = QFont(fixedFontFamily, fixedFontSize);
     fixedLabel->setText(QString(QLatin1String("%1 %2")).arg(m_fixedFont.family()).arg(m_fixedFont.pointSize()));
     downloadsLocation->setText(QStandardPaths::writableLocation(QStandardPaths::DesktopLocation));
     blockPopupWindows->setChecked(!defaultSettings->testAttribute(QWebEngineSettings::JavascriptCanOpenWindows));
     enableJavascript->setChecked(defaultSettings->testAttribute(QWebEngineSettings::JavascriptEnabled));
     enableImages->setChecked(defaultSettings->testAttribute(QWebEngineSettings::AutoLoadImages));
     enableLocalStorage->setChecked(defaultSettings->testAttribute(QWebEngineSettings::LocalStorageEnabled));
     minimFontSizeCheckBox->setChecked(false);
     minimumFontSizeSpinBox->setValue(9);
 }
References m_fixedFont, and m_standardFont.
Referenced by SettingsDialog().
loadFromSettings
void SettingsDialog::loadFromSettings () private slot
Definition at line 122 of file settings.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("Settings"));
     tabWidget->setCurrentIndex(settings.value(QLatin1String("currentTab"), 0).toInt());
     settings.endGroup();
     settings.beginGroup(QLatin1String("MainWindow"));
     QString defaultHome = QLatin1String("about:home");
     homeLineEdit->setText(settings.value(QLatin1String("home"), defaultHome).toString());
     startupBehavior->setCurrentIndex(settings.value(QLatin1String("startupBehavior"), 0).toInt());
     settings.endGroup();
     settings.beginGroup(QLatin1String("history"));
     int historyExpire = settings.value(QLatin1String("historyLimit")).toInt();
     int idx = 0;
     switch (historyExpire) {
     case 1:
         idx = 0;
         break;
     case 7:
         idx = 1;
         break;
     case 14:
         idx = 2;
         break;
     case 30:
         idx = 3;
         break;
     case 365:
         idx = 4;
         break;
     case -1:
         idx = 5;
         break;
     case -2:
         idx = 6;
         break;
     default:
         idx = 5;
     }
     expireHistory->setCurrentIndex(idx);
     settings.endGroup();
     settings.beginGroup(QLatin1String("urlloading"));
     bool search = settings.value(QLatin1String("searchEngineFallback"), false).toBool();
     searchEngineFallback->setChecked(search);
     settings.endGroup();
     settings.beginGroup(QLatin1String("downloadmanager"));
     bool alwaysPromptForFileName = settings.value(QLatin1String("alwaysPromptForFileName"), false).toBool();
     downloadAsk->setChecked(alwaysPromptForFileName);
     QString downloadDirectory = settings.value(QLatin1String("downloadDirectory"), downloadsLocation->text()).toString();
     downloadsLocation->setText(downloadDirectory);
     externalDownloadButton->setChecked(settings.value(QLatin1String("external"), false).toBool());
     externalDownloadPath->setText(settings.value(QLatin1String("externalPath")).toString());
     settings.endGroup();
     // Appearance
     settings.beginGroup(QLatin1String("websettings"));
     m_fixedFont = settings.value(QLatin1String("fixedFont"), m_fixedFont).value<QFont>();
     m_standardFont = settings.value(QLatin1String("standardFont"), m_standardFont).value<QFont>();
     standardLabel->setText(QString(QLatin1String("%1 %2")).arg(m_standardFont.family()).arg(m_standardFont.pointSize()));
     fixedLabel->setText(QString(QLatin1String("%1 %2")).arg(m_fixedFont.family()).arg(m_fixedFont.pointSize()));
     blockPopupWindows->setChecked(settings.value(QLatin1String("blockPopupWindows"), blockPopupWindows->isChecked()).toBool());
     enableJavascript->setChecked(settings.value(QLatin1String("enableJavascript"), enableJavascript->isChecked()).toBool());
     enableImages->setChecked(settings.value(QLatin1String("enableImages"), enableImages->isChecked()).toBool());
     enableLocalStorage->setChecked(settings.value(QLatin1String("enableLocalStorage"), enableLocalStorage->isChecked()).toBool());
     userStyleSheet->setText(QString::fromUtf8(settings.value(QLatin1String("userStyleSheet")).toUrl().toEncoded()));
     int minimumFontSize = settings.value(QLatin1String("minimumFontSize"), 0).toInt();
     minimFontSizeCheckBox->setChecked(minimumFontSize != 0);
     if (minimumFontSize != 0)
         minimumFontSizeSpinBox->setValue(minimumFontSize);
     settings.endGroup();
     // Network
     settings.beginGroup(QLatin1String("network"));
     m_cacheEnabled = settings.value(QLatin1String("cacheEnabled"), true).toBool();
     networkCache->setChecked(m_cacheEnabled);
     networkCacheMaximumSizeSpinBox->setValue(settings.value(QLatin1String("maximumCacheSize"), 50).toInt());
     settings.endGroup();
     // Proxy
     settings.beginGroup(QLatin1String("proxy"));
     proxySupport->setChecked(settings.value(QLatin1String("enabled"), false).toBool());
     proxyType->setCurrentIndex(settings.value(QLatin1String("type"), 0).toInt());
     proxyHostName->setText(settings.value(QLatin1String("hostName")).toString());
     proxyPort->setValue(settings.value(QLatin1String("port"), 1080).toInt());
     proxyUserName->setText(settings.value(QLatin1String("userName")).toString());
     proxyPassword->setText(settings.value(QLatin1String("password")).toString());
     settings.endGroup();
     // Tabs
     settings.beginGroup(QLatin1String("tabs"));
     selectTabsWhenCreated->setChecked(settings.value(QLatin1String("selectNewTabs"), false).toBool());
     confirmClosingMultipleTabs->setChecked(settings.value(QLatin1String("confirmClosingMultipleTabs"), true).toBool());
     oneCloseButton->setChecked(settings.value(QLatin1String("oneCloseButton"),false).toBool());
     quitAsLastTabClosed->setChecked(settings.value(QLatin1String("quitAsLastTabClosed"), true).toBool());
     openTargetBlankLinksIn->setCurrentIndex(settings.value(QLatin1String("openTargetBlankLinksIn"), TabWidget::NewSelectedTab).toInt());
     openLinksFromAppsIn->setCurrentIndex(settings.value(QLatin1String("openLinksFromAppsIn"), TabWidget::NewSelectedTab).toInt());
     settings.endGroup();
     // Accessibility
     settings.beginGroup(QLatin1String("WebView"));
     enableAccessKeys->setChecked(settings.value(QLatin1String("enableAccessKeys"), true).toBool());
     settings.endGroup();
 }
References m_cacheEnabled, m_fixedFont, m_standardFont, and TabWidget::NewSelectedTab.
Referenced by SettingsDialog().
saveToSettings
void SettingsDialog::saveToSettings () private slot
Definition at line 232 of file settings.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("Settings"));
     settings.setValue(QLatin1String("currentTab"), tabWidget->currentIndex());
     settings.endGroup();
     settings.beginGroup(QLatin1String("MainWindow"));
     settings.setValue(QLatin1String("home"), homeLineEdit->text());
     settings.setValue(QLatin1String("startupBehavior"), startupBehavior->currentIndex());
     settings.endGroup();
     settings.beginGroup(QLatin1String("downloadmanager"));
     settings.setValue(QLatin1String("alwaysPromptForFileName"), downloadAsk->isChecked());
     settings.setValue(QLatin1String("downloadDirectory"), downloadsLocation->text());
     settings.setValue(QLatin1String("external"), externalDownloadButton->isChecked());
     settings.setValue(QLatin1String("externalPath"), externalDownloadPath->text());
     settings.endGroup();
     settings.beginGroup(QLatin1String("history"));
     int historyExpire = expireHistory->currentIndex();
     int idx = -1;
     switch (historyExpire) {
     case 0:
         idx = 1;
         break;
     case 1:
         idx = 7;
         break;
     case 2:
         idx = 14;
         break;
     case 3:
         idx = 30;
         break;
     case 4:
         idx = 365;
         break;
     case 5:
         idx = -1;
         break;
     case 6:
         idx = -2;
         break;
     }
     settings.setValue(QLatin1String("historyLimit"), idx);
     settings.endGroup();
     settings.beginGroup(QLatin1String("urlloading"));
     settings.setValue(QLatin1String("searchEngineFallback"), searchEngineFallback->isChecked());
     settings.endGroup();
     // Appearance
     settings.beginGroup(QLatin1String("websettings"));
     settings.setValue(QLatin1String("fixedFont"), m_fixedFont);
     settings.setValue(QLatin1String("standardFont"), m_standardFont);
     settings.setValue(QLatin1String("blockPopupWindows"), blockPopupWindows->isChecked());
     settings.setValue(QLatin1String("enableJavascript"), enableJavascript->isChecked());
     settings.setValue(QLatin1String("enableImages"), enableImages->isChecked());
     settings.setValue(QLatin1String("enableLocalStorage"), enableLocalStorage->isChecked());
     QString userStyleSheetString = userStyleSheet->text();
     if (QFile::exists(userStyleSheetString))
         settings.setValue(QLatin1String("userStyleSheet"), QUrl::fromLocalFile(userStyleSheetString));
     else
         settings.setValue(QLatin1String("userStyleSheet"), QUrl::fromEncoded(userStyleSheetString.toUtf8()));
     if (minimFontSizeCheckBox->isChecked())
         settings.setValue(QLatin1String("minimumFontSize"), minimumFontSizeSpinBox->value());
     else
         settings.setValue(QLatin1String("minimumFontSize"), 0);
     settings.endGroup();
     // Network
     settings.beginGroup(QLatin1String("network"));
     settings.setValue(QLatin1String("cacheEnabled"), networkCache->isChecked());
     settings.setValue(QLatin1String("maximumCacheSize"), networkCacheMaximumSizeSpinBox->value());
     settings.endGroup();
     // proxy
     settings.beginGroup(QLatin1String("proxy"));
     settings.setValue(QLatin1String("enabled"), proxySupport->isChecked());
     settings.setValue(QLatin1String("type"), proxyType->currentIndex());
     settings.setValue(QLatin1String("hostName"), proxyHostName->text());
     settings.setValue(QLatin1String("port"), proxyPort->text());
     settings.setValue(QLatin1String("userName"), proxyUserName->text());
     settings.setValue(QLatin1String("password"), proxyPassword->text());
     settings.endGroup();
     // Tabs
     settings.beginGroup(QLatin1String("tabs"));
     settings.setValue(QLatin1String("selectNewTabs"), selectTabsWhenCreated->isChecked());
     settings.setValue(QLatin1String("confirmClosingMultipleTabs"), confirmClosingMultipleTabs->isChecked());
     settings.setValue(QLatin1String("oneCloseButton"), oneCloseButton->isChecked());
     settings.setValue(QLatin1String("quitAsLastTabClosed"), quitAsLastTabClosed->isChecked());
     settings.setValue(QLatin1String("openTargetBlankLinksIn"), openTargetBlankLinksIn->currentIndex());
     settings.setValue(QLatin1String("openLinksFromAppsIn"), openLinksFromAppsIn->currentIndex());
     settings.endGroup();
     // Accessibility
     settings.beginGroup(QLatin1String("WebView"));
     settings.setValue(QLatin1String("enableAccessKeys"), enableAccessKeys->isChecked());
     settings.endGroup();
     BrowserApplication::instance()->loadSettings();
     BrowserApplication::historyManager()->loadSettings();
     QList<BrowserMainWindow*> list = BrowserApplication::instance()->mainWindows();
     foreach (BrowserMainWindow *mainWindow, list) {
         mainWindow->tabWidget()->loadSettings();
     }
 }
References BrowserApplication::historyManager(), BrowserApplication::instance(), BrowserApplication::loadSettings(), TabWidget::loadSettings(), HistoryManager::loadSettings(), m_fixedFont, m_standardFont, BrowserApplication::mainWindows(), and BrowserMainWindow::tabWidget().
Referenced by accept().
setHomeToCurrentPage
void SettingsDialog::setHomeToCurrentPage () private slot
Definition at line 385 of file settings.cpp.
 {
     BrowserMainWindow *mw = static_cast<BrowserMainWindow*>(parent());
     WebView *webView = mw->currentTab();
     if (webView)
         homeLineEdit->setText(QString::fromUtf8(webView->url().toEncoded()));
 }
References BrowserMainWindow::currentTab(), and WebView::url().
Referenced by SettingsDialog().
Member Data Documentation
m_cacheEnabled
bool SettingsDialog::m_cacheEnabled private
Definition at line 136 of file settings.h.
Referenced by loadFromSettings().
m_fixedFont
QFont SettingsDialog::m_fixedFont private
Definition at line 135 of file settings.h.
Referenced by chooseFixedFont(), loadDefaults(), loadFromSettings(), and saveToSettings().
m_standardFont
QFont SettingsDialog::m_standardFont private
Definition at line 134 of file settings.h.
Referenced by chooseFont(), loadDefaults(), loadFromSettings(), and saveToSettings().
The documentation for this class was generated from the following files:
src/settings.h
src/settings.cpp