Endorphin: XbelReader Class Reference
XbelReader Class Reference
#include <xbelreader.h>
Public Member Functions
XbelReader ()
~XbelReader ()
BookmarkNode * read (const QString &fileName)
BookmarkNode * read (QIODevice *device)
Private Member Functions
void skipUnknownElement ()
void readXBEL (BookmarkNode *parent)
void readTitle (BookmarkNode *parent)
void readDescription (BookmarkNode *parent)
void readSeparator (BookmarkNode *parent)
void readFolder (BookmarkNode *parent)
void readBookmarkNode (BookmarkNode *parent)
Private Attributes
XmlEntityResolver * m_entityResolver
Detailed Description
Definition at line 76 of file xbelreader.h.
Constructor & Destructor Documentation
XbelReader()
XbelReader::XbelReader ()
Definition at line 77 of file xbelreader.cpp.
     : m_entityResolver(nullptr)
 {
     m_entityResolver = new XmlEntityResolver();
     setEntityResolver(m_entityResolver);
 }
References m_entityResolver.
~XbelReader()
XbelReader::~XbelReader ()
Definition at line 84 of file xbelreader.cpp.
 {
     delete m_entityResolver;
 }
References m_entityResolver.
Member Function Documentation
read() [1/2]
BookmarkNode * XbelReader::read (const QString & fileName)
Definition at line 89 of file xbelreader.cpp.
 {
     QFile file(fileName);
     if (!file.exists()) {
         return new BookmarkNode(BookmarkNode::Root);
     }
     file.open(QFile::ReadOnly);
     return read(&file);
 }
References BookmarkNode::Root.
Referenced by BookmarksModel::dropMimeData(), BookmarksManager::importBookmarks(), and BookmarksManager::load().
read() [2/2]
BookmarkNode * XbelReader::read (QIODevice * device)
Definition at line 99 of file xbelreader.cpp.
 {
     BookmarkNode *root = new BookmarkNode(BookmarkNode::Root);
     setDevice(device);
     while (!atEnd()) {
         readNext();
         if (isStartElement()) {
             QString version = attributes().value(QLatin1String("version")).toString();
             if (name() == QLatin1String("xbel")
                     && (version.isEmpty() || version == QLatin1String("1.0"))) {
                 readXBEL(root);
             } else {
                 raiseError(QObject::tr("The file is not an XBEL version 1.0 file."));
             }
         }
     }
     return root;
 }
References readXBEL(), and BookmarkNode::Root.
readBookmarkNode()
void XbelReader::readBookmarkNode (BookmarkNode * parent) private
Definition at line 189 of file xbelreader.cpp.
 {
     Q_ASSERT(isStartElement() && name() == QLatin1String("bookmark"));
     BookmarkNode *bookmark = new BookmarkNode(BookmarkNode::Bookmark, parent);
     bookmark->url = attributes().value(QLatin1String("href")).toString();
     while (!atEnd()) {
         readNext();
         if (isEndElement())
             break;
         if (isStartElement()) {
             if (name() == QLatin1String("title"))
                 readTitle(bookmark);
             else if (name() == QLatin1String("desc"))
                 readDescription(bookmark);
             else
                 skipUnknownElement();
         }
     }
     if (bookmark->title.isEmpty())
         bookmark->title = QObject::tr("Unknown title");
 }
References BookmarkNode::Bookmark, readDescription(), readTitle(), skipUnknownElement(), BookmarkNode::title, and BookmarkNode::url.
Referenced by readFolder(), and readXBEL().
readDescription()
void XbelReader::readDescription (BookmarkNode * parent) private
Definition at line 176 of file xbelreader.cpp.
 {
     Q_ASSERT(isStartElement() && name() == QLatin1String("desc"));
     parent->desc = readElementText();
 }
References BookmarkNode::desc.
Referenced by readBookmarkNode(), and readFolder().
readFolder()
void XbelReader::readFolder (BookmarkNode * parent) private
Definition at line 140 of file xbelreader.cpp.
 {
     Q_ASSERT(isStartElement() && name() == QLatin1String("folder"));
     BookmarkNode *folder = new BookmarkNode(BookmarkNode::Folder, parent);
     folder->expanded = (attributes().value(QLatin1String("folded")) == QLatin1String("no"));
     while (!atEnd()) {
         readNext();
         if (isEndElement())
             break;
         if (isStartElement()) {
             if (name() == QLatin1String("title"))
                 readTitle(folder);
             else if (name() == QLatin1String("desc"))
                 readDescription(folder);
             else if (name() == QLatin1String("folder"))
                 readFolder(folder);
             else if (name() == QLatin1String("bookmark"))
                 readBookmarkNode(folder);
             else if (name() == QLatin1String("separator"))
                 readSeparator(folder);
             else
                 skipUnknownElement();
         }
     }
 }
References BookmarkNode::expanded, BookmarkNode::Folder, readBookmarkNode(), readDescription(), readSeparator(), readTitle(), and skipUnknownElement().
Referenced by readXBEL().
readSeparator()
void XbelReader::readSeparator (BookmarkNode * parent) private
Definition at line 182 of file xbelreader.cpp.
 {
     new BookmarkNode(BookmarkNode::Separator, parent);
     // empty elements have a start and end element
     readNext();
 }
References BookmarkNode::Separator.
Referenced by readFolder(), and readXBEL().
readTitle()
void XbelReader::readTitle (BookmarkNode * parent) private
Definition at line 170 of file xbelreader.cpp.
 {
     Q_ASSERT(isStartElement() && name() == QLatin1String("title"));
     parent->title = readElementText();
 }
References BookmarkNode::title.
Referenced by readBookmarkNode(), and readFolder().
readXBEL()
void XbelReader::readXBEL (BookmarkNode * parent) private
Definition at line 118 of file xbelreader.cpp.
 {
     Q_ASSERT(isStartElement() && name() == QLatin1String("xbel"));
     while (!atEnd()) {
         readNext();
         if (isEndElement())
             break;
         if (isStartElement()) {
             if (name() == QLatin1String("folder"))
                 readFolder(parent);
             else if (name() == QLatin1String("bookmark"))
                 readBookmarkNode(parent);
             else if (name() == QLatin1String("separator"))
                 readSeparator(parent);
             else
                 skipUnknownElement();
         }
     }
 }
References readBookmarkNode(), readFolder(), readSeparator(), and skipUnknownElement().
Referenced by read().
skipUnknownElement()
void XbelReader::skipUnknownElement () private
Definition at line 212 of file xbelreader.cpp.
 {
     Q_ASSERT(isStartElement());
     while (!atEnd()) {
         readNext();
         if (isEndElement())
             break;
         if (isStartElement())
             skipUnknownElement();
     }
 }
Referenced by readBookmarkNode(), readFolder(), and readXBEL().
Member Data Documentation
m_entityResolver
XmlEntityResolver* XbelReader::m_entityResolver private
Definition at line 95 of file xbelreader.h.
Referenced by XbelReader(), and ~XbelReader().
The documentation for this class was generated from the following files:
src/bookmarks/xbel/xbelreader.h
src/bookmarks/xbel/xbelreader.cpp