Endorphin: ToolbarSearch Class Reference
ToolbarSearch Class Reference
#include <toolbarsearch.h>
Public Slots
void clear ()
void searchNow ()
Signals
void search (const QUrl &url, TabWidget::OpenUrlIn tab)
Public Member Functions
ToolbarSearch (QWidget *parent=nullptr)
~ToolbarSearch ()
Public Member Functions inherited from SearchLineEdit
SearchLineEdit (QWidget *parent=nullptr)
ClearButton * clearButton () const
SearchButton * searchButton () const
Public Member Functions inherited from LineEdit
LineEdit (QWidget *parent=nullptr)
LineEdit (const QString &contents, QWidget *parent=nullptr)
void addWidget (QWidget *widget, WidgetPosition position)
void removeWidget (QWidget *widget)
void setWidgetSpacing (int spacing)
int widgetSpacing () const
int textMargin (WidgetPosition position) const
QString inactiveText () const
void setInactiveText (const QString &text)
void paintEvent (QPaintEvent *event)
Static Public Member Functions
static OpenSearchManager * openSearchManager ()
Protected Member Functions
void changeEvent (QEvent *event)
void focusInEvent (QFocusEvent *event)
Protected Member Functions inherited from LineEdit
void resizeEvent (QResizeEvent *event)
bool event (QEvent *event)
Private Slots
void currentEngineChanged ()
void save ()
void textEdited (const QString &)
void newSuggestions (const QStringList &suggestions)
void completerActivated (const QModelIndex &index)
bool completerHighlighted (const QModelIndex &index)
void getSuggestions ()
void showEnginesMenu ()
void changeCurrentEngine ()
void addEngineFromUrl ()
Private Member Functions
void load ()
void setupList ()
void retranslate ()
Private Attributes
QString m_currentEngine
bool m_suggestionsEnabled
AutoSaver * m_autosaver
int m_maxSavedSearches
QStringList m_recentSearches
QStringList m_suggestions
QStandardItemModel * m_model
QStandardItem * m_suggestionsItem
QStandardItem * m_recentSearchesItem
QTimer * m_suggestTimer
QCompleter * m_completer
Static Private Attributes
static OpenSearchManager * s_openSearchManager = nullptr
Additional Inherited Members
Public Types inherited from LineEdit
enum WidgetPosition { LeftSide, RightSide }
Protected Slots inherited from LineEdit
void updateTextMargins ()
Properties inherited from LineEdit
QString inactiveText
Detailed Description
Definition at line 78 of file toolbarsearch.h.
Constructor & Destructor Documentation
ToolbarSearch()
ToolbarSearch::ToolbarSearch (QWidget * parent = nullptr)
Definition at line 93 of file toolbarsearch.cpp.
     : SearchLineEdit(parent)
     , m_suggestionsEnabled(true)
     , m_autosaver(new AutoSaver(this))
     , m_maxSavedSearches(10)
     , m_model(new QStandardItemModel(this))
     , m_suggestionsItem(nullptr)
     , m_recentSearchesItem(nullptr)
     , m_suggestTimer(nullptr)
     , m_completer(nullptr)
 {
     connect(openSearchManager(), SIGNAL(currentEngineChanged()),
             this, SLOT(currentEngineChanged()));
     m_completer = new QCompleter(m_model, this);
     m_completer->setCompletionMode(QCompleter::UnfilteredPopupCompletion);
     setCompleter(m_completer);
     searchButton()->setShowMenuTriangle(true);
     connect(searchButton(), SIGNAL(clicked()),
             this, SLOT(showEnginesMenu()));
     connect(this, SIGNAL(returnPressed()),
             this, SLOT(searchNow()));
     load();
     currentEngineChanged();
 }
References currentEngineChanged(), load(), m_completer, m_model, openSearchManager(), SearchLineEdit::searchButton(), searchNow(), SearchButton::setShowMenuTriangle(), and showEnginesMenu().
~ToolbarSearch()
ToolbarSearch::~ToolbarSearch ()
Definition at line 188 of file toolbarsearch.cpp.
 {
     m_autosaver->saveIfNeccessary();
 }
References m_autosaver, and AutoSaver::saveIfNeccessary().
Member Function Documentation
addEngineFromUrl
void ToolbarSearch::addEngineFromUrl () private slot
Definition at line 364 of file toolbarsearch.cpp.
 {
     QAction *action = qobject_cast<QAction*>(sender());
     if (!action)
         return;
     QVariant variant = action->data();
     if (!variant.canConvert<QUrl>())
         return;
     QUrl url = variant.toUrl();
     openSearchManager()->addEngine(url);
 }
References OpenSearchManager::addEngine(), and openSearchManager().
changeCurrentEngine
void ToolbarSearch::changeCurrentEngine () private slot
Definition at line 356 of file toolbarsearch.cpp.
 {
     if (QAction *action = qobject_cast<QAction*>(sender())) {
         QString name = action->data().toString();
         openSearchManager()->setCurrentEngineName(name);
     }
 }
References openSearchManager(), and OpenSearchManager::setCurrentEngineName().
Referenced by showEnginesMenu().
changeEvent()
void ToolbarSearch::changeEvent (QEvent * event) protected
Definition at line 282 of file toolbarsearch.cpp.
 {
     if (event->type() == QEvent::LanguageChange)
         retranslate();
     SearchLineEdit::changeEvent(event);
 }
References LineEdit::event(), and retranslate().
clear
void ToolbarSearch::clear () slot
Definition at line 423 of file toolbarsearch.cpp.
 {
     m_recentSearches.clear();
     m_autosaver->changeOccurred();
     setupList();
     QLineEdit::clear();
     clearFocus();
 }
References AutoSaver::changeOccurred(), m_autosaver, m_recentSearches, and setupList().
Referenced by showEnginesMenu().
completerActivated
void ToolbarSearch::completerActivated (const QModelIndex & index) private slot
Definition at line 154 of file toolbarsearch.cpp.
 {
     if (completerHighlighted(index))
         searchNow();
 }
References completerHighlighted(), and searchNow().
Referenced by focusInEvent().
completerHighlighted
bool ToolbarSearch::completerHighlighted (const QModelIndex & index) private slot
Definition at line 160 of file toolbarsearch.cpp.
 {
     if (m_suggestionsItem && m_suggestionsItem->index().row() == index.row())
         return false;
     if (m_recentSearchesItem && m_recentSearchesItem->index().row() == index.row())
         return false;
     setText(index.data().toString());
     return true;
 }
References m_recentSearchesItem, and m_suggestionsItem.
Referenced by completerActivated(), and focusInEvent().
currentEngineChanged
void ToolbarSearch::currentEngineChanged () private slot
Definition at line 130 of file toolbarsearch.cpp.
 {
     OpenSearchEngine *newEngine = openSearchManager()->currentEngine();
     Q_ASSERT(newEngine);
     if (!newEngine)
         return;
     if (m_suggestionsEnabled) {
         if (openSearchManager()->engineExists(m_currentEngine)) {
             OpenSearchEngine *oldEngine = openSearchManager()->engine(m_currentEngine);
             disconnect(oldEngine, SIGNAL(suggestions(const QStringList &)),
                        this, SLOT(newSuggestions(const QStringList &)));
         }
         connect(newEngine, SIGNAL(suggestions(const QStringList &)),
                 this, SLOT(newSuggestions(const QStringList &)));
     }
     setInactiveText(newEngine->name());
     m_currentEngine = newEngine->name();
     m_suggestions.clear();
     setupList();
 }
References OpenSearchManager::currentEngine(), OpenSearchManager::engine(), m_currentEngine, m_suggestions, m_suggestionsEnabled, OpenSearchEngine::name, newSuggestions(), openSearchManager(), LineEdit::setInactiveText(), and setupList().
Referenced by ToolbarSearch().
focusInEvent()
void ToolbarSearch::focusInEvent (QFocusEvent * event) protected
Definition at line 170 of file toolbarsearch.cpp.
 {
     SearchLineEdit::focusInEvent(event);
     // Every time we get a focus in event QLineEdit re-connects...
     disconnect(completer(), SIGNAL(activated(QString)),
                this, SLOT(setText(QString)));
     disconnect(completer(), SIGNAL(highlighted(QString)),
                this, SLOT(_q_completionHighlighted(QString)));
     // And every time it gets a focus out it disconnects everything from the completer to this :(
     // So we have to re-connect
     connect(completer(), SIGNAL(activated(const QModelIndex &)),
             this, SLOT(completerActivated(const QModelIndex &)));
     connect(completer(), SIGNAL(highlighted(const QModelIndex &)),
             this, SLOT(completerHighlighted(const QModelIndex &)));
 }
References completerActivated(), completerHighlighted(), and LineEdit::event().
getSuggestions
void ToolbarSearch::getSuggestions () private slot
Definition at line 234 of file toolbarsearch.cpp.
 {
     OpenSearchEngine *engine = openSearchManager()->currentEngine();
     Q_ASSERT(engine);
     if (!engine)
         return;
     if (!engine->networkAccessManager())
         engine->setNetworkAccessManager(new QNetworkAccessManager());
     engine->requestSuggestions(text());
 }
References OpenSearchManager::currentEngine(), OpenSearchEngine::networkAccessManager, openSearchManager(), OpenSearchEngine::requestSuggestions(), and OpenSearchEngine::setNetworkAccessManager().
Referenced by textEdited().
load()
void ToolbarSearch::load () private
Definition at line 202 of file toolbarsearch.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("toolbarsearch"));
     m_recentSearches = settings.value(QLatin1String("recentSearches")).toStringList();
     m_maxSavedSearches = settings.value(QLatin1String("maximumSaved"), m_maxSavedSearches).toInt();
     m_suggestionsEnabled = settings.value(QLatin1String("useSuggestions"), true).toBool();
     if (m_suggestionsEnabled) {
         connect(this, SIGNAL(textEdited(const QString &)),
                 this, SLOT(textEdited(const QString &)));
     }
     settings.endGroup();
     setupList();
 }
References m_maxSavedSearches, m_recentSearches, m_suggestionsEnabled, setupList(), and textEdited().
Referenced by ToolbarSearch().
newSuggestions
void ToolbarSearch::newSuggestions (const QStringList & suggestions) private slot
Definition at line 276 of file toolbarsearch.cpp.
 {
     m_suggestions = suggestions;
     setupList();
 }
References m_suggestions, and setupList().
Referenced by currentEngineChanged().
openSearchManager()
OpenSearchManager * ToolbarSearch::openSearchManager () static
Definition at line 123 of file toolbarsearch.cpp.
 {
     if (!s_openSearchManager)
         s_openSearchManager = new OpenSearchManager;
     return s_openSearchManager;
 }
References s_openSearchManager.
Referenced by OpenSearchDialog::addButtonClicked(), addEngineFromUrl(), changeCurrentEngine(), WebView::contextMenuEvent(), currentEngineChanged(), getSuggestions(), TabWidget::guessUrlFromString(), OpenSearchDialog::OpenSearchDialog(), OpenSearchDialog::restoreButtonClicked(), searchNow(), WebView::searchRequested(), showEnginesMenu(), and ToolbarSearch().
retranslate()
void ToolbarSearch::retranslate () private
Definition at line 289 of file toolbarsearch.cpp.
 {
     if (m_suggestionsItem)
         m_suggestionsItem->setText(tr("Suggestions"));
 }
References m_suggestionsItem.
Referenced by changeEvent(), and setupList().
save
void ToolbarSearch::save () private slot
Definition at line 193 of file toolbarsearch.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("toolbarsearch"));
     settings.setValue(QLatin1String("recentSearches"), m_recentSearches);
     settings.setValue(QLatin1String("maximumSaved"), m_maxSavedSearches);
     settings.endGroup();
 }
References m_maxSavedSearches, and m_recentSearches.
search
void ToolbarSearch::search (const QUrl & url, TabWidget::OpenUrlIn tab) signal
Referenced by searchNow().
searchNow
void ToolbarSearch::searchNow () slot
Definition at line 247 of file toolbarsearch.cpp.
 {
     OpenSearchEngine *engine = openSearchManager()->currentEngine();
     Q_ASSERT(engine);
     if (!engine)
         return;
     QString searchText = text();
 //    QWebEngineSettings *globalSettings = QWebEngineSettings::globalSettings();
 //    if (!globalSettings->testAttribute(QWebEngineSettings::PrivateBrowsingEnabled)) {
     QStringList newList = m_recentSearches;
     if (newList.contains(searchText))
         newList.removeAt(newList.indexOf(searchText));
     newList.prepend(searchText);
     if (newList.size() >= m_maxSavedSearches)
         newList.removeLast();
     m_recentSearches = newList;
     m_autosaver->changeOccurred();
 //    }
     QUrl searchUrl = engine->searchUrl(searchText);
     TabWidget::OpenUrlIn tab = TabWidget::CurrentTab;
     if (qApp->keyboardModifiers() == Qt::AltModifier)
         tab = TabWidget::NewSelectedTab;
     emit search(searchUrl, tab);
 }
References AutoSaver::changeOccurred(), OpenSearchManager::currentEngine(), TabWidget::CurrentTab, m_autosaver, m_maxSavedSearches, m_recentSearches, TabWidget::NewSelectedTab, openSearchManager(), search(), and OpenSearchEngine::searchUrl().
Referenced by completerActivated(), and ToolbarSearch().
setupList()
void ToolbarSearch::setupList () private
Definition at line 377 of file toolbarsearch.cpp.
 {
     if (m_suggestions.isEmpty()
             || (m_model->rowCount() > 0
                 && m_model->item(0) != m_suggestionsItem)) {
         m_model->clear();
         m_suggestionsItem = nullptr;
     } else {
         m_model->removeRows(1, m_model->rowCount() - 1);
     }
     QFont lightFont;
     lightFont.setWeight(QFont::Light);
     if (!m_suggestions.isEmpty()) {
         if (m_model->rowCount() == 0) {
             if (!m_suggestionsItem) {
                 m_suggestionsItem = new QStandardItem();
                 m_suggestionsItem->setFont(lightFont);
                 retranslate();
             }
             m_model->appendRow(m_suggestionsItem);
         }
         for (int i = 0; i < m_suggestions.count(); ++i) {
             const QString &text = m_suggestions.at(i);
             m_model->appendRow(new QStandardItem(text));
         }
     }
     if (m_recentSearches.isEmpty()) {
         m_recentSearchesItem = new QStandardItem(tr("No Recent Searches"));
         m_recentSearchesItem->setFont(lightFont);
         m_model->appendRow(m_recentSearchesItem);
     } else {
         m_recentSearchesItem = new QStandardItem(tr("Recent Searches"));
         m_recentSearchesItem->setFont(lightFont);
         m_model->appendRow(m_recentSearchesItem);
         for (int i = 0; i < m_recentSearches.count(); ++i) {
             QString text = m_recentSearches.at(i);
             m_model->appendRow(new QStandardItem(text));
         }
     }
     QAbstractItemView *view = completer()->popup();
     view->setFixedHeight(view->sizeHintForRow(0) * m_model->rowCount() + view->frameWidth() * 2);
 }
References m_model, m_recentSearches, m_recentSearchesItem, m_suggestions, m_suggestionsItem, and retranslate().
Referenced by clear(), currentEngineChanged(), load(), and newSuggestions().
showEnginesMenu
void ToolbarSearch::showEnginesMenu () private slot
Definition at line 295 of file toolbarsearch.cpp.
 {
     QMenu menu;
     QWidget *parent = searchButton()->parentWidget();
     if (!parent)
         return;
     QPoint pos = parent->mapToGlobal(QPoint(0, parent->height()));
     QList<QString> list = openSearchManager()->allEnginesNames();
     for (int i = 0; i < list.count(); ++i) {
         QString name = list.at(i);
         OpenSearchEngine *engine = openSearchManager()->engine(name);
         OpenSearchEngineAction *action = new OpenSearchEngineAction(engine, &menu);
         action->setData(name);
         connect(action, SIGNAL(triggered()), this, SLOT(changeCurrentEngine()));
         menu.addAction(action);
         if (openSearchManager()->currentEngineName() == name) {
             action->setCheckable(true);
             action->setChecked(true);
         }
     }
     /*
         WebView *webView = BrowserMainWindow::parentWindow(this)->currentTab();
         QList<WebPageLinkedResource> engines = webView->webPage()->linkedResources(QLatin1String("search"));
         if (!engines.empty())
             menu.addSeparator();
         for (int i = 0; i < engines.count(); ++i) {
             WebPageLinkedResource engine = engines.at(i);
             QUrl url = engine.href;
             QString title = engine.title;
             QString mimetype = engine.type;
             if (mimetype != QLatin1String("application/opensearchdescription+xml"))
                 continue;
             if (url.isEmpty())
                 continue;
             if (title.isEmpty())
                 title = webView->title().isEmpty() ? url.host() : webView->title();
             QAction *action = menu.addAction(tr("Add '%1'").arg(title), this, SLOT(addEngineFromUrl()));
             action->setData(url);
             action->setIcon(webView->icon());
         }
     */
     menu.addSeparator();
     if (BrowserMainWindow *window = BrowserMainWindow::parentWindow(this))
         menu.addAction(window->searchManagerAction());
     if (!m_recentSearches.empty())
         menu.addAction(tr("Clear Recent Searches"), this, SLOT(clear()));
     menu.exec(pos);
 }
References OpenSearchManager::allEnginesNames(), changeCurrentEngine(), clear(), OpenSearchManager::engine(), m_recentSearches, openSearchManager(), BrowserMainWindow::parentWindow(), and SearchLineEdit::searchButton().
Referenced by ToolbarSearch().
textEdited
void ToolbarSearch::textEdited (const QString & text) private slot
Definition at line 219 of file toolbarsearch.cpp.
 {
     Q_UNUSED(text);
     // delay settings this to prevent BrowserApplication from creating
     // the object when it isn't needed on startup
     if (!m_suggestTimer) {
         m_suggestTimer = new QTimer(this);
         m_suggestTimer->setSingleShot(true);
         m_suggestTimer->setInterval(200);
         connect(m_suggestTimer, SIGNAL(timeout()),
                 this, SLOT(getSuggestions()));
     }
     m_suggestTimer->start();
 }
References getSuggestions(), and m_suggestTimer.
Referenced by load().
Member Data Documentation
m_autosaver
AutoSaver* ToolbarSearch::m_autosaver private
Definition at line 119 of file toolbarsearch.h.
Referenced by clear(), searchNow(), and ~ToolbarSearch().
m_completer
QCompleter* ToolbarSearch::m_completer private
Definition at line 129 of file toolbarsearch.h.
Referenced by ToolbarSearch().
m_currentEngine
QString ToolbarSearch::m_currentEngine private
Definition at line 116 of file toolbarsearch.h.
Referenced by currentEngineChanged().
m_maxSavedSearches
int ToolbarSearch::m_maxSavedSearches private
Definition at line 120 of file toolbarsearch.h.
Referenced by load(), save(), and searchNow().
m_model
QStandardItemModel* ToolbarSearch::m_model private
Definition at line 123 of file toolbarsearch.h.
Referenced by setupList(), and ToolbarSearch().
m_recentSearches
QStringList ToolbarSearch::m_recentSearches private
Definition at line 121 of file toolbarsearch.h.
Referenced by clear(), load(), save(), searchNow(), setupList(), and showEnginesMenu().
m_recentSearchesItem
QStandardItem* ToolbarSearch::m_recentSearchesItem private
Definition at line 126 of file toolbarsearch.h.
Referenced by completerHighlighted(), and setupList().
m_suggestions
QStringList ToolbarSearch::m_suggestions private
Definition at line 122 of file toolbarsearch.h.
Referenced by currentEngineChanged(), newSuggestions(), and setupList().
m_suggestionsEnabled
bool ToolbarSearch::m_suggestionsEnabled private
Definition at line 117 of file toolbarsearch.h.
Referenced by currentEngineChanged(), and load().
m_suggestionsItem
QStandardItem* ToolbarSearch::m_suggestionsItem private
Definition at line 125 of file toolbarsearch.h.
Referenced by completerHighlighted(), retranslate(), and setupList().
m_suggestTimer
QTimer* ToolbarSearch::m_suggestTimer private
Definition at line 127 of file toolbarsearch.h.
Referenced by textEdited().
s_openSearchManager
OpenSearchManager * ToolbarSearch::s_openSearchManager = nullptr static private
Definition at line 115 of file toolbarsearch.h.
Referenced by openSearchManager().
The documentation for this class was generated from the following files:
src/toolbarsearch.h
src/toolbarsearch.cpp