Endorphin: DownloadItem Class Reference
DownloadItem Class Reference
#include <downloadmanager.h>
Signals
void statusChanged ()
void progress (qint64 bytesReceived=0, qint64 bytesTotal=0)
void downloadFinished ()
Public Member Functions
DownloadItem (QNetworkReply *reply=nullptr, bool requestFileName=false, QWidget *parent=nullptr)
bool downloading () const
bool downloadedSuccessfully () const
qint64 bytesTotal () const
qint64 bytesReceived () const
double remainingTime () const
double currentSpeed () const
Public Attributes
QUrl m_url
QFile m_output
QNetworkReply * m_reply
Private Slots
void stop ()
void tryAgain ()
void open ()
void downloadReadyRead ()
void error (QNetworkReply::NetworkError code)
void downloadProgress (qint64 bytesReceived, qint64 bytesTotal)
void metaDataChanged ()
void finished ()
Private Member Functions
void getFileName ()
void init ()
void updateInfoLabel ()
QString saveFileName (const QString &directory) const
Private Attributes
bool m_requestFileName
qint64 m_bytesReceived
QElapsedTimer m_downloadTime
bool m_startedSaving
bool m_finishedDownloading
bool m_gettingFileName
bool m_canceledFileSelect
QTime m_lastProgressTime
Friends
class DownloadManager
Detailed Description
Definition at line 76 of file downloadmanager.h.
Constructor & Destructor Documentation
DownloadItem()
DownloadItem::DownloadItem (QNetworkReply * reply = nullptr, bool requestFileName = false, QWidget * parent = nullptr)
DownloadItem is a widget that is displayed in the download manager list. It moves the data from the QNetworkReply into the QFile as well as update the information/progressbar and report errors.
Definition at line 95 of file downloadmanager.cpp.
     : QWidget(parent)
     , m_reply(reply)
     , m_requestFileName(requestFileName)
     , m_bytesReceived(0)
     , m_startedSaving(false)
     , m_finishedDownloading(false)
     , m_gettingFileName(false)
     , m_canceledFileSelect(false)
 {
     setupUi(this);
     QPalette p = downloadInfoLabel->palette();
     p.setColor(QPalette::Text, Qt::darkGray);
     downloadInfoLabel->setPalette(p);
     progressBar->setMaximum(0);
     tryAgainButton->hide();
     connect(stopButton, SIGNAL(clicked()), this, SLOT(stop()));
     connect(openButton, SIGNAL(clicked()), this, SLOT(open()));
     connect(tryAgainButton, SIGNAL(clicked()), this, SLOT(tryAgain()));
     if (!requestFileName) {
         QSettings settings;
         settings.beginGroup(QLatin1String("downloadmanager"));
         m_requestFileName = settings.value(QLatin1String("alwaysPromptForFileName"), false).toBool();
     }
     init();
 }
References init(), m_requestFileName, open(), stop(), and tryAgain().
Member Function Documentation
bytesReceived()
qint64 DownloadItem::bytesReceived () const
Definition at line 377 of file downloadmanager.cpp.
 {
     return m_bytesReceived;
 }
References m_bytesReceived.
Referenced by downloadProgress(), and remainingTime().
bytesTotal()
qint64 DownloadItem::bytesTotal () const
Definition at line 372 of file downloadmanager.cpp.
 {
     return m_reply->header(QNetworkRequest::ContentLengthHeader).toULongLong();
 }
References m_reply.
Referenced by downloadProgress(), remainingTime(), and updateInfoLabel().
currentSpeed()
double DownloadItem::currentSpeed () const
Definition at line 396 of file downloadmanager.cpp.
 {
     if (!downloading())
         return -1.0;
     return m_bytesReceived * 1000.0 / m_downloadTime.elapsed();
 }
References downloading(), m_bytesReceived, and m_downloadTime.
Referenced by remainingTime(), and updateInfoLabel().
downloadedSuccessfully()
bool DownloadItem::downloadedSuccessfully () const
Definition at line 445 of file downloadmanager.cpp.
 {
     return (stopButton->isHidden() && tryAgainButton->isHidden());
 }
Referenced by DownloadModel::flags(), updateInfoLabel(), and DownloadManager::updateRow().
downloadFinished
void DownloadItem::downloadFinished () signal
Referenced by error(), finished(), and stop().
downloading()
bool DownloadItem::downloading () const
Definition at line 440 of file downloadmanager.cpp.
 {
     return (progressBar->isVisible());
 }
Referenced by currentSpeed(), remainingTime(), and DownloadManager::updateRow().
downloadProgress
void DownloadItem::downloadProgress (qint64 bytesReceived, qint64 bytesTotal) private slot
Definition at line 350 of file downloadmanager.cpp.
 {
     QTime now = QTime::currentTime();
     if (m_lastProgressTime.msecsTo(now) < 200)
         return;
     m_lastProgressTime = now;
     m_bytesReceived = bytesReceived;
     qint64 currentValue = 0;
     qint64 totalValue = 0;
     if (bytesTotal > 0) {
         currentValue = bytesReceived * 100 / bytesTotal;
         totalValue = 100;
     }
     progressBar->setValue(currentValue);
     progressBar->setMaximum(totalValue);
     emit progress(currentValue, totalValue);
     updateInfoLabel();
 }
References bytesReceived(), bytesTotal(), m_bytesReceived, m_lastProgressTime, progress(), and updateInfoLabel().
Referenced by init().
downloadReadyRead
void DownloadItem::downloadReadyRead () private slot
Definition at line 293 of file downloadmanager.cpp.
 {
     if (m_requestFileName && m_output.fileName().isEmpty())
         return;
     if (!m_output.isOpen()) {
         // in case someone else has already put a file there
         if (!m_requestFileName)
             getFileName();
         if (!m_output.open(QIODevice::WriteOnly)) {
             downloadInfoLabel->setText(tr("Error opening output file: %1")
                                        .arg(m_output.errorString()));
             stop();
             emit statusChanged();
             return;
         }
         emit statusChanged();
     }
     if (-1 == m_output.write(m_reply->readAll())) {
         downloadInfoLabel->setText(tr("Error saving: %1")
                                    .arg(m_output.errorString()));
         stopButton->click();
     } else {
         m_startedSaving = true;
         if (m_finishedDownloading)
             finished();
     }
 }
References finished(), getFileName(), m_finishedDownloading, m_output, m_reply, m_requestFileName, m_startedSaving, statusChanged(), and stop().
Referenced by getFileName(), and init().
error
void DownloadItem::error (QNetworkReply::NetworkError code) private slot
Definition at line 321 of file downloadmanager.cpp.
 {
 #ifdef DOWNLOADMANAGER_DEBUG
     qDebug() << "DownloadItem::" << __FUNCTION__ << m_reply->errorString() << m_url;
 #endif
     downloadInfoLabel->setText(tr("Network Error: %1").arg(m_reply->errorString()));
     tryAgainButton->setEnabled(true);
     tryAgainButton->setVisible(true);
     emit downloadFinished();
 }
References downloadFinished(), m_reply, and m_url.
Referenced by init().
finished
void DownloadItem::finished () private slot
Definition at line 450 of file downloadmanager.cpp.
 {
     m_finishedDownloading = true;
     if (!m_startedSaving) {
         return;
     }
     progressBar->hide();
     stopButton->setEnabled(false);
     stopButton->hide();
     openButton->setEnabled(true);
     m_output.close();
     updateInfoLabel();
     emit statusChanged();
     emit downloadFinished();
 }
References downloadFinished(), m_finishedDownloading, m_output, m_startedSaving, statusChanged(), and updateInfoLabel().
Referenced by downloadReadyRead(), and init().
getFileName()
void DownloadItem::getFileName () private
Definition at line 161 of file downloadmanager.cpp.
 {
     if (m_gettingFileName)
         return;
 #ifndef NO_BROWSERAPPLICATION
     QString downloadDirectory = BrowserApplication::downloadManager()->downloadDirectory();
 #else
     QString downloadDirectory = QStandardPaths::writableLocation(QStandardPaths::DesktopLocation) + '/';
 #endif
     QString defaultFileName = saveFileName(downloadDirectory);
     QString fileName = defaultFileName;
     if (m_requestFileName) {
         m_gettingFileName = true;
         fileName = QFileDialog::getSaveFileName(this, tr("Save File"), defaultFileName);
         m_gettingFileName = false;
         if (fileName.isEmpty()) {
             progressBar->setVisible(false);
             stop();
             fileNameLabel->setText(tr("Download canceled: %1").arg(QFileInfo(defaultFileName).fileName()));
             m_canceledFileSelect = true;
             return;
         }
         QFileInfo fileInfo = QFileInfo(fileName);
 #ifndef NO_BROWSERAPPLICATION
         BrowserApplication::downloadManager()->setDownloadDirectory(fileInfo.absoluteDir().absolutePath());
 #endif
         fileNameLabel->setText(fileInfo.fileName());
     }
     m_output.setFileName(fileName);
     // Check file path for saving.
     QDir saveDirPath = QFileInfo(m_output.fileName()).dir();
     if (!saveDirPath.exists()) {
         if (!saveDirPath.mkpath(saveDirPath.absolutePath())) {
             progressBar->setVisible(false);
             stop();
             downloadInfoLabel->setText(tr("Download directory (%1) couldn't be created.").arg(saveDirPath.absolutePath()));
             return;
         }
     }
     fileNameLabel->setText(QFileInfo(m_output.fileName()).fileName());
     if (m_requestFileName)
         downloadReadyRead();
 }
References DownloadManager::downloadDirectory(), BrowserApplication::downloadManager(), downloadReadyRead(), m_canceledFileSelect, m_gettingFileName, m_output, m_requestFileName, saveFileName(), DownloadManager::setDownloadDirectory(), and stop().
Referenced by downloadReadyRead(), and init().
init()
void DownloadItem::init () private
Definition at line 124 of file downloadmanager.cpp.
 {
     if (!m_reply)
         return;
     m_startedSaving = false;
     m_finishedDownloading = false;
     openButton->setEnabled(false);
     // attach to the m_reply
     m_url = m_reply->url();
     m_reply->setParent(this);
     connect(m_reply, SIGNAL(readyRead()), this, SLOT(downloadReadyRead()));
     connect(m_reply, SIGNAL(error(QNetworkReply::NetworkError)),
             this, SLOT(error(QNetworkReply::NetworkError)));
     connect(m_reply, SIGNAL(downloadProgress(qint64, qint64)),
             this, SLOT(downloadProgress(qint64, qint64)));
     connect(m_reply, SIGNAL(metaDataChanged()),
             this, SLOT(metaDataChanged()));
     connect(m_reply, SIGNAL(finished()),
             this, SLOT(finished()));
     // reset info
     downloadInfoLabel->clear();
     progressBar->setValue(0);
     getFileName();
     // start timer for the download estimation
     m_downloadTime.start();
     if (m_reply->error() != QNetworkReply::NoError) {
         error(m_reply->error());
         finished();
     }
 }
References downloadProgress(), downloadReadyRead(), error(), finished(), getFileName(), m_downloadTime, m_finishedDownloading, m_reply, m_startedSaving, m_url, and metaDataChanged().
Referenced by DownloadItem(), metaDataChanged(), and tryAgain().
metaDataChanged
void DownloadItem::metaDataChanged () private slot
Definition at line 333 of file downloadmanager.cpp.
 {
     QVariant locationHeader = m_reply->header(QNetworkRequest::LocationHeader);
     if (locationHeader.isValid()) {
         m_url = locationHeader.toUrl();
         m_reply->deleteLater();
         QNetworkAccessManager *manager = new QNetworkAccessManager();
         m_reply = manager->get(QNetworkRequest(m_url));
         init();
         return;
     }
 #ifdef DOWNLOADMANAGER_DEBUG
     qDebug() << "DownloadItem::" << __FUNCTION__ << "not handled.";
 #endif
 }
References init(), m_reply, and m_url.
Referenced by init().
open
void DownloadItem::open () private slot
Definition at line 264 of file downloadmanager.cpp.
 {
     QFileInfo info(m_output);
     QUrl url = QUrl::fromLocalFile(info.absoluteFilePath());
     QDesktopServices::openUrl(url);
 }
References m_output.
Referenced by DownloadItem().
progress
void DownloadItem::progress (qint64 bytesReceived = 0, qint64 bytesTotal = 0) signal
Referenced by downloadProgress().
remainingTime()
double DownloadItem::remainingTime () const
Definition at line 382 of file downloadmanager.cpp.
 {
     if (!downloading())
         return -1.0;
     double timeRemaining = ((double)(bytesTotal() - bytesReceived())) / currentSpeed();
     // When downloading the eta should never be 0
     if (timeRemaining == 0)
         timeRemaining = 1;
     return timeRemaining;
 }
References bytesReceived(), bytesTotal(), currentSpeed(), and downloading().
Referenced by updateInfoLabel().
saveFileName()
QString DownloadItem::saveFileName (const QString & directory) const private
Definition at line 209 of file downloadmanager.cpp.
 {
     // Move this function into QNetworkReply to also get file name sent from the server
     QString path;
     if (m_reply->hasRawHeader("Content-Disposition")) {
         QString value = QLatin1String(m_reply->rawHeader("Content-Disposition"));
         int pos = value.indexOf(QLatin1String("filename="));
         if (pos != -1) {
             QString name = value.mid(pos + 9);
             if (name.startsWith(QLatin1Char('"')) && name.endsWith(QLatin1Char('"')))
                 name = name.mid(1, name.size() - 2);
             path = name;
         }
     }
     if (path.isEmpty())
         path = m_url.path();
     QFileInfo info(path);
     QString baseName = info.completeBaseName();
     QString endName = info.suffix();
     if (baseName.isEmpty()) {
         baseName = QLatin1String("unnamed_download");
 #ifdef DOWNLOADMANAGER_DEBUG
         qDebug() << "DownloadItem::" << __FUNCTION__ << "downloading unknown file:" << m_url;
 #endif
     }
     if (!endName.isEmpty())
         endName = QLatin1Char('.') + endName;
     QString name = directory + baseName + endName;
     if (!m_requestFileName && QFile::exists(name)) {
         // already exists, don't overwrite
         int i = 1;
         do {
             name = directory + baseName + QLatin1Char('-') + QString::number(i++) + endName;
         } while (QFile::exists(name));
     }
     return name;
 }
References m_reply, m_requestFileName, and m_url.
Referenced by getFileName().
statusChanged
void DownloadItem::statusChanged () signal
Referenced by downloadReadyRead(), finished(), and tryAgain().
stop
void DownloadItem::stop () private slot
Definition at line 252 of file downloadmanager.cpp.
 {
     setUpdatesEnabled(false);
     stopButton->setEnabled(false);
     stopButton->hide();
     tryAgainButton->setEnabled(true);
     tryAgainButton->show();
     setUpdatesEnabled(true);
     m_reply->abort();
     emit downloadFinished();
 }
References downloadFinished(), and m_reply.
Referenced by DownloadItem(), downloadReadyRead(), and getFileName().
tryAgain
void DownloadItem::tryAgain () private slot
Definition at line 271 of file downloadmanager.cpp.
 {
     if (!tryAgainButton->isEnabled())
         return;
     tryAgainButton->setEnabled(false);
     tryAgainButton->setVisible(false);
     stopButton->setEnabled(true);
     stopButton->setVisible(true);
     progressBar->setVisible(true);
     QNetworkAccessManager *manager = new QNetworkAccessManager();
     QNetworkReply *r = manager->get(QNetworkRequest(m_url));
     if (m_reply)
         m_reply->deleteLater();
     if (m_output.exists())
         m_output.remove();
     m_reply = r;
     init();
     emit statusChanged();
 }
References init(), m_output, m_reply, m_url, and statusChanged().
Referenced by DownloadItem().
updateInfoLabel()
void DownloadItem::updateInfoLabel () private
Definition at line 404 of file downloadmanager.cpp.
 {
     if (m_reply->error() != QNetworkReply::NoError)
         return;
     qint64 bytesTotal = m_reply->header(QNetworkRequest::ContentLengthHeader).toULongLong();
     bool running = !downloadedSuccessfully();
     // update info label
     double speed = currentSpeed();
     double timeRemaining = remainingTime();
     QString info;
     if (running) {
         QString remaining;
         if (bytesTotal != 0) {
             remaining = DownloadManager::timeString(timeRemaining);
         }
         info = QString(tr("%1 of %2 (%3/sec) - %4"))
                .arg(DownloadManager::dataString(m_bytesReceived))
                .arg(bytesTotal == 0 ? tr("?") : DownloadManager::dataString(bytesTotal))
                .arg(DownloadManager::dataString((int)speed))
                .arg(remaining);
     } else {
         if (m_bytesReceived == bytesTotal)
             info = DownloadManager::dataString(m_output.size());
         else
             info = tr("%1 of %2 - Download Complete")
                    .arg(DownloadManager::dataString(m_bytesReceived))
                    .arg(DownloadManager::dataString(bytesTotal));
     }
     downloadInfoLabel->setText(info);
 }
References bytesTotal(), currentSpeed(), DownloadManager::dataString(), downloadedSuccessfully(), m_bytesReceived, m_output, m_reply, remainingTime(), and DownloadManager::timeString().
Referenced by downloadProgress(), and finished().
Friends And Related Function Documentation
DownloadManager
friend class DownloadManager friend
Definition at line 168 of file downloadmanager.h.
Member Data Documentation
m_bytesReceived
qint64 DownloadItem::m_bytesReceived private
Definition at line 160 of file downloadmanager.h.
Referenced by bytesReceived(), currentSpeed(), downloadProgress(), and updateInfoLabel().
m_canceledFileSelect
bool DownloadItem::m_canceledFileSelect private
Definition at line 165 of file downloadmanager.h.
Referenced by getFileName(), and DownloadManager::handleUnsupportedContent().
m_downloadTime
QElapsedTimer DownloadItem::m_downloadTime private
Definition at line 161 of file downloadmanager.h.
Referenced by currentSpeed(), and init().
m_finishedDownloading
bool DownloadItem::m_finishedDownloading private
Definition at line 163 of file downloadmanager.h.
Referenced by downloadReadyRead(), finished(), and init().
m_gettingFileName
bool DownloadItem::m_gettingFileName private
Definition at line 164 of file downloadmanager.h.
Referenced by getFileName().
m_lastProgressTime
QTime DownloadItem::m_lastProgressTime private
Definition at line 166 of file downloadmanager.h.
Referenced by downloadProgress().
m_output
QFile DownloadItem::m_output
Definition at line 138 of file downloadmanager.h.
Referenced by downloadReadyRead(), finished(), getFileName(), DownloadManager::load(), DownloadModel::mimeData(), open(), tryAgain(), updateInfoLabel(), and DownloadManager::updateRow().
m_reply
QNetworkReply* DownloadItem::m_reply
Definition at line 139 of file downloadmanager.h.
Referenced by bytesTotal(), downloadReadyRead(), error(), init(), metaDataChanged(), saveFileName(), stop(), tryAgain(), and updateInfoLabel().
m_requestFileName
bool DownloadItem::m_requestFileName private
Definition at line 159 of file downloadmanager.h.
Referenced by DownloadItem(), downloadReadyRead(), getFileName(), and saveFileName().
m_startedSaving
bool DownloadItem::m_startedSaving private
Definition at line 162 of file downloadmanager.h.
Referenced by downloadReadyRead(), finished(), and init().
m_url
QUrl DownloadItem::m_url
Definition at line 136 of file downloadmanager.h.
Referenced by error(), init(), DownloadManager::load(), metaDataChanged(), saveFileName(), and tryAgain().
The documentation for this class was generated from the following files:
src/downloadmanager.h
src/downloadmanager.cpp