Endorphin: SearchLineEdit Class Reference
SearchLineEdit Class Reference
#include <searchlineedit.h>
Public Member Functions
SearchLineEdit (QWidget *parent=nullptr)
ClearButton * clearButton () const
SearchButton * searchButton () const
Public Member Functions inherited from LineEdit
LineEdit (QWidget *parent=nullptr)
LineEdit (const QString &contents, QWidget *parent=nullptr)
void addWidget (QWidget *widget, WidgetPosition position)
void removeWidget (QWidget *widget)
void setWidgetSpacing (int spacing)
int widgetSpacing () const
int textMargin (WidgetPosition position) const
QString inactiveText () const
void setInactiveText (const QString &text)
void paintEvent (QPaintEvent *event)
Private Member Functions
void init ()
Private Attributes
ClearButton * m_clearButton
SearchButton * m_searchButton
Additional Inherited Members
Public Types inherited from LineEdit
enum WidgetPosition { LeftSide, RightSide }
Protected Slots inherited from LineEdit
void updateTextMargins ()
Protected Member Functions inherited from LineEdit
void resizeEvent (QResizeEvent *event)
bool event (QEvent *event)
Properties inherited from LineEdit
QString inactiveText
Detailed Description
Definition at line 36 of file searchlineedit.h.
Constructor & Destructor Documentation
SearchLineEdit()
SearchLineEdit::SearchLineEdit (QWidget * parent = nullptr)
Copyright (c) 2009, Aaron Dewes
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Endorphin nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS `‘AS IS’' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 34 of file searchlineedit.cpp.
     : LineEdit(parent)
 {
     init();
 }
References init().
Member Function Documentation
clearButton()
ClearButton * SearchLineEdit::clearButton () const
Definition at line 59 of file searchlineedit.cpp.
 {
     return m_clearButton;
 }
References m_clearButton.
init()
void SearchLineEdit::init () private
Definition at line 40 of file searchlineedit.cpp.
 {
     // search button on the left
     m_searchButton = new SearchButton(this);
     addWidget(m_searchButton, LeftSide);
     // clear button on the right
     m_clearButton = new ClearButton(this);
     connect(m_clearButton, SIGNAL(clicked()),
             this, SLOT(clear()));
     connect(this, SIGNAL(textChanged(const QString&)),
             m_clearButton, SLOT(textChanged(const QString&)));
     addWidget(m_clearButton, RightSide);
     m_clearButton->hide();
     updateTextMargins();
     setInactiveText(tr("Search"));
 }
References LineEdit::addWidget(), LineEdit::LeftSide, m_clearButton, m_searchButton, LineEdit::RightSide, LineEdit::setInactiveText(), and LineEdit::updateTextMargins().
Referenced by SearchLineEdit().
searchButton()
SearchButton * SearchLineEdit::searchButton () const
Definition at line 64 of file searchlineedit.cpp.
 {
     return m_searchButton;
 }
References m_searchButton.
Referenced by ToolbarSearch::showEnginesMenu(), and ToolbarSearch::ToolbarSearch().
Member Data Documentation
m_clearButton
ClearButton* SearchLineEdit::m_clearButton private
Definition at line 48 of file searchlineedit.h.
Referenced by clearButton(), and init().
m_searchButton
SearchButton* SearchLineEdit::m_searchButton private
Definition at line 49 of file searchlineedit.h.
Referenced by init(), and searchButton().
The documentation for this class was generated from the following files:
src/searchlineedit.h
src/searchlineedit.cpp