Endorphin: LineEdit Class Reference
LineEdit Class Reference
#include <lineedit.h>
Public Types
enum WidgetPosition { LeftSide, RightSide }
Public Member Functions
LineEdit (QWidget *parent=nullptr)
LineEdit (const QString &contents, QWidget *parent=nullptr)
void addWidget (QWidget *widget, WidgetPosition position)
void removeWidget (QWidget *widget)
void setWidgetSpacing (int spacing)
int widgetSpacing () const
int textMargin (WidgetPosition position) const
QString inactiveText () const
void setInactiveText (const QString &text)
void paintEvent (QPaintEvent *event)
Protected Slots
void updateTextMargins ()
Protected Member Functions
void resizeEvent (QResizeEvent *event)
bool event (QEvent *event)
Properties
QString inactiveText
Private Member Functions
void init ()
void updateSideWidgetLocations ()
Private Attributes
SideWidget * m_leftWidget
SideWidget * m_rightWidget
QHBoxLayout * m_leftLayout
QHBoxLayout * m_rightLayout
QString m_inactiveText
Detailed Description
Definition at line 47 of file lineedit.h.
Member Enumeration Documentation
WidgetPosition
enum LineEdit::WidgetPosition
Enumerator
LeftSide
RightSide
Definition at line 53 of file lineedit.h.
{
         LeftSide,
         RightSide
     };
Constructor & Destructor Documentation
LineEdit() [1/2]
LineEdit::LineEdit (QWidget * parent = nullptr)
Definition at line 51 of file lineedit.cpp.
     : QLineEdit(parent)
     , m_leftLayout(nullptr)
     , m_rightLayout(nullptr)
 {
     init();
 }
References init().
LineEdit() [2/2]
LineEdit::LineEdit (const QString & contents, QWidget * parent = nullptr)
Definition at line 59 of file lineedit.cpp.
     : QLineEdit(contents, parent)
     , m_leftWidget(nullptr)
     , m_rightWidget(nullptr)
     , m_leftLayout(nullptr)
     , m_rightLayout(nullptr)
 {
     init();
 }
References init().
Member Function Documentation
addWidget()
void LineEdit::addWidget (QWidget * widget, WidgetPosition position)
Definition at line 114 of file lineedit.cpp.
 {
     if (!widget)
         return;
     bool rtl = isRightToLeft();
     if (rtl)
         position = (position == LeftSide) ? RightSide : LeftSide;
     if (position == LeftSide) {
         m_leftLayout->addWidget(widget);
     } else {
         m_rightLayout->insertWidget(1, widget);
     }
 }
References LeftSide, m_leftLayout, m_rightLayout, and RightSide.
Referenced by SearchLineEdit::init(), and LocationBar::LocationBar().
event()
bool LineEdit::event (QEvent * event) protected
Definition at line 100 of file lineedit.cpp.
 {
     if (event->type() == QEvent::LayoutDirectionChange) {
         if (isRightToLeft()) {
             m_leftLayout->setDirection(QBoxLayout::RightToLeft);
             m_rightLayout->setDirection(QBoxLayout::RightToLeft);
         } else {
             m_leftLayout->setDirection(QBoxLayout::LeftToRight);
             m_rightLayout->setDirection(QBoxLayout::LeftToRight);
         }
     }
     return QLineEdit::event(event);
 }
References m_leftLayout, and m_rightLayout.
Referenced by ToolbarSearch::changeEvent(), LocationBar::dragEnterEvent(), LocationBar::dropEvent(), ToolbarSearch::focusInEvent(), LocationBar::focusOutEvent(), LocationBar::keyPressEvent(), LocationBar::mouseDoubleClickEvent(), LocationBar::paintEvent(), paintEvent(), and resizeEvent().
inactiveText()
QString LineEdit::inactiveText () const
Definition at line 205 of file lineedit.cpp.
 {
     return m_inactiveText;
 }
References m_inactiveText.
init()
void LineEdit::init () private
Definition at line 69 of file lineedit.cpp.
 {
     m_leftWidget = new SideWidget(this);
     m_leftWidget->resize(0, 0);
     m_leftLayout = new QHBoxLayout(m_leftWidget);
     m_leftLayout->setContentsMargins(0, 0, 0, 0);
     if (isRightToLeft())
         m_leftLayout->setDirection(QBoxLayout::RightToLeft);
     else
         m_leftLayout->setDirection(QBoxLayout::LeftToRight);
     m_leftLayout->setSizeConstraint(QLayout::SetFixedSize);
     m_rightWidget = new SideWidget(this);
     m_rightWidget->resize(0, 0);
     m_rightLayout = new QHBoxLayout(m_rightWidget);
     if (isRightToLeft())
         m_rightLayout->setDirection(QBoxLayout::RightToLeft);
     else
         m_rightLayout->setDirection(QBoxLayout::LeftToRight);
     m_rightLayout->setContentsMargins(0, 0, 0, 0);
     QSpacerItem *horizontalSpacer = new QSpacerItem(0, 0, QSizePolicy::Expanding, QSizePolicy::Minimum);
     m_rightLayout->addItem(horizontalSpacer);
     setWidgetSpacing(3);
     connect(m_leftWidget, SIGNAL(sizeHintChanged()),
             this, SLOT(updateTextMargins()));
     connect(m_rightWidget, SIGNAL(sizeHintChanged()),
             this, SLOT(updateTextMargins()));
 }
References m_leftLayout, m_leftWidget, m_rightLayout, m_rightWidget, setWidgetSpacing(), and updateTextMargins().
Referenced by LineEdit().
paintEvent()
void LineEdit::paintEvent (QPaintEvent * event)
Definition at line 215 of file lineedit.cpp.
 {
     QLineEdit::paintEvent(event);
     if (text().isEmpty() && !m_inactiveText.isEmpty() && !hasFocus()) {
         QStyleOptionFrame panel;
         initStyleOption(&panel);
         QRect textRect = style()->subElementRect(QStyle::SE_LineEditContents, &panel, this);
         int horizontalMargin = 2;
         textRect.adjust(horizontalMargin, 0, 0, 0);
         int left = textMargin(LineEdit::LeftSide);
         int right = textMargin(LineEdit::RightSide);
         textRect.adjust(left, 0, -right, 0);
         QPainter painter(this);
         painter.setPen(palette().brush(QPalette::Disabled, QPalette::Text).color());
         painter.drawText(textRect, Qt::AlignLeft | Qt::AlignVCenter, m_inactiveText);
     }
 }
References event(), LeftSide, m_inactiveText, RightSide, and textMargin().
Referenced by LocationBar::paintEvent().
removeWidget()
void LineEdit::removeWidget (QWidget * widget)
Definition at line 129 of file lineedit.cpp.
 {
     if (!widget)
         return;
     m_leftLayout->removeWidget(widget);
     m_rightLayout->removeWidget(widget);
     widget->hide();
 }
References m_leftLayout, and m_rightLayout.
resizeEvent()
void LineEdit::resizeEvent (QResizeEvent * event) protected
Definition at line 199 of file lineedit.cpp.
 {
     updateSideWidgetLocations();
     QLineEdit::resizeEvent(event);
 }
References event(), and updateSideWidgetLocations().
setInactiveText()
void LineEdit::setInactiveText (const QString & text)
Definition at line 210 of file lineedit.cpp.
 {
     m_inactiveText = text;
 }
References m_inactiveText.
Referenced by ToolbarSearch::currentEngineChanged(), and SearchLineEdit::init().
setWidgetSpacing()
void LineEdit::setWidgetSpacing (int spacing)
Definition at line 139 of file lineedit.cpp.
 {
     m_leftLayout->setSpacing(spacing);
     m_rightLayout->setSpacing(spacing);
     updateTextMargins();
 }
References m_leftLayout, m_rightLayout, and updateTextMargins().
Referenced by init().
textMargin()
int LineEdit::textMargin (WidgetPosition position) const
Definition at line 151 of file lineedit.cpp.
 {
     int spacing = m_rightLayout->spacing();
     int w = 0;
     if (position == LeftSide)
         w = m_leftWidget->sizeHint().width();
     else
         w = m_rightWidget->sizeHint().width();
     if (w == 0)
         return 0;
     return w + spacing * 2;
 }
References LeftSide, m_leftWidget, m_rightLayout, and m_rightWidget.
Referenced by paintEvent(), updateSideWidgetLocations(), and updateTextMargins().
updateSideWidgetLocations()
void LineEdit::updateSideWidgetLocations () private
Definition at line 174 of file lineedit.cpp.
 {
     QStyleOptionFrame opt;
     initStyleOption(&opt);
     QRect textRect = style()->subElementRect(QStyle::SE_LineEditContents, &opt, this);
     int spacing = m_rightLayout->spacing();
     textRect.adjust(spacing, 0, -spacing, 0);
     int left = textMargin(LineEdit::LeftSide);
     int midHeight = textRect.center().y() + 1;
     if (m_leftLayout->count() > 0) {
         int leftHeight = midHeight - m_leftWidget->height() / 2;
         int leftWidth = m_leftWidget->width();
         if (leftWidth == 0)
             leftHeight = midHeight - m_leftWidget->sizeHint().height() / 2;
         m_leftWidget->move(textRect.x(), leftHeight);
     }
     textRect.setX(left);
     textRect.setY(midHeight - m_rightWidget->sizeHint().height() / 2);
     textRect.setHeight(m_rightWidget->sizeHint().height());
     m_rightWidget->setGeometry(textRect);
 }
References LeftSide, m_leftLayout, m_leftWidget, m_rightLayout, m_rightWidget, and textMargin().
Referenced by resizeEvent(), and updateTextMargins().
updateTextMargins
void LineEdit::updateTextMargins () protected slot
Definition at line 164 of file lineedit.cpp.
 {
     int left = textMargin(LineEdit::LeftSide);
     int right = textMargin(LineEdit::RightSide);
     int top = 0;
     int bottom = 0;
     setTextMargins(left, top, right, bottom);
     updateSideWidgetLocations();
 }
References LeftSide, RightSide, textMargin(), and updateSideWidgetLocations().
Referenced by SearchLineEdit::init(), init(), LocationBar::LocationBar(), and setWidgetSpacing().
widgetSpacing()
int LineEdit::widgetSpacing () const
Definition at line 146 of file lineedit.cpp.
 {
     return m_leftLayout->spacing();
 }
References m_leftLayout.
Member Data Documentation
m_inactiveText
QString LineEdit::m_inactiveText private
Definition at line 86 of file lineedit.h.
Referenced by inactiveText(), paintEvent(), and setInactiveText().
m_leftLayout
QHBoxLayout* LineEdit::m_leftLayout private
Definition at line 84 of file lineedit.h.
Referenced by addWidget(), event(), init(), removeWidget(), setWidgetSpacing(), updateSideWidgetLocations(), and widgetSpacing().
m_leftWidget
SideWidget* LineEdit::m_leftWidget private
Definition at line 82 of file lineedit.h.
Referenced by init(), textMargin(), and updateSideWidgetLocations().
m_rightLayout
QHBoxLayout* LineEdit::m_rightLayout private
Definition at line 85 of file lineedit.h.
Referenced by addWidget(), event(), init(), removeWidget(), setWidgetSpacing(), textMargin(), and updateSideWidgetLocations().
m_rightWidget
SideWidget* LineEdit::m_rightWidget private
Definition at line 83 of file lineedit.h.
Referenced by init(), textMargin(), and updateSideWidgetLocations().
Property Documentation
inactiveText
QString LineEdit::inactiveText read write
Definition at line 1 of file lineedit.h.
The documentation for this class was generated from the following files:
src/utils/lineedit.h
src/utils/lineedit.cpp