Endorphin: PermissionBar Class Reference
PermissionBar Class Reference
#include <permissionbar.h>
Signals
void featurePermissionProvided (const QUrl &securityOrigin, QWebEnginePage::Feature, QWebEnginePage::PermissionPolicy)
Public Member Functions
PermissionBar (QWidget *)
void requestPermission (const QUrl &, QWebEnginePage::Feature feature)
Private Slots
void permissionDenied ()
void permissionGranted ()
void permissionUnknown ()
Private Attributes
QWebEnginePage::Feature m_feature
QLabel * m_messageLabel
QUrl m_securityOrigin
Detailed Description
Definition at line 62 of file permissionbar.h.
Constructor & Destructor Documentation
PermissionBar()
PermissionBar::PermissionBar (QWidget * view)
Definition at line 82 of file permissionbar.cpp.
     : QWidget(view)
     , m_messageLabel(new QLabel(this))
 {
     setAutoFillBackground(true);
     QHBoxLayout *l = new QHBoxLayout;
     setLayout(l);
     l->setContentsMargins(defaultHeight, 0, 0, 0);
     l->addWidget(m_messageLabel);
     l->addStretch();
     QPushButton *allowButton = new QPushButton(tr("Allow"), this);
     QPushButton *denyButton = new QPushButton(tr("Deny"), this);
     QPushButton *discardButton = new QPushButton(QIcon(QStringLiteral(":closetab.png")), QString(), this);
     connect(allowButton, &QPushButton::clicked, this, &PermissionBar::permissionGranted);
     connect(denyButton, &QPushButton::clicked, this, &PermissionBar::permissionDenied);
     connect(discardButton, &QPushButton::clicked, this, &PermissionBar::permissionUnknown);
     connect(allowButton, &QPushButton::clicked, this, &QObject::deleteLater);
     connect(denyButton, &QPushButton::clicked, this, &QObject::deleteLater);
     connect(discardButton, &QPushButton::clicked, this, &QObject::deleteLater);
     l->addWidget(denyButton);
     l->addWidget(allowButton);
     l->addWidget(discardButton);
     setGeometry(0, -defaultHeight, view->width(), defaultHeight);
 }
References defaultHeight, m_messageLabel, permissionDenied(), permissionGranted(), and permissionUnknown().
Member Function Documentation
featurePermissionProvided
void PermissionBar::featurePermissionProvided (const QUrl & securityOrigin, QWebEnginePage::Feature , QWebEnginePage::PermissionPolicy) signal
Referenced by WebView::onFeaturePermissionRequested(), permissionDenied(), permissionGranted(), and permissionUnknown().
permissionDenied
void PermissionBar::permissionDenied () private slot
Definition at line 124 of file permissionbar.cpp.
 {
     emit featurePermissionProvided(m_securityOrigin, m_feature, QWebEnginePage::PermissionDeniedByUser);
 }
References featurePermissionProvided(), m_feature, and m_securityOrigin.
Referenced by PermissionBar().
permissionGranted
void PermissionBar::permissionGranted () private slot
Definition at line 129 of file permissionbar.cpp.
 {
     emit featurePermissionProvided(m_securityOrigin, m_feature, QWebEnginePage::PermissionGrantedByUser);
 }
References featurePermissionProvided(), m_feature, and m_securityOrigin.
Referenced by PermissionBar().
permissionUnknown
void PermissionBar::permissionUnknown () private slot
Definition at line 134 of file permissionbar.cpp.
 {
     emit featurePermissionProvided(m_securityOrigin, m_feature, QWebEnginePage::PermissionUnknown);
 }
References featurePermissionProvided(), m_feature, and m_securityOrigin.
Referenced by PermissionBar().
requestPermission()
void PermissionBar::requestPermission (const QUrl & securityOrigin, QWebEnginePage::Feature feature)
Definition at line 107 of file permissionbar.cpp.
 {
     m_securityOrigin = securityOrigin;
     m_feature = feature;
     m_messageLabel->setText(tr("%1 wants to %2.").arg(securityOrigin.host()).arg(textForPermissionType(feature)));
     show();
     // Ease in
     QPropertyAnimation *animation = new QPropertyAnimation(this);
     animation->setTargetObject(this);
     animation->setPropertyName(QByteArrayLiteral("pos"));
     animation->setDuration(300);
     animation->setStartValue(QVariant::fromValue(pos()));
     animation->setEndValue(QVariant::fromValue(QPoint(0,0)));
     animation->setEasingCurve(QEasingCurve::InOutQuad);
     animation->start(QPropertyAnimation::DeleteWhenStopped);
 }
References m_feature, m_messageLabel, m_securityOrigin, and textForPermissionType().
Referenced by WebView::onFeaturePermissionRequested().
Member Data Documentation
m_feature
QWebEnginePage::Feature PermissionBar::m_feature private
Definition at line 78 of file permissionbar.h.
Referenced by permissionDenied(), permissionGranted(), permissionUnknown(), and requestPermission().
m_messageLabel
QLabel* PermissionBar::m_messageLabel private
Definition at line 79 of file permissionbar.h.
Referenced by PermissionBar(), and requestPermission().
m_securityOrigin
QUrl PermissionBar::m_securityOrigin private
Definition at line 80 of file permissionbar.h.
Referenced by permissionDenied(), permissionGranted(), permissionUnknown(), and requestPermission().
The documentation for this class was generated from the following files:
src/permissionbar.h
src/permissionbar.cpp