Endorphin: WebPage Class Reference
WebPage Class Reference
#include <webpage.h>
Signals
void aboutToLoadUrl (const QUrl &url)
Public Member Functions
WebPage (QObject *parent=nullptr)
~WebPage ()
void loadSettings ()
Static Public Member Functions
static QString userAgent ()
static void setUserAgent (const QString &userAgent)
Protected Member Functions
QString userAgentForUrl (const QUrl &url) const
bool acceptNavigationRequest (const QUrl &url, QWebEnginePage::NavigationType type, bool isMainFrame)
QWebEnginePage * createWindow (QWebEnginePage::WebWindowType type)
Protected Attributes
TabWidget::OpenUrlIn m_openTargetBlankLinksIn
QUrl m_requestedUrl
Static Protected Attributes
static QString s_userAgent
Private Attributes
QNetworkRequest lastRequest
QWebEnginePage::NavigationType lastRequestType
Detailed Description
Definition at line 41 of file webpage.h.
Constructor & Destructor Documentation
WebPage()
WebPage::WebPage (QObject * parent = nullptr)
Definition at line 46 of file webpage.cpp.
     : QWebEnginePage(parent)
     , m_openTargetBlankLinksIn(TabWidget::NewWindow)
 {
     loadSettings();
 }
References loadSettings().
~WebPage()
WebPage::~WebPage ()
Definition at line 53 of file webpage.cpp.
 {
 }
Member Function Documentation
aboutToLoadUrl
void WebPage::aboutToLoadUrl (const QUrl & url) signal
Referenced by acceptNavigationRequest().
acceptNavigationRequest()
bool WebPage::acceptNavigationRequest (const QUrl & url, QWebEnginePage::NavigationType type, bool isMainFrame) protected
Definition at line 121 of file webpage.cpp.
 {
     /*
         lastRequest = request;
         lastRequestType = type;
     */
     QString scheme = url.scheme();
     if (scheme == QLatin1String("mailto")
             || scheme == QLatin1String("ftp")) {
         BrowserApplication::instance()->askDesktopToOpenUrl(url);
         return false;
     }
     /*
         if (type == QWebEnginePage::NavigationTypeFormResubmitted) {
             QMessageBox::StandardButton button = QMessageBox::warning(view(), tr("Resending POST request"),
                                  tr("In order to display the site, the request along with all the data must be sent once again, "
                                     "which may lead to some unexpected behaviour of the site e.g. the same action might be "
                                     "performed once again. Do you want to continue anyway?"), QMessageBox::Yes | QMessageBox::No);
             if (button != QMessageBox::Yes)
                 return false;
         }
     */
     TabWidget::OpenUrlIn openIn =  isMainFrame ? TabWidget::CurrentTab : TabWidget::NewWindow;
     openIn = TabWidget::modifyWithUserBehavior(openIn);
     // handle the case where we want to do something different then
     // what QWebEnginePage would do
     if (openIn == TabWidget::NewSelectedTab
             || openIn == TabWidget::NewNotSelectedTab
             || (openIn == TabWidget::NewWindow)) {
         if (WebView *webView = qobject_cast<WebView*>(view())) {
             TabWidget *tabWidget = webView->tabWidget();
             if (tabWidget) {
                 WebView *newView = tabWidget->getView(openIn, webView);
                 QWebEnginePage *page = nullptr;
                 if (newView)
                     page = newView->page();
                 if (page)
                     page->load(url);
             }
         }
         return false;
     }
     bool accepted = QWebEnginePage::acceptNavigationRequest(url, type, isMainFrame);
     if (accepted &&  isMainFrame) {
         m_requestedUrl = url;
         emit aboutToLoadUrl(url);
     }
     return accepted;
 }
References aboutToLoadUrl(), BrowserApplication::askDesktopToOpenUrl(), TabWidget::CurrentTab, TabWidget::getView(), BrowserApplication::instance(), m_requestedUrl, TabWidget::modifyWithUserBehavior(), TabWidget::NewNotSelectedTab, TabWidget::NewSelectedTab, and TabWidget::NewWindow.
createWindow()
QWebEnginePage * WebPage::createWindow (QWebEnginePage::WebWindowType type) protected
Definition at line 184 of file webpage.cpp.
 {
     Q_UNUSED(type);
     if (WebView *webView = qobject_cast<WebView*>(view())) {
         TabWidget *tabWidget = webView->tabWidget();
         if (tabWidget) {
             TabWidget::OpenUrlIn openIn = m_openTargetBlankLinksIn;
             openIn = TabWidget::modifyWithUserBehavior(openIn);
             return tabWidget->getView(openIn, webView)->page();
         }
     }
     return nullptr;
 }
References TabWidget::getView(), m_openTargetBlankLinksIn, and TabWidget::modifyWithUserBehavior().
loadSettings()
void WebPage::loadSettings ()
Definition at line 174 of file webpage.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("tabs"));
     m_openTargetBlankLinksIn = (TabWidget::OpenUrlIn)settings.value(QLatin1String("openTargetBlankLinksIn"),
                                TabWidget::NewSelectedTab).toInt();
     settings.endGroup();
     s_userAgent = settings.value(QLatin1String("userAgent")).toString();
 }
References m_openTargetBlankLinksIn, TabWidget::NewSelectedTab, and s_userAgent.
Referenced by WebView::loadSettings(), and WebPage().
setUserAgent()
void WebPage::setUserAgent (const QString & userAgent) static
Definition at line 93 of file webpage.cpp.
 {
     if (userAgent == s_userAgent)
         return;
     QSettings settings;
     if (userAgent.isEmpty()) {
         settings.remove(QLatin1String("userAgent"));
     } else {
         settings.setValue(QLatin1String("userAgent"), userAgent);
     }
     s_userAgent = userAgent;
 }
References s_userAgent, and userAgent().
Referenced by UserAgentMenu::changeUserAgent(), UserAgentMenu::switchToDefaultUserAgent(), and UserAgentMenu::switchToOtherUserAgent().
userAgent()
QString WebPage::userAgent () static
Definition at line 88 of file webpage.cpp.
 {
     return s_userAgent;
 }
References s_userAgent.
Referenced by UserAgentMenu::addActionsFromFile(), setUserAgent(), and UserAgentMenu::switchToOtherUserAgent().
userAgentForUrl()
QString WebPage::userAgentForUrl (const QUrl & url) const protected
Definition at line 108 of file webpage.cpp.
 {
     if (s_userAgent.isEmpty())
         //s_userAgent = QWebEnginePage::userAgentForUrl(url);
         s_userAgent = "";
     return s_userAgent;
 }
References s_userAgent.
Member Data Documentation
lastRequest
QNetworkRequest WebPage::lastRequest private
Definition at line 74 of file webpage.h.
lastRequestType
QWebEnginePage::NavigationType WebPage::lastRequestType private
Definition at line 75 of file webpage.h.
m_openTargetBlankLinksIn
TabWidget::OpenUrlIn WebPage::m_openTargetBlankLinksIn protected
Definition at line 70 of file webpage.h.
Referenced by createWindow(), and loadSettings().
m_requestedUrl
QUrl WebPage::m_requestedUrl protected
Definition at line 71 of file webpage.h.
Referenced by acceptNavigationRequest().
s_userAgent
QString WebPage::s_userAgent static protected
Definition at line 69 of file webpage.h.
Referenced by loadSettings(), setUserAgent(), userAgent(), and userAgentForUrl().
The documentation for this class was generated from the following files:
src/webpage.h
src/webpage.cpp