Endorphin: OpenSearchReader Class Reference
OpenSearchReader Class Reference
A class reading a search engine description from an external source.
#include <opensearchreader.h>
Public Member Functions
OpenSearchReader ()
OpenSearchEngine * read (QIODevice *device)
Private Member Functions
OpenSearchEngine * read ()
Detailed Description
A class reading a search engine description from an external source.
OpenSearchReader is a class that can be used to read search engine descriptions formed using the OpenSearch format.
It inherits QXmlStreamReader and thus provides additional functions, such as QXmlStreamReader::error(), QXmlStreamReader::hasError() that can be used to make sure the reading procedure succeeded.
For more information see: http://www.opensearch.org/Specifications/OpenSearch/1.1/Draft_4#OpenSearch_description_document
See also
OpenSearchEngine, OpenSearchWriter
Definition at line 27 of file opensearchreader.h.
Constructor & Destructor Documentation
OpenSearchReader()
OpenSearchReader::OpenSearchReader ()
Constructs a new reader.
Note
One instance can be used to read multiple files, one by one.
Definition at line 48 of file opensearchreader.cpp.
     : QXmlStreamReader()
 {
 }
Member Function Documentation
read() [1/2]
OpenSearchEngine * OpenSearchReader::read () private
Definition at line 80 of file opensearchreader.cpp.
 {
     OpenSearchEngine *engine = new OpenSearchEngine();
     while (!isStartElement() && !atEnd())
         readNext();
     if (name() != QLatin1String("OpenSearchDescription")
             || namespaceUri() != QLatin1String("http://a9.com/-/spec/opensearch/1.1/")) {
         raiseError(QObject::tr("The file is not an OpenSearch 1.1 file."));
         return engine;
     }
     while (!atEnd()) {
         readNext();
         if (!isStartElement())
             continue;
         if (name() == QLatin1String("ShortName")) {
             engine->setName(readElementText());
         } else if (name() == QLatin1String("Description")) {
             engine->setDescription(readElementText());
         } else if (name() == QLatin1String("Url")) {
             QString type = attributes().value(QLatin1String("type")).toString();
             QString url = attributes().value(QLatin1String("template")).toString();
             QString method = attributes().value(QLatin1String("method")).toString();
             if (type == QLatin1String("application/x-suggestions+json")
                     && !engine->suggestionsUrlTemplate().isEmpty())
                 continue;
             if ((type.isEmpty()
                     || type == QLatin1String("text/html")
                     || type == QLatin1String("application/xhtml+xml"))
                     && !engine->searchUrlTemplate().isEmpty())
                 continue;
             if (url.isEmpty())
                 continue;
             QList<OpenSearchEngine::Parameter> parameters;
             readNext();
             while (!(isEndElement() && name() == QLatin1String("Url"))) {
                 if (!isStartElement() || (name() != QLatin1String("Param") && name() != QLatin1String("Parameter"))) {
                     readNext();
                     continue;
                 }
                 QString key = attributes().value(QLatin1String("name")).toString();
                 QString value = attributes().value(QLatin1String("value")).toString();
                 if (!key.isEmpty() && !value.isEmpty())
                     parameters.append(OpenSearchEngine::Parameter(key, value));
                 while (!isEndElement())
                     readNext();
             }
             if (type == QLatin1String("application/x-suggestions+json")) {
                 engine->setSuggestionsUrlTemplate(url);
                 engine->setSuggestionsParameters(parameters);
                 engine->setSuggestionsMethod(method);
             } else if (type.isEmpty() || type == QLatin1String("text/html") || type == QLatin1String("application/xhtml+xml")) {
                 engine->setSearchUrlTemplate(url);
                 engine->setSearchParameters(parameters);
                 engine->setSearchMethod(method);
             }
         } else if (name() == QLatin1String("Image")) {
             engine->setImageUrl(readElementText());
         }
         if (!engine->name().isEmpty()
                 && !engine->description().isEmpty()
                 && !engine->suggestionsUrlTemplate().isEmpty()
                 && !engine->searchUrlTemplate().isEmpty()
                 && !engine->imageUrl().isEmpty())
             break;
     }
     return engine;
 }
References OpenSearchEngine::description, OpenSearchEngine::imageUrl, OpenSearchEngine::name, OpenSearchEngine::searchUrlTemplate, OpenSearchEngine::setDescription(), OpenSearchEngine::setImageUrl(), OpenSearchEngine::setName(), OpenSearchEngine::setSearchMethod(), OpenSearchEngine::setSearchParameters(), OpenSearchEngine::setSearchUrlTemplate(), OpenSearchEngine::setSuggestionsMethod(), OpenSearchEngine::setSuggestionsParameters(), OpenSearchEngine::setSuggestionsUrlTemplate(), and OpenSearchEngine::suggestionsUrlTemplate.
Referenced by read().
read() [2/2]
OpenSearchEngine * OpenSearchReader::read (QIODevice * device)
Reads an OpenSearch engine from the device and returns an OpenSearchEngine object, filled in with all the data that has been retrieved from the document.
If the device is closed, it will be opened.
To make sure if the procedure succeeded, check QXmlStreamReader::error().
Returns
a new constructed OpenSearchEngine object
Note
The function returns an object of the OpenSearchEngine class even if the document is bad formed or doesn't conform to the specification. It needs to be manually deleted afterwards, if intended.
The lifetime of the returned OpenSearchEngine object is up to the user. The object should be deleted once it is not used anymore to avoid memory leaks.
Definition at line 69 of file opensearchreader.cpp.
 {
     clear();
     if (!device->isOpen())
         device->open(QIODevice::ReadOnly);
     setDevice(device);
     return read();
 }
References read().
Referenced by OpenSearchManager::addEngine(), and OpenSearchManager::engineFromUrlAvailable().
The documentation for this class was generated from the following files:
src/opensearch/opensearchreader.h
src/opensearch/opensearchreader.cpp