Endorphin: BookmarksMenuBarMenu Class Reference
BookmarksMenuBarMenu Class Reference
#include <bookmarksmenu.h>
Public Member Functions
BookmarksMenuBarMenu (QWidget *parent=nullptr)
void setInitialActions (QList< QAction * > actions)
Public Member Functions inherited from BookmarksMenu
BookmarksMenu (QWidget *parent=nullptr)
Public Member Functions inherited from ModelMenu
ModelMenu (QWidget *parent=nullptr)
void setModel (QAbstractItemModel *model)
QAbstractItemModel * model () const
void setMaxRows (int max)
int maxRows () const
void setFirstSeparator (int offset)
int firstSeparator () const
void setRootIndex (const QModelIndex &index)
QModelIndex rootIndex () const
void setStatusBarTextRole (int role)
int statusBarTextRole () const
void setSeparatorRole (int role)
int separatorRole () const
QAction * makeAction (const QIcon &icon, const QString &text, QObject *parent)
QModelIndex index (QAction *action)
Protected Member Functions
bool prePopulated ()
Protected Member Functions inherited from BookmarksMenu
void postPopulated ()
ModelMenu * createBaseMenu ()
Protected Member Functions inherited from ModelMenu
void createMenu (const QModelIndex &parent, int max, QMenu *parentMenu=nullptr, QMenu *menu=nullptr)
void dragEnterEvent (QDragEnterEvent *event)
void dropEvent (QDropEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
Private Attributes
BookmarksManager * m_bookmarksManager
QList< QAction * > m_initialActions
Additional Inherited Members
Signals inherited from BookmarksMenu
void openUrl (const QUrl &url, const QString &title)
void openUrl (const QUrl &url, TabWidget::OpenUrlIn tab, const QString &title)
Signals inherited from ModelMenu
void activated (const QModelIndex &index)
Detailed Description
Definition at line 98 of file bookmarksmenu.h.
Constructor & Destructor Documentation
BookmarksMenuBarMenu()
BookmarksMenuBarMenu::BookmarksMenuBarMenu (QWidget * parent = nullptr)
Definition at line 148 of file bookmarksmenu.cpp.
     : BookmarksMenu(parent)
     , m_bookmarksManager(nullptr)
 {
 }
Member Function Documentation
prePopulated()
bool BookmarksMenuBarMenu::prePopulated () protected virtual
Reimplemented from ModelMenu.
Definition at line 154 of file bookmarksmenu.cpp.
 {
 #ifndef NO_BROWSERAPPLICATION
     m_bookmarksManager = BrowserApplication::bookmarksManager();
 #else
     #ifdef FOR_AUTOTEST
     m_bookmarksManager = tst_AddBookmarkDialog::bookmarksManager();
     #else
         #error "Nothing provides a bookmarksmanager"
     #endif
 #endif
     setModel(m_bookmarksManager->bookmarksModel());
     setRootIndex(m_bookmarksManager->bookmarksModel()->index(m_bookmarksManager->menu()));
     // initial actions
     for (int i = 0; i < m_initialActions.count(); ++i)
         addAction(m_initialActions.at(i));
     if (!m_initialActions.isEmpty())
         addSeparator();
     createMenu(m_bookmarksManager->bookmarksModel()->index(m_bookmarksManager->toolbar()), 1, this);
     return true;
 }
References BrowserApplication::bookmarksManager(), BookmarksManager::bookmarksModel(), ModelMenu::createMenu(), BookmarksModel::index(), m_bookmarksManager, m_initialActions, BookmarksManager::menu(), ModelMenu::setModel(), ModelMenu::setRootIndex(), and BookmarksManager::toolbar().
setInitialActions()
void BookmarksMenuBarMenu::setInitialActions (QList< QAction * > actions)
Definition at line 176 of file bookmarksmenu.cpp.
 {
     m_initialActions = actions;
     for (int i = 0; i < m_initialActions.count(); ++i)
         addAction(m_initialActions.at(i));
 }
References m_initialActions.
Referenced by BrowserMainWindow::setupMenu().
Member Data Documentation
m_bookmarksManager
BookmarksManager* BookmarksMenuBarMenu::m_bookmarksManager private
Definition at line 110 of file bookmarksmenu.h.
Referenced by prePopulated().
m_initialActions
QList<QAction*> BookmarksMenuBarMenu::m_initialActions private
Definition at line 111 of file bookmarksmenu.h.
Referenced by prePopulated(), and setInitialActions().
The documentation for this class was generated from the following files:
src/bookmarks/bookmarksmenu.h
src/bookmarks/bookmarksmenu.cpp