Endorphin: HistoryCompletionModel Class Reference
HistoryCompletionModel Class Reference
#include <historycompleter.h>
Public Types
enum Roles { HistoryCompletionRole = HistoryFilterModel::MaxRole + 1 }
Public Member Functions
HistoryCompletionModel (QObject *parent=nullptr)
QString searchString () const
void setSearchString (const QString &str)
bool isValid () const
void setValid (bool b)
virtual QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Protected Member Functions
virtual bool filterAcceptsRow (int source_row, const QModelIndex &source_parent) const
virtual bool lessThan (const QModelIndex &left, const QModelIndex &right) const
Properties
QString searchString
Private Attributes
QString m_searchString
QRegExp m_searchMatcher
QRegExp m_wordMatcher
bool m_isValid
Detailed Description
Definition at line 55 of file historycompleter.h.
Member Enumeration Documentation
Roles
enum HistoryCompletionModel::Roles
Enumerator
HistoryCompletionRole
Definition at line 63 of file historycompleter.h.
 { HistoryCompletionRole = HistoryFilterModel::MaxRole + 1 };
Constructor & Destructor Documentation
HistoryCompletionModel()
HistoryCompletionModel::HistoryCompletionModel (QObject * parent = nullptr)
Definition at line 60 of file historycompleter.cpp.
     : QSortFilterProxyModel(parent)
     , m_searchMatcher(QString(), Qt::CaseInsensitive, QRegExp::FixedString)
     , m_wordMatcher(QString(), Qt::CaseInsensitive)
     , m_isValid(false)
 {
     setDynamicSortFilter(true);
 }
Member Function Documentation
data()
QVariant HistoryCompletionModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Definition at line 69 of file historycompleter.cpp.
 {
     // if we are valid, tell QCompleter that everything we have filtered matches
     // what the user typed; if not, nothing matches
     if (role == HistoryCompletionRole && index.isValid()) {
         if (isValid())
             return QLatin1String("a");
         else
             return QLatin1String("b");
     }
     if (role == Qt::FontRole && index.column() == 1) {
         QFont font = qvariant_cast<QFont>(QSortFilterProxyModel::data(index, role));
         font.setWeight(QFont::Light);
         return font;
     }
     if (role == Qt::DisplayRole)
         role = (index.column() == 0) ? HistoryModel::UrlStringRole : HistoryModel::TitleRole;
     return QSortFilterProxyModel::data(index, role);
 }
References HistoryCompletionRole, isValid(), HistoryModel::TitleRole, and HistoryModel::UrlStringRole.
filterAcceptsRow()
bool HistoryCompletionModel::filterAcceptsRow (int source_row, const QModelIndex & source_parent) const protected virtual
Definition at line 124 of file historycompleter.cpp.
 {
     // do a case-insensitive substring match against both the url and title;
     // we have also made sure that the user doesn't accidentally use regexp
     // metacharacters
     QModelIndex idx = sourceModel()->index(source_row, 0, source_parent);
     QString url = sourceModel()->data(idx, HistoryModel::UrlStringRole).toString();
     if (m_searchMatcher.indexIn(url) != -1)
         return true;
     QString title = sourceModel()->data(idx, HistoryModel::TitleRole).toString();
     if (m_searchMatcher.indexIn(title) != -1)
         return true;
     return false;
 }
References m_searchMatcher, HistoryModel::TitleRole, and HistoryModel::UrlStringRole.
isValid()
bool HistoryCompletionModel::isValid () const
Definition at line 108 of file historycompleter.cpp.
 {
     return m_isValid;
 }
References m_isValid.
Referenced by data().
lessThan()
bool HistoryCompletionModel::lessThan (const QModelIndex & left, const QModelIndex & right) const protected virtual
Definition at line 143 of file historycompleter.cpp.
 {
     // We give a bonus to hits that match on a word boundary so that e.g. "dot.kde.org"
     // is a better result for typing "dot" than "slashdot.org". However, we only look
     // for the string in the host name, not the entire url, since while it makes sense
     // to e.g. give "www.phoronix.com" a bonus for "ph", it does _not_ make sense to
     // give "www.yadda.com/foo.php" the bonus.
     int frecency_l = sourceModel()->data(left, HistoryFilterModel::FrecencyRole).toInt();
     QString url_l = sourceModel()->data(left, HistoryModel::UrlRole).toUrl().host();
     QString title_l = sourceModel()->data(left, HistoryModel::TitleRole).toString();
     if (m_wordMatcher.indexIn(url_l) != -1 || m_wordMatcher.indexIn(title_l) != -1)
         frecency_l *= 2;
     int frecency_r = sourceModel()->data(right, HistoryFilterModel::FrecencyRole).toInt();
     QString url_r = sourceModel()->data(right, HistoryModel::UrlRole).toUrl().host();
     QString title_r = sourceModel()->data(right, HistoryModel::TitleRole).toString();
     if (m_wordMatcher.indexIn(url_r) != -1 || m_wordMatcher.indexIn(title_r) != -1)
         frecency_r *= 2;
     // sort results in descending frecency-derived score
     return (frecency_r < frecency_l);
 }
References HistoryFilterModel::FrecencyRole, m_wordMatcher, HistoryModel::TitleRole, and HistoryModel::UrlRole.
searchString()
QString HistoryCompletionModel::searchString () const
Definition at line 92 of file historycompleter.cpp.
 {
     return m_searchString;
 }
References m_searchString.
setSearchString()
void HistoryCompletionModel::setSearchString (const QString & str)
Definition at line 97 of file historycompleter.cpp.
 {
     if (str == m_searchString)
         return;
     m_searchString = str;
     m_searchMatcher.setPattern(str);
     m_wordMatcher.setPattern(QLatin1String("\\b") + QRegExp::escape(str));
     invalidateFilter();
 }
References m_searchMatcher, m_searchString, and m_wordMatcher.
Referenced by HistoryCompleter::updateFilter().
setValid()
void HistoryCompletionModel::setValid (bool b)
Definition at line 113 of file historycompleter.cpp.
 {
     if (b == m_isValid)
         return;
     m_isValid = b;
     // tell the HistoryCompleter that we've changed
     emit dataChanged(index(0, 0), index(0, rowCount() - 1));
 }
References m_isValid.
Referenced by HistoryCompleter::splitPath(), and HistoryCompleter::updateFilter().
Member Data Documentation
m_isValid
bool HistoryCompletionModel::m_isValid private
Definition at line 81 of file historycompleter.h.
Referenced by isValid(), and setValid().
m_searchMatcher
QRegExp HistoryCompletionModel::m_searchMatcher private
Definition at line 79 of file historycompleter.h.
Referenced by filterAcceptsRow(), and setSearchString().
m_searchString
QString HistoryCompletionModel::m_searchString private
Definition at line 78 of file historycompleter.h.
Referenced by searchString(), and setSearchString().
m_wordMatcher
QRegExp HistoryCompletionModel::m_wordMatcher private
Definition at line 80 of file historycompleter.h.
Referenced by lessThan(), and setSearchString().
Property Documentation
searchString
QString HistoryCompletionModel::searchString read write
Definition at line 40 of file historycompleter.h.
The documentation for this class was generated from the following files:
src/history/historycompleter.h
src/history/historycompleter.cpp