Endorphin: BookmarksManager Class Reference
BookmarksManager Class Reference
#include <bookmarksmanager.h>
Public Slots
void importBookmarks ()
void exportBookmarks ()
Signals
void entryAdded (BookmarkNode *item)
void entryRemoved (BookmarkNode *parent, int row, BookmarkNode *item)
void entryChanged (BookmarkNode *item)
Public Member Functions
BookmarksManager (QObject *parent=nullptr)
~BookmarksManager ()
void addBookmark (BookmarkNode *parent, BookmarkNode *node, int row=-1)
void removeBookmark (BookmarkNode *node)
void setTitle (BookmarkNode *node, const QString &newTitle)
void setUrl (BookmarkNode *node, const QString &newUrl)
void changeExpanded ()
void retranslate () const
BookmarkNode * bookmarks ()
BookmarkNode * menu ()
BookmarkNode * toolbar ()
BookmarksModel * bookmarksModel ()
QUndoStack * undoRedoStack ()
Private Slots
void save () const
Private Member Functions
void load ()
Private Attributes
bool m_loaded
AutoSaver * m_saveTimer
BookmarkNode * m_bookmarkRootNode
BookmarkNode * m_toolbar
BookmarkNode * m_menu
BookmarksModel * m_bookmarkModel
QUndoStack m_commands
Friends
class RemoveBookmarksCommand
class ChangeBookmarkCommand
Detailed Description
Definition at line 32 of file bookmarksmanager.h.
Constructor & Destructor Documentation
BookmarksManager()
BookmarksManager::BookmarksManager (QObject * parent = nullptr)
Definition at line 92 of file bookmarksmanager.cpp.
     : QObject(parent)
     , m_loaded(false)
     , m_saveTimer(new AutoSaver(this))
     , m_bookmarkRootNode(nullptr)
     , m_toolbar(nullptr)
     , m_menu(nullptr)
     , m_bookmarkModel(nullptr)
 {
     connect(this, SIGNAL(entryAdded(BookmarkNode *)),
             m_saveTimer, SLOT(changeOccurred()));
     connect(this, SIGNAL(entryRemoved(BookmarkNode *, int, BookmarkNode *)),
             m_saveTimer, SLOT(changeOccurred()));
     connect(this, SIGNAL(entryChanged(BookmarkNode *)),
             m_saveTimer, SLOT(changeOccurred()));
 }
References entryAdded(), entryChanged(), entryRemoved(), and m_saveTimer.
~BookmarksManager()
BookmarksManager::~BookmarksManager ()
Definition at line 109 of file bookmarksmanager.cpp.
 {
     m_saveTimer->saveIfNeccessary();
     delete m_bookmarkRootNode;
 }
References m_bookmarkRootNode, m_saveTimer, and AutoSaver::saveIfNeccessary().
Member Function Documentation
addBookmark()
void BookmarksManager::addBookmark (BookmarkNode * parent, BookmarkNode * node, int row = -1)
Definition at line 206 of file bookmarksmanager.cpp.
 {
     if (!m_loaded)
         return;
     Q_ASSERT(parent);
     InsertBookmarksCommand *command = new InsertBookmarksCommand(this, parent, node, row);
     m_commands.push(command);
 }
References m_commands, and m_loaded.
Referenced by AddBookmarkDialog::accept(), TabWidget::bookmarkTabs(), BookmarksModel::dropMimeData(), importBookmarks(), and BookmarksDialog::newFolder().
bookmarks()
BookmarkNode * BookmarksManager::bookmarks ()
Definition at line 247 of file bookmarksmanager.cpp.
 {
     if (!m_loaded)
         load();
     return m_bookmarkRootNode;
 }
References load(), m_bookmarkRootNode, and m_loaded.
Referenced by BookmarksDialog::BookmarksDialog(), BookmarksModel::node(), BookmarksModel::parent(), and BookmarksModel::rowCount().
bookmarksModel()
BookmarksModel * BookmarksManager::bookmarksModel ()
Definition at line 272 of file bookmarksmanager.cpp.
 {
     if (!m_bookmarkModel)
         m_bookmarkModel = new BookmarksModel(this, this);
     return m_bookmarkModel;
 }
References m_bookmarkModel.
Referenced by AddBookmarkDialog::accept(), BrowserMainWindow::addBookmark(), AddBookmarkDialog::AddBookmarkDialog(), BrowserMainWindow::addBookmarkFolder(), BookmarksDialog::BookmarksDialog(), BrowserMainWindow::BrowserMainWindow(), BookmarksDialog::newFolder(), and BookmarksMenuBarMenu::prePopulated().
changeExpanded()
void BookmarksManager::changeExpanded ()
Definition at line 115 of file bookmarksmanager.cpp.
 {
     m_saveTimer->changeOccurred();
 }
References AutoSaver::changeOccurred(), and m_saveTimer.
Referenced by BookmarksDialog::~BookmarksDialog().
entryAdded
void BookmarksManager::entryAdded (BookmarkNode * item) signal
Referenced by BookmarksManager(), and RemoveBookmarksCommand::undo().
entryChanged
void BookmarksManager::entryChanged (BookmarkNode * item) signal
Referenced by BookmarksManager(), ChangeBookmarkCommand::redo(), and ChangeBookmarkCommand::undo().
entryRemoved
void BookmarksManager::entryRemoved (BookmarkNode * parent, int row, BookmarkNode * item) signal
Referenced by BookmarksManager(), and RemoveBookmarksCommand::redo().
exportBookmarks
void BookmarksManager::exportBookmarks () slot
Definition at line 327 of file bookmarksmanager.cpp.
 {
     QString fileName = QFileDialog::getSaveFileName(nullptr, tr("Save File"),
                        tr("%1 Bookmarks.xbel").arg(QCoreApplication::applicationName()),
                        tr("XBEL bookmarks").append(QLatin1String("(*.xbel *.xml)")));
     if (fileName.isEmpty())
         return;
     XbelWriter writer;
     if (!writer.write(fileName, m_bookmarkRootNode))
         QMessageBox::critical(nullptr, tr("Export error"), tr("error saving bookmarks"));
 }
References m_bookmarkRootNode, and XbelWriter::write().
importBookmarks
void BookmarksManager::importBookmarks () slot
Definition at line 279 of file bookmarksmanager.cpp.
 {
     QStringList supportedFormats;
     supportedFormats << tr("XBEL bookmarks").append(QLatin1String("(*.xbel *.xml)"));
     supportedFormats << tr("HTML Netscape bookmarks").append(QLatin1String("(*.html)"));
     QString fileName = QFileDialog::getOpenFileName(nullptr, tr("Open File"),
                        QString(), supportedFormats.join(QLatin1String(";;")));
     if (fileName.isEmpty())
         return;
     XbelReader reader;
     BookmarkNode *importRootNode = nullptr;
     if (fileName.endsWith(QLatin1String(".html"))) {
         QString program = QLatin1String("htmlToXBel");
         QStringList arguments;
         arguments << fileName;
         QProcess process;
         process.start(program, arguments);
         process.waitForFinished(-1);
         if (process.error() != QProcess::UnknownError) {
             if (process.error() == QProcess::FailedToStart) {
                 QMessageBox::warning(nullptr, tr("htmlToXBel tool required"),
                                      tr("htmlToXBel tool, which is shipped with Endorphin and is needed to import HTML bookmarks, "
                                         "is not installed or not available in the search paths."));
             } else {
                 QMessageBox::warning(nullptr, tr("Loading Bookmark"),
                                      tr("Error when loading HTML bookmarks: %1\n").arg(process.errorString()));
             }
             return;
         }
         importRootNode = reader.read(&process);
     } else {
         importRootNode = reader.read(fileName);
     }
     if (reader.error() != QXmlStreamReader::NoError) {
         QMessageBox::warning(nullptr, QLatin1String("Loading Bookmark"),
                              tr("Error when loading bookmarks on line %1, column %2:\n"
                                 "%3").arg(reader.lineNumber()).arg(reader.columnNumber()).arg(reader.errorString()));
         delete importRootNode;
         return;
     }
     importRootNode->setType(BookmarkNode::Folder);
     importRootNode->title = (tr("Imported %1").arg(QDate::currentDate().toString(Qt::SystemLocaleShortDate)));
     addBookmark(menu(), importRootNode);
 }
References addBookmark(), BookmarkNode::Folder, menu(), XbelReader::read(), BookmarkNode::setType(), and BookmarkNode::title.
load()
void BookmarksManager::load () private
Definition at line 120 of file bookmarksmanager.cpp.
 {
     if (m_loaded)
         return;
     m_loaded = true;
     QString dir = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation) + "/data/Endorphin";
     QString bookmarkFile = dir + QLatin1String("/bookmarks.xbel");
     if (!QFile::exists(bookmarkFile))
         bookmarkFile = QLatin1String(":defaultbookmarks.xbel");
     XbelReader reader;
     m_bookmarkRootNode = reader.read(bookmarkFile);
     if (reader.error() != QXmlStreamReader::NoError) {
         QMessageBox::warning(nullptr, QLatin1String("Loading Bookmark"),
                              tr("Error when loading bookmarks on line %1, column %2:\n"
                                 "%3").arg(reader.lineNumber()).arg(reader.columnNumber()).arg(reader.errorString()));
     }
     QList<BookmarkNode*> others;
     for (int i = m_bookmarkRootNode->children().count() - 1; i >= 0; --i) {
         BookmarkNode *node = m_bookmarkRootNode->children().at(i);
         if (node->type() == BookmarkNode::Folder) {
             // Automatically convert
             if ((node->title == tr("Toolbar Bookmarks")
                     || node->title == QLatin1String(BOOKMARKBAR)) && !m_toolbar) {
                 node->title = tr(BOOKMARKBAR);
                 m_toolbar = node;
             }
             // Automatically convert
             if ((node->title == tr("Menu")
                     || node->title == QLatin1String(BOOKMARKMENU)) && !m_menu) {
                 node->title = tr(BOOKMARKMENU);
                 m_menu = node;
             }
         } else {
             others.append(node);
         }
         m_bookmarkRootNode->remove(node);
     }
     Q_ASSERT(m_bookmarkRootNode->children().count() == 0);
     if (!m_toolbar) {
         m_toolbar = new BookmarkNode(BookmarkNode::Folder, m_bookmarkRootNode);
         m_toolbar->title = tr(BOOKMARKBAR);
     } else {
         m_bookmarkRootNode->add(m_toolbar);
     }
     if (!m_menu) {
         m_menu = new BookmarkNode(BookmarkNode::Folder, m_bookmarkRootNode);
         m_menu->title = tr(BOOKMARKMENU);
     } else {
         m_bookmarkRootNode->add(m_menu);
     }
     for (int i = 0; i < others.count(); ++i)
         m_menu->add(others.at(i));
 }
References BookmarkNode::add(), BOOKMARKBAR, BOOKMARKMENU, BookmarkNode::children(), BookmarkNode::Folder, m_bookmarkRootNode, m_loaded, m_menu, m_toolbar, XbelReader::read(), BookmarkNode::remove(), BookmarkNode::title, and BookmarkNode::type().
Referenced by bookmarks(), menu(), and toolbar().
menu()
BookmarkNode * BookmarksManager::menu ()
Definition at line 254 of file bookmarksmanager.cpp.
 {
     if (!m_loaded)
         load();
     Q_ASSERT(m_menu);
     return m_menu;
 }
References load(), m_loaded, and m_menu.
Referenced by BrowserMainWindow::addBookmark(), BrowserMainWindow::addBookmarkFolder(), BookmarksModel::flags(), importBookmarks(), BookmarksMenuBarMenu::prePopulated(), and BookmarksModel::removeRows().
removeBookmark()
void BookmarksManager::removeBookmark (BookmarkNode * node)
Definition at line 215 of file bookmarksmanager.cpp.
 {
     if (!m_loaded)
         return;
     Q_ASSERT(node);
     BookmarkNode *parent = node->parent();
     int row = parent->children().indexOf(node);
     RemoveBookmarksCommand *command = new RemoveBookmarksCommand(this, parent, row);
     m_commands.push(command);
 }
References BookmarkNode::children(), m_commands, m_loaded, BookmarkNode::parent(), and RemoveBookmarksCommand.
Referenced by BookmarksModel::removeRows().
retranslate()
void BookmarksManager::retranslate () const
Definition at line 198 of file bookmarksmanager.cpp.
 {
     if (m_menu)
         m_menu->title = tr(BOOKMARKMENU);
     if (m_toolbar)
         m_toolbar->title = tr(BOOKMARKBAR);
 }
References BOOKMARKBAR, BOOKMARKMENU, m_menu, m_toolbar, and BookmarkNode::title.
Referenced by BrowserApplication::retranslate(), and save().
save
void BookmarksManager::save () const private slot
Definition at line 181 of file bookmarksmanager.cpp.
 {
     if (!m_loaded)
         return;
     XbelWriter writer;
     QString dir = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation) + "/data/Endorphin";
     QString bookmarkFile = dir + QLatin1String("/bookmarks.xbel");
     // Save root folder titles in English (i.e. not localized)
     m_menu->title = QLatin1String(BOOKMARKMENU);
     m_toolbar->title = QLatin1String(BOOKMARKBAR);
     if (!writer.write(bookmarkFile, m_bookmarkRootNode))
         qWarning() << "BookmarkManager: error saving to" << bookmarkFile;
     // Restore localized titles
     retranslate();
 }
References BOOKMARKBAR, BOOKMARKMENU, m_bookmarkRootNode, m_loaded, m_menu, m_toolbar, retranslate(), BookmarkNode::title, and XbelWriter::write().
setTitle()
void BookmarksManager::setTitle (BookmarkNode * node, const QString & newTitle)
Definition at line 227 of file bookmarksmanager.cpp.
 {
     if (!m_loaded)
         return;
     Q_ASSERT(node);
     ChangeBookmarkCommand *command = new ChangeBookmarkCommand(this, node, newTitle, true);
     m_commands.push(command);
 }
References ChangeBookmarkCommand, m_commands, and m_loaded.
Referenced by BookmarksModel::setData().
setUrl()
void BookmarksManager::setUrl (BookmarkNode * node, const QString & newUrl)
Definition at line 237 of file bookmarksmanager.cpp.
 {
     if (!m_loaded)
         return;
     Q_ASSERT(node);
     ChangeBookmarkCommand *command = new ChangeBookmarkCommand(this, node, newUrl, false);
     m_commands.push(command);
 }
References ChangeBookmarkCommand, m_commands, and m_loaded.
Referenced by BookmarksModel::setData().
toolbar()
BookmarkNode * BookmarksManager::toolbar ()
Definition at line 263 of file bookmarksmanager.cpp.
 {
     if (!m_loaded)
         load();
     Q_ASSERT(m_toolbar);
     return m_toolbar;
 }
References load(), m_loaded, and m_toolbar.
Referenced by BookmarksToolBar::BookmarksToolBar(), BookmarksModel::flags(), BookmarksMenuBarMenu::prePopulated(), and BookmarksModel::removeRows().
undoRedoStack()
QUndoStack* BookmarksManager::undoRedoStack () inline
Definition at line 57 of file bookmarksmanager.h.
{
         return &m_commands;
     }
References m_commands.
Referenced by BookmarksModel::dropMimeData(), and BookmarksModel::removeRows().
Friends And Related Function Documentation
ChangeBookmarkCommand
friend class ChangeBookmarkCommand friend
Definition at line 80 of file bookmarksmanager.h.
Referenced by setTitle(), and setUrl().
RemoveBookmarksCommand
friend class RemoveBookmarksCommand friend
Definition at line 79 of file bookmarksmanager.h.
Referenced by removeBookmark().
Member Data Documentation
m_bookmarkModel
BookmarksModel* BookmarksManager::m_bookmarkModel private
Definition at line 76 of file bookmarksmanager.h.
Referenced by bookmarksModel().
m_bookmarkRootNode
BookmarkNode* BookmarksManager::m_bookmarkRootNode private
Definition at line 73 of file bookmarksmanager.h.
Referenced by bookmarks(), exportBookmarks(), load(), save(), and ~BookmarksManager().
m_commands
QUndoStack BookmarksManager::m_commands private
Definition at line 77 of file bookmarksmanager.h.
Referenced by addBookmark(), removeBookmark(), setTitle(), setUrl(), and undoRedoStack().
m_loaded
bool BookmarksManager::m_loaded private
Definition at line 71 of file bookmarksmanager.h.
Referenced by addBookmark(), bookmarks(), load(), menu(), removeBookmark(), save(), setTitle(), setUrl(), and toolbar().
m_menu
BookmarkNode* BookmarksManager::m_menu private
Definition at line 75 of file bookmarksmanager.h.
Referenced by load(), menu(), retranslate(), and save().
m_saveTimer
AutoSaver* BookmarksManager::m_saveTimer private
Definition at line 72 of file bookmarksmanager.h.
Referenced by BookmarksManager(), changeExpanded(), and ~BookmarksManager().
m_toolbar
BookmarkNode* BookmarksManager::m_toolbar private
Definition at line 74 of file bookmarksmanager.h.
Referenced by load(), retranslate(), save(), and toolbar().
The documentation for this class was generated from the following files:
src/bookmarks/bookmarksmanager.h
src/bookmarks/bookmarksmanager.cpp