Endorphin: RemoveBookmarksCommand Class Reference
RemoveBookmarksCommand Class Reference
#include <bookmarksmanager.h>
Public Member Functions
RemoveBookmarksCommand (BookmarksManager *m_bookmarkManagaer, BookmarkNode *parent, int row)
~RemoveBookmarksCommand ()
void undo ()
void redo ()
Protected Attributes
int m_row
BookmarksManager * m_bookmarkManagaer
BookmarkNode * m_node
BookmarkNode * m_parent
bool m_done
Detailed Description
Definition at line 83 of file bookmarksmanager.h.
Constructor & Destructor Documentation
RemoveBookmarksCommand()
RemoveBookmarksCommand::RemoveBookmarksCommand (BookmarksManager * m_bookmarkManagaer, BookmarkNode * parent, int row)
Definition at line 340 of file bookmarksmanager.cpp.
     : QUndoCommand(BookmarksManager::tr("Remove Bookmark"))
     , m_row(row)
     , m_bookmarkManagaer(m_bookmarkManagaer)
     , m_node(parent->children().value(row))
     , m_parent(parent)
     , m_done(false)
 {
 }
~RemoveBookmarksCommand()
RemoveBookmarksCommand::~RemoveBookmarksCommand ()
Definition at line 350 of file bookmarksmanager.cpp.
 {
     if (m_done && !m_node->parent()) {
         delete m_node;
     }
 }
References m_done, m_node, and BookmarkNode::parent().
Member Function Documentation
redo()
void RemoveBookmarksCommand::redo ()
Definition at line 364 of file bookmarksmanager.cpp.
 {
     m_parent->remove(m_node);
     emit m_bookmarkManagaer->entryRemoved(m_parent, m_row, m_node);
     m_done = true;
 }
References BookmarksManager::entryRemoved(), m_bookmarkManagaer, m_done, m_node, m_parent, m_row, and BookmarkNode::remove().
Referenced by InsertBookmarksCommand::undo().
undo()
void RemoveBookmarksCommand::undo ()
Definition at line 357 of file bookmarksmanager.cpp.
 {
     m_parent->add(m_node, m_row);
     emit m_bookmarkManagaer->entryAdded(m_node);
     m_done = false;
 }
References BookmarkNode::add(), BookmarksManager::entryAdded(), m_bookmarkManagaer, m_done, m_node, m_parent, and m_row.
Referenced by InsertBookmarksCommand::redo().
Member Data Documentation
m_bookmarkManagaer
BookmarksManager* RemoveBookmarksCommand::m_bookmarkManagaer protected
Definition at line 94 of file bookmarksmanager.h.
Referenced by redo(), and undo().
m_done
bool RemoveBookmarksCommand::m_done protected
Definition at line 97 of file bookmarksmanager.h.
Referenced by redo(), undo(), and ~RemoveBookmarksCommand().
m_node
BookmarkNode* RemoveBookmarksCommand::m_node protected
Definition at line 95 of file bookmarksmanager.h.
Referenced by InsertBookmarksCommand::InsertBookmarksCommand(), redo(), undo(), and ~RemoveBookmarksCommand().
m_parent
BookmarkNode* RemoveBookmarksCommand::m_parent protected
Definition at line 96 of file bookmarksmanager.h.
Referenced by redo(), and undo().
m_row
int RemoveBookmarksCommand::m_row protected
Definition at line 93 of file bookmarksmanager.h.
Referenced by redo(), and undo().
The documentation for this class was generated from the following files:
src/bookmarks/bookmarksmanager.h
src/bookmarks/bookmarksmanager.cpp