Endorphin: AboutDialog Class Reference
AboutDialog Class Reference
#include <aboutdialog.h>
Public Member Functions
AboutDialog (QWidget *parent=nullptr)
Private Slots
void authorsButtonClicked ()
void licenseButtonClicked ()
Private Member Functions
void displayFile (const QString &fileName, const QString &title)
Detailed Description
Definition at line 26 of file aboutdialog.h.
Constructor & Destructor Documentation
AboutDialog()
AboutDialog::AboutDialog (QWidget * parent = nullptr)
Definition at line 30 of file aboutdialog.cpp.
     : QDialog(parent)
 {
     setupUi(this);
     setWindowTitle(tr("About %1").arg(qApp->applicationName()));
     logo->setPixmap(qApp->windowIcon().pixmap(128, 128));
     name->setText(qApp->applicationName());
     version->setText(qApp->applicationVersion());
     connect(authorsButton, SIGNAL(clicked()),
             this, SLOT(authorsButtonClicked()));
     connect(licenseButton, SIGNAL(clicked()),
             this, SLOT(licenseButtonClicked()));
 }
References authorsButtonClicked(), and licenseButtonClicked().
Member Function Documentation
authorsButtonClicked
void AboutDialog::authorsButtonClicked () private slot
Definition at line 77 of file aboutdialog.cpp.
 {
     displayFile(QLatin1String(":AUTHORS"), tr("Authors"));
 }
References displayFile().
Referenced by AboutDialog().
displayFile()
void AboutDialog::displayFile (const QString & fileName, const QString & title) private
Definition at line 44 of file aboutdialog.cpp.
 {
     QDialog dialog(this);
     QVBoxLayout layout(&dialog);
     QTextEdit textEdit(&dialog);
     QDialogButtonBox buttonBox(QDialogButtonBox::Close, Qt::Horizontal, &dialog);
     textEdit.setLayoutDirection(Qt::LeftToRight);
     QFile file(fileName);
     if (!file.open(QIODevice::ReadOnly))
         return;
     QTextStream stream(&file);
     stream.setCodec("UTF-8");
     QString text = stream.readAll();
     // this is done to force the content of the text editor to be LTR, and monospaced.
     textEdit.setHtml(QString(QLatin1String("<pre>%1</pre>")).arg(text));
     textEdit.setReadOnly(true);
     connect(&buttonBox, SIGNAL(rejected()), &dialog, SLOT(close()));
     buttonBox.setCenterButtons(true);
     layout.addWidget(&textEdit);
     layout.addWidget(&buttonBox);
     layout.setMargin(6);
     dialog.setLayout(&layout);
     dialog.setWindowTitle(title);
     dialog.setWindowFlags(Qt::Sheet);
     dialog.resize(600, 350);
     dialog.exec();
 }
Referenced by authorsButtonClicked(), and licenseButtonClicked().
licenseButtonClicked
void AboutDialog::licenseButtonClicked () private slot
Definition at line 82 of file aboutdialog.cpp.
 {
     displayFile(QLatin1String(":LICENSE.GPL2"), tr("License"));
 }
References displayFile().
Referenced by AboutDialog().
The documentation for this class was generated from the following files:
src/aboutdialog.h
src/aboutdialog.cpp