Endorphin: HistoryMenuModel Class Reference
HistoryMenuModel Class Reference
#include <history.h>
Public Member Functions
HistoryMenuModel (HistoryTreeModel *sourceModel, QObject *parent=nullptr)
int columnCount (const QModelIndex &parent) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
QModelIndex mapFromSource (const QModelIndex &sourceIndex) const
QModelIndex mapToSource (const QModelIndex &proxyIndex) const
QModelIndex index (int, int, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &index=QModelIndex()) const
QMimeData * mimeData (const QModelIndexList &indexes) const
QModelIndex buddy (const QModelIndex &index) const
int bumpedRows () const
Private Attributes
HistoryTreeModel * m_treeModel
Detailed Description
Definition at line 190 of file history.h.
Constructor & Destructor Documentation
HistoryMenuModel()
HistoryMenuModel::HistoryMenuModel (HistoryTreeModel * sourceModel, QObject * parent = nullptr)
Definition at line 211 of file history.cpp.
     : QAbstractProxyModel(parent)
     , m_treeModel(sourceModel)
 {
     setSourceModel(sourceModel);
 }
Member Function Documentation
buddy()
QModelIndex HistoryMenuModel::buddy (const QModelIndex & index) const
Definition at line 257 of file history.cpp.
 {
     return index;
 }
References index().
bumpedRows()
int HistoryMenuModel::bumpedRows () const
Definition at line 218 of file history.cpp.
 {
     QModelIndex first = m_treeModel->index(0, 0);
     if (!first.isValid())
         return 0;
     return qMin(m_treeModel->rowCount(first), MOVEDROWS);
 }
References HistoryTreeModel::index(), m_treeModel, MOVEDROWS, and HistoryTreeModel::rowCount().
Referenced by index(), mapToSource(), parent(), HistoryMenu::prePopulated(), and rowCount().
columnCount()
int HistoryMenuModel::columnCount (const QModelIndex & parent) const
Definition at line 226 of file history.cpp.
 {
     return m_treeModel->columnCount(mapToSource(parent));
 }
References HistoryTreeModel::columnCount(), m_treeModel, mapToSource(), and parent().
Referenced by index().
index()
QModelIndex HistoryMenuModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
Definition at line 289 of file history.cpp.
 {
     if (row < 0
             || column < 0 || column >= columnCount(parent)
             || parent.column() > 0)
         return QModelIndex();
     if (!parent.isValid())
         return createIndex(row, column, -1);
     QModelIndex treeIndexParent = mapToSource(parent);
     int bumpedItems = 0;
     if (treeIndexParent == m_treeModel->index(0, 0))
         bumpedItems = bumpedRows();
     QModelIndex treeIndex = m_treeModel->index(row + bumpedItems, column, treeIndexParent);
     QModelIndex historyIndex = m_treeModel->mapToSource(treeIndex);
     int historyRow = historyIndex.row();
     if (historyRow == -1)
         historyRow = treeIndex.row();
     return createIndex(row, column, historyRow);
 }
References bumpedRows(), columnCount(), HistoryTreeModel::index(), m_treeModel, mapToSource(), HistoryTreeModel::mapToSource(), and parent().
Referenced by buddy(), parent(), and rowCount().
mapFromSource()
QModelIndex HistoryMenuModel::mapFromSource (const QModelIndex & sourceIndex) const
Definition at line 262 of file history.cpp.
 {
     // currently not used or autotested
     Q_ASSERT(false);
     int sr = m_treeModel->mapToSource(sourceIndex).row();
     return createIndex(sourceIndex.row(), sourceIndex.column(), sr);
 }
References m_treeModel, and HistoryTreeModel::mapToSource().
mapToSource()
QModelIndex HistoryMenuModel::mapToSource (const QModelIndex & proxyIndex) const
Definition at line 270 of file history.cpp.
 {
     if (!proxyIndex.isValid())
         return QModelIndex();
     if (proxyIndex.internalId() == -1) {
         int bumpedItems = bumpedRows();
         if (proxyIndex.row() < bumpedItems)
             return m_treeModel->index(proxyIndex.row(), proxyIndex.column(), m_treeModel->index(0, 0));
         if (bumpedItems <= MOVEDROWS && bumpedItems == sourceModel()->rowCount(m_treeModel->index(0, 0)))
             --bumpedItems;
         return m_treeModel->index(proxyIndex.row() - bumpedItems, proxyIndex.column());
     }
     QModelIndex historyIndex = m_treeModel->sourceModel()->index(proxyIndex.internalId(), proxyIndex.column());
     QModelIndex treeIndex = m_treeModel->mapFromSource(historyIndex);
     return treeIndex;
 }
References bumpedRows(), HistoryTreeModel::index(), m_treeModel, HistoryTreeModel::mapFromSource(), MOVEDROWS, and rowCount().
Referenced by columnCount(), index(), and rowCount().
mimeData()
QMimeData * HistoryMenuModel::mimeData (const QModelIndexList & indexes) const
Definition at line 328 of file history.cpp.
 {
     QMimeData *mimeData = new QMimeData;
     QList<QUrl> urls;
     foreach (const QModelIndex &idx, indexes) {
         QUrl url = idx.data(HistoryModel::UrlRole).toUrl();
         urls.append(url);
     }
     mimeData->setUrls(urls);
     return mimeData;
 }
References HistoryModel::UrlRole.
parent()
QModelIndex HistoryMenuModel::parent (const QModelIndex & index = QModelIndex()) const
Definition at line 311 of file history.cpp.
 {
     int offset = index.internalId();
     if (offset == -1 || !index.isValid())
         return QModelIndex();
     QModelIndex historyIndex = m_treeModel->sourceModel()->index(index.internalId(), 0);
     QModelIndex treeIndex = m_treeModel->mapFromSource(historyIndex);
     QModelIndex treeIndexParent = treeIndex.parent();
     int sr = m_treeModel->mapToSource(treeIndexParent).row();
     int bumpedItems = bumpedRows();
     if (bumpedItems <= MOVEDROWS && bumpedItems == sourceModel()->rowCount(sourceModel()->index(0, 0)))
         --bumpedItems;
     return createIndex(bumpedItems + treeIndexParent.row(), treeIndexParent.column(), sr);
 }
References bumpedRows(), index(), HistoryTreeModel::index(), m_treeModel, HistoryTreeModel::mapFromSource(), HistoryTreeModel::mapToSource(), MOVEDROWS, and rowCount().
Referenced by columnCount(), index(), and rowCount().
rowCount()
int HistoryMenuModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 231 of file history.cpp.
 {
     if (parent.column() > 0)
         return 0;
     if (!parent.isValid()) {
         int folders = sourceModel()->rowCount();
         int bumpedItems = bumpedRows();
         if (bumpedItems <= MOVEDROWS
                 && bumpedItems == sourceModel()->rowCount(sourceModel()->index(0, 0)))
             --folders;
         return bumpedItems + folders;
     }
     if (parent.internalId() == -1) {
         if (parent.row() < bumpedRows())
             return 0;
     }
     QModelIndex idx = mapToSource(parent);
     int defaultCount = sourceModel()->rowCount(idx);
     if (idx == sourceModel()->index(0, 0))
         return defaultCount - bumpedRows();
     return defaultCount;
 }
References bumpedRows(), index(), mapToSource(), MOVEDROWS, and parent().
Referenced by mapToSource(), and parent().
Member Data Documentation
m_treeModel
HistoryTreeModel* HistoryMenuModel::m_treeModel private
Definition at line 208 of file history.h.
Referenced by bumpedRows(), columnCount(), index(), mapFromSource(), mapToSource(), and parent().
The documentation for this class was generated from the following files:
src/history/history.h
src/history/history.cpp