Endorphin: PrivacyIndicator Class Reference
PrivacyIndicator Class Reference
#include <privacyindicator.h>
Public Member Functions
PrivacyIndicator (QWidget *parent=nullptr)
Protected Member Functions
void mousePressEvent (QMouseEvent *event)
Detailed Description
Definition at line 25 of file privacyindicator.h.
Constructor & Destructor Documentation
PrivacyIndicator()
PrivacyIndicator::PrivacyIndicator (QWidget * parent = nullptr)
Definition at line 24 of file privacyindicator.cpp.
     : QLabel(parent)
 {
     setPixmap(QPixmap(QLatin1String(":graphics/private.png")));
     connect(BrowserApplication::instance(), SIGNAL(privacyChanged(bool)),
             this, SLOT(setVisible(bool)));
     setCursor(Qt::ArrowCursor);
     setVisible(BrowserApplication::isPrivate());
 }
References BrowserApplication::instance(), and BrowserApplication::isPrivate().
Member Function Documentation
mousePressEvent()
void PrivacyIndicator::mousePressEvent (QMouseEvent * event) protected
Definition at line 34 of file privacyindicator.cpp.
 {
     Q_UNUSED(event)
     BrowserApplication::instance()->setPrivate(false);
 }
References BrowserApplication::instance(), and BrowserApplication::setPrivate().
The documentation for this class was generated from the following files:
src/locationbar/privacyindicator.h
src/locationbar/privacyindicator.cpp