Endorphin: SearchButton Class Reference
SearchButton Class Reference
#include <searchbutton.h>
Public Member Functions
SearchButton (QWidget *parent=nullptr)
void setImage (const QImage &image)
void setShowMenuTriangle (bool show)
bool showMenuTriangle () const
void paintEvent (QPaintEvent *event)
QSize sizeHint () const
Private Member Functions
QImage generateSearchImage (bool dropDown)
Private Attributes
QImage m_cache
bool m_showMenuTriangle
Detailed Description
Definition at line 26 of file searchbutton.h.
Constructor & Destructor Documentation
SearchButton()
SearchButton::SearchButton (QWidget * parent = nullptr)
Definition at line 28 of file searchbutton.cpp.
     : QAbstractButton(parent)
     , m_showMenuTriangle(false)
 {
     setFocusPolicy(Qt::NoFocus);
     setCursor(Qt::ArrowCursor);
     setMinimumSize(sizeHint());
 }
References sizeHint().
Member Function Documentation
generateSearchImage()
QImage SearchButton::generateSearchImage (bool dropDown) private
Definition at line 46 of file searchbutton.cpp.
 {
     QImage image(dropDown ? 16 : 12, 16, QImage::Format_ARGB32);
     image.fill(qRgba(0, 0, 0, 0));
     QPainterPath path;
     // draw magnify glass circle
     int radius = image.height() / 2;
     QRect circle(1, 1, radius, radius);
     path.addEllipse(circle);
     // draw handle
     path.arcMoveTo(circle, 300);
     QPointF currentPosition = path.currentPosition();
     path.moveTo(currentPosition.x() + 1, currentPosition.y() + 1);
     if (dropDown)
         path.lineTo(image.width()-6, image.height()-4);
     else
         path.lineTo(image.width()-2, image.height()-4);
     QPainter painter(&image);
     painter.setRenderHint(QPainter::Antialiasing, true);
     painter.setPen(QPen(Qt::darkGray, 2));
     painter.drawPath(path);
     if (dropDown) {
         // draw the dropdown triangle
         QPainterPath dropPath;
         dropPath.arcMoveTo(circle, 320);
         QPointF currentPosition = dropPath.currentPosition();
         currentPosition = QPointF(currentPosition.x() + 2, currentPosition.y() + 0.5);
         dropPath.moveTo(currentPosition);
         dropPath.lineTo(currentPosition.x() + 4, currentPosition.y());
         dropPath.lineTo(currentPosition.x() + 2, currentPosition.y() + 2);
         dropPath.closeSubpath();
         painter.setPen(Qt::darkGray);
         painter.setBrush(Qt::darkGray);
         painter.setRenderHint(QPainter::Antialiasing, false);
         painter.drawPath(dropPath);
     }
     painter.end();
     return image;
 }
Referenced by paintEvent().
paintEvent()
void SearchButton::paintEvent (QPaintEvent * event)
Definition at line 108 of file searchbutton.cpp.
 {
     Q_UNUSED(event);
     if (m_cache.isNull())
         m_cache = generateSearchImage(m_showMenuTriangle);
     QPainter painter(this);
     painter.drawImage(QPoint(0, 0), m_cache);
 }
References generateSearchImage(), m_cache, and m_showMenuTriangle.
setImage()
void SearchButton::setImage (const QImage & image)
Definition at line 90 of file searchbutton.cpp.
 {
     m_cache = image;
     setMinimumSize(sizeHint());
     update();
 }
References m_cache, and sizeHint().
setShowMenuTriangle()
void SearchButton::setShowMenuTriangle (bool show)
Definition at line 97 of file searchbutton.cpp.
 {
     m_showMenuTriangle = show;
     setMinimumSize(sizeHint());
 }
References m_showMenuTriangle, and sizeHint().
Referenced by ToolbarSearch::ToolbarSearch().
showMenuTriangle()
bool SearchButton::showMenuTriangle () const
Definition at line 103 of file searchbutton.cpp.
 {
     return m_showMenuTriangle;
 }
References m_showMenuTriangle.
sizeHint()
QSize SearchButton::sizeHint () const
Definition at line 37 of file searchbutton.cpp.
 {
     if (!m_cache.isNull())
         return m_cache.size();
     if (m_showMenuTriangle)
         return QSize(16, 16);
     return QSize(12, 16);
 }
References m_cache, and m_showMenuTriangle.
Referenced by SearchButton(), setImage(), and setShowMenuTriangle().
Member Data Documentation
m_cache
QImage SearchButton::m_cache private
Definition at line 40 of file searchbutton.h.
Referenced by paintEvent(), setImage(), and sizeHint().
m_showMenuTriangle
bool SearchButton::m_showMenuTriangle private
Definition at line 41 of file searchbutton.h.
Referenced by paintEvent(), setShowMenuTriangle(), showMenuTriangle(), and sizeHint().
The documentation for this class was generated from the following files:
src/searchbutton.h
src/searchbutton.cpp