Endorphin: OpenSearchManager Class Reference
OpenSearchManager Class Reference
#include <opensearchmanager.h>
Public Slots
void save ()
Signals
void changed ()
void currentEngineChanged ()
Public Member Functions
OpenSearchManager (QObject *parent=nullptr)
~OpenSearchManager ()
QStringList allEnginesNames () const
int enginesCount () const
QString currentEngineName () const
void setCurrentEngineName (const QString &currentName)
OpenSearchEngine * currentEngine () const
void setCurrentEngine (OpenSearchEngine *current)
OpenSearchEngine * engine (const QString &name)
bool engineExists (const QString &name)
QUrl convertKeywordSearchToUrl (const QString &string)
OpenSearchEngine * engineForKeyword (const QString &keyword) const
void setEngineForKeyword (const QString &keyword, OpenSearchEngine *engine)
QStringList keywordsForEngine (OpenSearchEngine *engine) const
void setKeywordsForEngine (OpenSearchEngine *engine, const QStringList &keywords)
void addEngine (const QUrl &url)
bool addEngine (const QString &fileName)
bool addEngine (OpenSearchEngine *engine)
void removeEngine (const QString &name)
void restoreDefaults ()
Protected Slots
void engineFromUrlAvailable ()
Protected Member Functions
void load ()
bool loadDirectory (const QString &dirName)
void saveDirectory (const QString &dirName)
QString enginesDirectory () const
QString generateEngineFileName (const QString &engineName) const
Private Member Functions
bool confirmAddition (OpenSearchEngine *engine)
Private Attributes
AutoSaver * m_autoSaver
QHash< QString, OpenSearchEngine * > m_engines
QHash< QString, OpenSearchEngine * > m_keywords
QString m_current
Detailed Description
Definition at line 38 of file opensearchmanager.h.
Constructor & Destructor Documentation
OpenSearchManager()
OpenSearchManager::OpenSearchManager (QObject * parent = nullptr)
Definition at line 42 of file opensearchmanager.cpp.
     : QObject(parent)
     , m_autoSaver(new AutoSaver(this))
 {
     connect(this, SIGNAL(changed()),
             m_autoSaver, SLOT(changeOccurred()));
     load();
 }
References changed(), load(), and m_autoSaver.
~OpenSearchManager()
OpenSearchManager::~OpenSearchManager ()
Definition at line 52 of file opensearchmanager.cpp.
 {
     m_autoSaver->saveIfNeccessary();
     qDeleteAll(m_engines.values());
     m_engines.clear();
 }
References m_autoSaver, m_engines, and AutoSaver::saveIfNeccessary().
Member Function Documentation
addEngine() [1/3]
bool OpenSearchManager::addEngine (const QString & fileName)
Definition at line 124 of file opensearchmanager.cpp.
 {
     QFile file(fileName);
     if (!file.open(QIODevice::ReadOnly))
         return false;
     OpenSearchReader reader;
     OpenSearchEngine *engine = reader.read(&file);
     if (!addEngine(engine)) {
         delete engine;
         return false;
     }
     return true;
 }
References addEngine(), engine(), and OpenSearchReader::read().
addEngine() [2/3]
void OpenSearchManager::addEngine (const QUrl & url)
Definition at line 113 of file opensearchmanager.cpp.
 {
     if (!url.isValid())
         return;
     QNetworkAccessManager *manager = new QNetworkAccessManager();
     QNetworkReply *reply = manager->get(QNetworkRequest(url));
     connect(reply, SIGNAL(finished()), this, SLOT(engineFromUrlAvailable()));
     reply->setParent(this);
 }
References engineFromUrlAvailable().
Referenced by addEngine(), ToolbarSearch::addEngineFromUrl(), engineFromUrlAvailable(), and loadDirectory().
addEngine() [3/3]
bool OpenSearchManager::addEngine (OpenSearchEngine * engine)
Definition at line 141 of file opensearchmanager.cpp.
 {
     if (!engine)
         return false;
     if (!engine->isValid())
         return false;
     if (m_engines.contains(engine->name()))
         return false;
     m_engines[engine->name()] = engine;
     emit changed();
     return true;
 }
References changed(), engine(), OpenSearchEngine::isValid(), m_engines, and OpenSearchEngine::name.
allEnginesNames()
QStringList OpenSearchManager::allEnginesNames () const
Definition at line 103 of file opensearchmanager.cpp.
 {
     return m_engines.keys();
 }
References m_engines.
Referenced by WebView::contextMenuEvent(), OpenSearchEngineModel::data(), OpenSearchEngineModel::removeRows(), OpenSearchEngineModel::setData(), and ToolbarSearch::showEnginesMenu().
changed
void OpenSearchManager::changed () signal
Referenced by addEngine(), OpenSearchManager(), removeEngine(), setCurrentEngineName(), setEngineForKeyword(), and setKeywordsForEngine().
confirmAddition()
bool OpenSearchManager::confirmAddition (OpenSearchEngine * engine) private
Definition at line 305 of file opensearchmanager.cpp.
 {
     if (!engine || !engine->isValid())
         return false;
     QString host = QUrl(engine->searchUrlTemplate()).host();
     QMessageBox::StandardButton button = QMessageBox::question(nullptr, QString(),
                                          tr("Do you want to add the following engine to your list of search engines?<br /><br />"
                                             "Name: %1<br />Searches on: %2").arg(engine->name(), host),
                                          QMessageBox::Yes | QMessageBox::No, QMessageBox::No);
     return (button == QMessageBox::Yes);
 }
References engine(), OpenSearchEngine::isValid(), OpenSearchEngine::name, and OpenSearchEngine::searchUrlTemplate.
Referenced by engineFromUrlAvailable().
convertKeywordSearchToUrl()
QUrl OpenSearchManager::convertKeywordSearchToUrl (const QString & string)
Definition at line 359 of file opensearchmanager.cpp.
 {
     int i = string.indexOf(QLatin1Char(' '));
     if (i <= 0)
         return QUrl();
     const QString keyword = string.left(i);
     const QString terms = string.mid(i + 1);
     if (terms.isEmpty())
         return QUrl();
     if (OpenSearchEngine *engine = engineForKeyword(keyword))
         return engine->searchUrl(terms);
     return QUrl();
 }
References engine(), engineForKeyword(), and OpenSearchEngine::searchUrl().
Referenced by TabWidget::guessUrlFromString().
currentEngine()
OpenSearchEngine * OpenSearchManager::currentEngine () const
Definition at line 74 of file opensearchmanager.cpp.
 {
     if (m_current.isEmpty() || !m_engines.contains(m_current))
         return nullptr;
     return m_engines[m_current];
 }
References m_current, and m_engines.
Referenced by ToolbarSearch::currentEngineChanged(), ToolbarSearch::getSuggestions(), TabWidget::guessUrlFromString(), and ToolbarSearch::searchNow().
currentEngineChanged
void OpenSearchManager::currentEngineChanged () signal
Referenced by load(), and setCurrentEngineName().
currentEngineName()
QString OpenSearchManager::currentEngineName () const
Definition at line 59 of file opensearchmanager.cpp.
 {
     return m_current;
 }
References m_current.
engine()
OpenSearchEngine * OpenSearchManager::engine (const QString & name)
Definition at line 90 of file opensearchmanager.cpp.
 {
     if (!m_engines.contains(name))
         return nullptr;
     return m_engines[name];
 }
References m_engines.
Referenced by addEngine(), confirmAddition(), WebView::contextMenuEvent(), convertKeywordSearchToUrl(), ToolbarSearch::currentEngineChanged(), OpenSearchEngineModel::data(), engineFromUrlAvailable(), keywordsForEngine(), load(), removeEngine(), saveDirectory(), WebView::searchRequested(), setCurrentEngine(), OpenSearchEngineModel::setData(), setEngineForKeyword(), setKeywordsForEngine(), and ToolbarSearch::showEnginesMenu().
engineExists()
bool OpenSearchManager::engineExists (const QString & name)
Definition at line 98 of file opensearchmanager.cpp.
 {
     return m_engines.contains(name);
 }
References m_engines.
Referenced by engineFromUrlAvailable().
engineForKeyword()
OpenSearchEngine * OpenSearchManager::engineForKeyword (const QString & keyword) const
Definition at line 376 of file opensearchmanager.cpp.
 {
     if (keyword.isEmpty())
         return nullptr;
     if (!m_keywords.contains(keyword))
         return nullptr;
     return m_keywords.value(keyword);
 }
References m_keywords.
Referenced by convertKeywordSearchToUrl().
engineFromUrlAvailable
void OpenSearchManager::engineFromUrlAvailable () protected slot
Definition at line 319 of file opensearchmanager.cpp.
 {
     QNetworkReply *reply = qobject_cast<QNetworkReply*>(sender());
     if (!reply)
         return;
     if (reply->error() != QNetworkReply::NoError) {
         reply->close();
         reply->deleteLater();
         return;
     }
     OpenSearchReader reader;
     OpenSearchEngine *engine = reader.read(reply);
     reply->close();
     reply->deleteLater();
     if (!engine->isValid()) {
         delete engine;
         return;
     }
     if (engineExists(engine->name())) {
         delete engine;
         return;
     }
     if (!confirmAddition(engine)) {
         delete engine;
         return;
     }
     if (!addEngine(engine)) {
         delete engine;
         return;
     }
 }
References addEngine(), confirmAddition(), engine(), engineExists(), OpenSearchEngine::isValid(), OpenSearchEngine::name, and OpenSearchReader::read().
Referenced by addEngine().
enginesCount()
int OpenSearchManager::enginesCount () const
Definition at line 108 of file opensearchmanager.cpp.
 {
     return m_engines.count();
 }
References m_engines.
Referenced by OpenSearchEngineModel::data(), and OpenSearchEngineModel::rowCount().
enginesDirectory()
QString OpenSearchManager::enginesDirectory () const protected
Definition at line 299 of file opensearchmanager.cpp.
 {
     QDir directory(QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation) + "/data/Endorphin");
     return directory.filePath(QLatin1String("searchengines"));
 }
Referenced by load(), removeEngine(), and save().
generateEngineFileName()
QString OpenSearchManager::generateEngineFileName (const QString & engineName) const protected
Definition at line 184 of file opensearchmanager.cpp.
 {
     QString fileName;
     // Strip special characters from the name.
     for (int i = 0; i < engineName.count(); ++i) {
         if (engineName.at(i).isSpace()) {
             fileName.append(QLatin1Char('_'));
             continue;
         }
         if (engineName.at(i).isLetterOrNumber())
             fileName.append(engineName.at(i));
     }
     fileName.append(QLatin1String(".xml"));
     return fileName;
 }
Referenced by removeEngine(), and saveDirectory().
keywordsForEngine()
QStringList OpenSearchManager::keywordsForEngine (OpenSearchEngine * engine) const
Definition at line 398 of file opensearchmanager.cpp.
 {
     return m_keywords.keys(engine);
 }
References engine(), and m_keywords.
Referenced by OpenSearchEngineModel::data(), and setKeywordsForEngine().
load()
void OpenSearchManager::load () protected
Definition at line 267 of file opensearchmanager.cpp.
 {
     if (!loadDirectory(enginesDirectory()))
         loadDirectory(QLatin1String(":/searchengines"));
     // get current engine
     QSettings settings;
     settings.beginGroup(QLatin1String("openSearch"));
     m_current = settings.value(QLatin1String("engine"), QLatin1String("Google")).toString();
     int size = settings.beginReadArray(QLatin1String("keywords"));
     for (int i = 0; i < size; ++i) {
         settings.setArrayIndex(i);
         QString keyword = settings.value(QLatin1String("keyword")).toString();
         QString engineName = settings.value(QLatin1String("engine")).toString();
         m_keywords.insert(keyword, engine(engineName));
     }
     settings.endArray();
     settings.endGroup();
     if (!m_engines.contains(m_current) && m_engines.count() > 0)
         m_current = m_engines.keys().at(0);
     emit currentEngineChanged();
 }
References currentEngineChanged(), engine(), enginesDirectory(), loadDirectory(), m_current, m_engines, and m_keywords.
Referenced by OpenSearchManager().
loadDirectory()
bool OpenSearchManager::loadDirectory (const QString & dirName) protected
Definition at line 247 of file opensearchmanager.cpp.
 {
     if (!QFile::exists(dirName))
         return false;
     QDirIterator iterator(dirName, QStringList() << QLatin1String("*.xml"));
     if (!iterator.hasNext())
         return false;
     bool success = false;
     while (iterator.hasNext()) {
         if (addEngine(iterator.next()))
             success = true;
     }
     return success;
 }
References addEngine().
Referenced by load(), and restoreDefaults().
removeEngine()
void OpenSearchManager::removeEngine (const QString & name)
Definition at line 159 of file opensearchmanager.cpp.
 {
     if (m_engines.count() <= 1)
         return;
     if (!m_engines.contains(name))
         return;
     OpenSearchEngine *engine = m_engines[name];
     foreach (const QString &keyword, m_keywords.keys(engine))
         m_keywords.remove(keyword);
     engine->deleteLater();
     m_engines[name] = 0;
     m_engines.remove(name);
     QString file = QDir(enginesDirectory()).filePath(generateEngineFileName(name));
     QFile::remove(file);
     if (name == m_current)
         setCurrentEngineName(m_engines.keys().at(0));
     emit changed();
 }
References changed(), engine(), enginesDirectory(), generateEngineFileName(), m_current, m_engines, m_keywords, and setCurrentEngineName().
Referenced by OpenSearchEngineModel::removeRows().
restoreDefaults()
void OpenSearchManager::restoreDefaults ()
Definition at line 294 of file opensearchmanager.cpp.
 {
     loadDirectory(QLatin1String(":/searchengines"));
 }
References loadDirectory().
Referenced by OpenSearchDialog::restoreButtonClicked().
save
void OpenSearchManager::save () slot
Definition at line 225 of file opensearchmanager.cpp.
 {
     saveDirectory(enginesDirectory());
     QSettings settings;
     settings.beginGroup(QLatin1String("openSearch"));
     settings.setValue(QLatin1String("engine"), m_current);
     settings.beginWriteArray(QLatin1String("keywords"), m_keywords.count());
     QHash<QString, OpenSearchEngine*>::const_iterator i = m_keywords.constBegin();
     QHash<QString, OpenSearchEngine*>::const_iterator end = m_keywords.constEnd();
     int j = 0;
     for (; i != end; ++i) {
         settings.setArrayIndex(j++);
         settings.setValue(QLatin1String("keyword"), i.key());
         settings.setValue(QLatin1String("engine"), i.value()->name());
     }
     settings.endArray();
     settings.endGroup();
 }
References enginesDirectory(), m_current, m_keywords, and saveDirectory().
saveDirectory()
void OpenSearchManager::saveDirectory (const QString & dirName) protected
Definition at line 204 of file opensearchmanager.cpp.
 {
     QDir dir;
     if (!dir.mkpath(dirName))
         return;
     dir.setPath(dirName);
     OpenSearchWriter writer;
     foreach (OpenSearchEngine *engine, m_engines.values()) {
         QString name = generateEngineFileName(engine->name());
         QString fileName = dir.filePath(name);
         QFile file(fileName);
         if (!file.open(QIODevice::WriteOnly))
             continue;
         writer.write(&file, engine);
     }
 }
References engine(), generateEngineFileName(), m_engines, OpenSearchEngine::name, and OpenSearchWriter::write().
Referenced by save().
setCurrentEngine()
void OpenSearchManager::setCurrentEngine (OpenSearchEngine * current)
Definition at line 82 of file opensearchmanager.cpp.
 {
     if (!engine)
         return;
     setCurrentEngineName(m_engines.key(engine));
 }
References engine(), m_engines, and setCurrentEngineName().
setCurrentEngineName()
void OpenSearchManager::setCurrentEngineName (const QString & currentName)
Definition at line 64 of file opensearchmanager.cpp.
 {
     if (!m_engines.contains(name))
         return;
     m_current = name;
     emit currentEngineChanged();
     emit changed();
 }
References changed(), currentEngineChanged(), m_current, and m_engines.
Referenced by ToolbarSearch::changeCurrentEngine(), removeEngine(), and setCurrentEngine().
setEngineForKeyword()
void OpenSearchManager::setEngineForKeyword (const QString & keyword, OpenSearchEngine * engine)
Definition at line 385 of file opensearchmanager.cpp.
 {
     if (keyword.isEmpty())
         return;
     if (!engine)
         m_keywords.remove(keyword);
     else
         m_keywords.insert(keyword, engine);
     emit changed();
 }
References changed(), engine(), and m_keywords.
setKeywordsForEngine()
void OpenSearchManager::setKeywordsForEngine (OpenSearchEngine * engine, const QStringList & keywords)
Definition at line 403 of file opensearchmanager.cpp.
 {
     if (!engine)
         return;
     foreach (const QString &keyword, keywordsForEngine(engine))
         m_keywords.remove(keyword);
     foreach (const QString &keyword, keywords) {
         if (keyword.isEmpty())
             continue;
         m_keywords.insert(keyword, engine);
     }
     emit changed();
 }
References changed(), engine(), keywordsForEngine(), and m_keywords.
Referenced by OpenSearchEngineModel::setData().
Member Data Documentation
m_autoSaver
AutoSaver* OpenSearchManager::m_autoSaver private
Definition at line 93 of file opensearchmanager.h.
Referenced by OpenSearchManager(), and ~OpenSearchManager().
m_current
QString OpenSearchManager::m_current private
Definition at line 97 of file opensearchmanager.h.
Referenced by currentEngine(), currentEngineName(), load(), removeEngine(), save(), and setCurrentEngineName().
m_engines
QHash<QString, OpenSearchEngine*> OpenSearchManager::m_engines private
Definition at line 95 of file opensearchmanager.h.
Referenced by addEngine(), allEnginesNames(), currentEngine(), engine(), engineExists(), enginesCount(), load(), removeEngine(), saveDirectory(), setCurrentEngine(), setCurrentEngineName(), and ~OpenSearchManager().
m_keywords
QHash<QString, OpenSearchEngine*> OpenSearchManager::m_keywords private
Definition at line 96 of file opensearchmanager.h.
Referenced by engineForKeyword(), keywordsForEngine(), load(), removeEngine(), save(), setEngineForKeyword(), and setKeywordsForEngine().
The documentation for this class was generated from the following files:
src/opensearch/opensearchmanager.h
src/opensearch/opensearchmanager.cpp