Endorphin: BookmarksModel Class Reference
BookmarksModel Class Reference
#include <bookmarksmodel.h>
Public Types
enum Roles { TypeRole = Qt::UserRole + 1, UrlRole = Qt::UserRole + 2, UrlStringRole = Qt::UserRole + 3, SeparatorRole = Qt::UserRole + 4 }
Public Slots
void entryAdded (BookmarkNode *item)
void entryRemoved (BookmarkNode *parent, int row, BookmarkNode *item)
void entryChanged (BookmarkNode *item)
Public Member Functions
BookmarksModel (BookmarksManager *bookmarkManager, QObject *parent=nullptr)
BookmarksManager * bookmarksManager () const
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
int columnCount (const QModelIndex &parent=QModelIndex()) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
QModelIndex index (int, int, const QModelIndex &parent=QModelIndex()) const
QModelIndex parent (const QModelIndex &index=QModelIndex()) const
Qt::ItemFlags flags (const QModelIndex &index) const
Qt::DropActions supportedDropActions () const
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
QMimeData * mimeData (const QModelIndexList &indexes) const
QStringList mimeTypes () const
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
bool hasChildren (const QModelIndex &parent=QModelIndex()) const
BookmarkNode * node (const QModelIndex &index) const
QModelIndex index (BookmarkNode *node) const
Private Attributes
bool m_endMacro
BookmarksManager * m_bookmarksManager
Detailed Description
Definition at line 72 of file bookmarksmodel.h.
Member Enumeration Documentation
Roles
enum BookmarksModel::Roles
Enumerator
TypeRole
UrlRole
UrlStringRole
SeparatorRole
Definition at line 82 of file bookmarksmodel.h.
                {
         TypeRole = Qt::UserRole + 1,
         UrlRole = Qt::UserRole + 2,
         UrlStringRole = Qt::UserRole + 3,
         SeparatorRole = Qt::UserRole + 4
     };
Constructor & Destructor Documentation
BookmarksModel()
BookmarksModel::BookmarksModel (BookmarksManager * bookmarkManager, QObject * parent = nullptr)
Definition at line 79 of file bookmarksmodel.cpp.
     : QAbstractItemModel(parent)
     , m_endMacro(false)
     , m_bookmarksManager(bookmarkManager)
 {
     connect(bookmarkManager, SIGNAL(entryAdded(BookmarkNode *)),
             this, SLOT(entryAdded(BookmarkNode *)));
     connect(bookmarkManager, SIGNAL(entryRemoved(BookmarkNode *, int, BookmarkNode *)),
             this, SLOT(entryRemoved(BookmarkNode *, int, BookmarkNode *)));
     connect(bookmarkManager, SIGNAL(entryChanged(BookmarkNode *)),
             this, SLOT(entryChanged(BookmarkNode *)));
 }
References entryAdded(), entryChanged(), and entryRemoved().
Member Function Documentation
bookmarksManager()
BookmarksManager* BookmarksModel::bookmarksManager () const inline
Definition at line 90 of file bookmarksmodel.h.
{
         return m_bookmarksManager;
     }
References m_bookmarksManager.
columnCount()
int BookmarksModel::columnCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 211 of file bookmarksmodel.cpp.
 {
     return (parent.column() > 0) ? 0 : 2;
 }
References parent().
Referenced by index().
data()
QVariant BookmarksModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Definition at line 161 of file bookmarksmodel.cpp.
 {
     if (!index.isValid() || index.model() != this)
         return QVariant();
     const BookmarkNode *bookmarkNode = node(index);
     switch (role) {
     case Qt::EditRole:
     case Qt::DisplayRole:
         if (bookmarkNode->type() == BookmarkNode::Separator) {
             switch (index.column()) {
             case 0:
                 return QString(50, 0xB7);
             case 1:
                 return QString();
             }
         }
         switch (index.column()) {
         case 0:
             return bookmarkNode->title;
         case 1:
             return bookmarkNode->url;
         }
         break;
     case BookmarksModel::UrlRole:
         return QUrl(bookmarkNode->url);
         break;
     case BookmarksModel::UrlStringRole:
         return bookmarkNode->url;
         break;
     case BookmarksModel::TypeRole:
         return bookmarkNode->type();
         break;
     case BookmarksModel::SeparatorRole:
         return (bookmarkNode->type() == BookmarkNode::Separator);
         break;
     case Qt::DecorationRole:
         if (index.column() == 0) {
             if (bookmarkNode->type() == BookmarkNode::Folder)
                 return QApplication::style()->standardIcon(QStyle::SP_DirIcon);
 #ifndef NO_BROWSERAPPLICATION
             return BrowserApplication::instance()->icon(bookmarkNode->url);
 #endif
         }
     }
     return QVariant();
 }
References BookmarkNode::Folder, BrowserApplication::icon(), index(), BrowserApplication::instance(), node(), BookmarkNode::Separator, SeparatorRole, BookmarkNode::title, BookmarkNode::type(), TypeRole, BookmarkNode::url, UrlRole, and UrlStringRole.
Referenced by dropMimeData(), and mimeData().
dropMimeData()
bool BookmarksModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent)
Definition at line 326 of file bookmarksmodel.cpp.
 {
     if (action == Qt::IgnoreAction)
         return true;
     if (column > 0)
         return false;
     BookmarkNode *parentNode = node(parent);
     if (!data->hasFormat(MIMETYPE)) {
         if (!data->hasUrls())
             return false;
         BookmarkNode *node = new BookmarkNode(BookmarkNode::Bookmark, parentNode);
         node->url = QString::fromUtf8(data->urls().at(0).toEncoded());
         if (data->hasText())
             node->title = data->text();
         else
             node->title = node->url;
         m_bookmarksManager->addBookmark(parentNode, node, row);
         return true;
     }
     QByteArray ba = data->data(MIMETYPE);
     QDataStream stream(&ba, QIODevice::ReadOnly);
     if (stream.atEnd())
         return false;
     QUndoStack *undoStack = m_bookmarksManager->undoRedoStack();
     undoStack->beginMacro(QLatin1String("Move Bookmarks"));
     while (!stream.atEnd()) {
         QByteArray encodedData;
         stream >> encodedData;
         QBuffer buffer(&encodedData);
         buffer.open(QBuffer::ReadOnly);
         XbelReader reader;
         BookmarkNode *rootNode = reader.read(&buffer);
         QList<BookmarkNode*> children = rootNode->children();
         for (int i = 0; i < children.count(); ++i) {
             BookmarkNode *bookmarkNode = children.at(i);
             rootNode->remove(bookmarkNode);
             row = qMax(0, row);
             m_bookmarksManager->addBookmark(parentNode, bookmarkNode, row);
             m_endMacro = true;
         }
         delete rootNode;
     }
     return true;
 }
References BookmarksManager::addBookmark(), BookmarkNode::Bookmark, BookmarkNode::children(), data(), m_bookmarksManager, m_endMacro, MIMETYPE, node(), parent(), XbelReader::read(), BookmarkNode::remove(), BookmarkNode::title, BookmarksManager::undoRedoStack(), and BookmarkNode::url.
entryAdded
void BookmarksModel::entryAdded (BookmarkNode * item) slot
Definition at line 100 of file bookmarksmodel.cpp.
 {
     Q_ASSERT(item && item->parent());
     int row = item->parent()->children().indexOf(item);
     BookmarkNode *parent = item->parent();
     // item was already added so remove beore beginInsertRows is called
     parent->remove(item);
     beginInsertRows(index(parent), row, row);
     parent->add(item, row);
     endInsertRows();
 }
References BookmarkNode::children(), index(), parent(), and BookmarkNode::parent().
Referenced by BookmarksModel().
entryChanged
void BookmarksModel::entryChanged (BookmarkNode * item) slot
Definition at line 121 of file bookmarksmodel.cpp.
 {
     QModelIndex idx = index(item);
     emit dataChanged(idx, idx);
 }
References index().
Referenced by BookmarksModel().
entryRemoved
void BookmarksModel::entryRemoved (BookmarkNode * parent, int row, BookmarkNode * item) slot
Definition at line 112 of file bookmarksmodel.cpp.
 {
     // item was already removed, re-add so beginRemoveRows works
     parent->add(item, row);
     beginRemoveRows(index(parent), row, row);
     parent->remove(item);
     endRemoveRows();
 }
References index(), and parent().
Referenced by BookmarksModel().
flags()
Qt::ItemFlags BookmarksModel::flags (const QModelIndex & index) const
Definition at line 263 of file bookmarksmodel.cpp.
 {
     if (!index.isValid())
         return Qt::NoItemFlags;
     BookmarkNode *node = this->node(index);
     BookmarkNode::Type type = node->type();
     Qt::ItemFlags flags = Qt::ItemIsSelectable | Qt::ItemIsEnabled;
     if (hasChildren(index))
         flags |= Qt::ItemIsDropEnabled;
     if (node == m_bookmarksManager->menu()
             || node == m_bookmarksManager->toolbar())
         return flags;
     flags |= Qt::ItemIsDragEnabled;
     if ((index.column() == 0 && type != BookmarkNode::Separator)
             || (index.column() == 1 && type == BookmarkNode::Bookmark))
         flags |= Qt::ItemIsEditable;
     return flags;
 }
References BookmarkNode::Bookmark, hasChildren(), index(), m_bookmarksManager, BookmarksManager::menu(), node(), BookmarkNode::Separator, BookmarksManager::toolbar(), and BookmarkNode::type().
Referenced by setData().
hasChildren()
bool BookmarksModel::hasChildren (const QModelIndex & parent = QModelIndex()) const
Definition at line 255 of file bookmarksmodel.cpp.
 {
     if (!parent.isValid())
         return true;
     const BookmarkNode *parentNode = node(parent);
     return (parentNode->type() == BookmarkNode::Folder);
 }
References BookmarkNode::Folder, node(), parent(), and BookmarkNode::type().
Referenced by flags().
headerData()
QVariant BookmarksModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Definition at line 148 of file bookmarksmodel.cpp.
 {
     if (orientation == Qt::Horizontal && role == Qt::DisplayRole) {
         switch (section) {
         case 0:
             return tr("Title");
         case 1:
             return tr("Address");
         }
     }
     return QAbstractItemModel::headerData(section, orientation, role);
 }
index() [1/2]
QModelIndex BookmarksModel::index (BookmarkNode * node) const
Definition at line 92 of file bookmarksmodel.cpp.
 {
     BookmarkNode *parent = node->parent();
     if (!parent)
         return QModelIndex();
     return createIndex(parent->children().indexOf(node), 0, node);
 }
References node(), parent(), and BookmarkNode::parent().
index() [2/2]
QModelIndex BookmarksModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const
Definition at line 228 of file bookmarksmodel.cpp.
 {
     if (row < 0 || column < 0 || row >= rowCount(parent) || column >= columnCount(parent))
         return QModelIndex();
     // get the parent node
     BookmarkNode *parentNode = node(parent);
     return createIndex(row, column, parentNode->children().at(row));
 }
References BookmarkNode::children(), columnCount(), node(), parent(), and rowCount().
Referenced by AddBookmarkDialog::accept(), BrowserMainWindow::addBookmark(), BrowserMainWindow::addBookmarkFolder(), data(), entryAdded(), entryChanged(), entryRemoved(), BookmarksDialog::expandNodes(), flags(), mimeData(), node(), parent(), BookmarksMenuBarMenu::prePopulated(), and setData().
mimeData()
QMimeData * BookmarksModel::mimeData (const QModelIndexList & indexes) const
Definition at line 303 of file bookmarksmodel.cpp.
 {
     QMimeData *mimeData = new QMimeData();
     QByteArray data;
     QDataStream stream(&data, QIODevice::WriteOnly);
     QList<QUrl> urls;
     foreach (const QModelIndex &index, indexes) {
         if (index.column() != 0 || !index.isValid())
             continue;
         QByteArray encodedData;
         QBuffer buffer(&encodedData);
         buffer.open(QBuffer::ReadWrite);
         XbelWriter writer;
         const BookmarkNode *parentNode = node(index);
         writer.write(&buffer, parentNode);
         stream << encodedData;
         urls.append(index.data(BookmarksModel::UrlRole).toUrl());
     }
     mimeData->setData(MIMETYPE, data);
     mimeData->setUrls(urls);
     return mimeData;
 }
References data(), index(), MIMETYPE, node(), UrlRole, and XbelWriter::write().
mimeTypes()
QStringList BookmarksModel::mimeTypes () const
Definition at line 295 of file bookmarksmodel.cpp.
 {
     QStringList types;
     types << MIMETYPE;
     types << QLatin1String("text/uri-list");
     return types;
 }
References MIMETYPE.
node()
BookmarkNode * BookmarksModel::node (const QModelIndex & index) const
Definition at line 415 of file bookmarksmodel.cpp.
 {
     BookmarkNode *itemNode = static_cast<BookmarkNode*>(index.internalPointer());
     if (!itemNode)
         return m_bookmarksManager->bookmarks();
     return itemNode;
 }
References BookmarksManager::bookmarks(), index(), and m_bookmarksManager.
Referenced by AddBookmarkDialog::accept(), BookmarksDialog::customContextMenuRequested(), data(), dropMimeData(), flags(), hasChildren(), index(), mimeData(), BookmarksDialog::newFolder(), BookmarksDialog::openBookmark(), parent(), removeRows(), BookmarksDialog::saveExpandedNodes(), and setData().
parent()
QModelIndex BookmarksModel::parent (const QModelIndex & index = QModelIndex()) const
Definition at line 238 of file bookmarksmodel.cpp.
 {
     if (!index.isValid())
         return QModelIndex();
     BookmarkNode *itemNode = node(index);
     BookmarkNode *parentNode = (itemNode ? itemNode->parent() : nullptr);
     if (!parentNode || parentNode == m_bookmarksManager->bookmarks())
         return QModelIndex();
     // get the parent's row
     BookmarkNode *grandParentNode = parentNode->parent();
     int parentRow = grandParentNode->children().indexOf(parentNode);
     Q_ASSERT(parentRow >= 0);
     return createIndex(parentRow, 0, parentNode);
 }
References BookmarksManager::bookmarks(), BookmarkNode::children(), index(), m_bookmarksManager, node(), and BookmarkNode::parent().
Referenced by columnCount(), dropMimeData(), entryAdded(), entryRemoved(), hasChildren(), index(), removeRows(), and rowCount().
removeRows()
bool BookmarksModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex())
Definition at line 127 of file bookmarksmodel.cpp.
 {
     if (row < 0 || count <= 0 || row + count > rowCount(parent))
         return false;
     BookmarkNode *bookmarkNode = node(parent);
     for (int i = row + count - 1; i >= row; --i) {
         BookmarkNode *node = bookmarkNode->children().at(i);
         if (node == m_bookmarksManager->menu()
                 || node == m_bookmarksManager->toolbar())
             continue;
         m_bookmarksManager->removeBookmark(node);
     }
     if (m_endMacro) {
         m_bookmarksManager->undoRedoStack()->endMacro();
         m_endMacro = false;
     }
     return true;
 }
References BookmarkNode::children(), m_bookmarksManager, m_endMacro, BookmarksManager::menu(), node(), parent(), BookmarksManager::removeBookmark(), rowCount(), BookmarksManager::toolbar(), and BookmarksManager::undoRedoStack().
rowCount()
int BookmarksModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 216 of file bookmarksmodel.cpp.
 {
     if (parent.column() > 0)
         return 0;
     if (!parent.isValid())
         return m_bookmarksManager->bookmarks()->children().count();
     const BookmarkNode *item = static_cast<BookmarkNode*>(parent.internalPointer());
     return item->children().count();
 }
References BookmarksManager::bookmarks(), BookmarkNode::children(), m_bookmarksManager, and parent().
Referenced by index(), and removeRows().
setData()
bool BookmarksModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole)
Definition at line 382 of file bookmarksmodel.cpp.
 {
     if (!index.isValid() || (flags(index) & Qt::ItemIsEditable) == 0)
         return false;
     BookmarkNode *item = node(index);
     switch (role) {
     case Qt::EditRole:
     case Qt::DisplayRole:
         if (index.column() == 0) {
             m_bookmarksManager->setTitle(item, value.toString());
             break;
         }
         if (index.column() == 1) {
             m_bookmarksManager->setUrl(item, value.toString());
             break;
         }
         return false;
     case BookmarksModel::UrlRole:
         m_bookmarksManager->setUrl(item, value.toUrl().toString());
         break;
     case BookmarksModel::UrlStringRole:
         m_bookmarksManager->setUrl(item, value.toString());
         break;
     default:
         break;
         return false;
     }
     return true;
 }
References flags(), index(), m_bookmarksManager, node(), BookmarksManager::setTitle(), BookmarksManager::setUrl(), UrlRole, and UrlStringRole.
supportedDropActions()
Qt::DropActions BookmarksModel::supportedDropActions () const
Definition at line 288 of file bookmarksmodel.cpp.
 {
     return Qt::CopyAction | Qt::MoveAction;
 }
Member Data Documentation
m_bookmarksManager
BookmarksManager* BookmarksModel::m_bookmarksManager private
Definition at line 116 of file bookmarksmodel.h.
Referenced by bookmarksManager(), dropMimeData(), flags(), node(), parent(), removeRows(), rowCount(), and setData().
m_endMacro
bool BookmarksModel::m_endMacro private
Definition at line 115 of file bookmarksmodel.h.
Referenced by dropMimeData(), and removeRows().
The documentation for this class was generated from the following files:
src/bookmarks/bookmarksmodel.h
src/bookmarks/bookmarksmodel.cpp