Endorphin: BrowserMainWindow Class Reference
BrowserMainWindow Class Reference
#include <browsermainwindow.h>
Public Slots
void goHome ()
void privacyChanged (bool isPrivate)
void zoomTextOnlyChanged (bool textOnly)
void runScriptOnOpenViews (QString source)
Signals
void notifyGotHTML ()
Public Member Functions
BrowserMainWindow (QWidget *parent=nullptr, Qt::WindowFlags flags=nullptr)
~BrowserMainWindow ()
QSize sizeHint () const
TabWidget * tabWidget () const
WebView * currentTab () const
ToolbarSearch * toolbarSearch () const
QByteArray saveState (bool withTabs=true) const
bool restoreState (const QByteArray &state)
QAction * showMenuBarAction () const
QAction * searchManagerAction () const
void handleDevToolsRequested (QWebEnginePage *source)
Static Public Member Functions
static BrowserMainWindow * parentWindow (QWidget *widget)
Protected Member Functions
void closeEvent (QCloseEvent *event)
void keyPressEvent (QKeyEvent *event)
void mousePressEvent (QMouseEvent *event)
void changeEvent (QEvent *event)
Private Slots
void save ()
void lastTabClosed ()
void loadProgress (int)
void updateStatusbar (const QString &string)
void updateWindowTitle (const QString &title=QString())
void preferences ()
void fileNew ()
void fileOpen ()
void filePrintPreview ()
void filePrint ()
void privateBrowsing ()
void fileSaveAs ()
void editFind ()
void editFindNext ()
void editFindPrevious ()
void showBookmarksDialog ()
void addBookmark ()
void addBookmarkFolder ()
void zoomIn ()
void zoomNormal ()
void zoomOut ()
void viewMenuBar ()
void viewToolbar ()
void viewBookmarksBar ()
void viewStatusbar ()
void viewPageSource ()
void viewFullScreen (bool enable)
void viewTextEncoding (QAction *action)
void webSearch ()
void clearPrivateData ()
void aboutApplication ()
void downloadManager ()
void selectLineEdit ()
void aboutToShowBackMenu ()
void aboutToShowForwardMenu ()
void aboutToShowViewMenu ()
void aboutToShowWindowMenu ()
void aboutToShowTextEncodingMenu ()
void openActionUrl (QAction *action)
void showSearchDialog ()
void showWindow ()
void swapFocus ()
void printRequested (QWebEnginePage *page)
void geometryChangeRequested (const QRect &geometry)
void gotHTML (QString &value)
Private Member Functions
void retranslate ()
void loadDefaultState ()
void setupMenu ()
void setupToolBar ()
void updateStopReloadActionText (bool loading)
DevToolsWindow * createDevToolsWindow ()
Private Attributes
QMenu * m_fileMenu
QAction * m_fileNewWindowAction
QAction * m_fileOpenFileAction
QAction * m_fileOpenLocationAction
QAction * m_fileSaveAsAction
QAction * m_fileImportBookmarksAction
QAction * m_fileExportBookmarksAction
QAction * m_filePrintPreviewAction
QAction * m_filePrintAction
QAction * m_filePrivateBrowsingAction
QAction * m_fileCloseWindow
QAction * m_fileQuit
QMenu * m_editMenu
QAction * m_editUndoAction
QAction * m_editRedoAction
QAction * m_editCutAction
QAction * m_editCopyAction
QAction * m_editPasteAction
QAction * m_editSelectAllAction
QAction * m_editFindAction
QAction * m_editFindNextAction
QAction * m_editFindPreviousAction
QMenu * m_viewMenu
QAction * m_viewShowMenuBarAction
QAction * m_viewToolbarAction
QAction * m_viewBookmarkBarAction
QAction * m_viewStatusbarAction
QAction * m_viewStopAction
QAction * m_viewReloadAction
QAction * m_viewZoomInAction
QAction * m_viewZoomNormalAction
QAction * m_viewZoomOutAction
QAction * m_viewZoomTextOnlyAction
QAction * m_viewSourceAction
QAction * m_viewFullScreenAction
QAction * m_viewTextEncodingAction
QMenu * m_viewTextEncodingMenu
HistoryMenu * m_historyMenu
QAction * m_historyBackAction
QAction * m_historyForwardAction
QAction * m_historyHomeAction
QAction * m_historyRestoreLastSessionAction
BookmarksMenuBarMenu * m_bookmarksMenu
QAction * m_bookmarksShowAllAction
QAction * m_bookmarksAddAction
QAction * m_bookmarksAddFolderAction
QMenu * m_windowMenu
QMenu * m_toolsMenu
QAction * m_toolsWebSearchAction
QAction * m_toolsClearPrivateDataAction
QAction * m_toolsPreferencesAction
QAction * m_toolsSearchManagerAction
UserAgentMenu * m_toolsUserAgentMenu
QMenu * m_helpMenu
QAction * m_helpChangeLanguageAction
QAction * m_helpAboutQtAction
QAction * m_helpAboutApplicationAction
QToolBar * m_navigationBar
QMenu * m_historyBackMenu
QMenu * m_historyForwardMenu
QAction * m_stopReloadAction
QIcon m_reloadIcon
QIcon m_stopIcon
QSplitter * m_navigationSplitter
ToolbarSearch * m_toolbarSearch
BookmarksToolBar * m_bookmarksToolbar
TabWidget * m_tabWidget
AutoSaver * m_autoSaver
bool m_menuBarVisible
bool m_statusBarVisible
QString markup
Friends
class BrowserApplication
Detailed Description
The MainWindow of the Browser Application.
Handles the tab widget and all the actions
Definition at line 86 of file browsermainwindow.h.
Constructor & Destructor Documentation
BrowserMainWindow()
BrowserMainWindow::BrowserMainWindow (QWidget * parent = nullptr, Qt::WindowFlags flags = nullptr)
Definition at line 111 of file browsermainwindow.cpp.
     : QMainWindow(parent, flags)
     , m_navigationBar(nullptr)
     , m_navigationSplitter(nullptr)
     , m_toolbarSearch(nullptr)
 #if defined(Q_WS_MAC)
     , m_bookmarksToolbarFrame(0)
 #endif
     , m_bookmarksToolbar(nullptr)
     , m_tabWidget(new TabWidget(this))
     , m_autoSaver(new AutoSaver(this))
 {
     setAttribute(Qt::WA_DeleteOnClose, true);
     statusBar()->setSizeGripEnabled(true);
     // fixes https://bugzilla.mozilla.org/show_bug.cgi?id=219070
     // yes, that's a Firefox bug!
     statusBar()->setLayoutDirection(Qt::LeftToRight);
     setupMenu();
     setupToolBar();
     m_filePrivateBrowsingAction->setChecked(BrowserApplication::isPrivate());
     QWidget *centralWidget = new QWidget(this);
     BookmarksModel *boomarksModel = BrowserApplication::bookmarksManager()->bookmarksModel();
     m_bookmarksToolbar = new BookmarksToolBar(boomarksModel, this);
     m_bookmarksToolbar->setObjectName(QLatin1String("BookmarksToolbar"));
     connect(m_bookmarksToolbar, SIGNAL(openUrl(const QUrl&, const QString&)),
             m_tabWidget, SLOT(loadUrlFromUser(const QUrl&, const QString&)));
     connect(m_bookmarksToolbar, SIGNAL(openUrl(const QUrl&, TabWidget::OpenUrlIn, const QString&)),
             m_tabWidget, SLOT(loadUrl(const QUrl&, TabWidget::OpenUrlIn, const QString&)));
     QVBoxLayout *layout = new QVBoxLayout;
     layout->setSpacing(0);
     layout->setMargin(0);
 #if defined(Q_WS_MAC)
     m_bookmarksToolbarFrame = new QFrame(this);
     m_bookmarksToolbarFrame->setLineWidth(1);
     m_bookmarksToolbarFrame->setMidLineWidth(0);
     m_bookmarksToolbarFrame->setFrameShape(QFrame::HLine);
     m_bookmarksToolbarFrame->setFrameShadow(QFrame::Raised);
     QPalette fp = m_bookmarksToolbarFrame->palette();
     fp.setColor(QPalette::Active, QPalette::Light, QColor(64, 64, 64));
     fp.setColor(QPalette::Active, QPalette::Dark, QColor(192, 192, 192));
     fp.setColor(QPalette::Inactive, QPalette::Light, QColor(135, 135, 135));
     fp.setColor(QPalette::Inactive, QPalette::Dark, QColor(226, 226, 226));
     m_bookmarksToolbarFrame->setAttribute(Qt::WA_MacNoClickThrough, true);
     m_bookmarksToolbarFrame->setPalette(fp);
     layout->addWidget(m_bookmarksToolbarFrame);
     layout->addWidget(m_bookmarksToolbar);
     QPalette p = m_bookmarksToolbar->palette();
     p.setColor(QPalette::Active, QPalette::Window, QColor(150, 150, 150));
     p.setColor(QPalette::Inactive, QPalette::Window, QColor(207, 207, 207));
     m_bookmarksToolbar->setAttribute(Qt::WA_MacNoClickThrough, true);
     m_bookmarksToolbar->setAutoFillBackground(true);
     m_bookmarksToolbar->setPalette(p);
     m_bookmarksToolbar->setBackgroundRole(QPalette::Window);
     m_bookmarksToolbar->setMaximumHeight(19);
     QWidget *w = new QWidget(this);
     w->setMaximumHeight(0);
     layout->addWidget(w); // <- OS X tab widget style bug
 #else
     addToolBarBreak();
     addToolBar(m_bookmarksToolbar);
 #endif
     layout->addWidget(m_tabWidget);
     centralWidget->setLayout(layout);
     setCentralWidget(centralWidget);
     connect(m_tabWidget, SIGNAL(setCurrentTitle(const QString &)),
             this, SLOT(updateWindowTitle(const QString &)));
     connect(m_tabWidget, SIGNAL(showStatusBarMessage(const QString&)),
             statusBar(), SLOT(showMessage(const QString&)));
     connect(m_tabWidget, SIGNAL(linkHovered(const QString&)),
             statusBar(), SLOT(showMessage(const QString&)));
     connect(m_tabWidget, SIGNAL(loadProgress(int)),
             this, SLOT(loadProgress(int)));
     connect(m_tabWidget, SIGNAL(tabsChanged()),
             m_autoSaver, SLOT(changeOccurred()));
     connect(m_tabWidget, SIGNAL(geometryChangeRequested(const QRect &)),
             this, SLOT(geometryChangeRequested(const QRect &)));
     connect(m_tabWidget, SIGNAL(printRequested(QWebEnginePage *)),
             this, SLOT(printRequested(QWebEnginePage *)));
     connect(m_tabWidget, SIGNAL(lastTabClosed()),
             this, SLOT(lastTabClosed()));
     connect(m_tabWidget, &TabWidget::devToolsRequested, this, &BrowserMainWindow::handleDevToolsRequested);
     updateWindowTitle();
     loadDefaultState();
     m_tabWidget->newTab();
     m_tabWidget->currentLocationBar()->setFocus();
 #if defined(Q_WS_MAC)
     m_navigationBar->setIconSize(QSize(18, 18));
 #endif
     // Add each item in the menu bar to the main window so
     // if the menu bar is hidden the shortcuts still work.
     QList<QAction*> actions = menuBar()->actions();
     foreach (QAction *action, actions) {
         if (action->menu())
             actions += action->menu()->actions();
         addAction(action);
     }
 #if defined(Q_WS_MAC)
     setWindowIcon(QIcon());
 #endif
 #if defined(Q_WS_X11)
     setWindowRole(QLatin1String("browser"));
 #endif
     retranslate();
 }
References BrowserApplication::bookmarksManager(), BookmarksManager::bookmarksModel(), TabWidget::currentLocationBar(), TabWidget::devToolsRequested(), geometryChangeRequested(), handleDevToolsRequested(), BrowserApplication::isPrivate(), lastTabClosed(), loadDefaultState(), loadProgress(), m_autoSaver, m_bookmarksToolbar, m_filePrivateBrowsingAction, m_navigationBar, m_tabWidget, TabWidget::newTab(), printRequested(), retranslate(), setupMenu(), setupToolBar(), and updateWindowTitle().
~BrowserMainWindow()
BrowserMainWindow::~BrowserMainWindow ()
Definition at line 224 of file browsermainwindow.cpp.
 {
     m_autoSaver->changeOccurred();
     m_autoSaver->saveIfNeccessary();
 }
References AutoSaver::changeOccurred(), m_autoSaver, and AutoSaver::saveIfNeccessary().
Member Function Documentation
aboutApplication
void BrowserMainWindow::aboutApplication () private slot
Definition at line 1155 of file browsermainwindow.cpp.
 {
     AboutDialog *aboutDialog = new AboutDialog(this);
     aboutDialog->setAttribute(Qt::WA_DeleteOnClose);
     aboutDialog->show();
 }
Referenced by setupMenu().
aboutToShowBackMenu
void BrowserMainWindow::aboutToShowBackMenu () private slot
Definition at line 1464 of file browsermainwindow.cpp.
 {
     m_historyBackMenu->clear();
     if (!currentTab())
         return;
     QWebEngineHistory *history = currentTab()->history();
     int historyCount = history->count();
     for (int i = history->backItems(historyCount).count() - 1; i >= 0; --i) {
         QWebEngineHistoryItem item = history->backItems(history->count()).at(i);
         QAction *action = new QAction(this);
         action->setData(-1*(historyCount - i - 1));
         QIcon icon = BrowserApplication::instance()->icon(item.url());
         action->setIcon(icon);
         action->setText(item.title());
         m_historyBackMenu->addAction(action);
     }
 }
References currentTab(), BrowserApplication::icon(), BrowserApplication::instance(), and m_historyBackMenu.
Referenced by setupToolBar().
aboutToShowForwardMenu
void BrowserMainWindow::aboutToShowForwardMenu () private slot
Definition at line 1482 of file browsermainwindow.cpp.
 {
     m_historyForwardMenu->clear();
     if (!currentTab())
         return;
     QWebEngineHistory *history = currentTab()->history();
     int historyCount = history->count();
     for (int i = 0; i < history->forwardItems(history->count()).count(); ++i) {
         QWebEngineHistoryItem item = history->forwardItems(historyCount).at(i);
         QAction *action = new QAction(this);
         action->setData(historyCount - i);
         QIcon icon = BrowserApplication::instance()->icon(item.url());
         action->setIcon(icon);
         action->setText(item.title());
         m_historyForwardMenu->addAction(action);
     }
 }
References currentTab(), BrowserApplication::icon(), BrowserApplication::instance(), and m_historyForwardMenu.
Referenced by setupToolBar().
aboutToShowTextEncodingMenu
void BrowserMainWindow::aboutToShowTextEncodingMenu () private slot
Definition at line 862 of file browsermainwindow.cpp.
 {
     m_viewTextEncodingMenu->clear();
     int currentCodec = -1;
     QStringList codecs;
     QList<int> mibs = QTextCodec::availableMibs();
     foreach (const int &mib, mibs) {
         QString codec = QLatin1String(QTextCodec::codecForMib(mib)->name());
         codecs.append(codec);
     }
     codecs.sort();
     QString defaultTextEncoding = QWebEngineSettings::globalSettings()->defaultTextEncoding();
     currentCodec = codecs.indexOf(defaultTextEncoding);
     QAction *defaultEncoding = m_viewTextEncodingMenu->addAction(tr("Default"));
     defaultEncoding->setData(QString());
     defaultEncoding->setCheckable(true);
     if (currentCodec == -1)
         defaultEncoding->setChecked(true);
     m_viewTextEncodingMenu->addSeparator();
     for (int i = 0; i < codecs.count(); ++i) {
         const QString &codec = codecs.at(i);
         QAction *action = m_viewTextEncodingMenu->addAction(codec);
         action->setData(codec);
         action->setCheckable(true);
         if (currentCodec == i)
             action->setChecked(true);
     }
 }
References m_viewTextEncodingMenu.
Referenced by setupMenu().
aboutToShowViewMenu
void BrowserMainWindow::aboutToShowViewMenu () private slot
Definition at line 855 of file browsermainwindow.cpp.
 {
     m_viewToolbarAction->setText(m_navigationBar->isVisible() ? tr("Hide Toolbar") : tr("Show Toolbar"));
     m_viewBookmarkBarAction->setText(m_bookmarksToolbar->isVisible() ? tr("Hide Bookmarks Bar") : tr("Show Bookmarks Bar"));
     m_viewStatusbarAction->setText(statusBar()->isVisible() ? tr("Hide Status Bar") : tr("Show Status Bar"));
 }
References m_bookmarksToolbar, m_navigationBar, m_viewBookmarkBarAction, m_viewStatusbarAction, and m_viewToolbarAction.
Referenced by setupMenu().
aboutToShowWindowMenu
void BrowserMainWindow::aboutToShowWindowMenu () private slot
Definition at line 1500 of file browsermainwindow.cpp.
 {
     m_windowMenu->clear();
     m_windowMenu->addAction(m_tabWidget->nextTabAction());
     m_windowMenu->addAction(m_tabWidget->previousTabAction());
     m_windowMenu->addSeparator();
     QAction *downloadManagerAction = m_windowMenu->addAction(tr("Downloads"), this, SLOT(downloadManager()), QKeySequence(tr("Ctrl+Y", "Download Manager")));
     downloadManagerAction->setIcon(QIcon::fromTheme(QLatin1String("emblem-downloads")));
     m_windowMenu->addSeparator();
     QList<BrowserMainWindow*> windows = BrowserApplication::instance()->mainWindows();
     for (int i = 0; i < windows.count(); ++i) {
         BrowserMainWindow *window = windows.at(i);
         QAction *action = m_windowMenu->addAction(window->windowTitle(), this, SLOT(showWindow()));
         action->setData(i);
         action->setCheckable(true);
         if (window == this)
             action->setChecked(true);
     }
 }
References downloadManager(), BrowserApplication::instance(), m_tabWidget, m_windowMenu, BrowserApplication::mainWindows(), TabWidget::nextTabAction(), TabWidget::previousTabAction(), and showWindow().
Referenced by setupMenu().
addBookmark
void BrowserMainWindow::addBookmark () private slot
Definition at line 1039 of file browsermainwindow.cpp.
 {
     WebView *webView = currentTab();
     QString url = QLatin1String(webView->url().toEncoded());
     QString title = webView->title();
     AddBookmarkDialog dialog;
     dialog.setUrl(url);
     dialog.setTitle(title);
     BookmarkNode *menu = BrowserApplication::bookmarksManager()->menu();
     QModelIndex index = BrowserApplication::bookmarksManager()->bookmarksModel()->index(menu);
     dialog.setCurrentIndex(index);
     dialog.exec();
 }
References BrowserApplication::bookmarksManager(), BookmarksManager::bookmarksModel(), currentTab(), BookmarksModel::index(), BookmarksManager::menu(), AddBookmarkDialog::setCurrentIndex(), AddBookmarkDialog::setTitle(), AddBookmarkDialog::setUrl(), and WebView::url().
Referenced by setupMenu().
addBookmarkFolder
void BrowserMainWindow::addBookmarkFolder () private slot
Definition at line 1054 of file browsermainwindow.cpp.
 {
     AddBookmarkDialog dialog;
     BookmarksManager *bookmarksManager = BrowserApplication::bookmarksManager();
     BookmarkNode *menu = bookmarksManager->menu();
     QModelIndex index = bookmarksManager->bookmarksModel()->index(menu);
     dialog.setCurrentIndex(index);
     dialog.setFolder(true);
     dialog.exec();
 }
References BrowserApplication::bookmarksManager(), BookmarksManager::bookmarksModel(), BookmarksModel::index(), BookmarksManager::menu(), AddBookmarkDialog::setCurrentIndex(), and AddBookmarkDialog::setFolder().
Referenced by setupMenu().
changeEvent()
void BrowserMainWindow::changeEvent (QEvent * event) protected
Definition at line 1301 of file browsermainwindow.cpp.
 {
     if (event->type() == QEvent::LanguageChange)
         retranslate();
     QMainWindow::changeEvent(event);
 }
References retranslate().
clearPrivateData
void BrowserMainWindow::clearPrivateData () private slot
Definition at line 1401 of file browsermainwindow.cpp.
 {
     ClearPrivateData dialog;
     dialog.exec();
 }
Referenced by setupMenu().
closeEvent()
void BrowserMainWindow::closeEvent (QCloseEvent * event) protected
Definition at line 1256 of file browsermainwindow.cpp.
 {
     if (!BrowserApplication::instance()->allowToCloseWindow(this)) {
         event->ignore();
         if (m_tabWidget->count() == 0)
             m_tabWidget->newTab();
         return;
     }
     if (m_tabWidget->count() > 1) {
         QSettings settings;
         settings.beginGroup(QLatin1String("tabs"));
         bool confirm = settings.value(QLatin1String("confirmClosingMultipleTabs"), true).toBool();
         if (confirm) {
             QApplication::alert(this);
             int ret = QMessageBox::warning(this, QString(),
                                            tr("Are you sure you want to close the window?"
                                               "  There are %1 tabs open").arg(m_tabWidget->count()),
                                            QMessageBox::Yes | QMessageBox::No,
                                            QMessageBox::No);
             if (ret == QMessageBox::No) {
                 event->ignore();
                 return;
             }
         }
     }
     event->accept();
 }
References BrowserApplication::instance(), m_tabWidget, and TabWidget::newTab().
createDevToolsWindow()
DevToolsWindow * BrowserMainWindow::createDevToolsWindow () private
Definition at line 1553 of file browsermainwindow.cpp.
 {
     auto devWindow = new DevToolsWindow(this);
     devWindow->show();
     return devWindow;
 }
Referenced by handleDevToolsRequested().
currentTab()
WebView * BrowserMainWindow::currentTab () const
Definition at line 1422 of file browsermainwindow.cpp.
 {
     return m_tabWidget->currentWebView();
 }
References TabWidget::currentWebView(), and m_tabWidget.
Referenced by aboutToShowBackMenu(), aboutToShowForwardMenu(), addBookmark(), filePrint(), filePrintPreview(), fileSaveAs(), TabWidget::getView(), openActionUrl(), SettingsDialog::setHomeToCurrentPage(), swapFocus(), viewPageSource(), zoomIn(), zoomNormal(), and zoomOut().
downloadManager
void BrowserMainWindow::downloadManager () private slot
Definition at line 1112 of file browsermainwindow.cpp.
 {
     BrowserApplication::downloadManager()->show();
 }
References BrowserApplication::downloadManager().
Referenced by aboutToShowWindowMenu().
editFind
void BrowserMainWindow::editFind () private slot
Definition at line 1308 of file browsermainwindow.cpp.
 {
     tabWidget()->webViewSearch(m_tabWidget->currentIndex())->showFind();
 }
References m_tabWidget, SearchBar::showFind(), tabWidget(), and TabWidget::webViewSearch().
Referenced by setupMenu().
editFindNext
void BrowserMainWindow::editFindNext () private slot
Definition at line 1313 of file browsermainwindow.cpp.
 {
     tabWidget()->webViewSearch(m_tabWidget->currentIndex())->findNext();
 }
References WebViewSearch::findNext(), m_tabWidget, tabWidget(), and TabWidget::webViewSearch().
Referenced by setupMenu().
editFindPrevious
void BrowserMainWindow::editFindPrevious () private slot
Definition at line 1318 of file browsermainwindow.cpp.
 {
     tabWidget()->webViewSearch(m_tabWidget->currentIndex())->findPrevious();
 }
References WebViewSearch::findPrevious(), m_tabWidget, tabWidget(), and TabWidget::webViewSearch().
Referenced by setupMenu().
fileNew
void BrowserMainWindow::fileNew () private slot
Definition at line 1162 of file browsermainwindow.cpp.
 {
     BrowserMainWindow *window = BrowserApplication::instance()->newMainWindow();
     QSettings settings;
     settings.beginGroup(QLatin1String("MainWindow"));
     int startup = settings.value(QLatin1String("startupBehavior")).toInt();
     if (startup == 0)
         window->goHome();
 }
References goHome(), BrowserApplication::instance(), and BrowserApplication::newMainWindow().
Referenced by setupMenu().
fileOpen
void BrowserMainWindow::fileOpen () private slot
Definition at line 1174 of file browsermainwindow.cpp.
 {
     QString file = QFileDialog::getOpenFileName(this, tr("Open Web Resource"), QString(),
                    tr("Web Resources (*.html *.htm *.svg *.png *.gif *.svgz);;All files (*.*)"));
     if (file.isEmpty())
         return;
     tabWidget()->loadUrl(QUrl::fromLocalFile(file));
 }
References TabWidget::loadUrl(), and tabWidget().
Referenced by setupMenu().
filePrint
void BrowserMainWindow::filePrint () private slot
Definition at line 1195 of file browsermainwindow.cpp.
 {
     if (!currentTab())
         return;
     printRequested(currentTab()->page());
 }
References currentTab(), and printRequested().
Referenced by setupMenu().
filePrintPreview
void BrowserMainWindow::filePrintPreview () private slot
Definition at line 1185 of file browsermainwindow.cpp.
 {
     if (!currentTab())
         return;
     QPrintPreviewDialog dialog(this);
     connect(&dialog, SIGNAL(paintRequested(QPrinter *)),
             currentTab(), SLOT(print(QPrinter *)));
     dialog.exec();
 }
References currentTab().
Referenced by setupMenu().
fileSaveAs
void BrowserMainWindow::fileSaveAs () private slot
Definition at line 1126 of file browsermainwindow.cpp.
 {
     BrowserApplication::downloadManager()->download(currentTab()->url(), true);
 }
References currentTab(), DownloadManager::download(), and BrowserApplication::downloadManager().
Referenced by setupMenu().
geometryChangeRequested
void BrowserMainWindow::geometryChangeRequested (const QRect & geometry) private slot
Definition at line 1546 of file browsermainwindow.cpp.
 {
     setGeometry(geometry);
 }
Referenced by BrowserMainWindow().
goHome
void BrowserMainWindow::goHome () slot
Definition at line 1387 of file browsermainwindow.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("MainWindow"));
     QString home = settings.value(QLatin1String("home"), QLatin1String("about:home")).toString();
     tabWidget()->loadString(home);
 }
References TabWidget::loadString(), and tabWidget().
Referenced by fileNew(), BrowserApplication::postLaunch(), and setupMenu().
gotHTML
void BrowserMainWindow::gotHTML (QString & value) private slot
Definition at line 1381 of file browsermainwindow.cpp.
 {
     markup = value;
     emit notifyGotHTML();
 }
References markup, and notifyGotHTML().
Referenced by viewPageSource().
handleDevToolsRequested()
void BrowserMainWindow::handleDevToolsRequested (QWebEnginePage * source)
Definition at line 1560 of file browsermainwindow.cpp.
 {
     source->setDevToolsPage(createDevToolsWindow()->page());
     source->triggerAction(QWebEnginePage::InspectElement);
 }
References createDevToolsWindow().
Referenced by BrowserMainWindow().
keyPressEvent()
void BrowserMainWindow::keyPressEvent (QKeyEvent * event) protected
Definition at line 230 of file browsermainwindow.cpp.
 {
     switch (event->key()) {
     case Qt::Key_HomePage:
         m_historyHomeAction->trigger();
         event->accept();
         break;
     case Qt::Key_Favorites:
         m_bookmarksShowAllAction->trigger();
         event->accept();
         break;
     case Qt::Key_Search:
         m_toolsWebSearchAction->trigger();
         event->accept();
         break;
     case Qt::Key_OpenUrl:
         m_fileOpenLocationAction->trigger();
         event->accept();
         break;
     default:
         QMainWindow::keyPressEvent(event);
         break;
     }
 }
References m_bookmarksShowAllAction, m_fileOpenLocationAction, m_historyHomeAction, and m_toolsWebSearchAction.
lastTabClosed
void BrowserMainWindow::lastTabClosed () private slot
Definition at line 427 of file browsermainwindow.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("tabs"));
     bool quit = settings.value(QLatin1String("quitAsLastTabClosed"), true).toBool();
     if (quit)
         close();
     else
         m_tabWidget->makeNewTab(true);
 }
References m_tabWidget, and TabWidget::makeNewTab().
Referenced by BrowserMainWindow().
loadDefaultState()
void BrowserMainWindow::loadDefaultState () private
Definition at line 268 of file browsermainwindow.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("BrowserMainWindow"));
     QByteArray data = settings.value(QLatin1String("defaultState")).toByteArray();
     restoreState(data);
     settings.endGroup();
 }
References restoreState().
Referenced by BrowserMainWindow().
loadProgress
void BrowserMainWindow::loadProgress (int progress) private slot
Definition at line 1443 of file browsermainwindow.cpp.
 {
     if (progress < 100 && progress > 0) {
         disconnect(m_stopReloadAction, SIGNAL(triggered()), m_viewReloadAction, SLOT(trigger()));
         m_stopReloadAction->setIcon(m_stopIcon);
         connect(m_stopReloadAction, SIGNAL(triggered()), m_viewStopAction, SLOT(trigger()));
         updateStopReloadActionText(true);
     } else {
         disconnect(m_stopReloadAction, SIGNAL(triggered()), m_viewStopAction, SLOT(trigger()));
         m_stopReloadAction->setIcon(m_reloadIcon);
         connect(m_stopReloadAction, SIGNAL(triggered()), m_viewReloadAction, SLOT(trigger()));
         updateStopReloadActionText(false);
     }
 }
References m_reloadIcon, m_stopIcon, m_stopReloadAction, m_viewReloadAction, m_viewStopAction, and updateStopReloadActionText().
Referenced by BrowserMainWindow().
mousePressEvent()
void BrowserMainWindow::mousePressEvent (QMouseEvent * event) protected
Definition at line 1286 of file browsermainwindow.cpp.
 {
     switch (event->button()) {
     case Qt::XButton1:
         m_historyBackAction->activate(QAction::Trigger);
         break;
     case Qt::XButton2:
         m_historyForwardAction->activate(QAction::Trigger);
         break;
     default:
         QMainWindow::mousePressEvent(event);
         break;
     }
 }
References m_historyBackAction, and m_historyForwardAction.
notifyGotHTML
void BrowserMainWindow::notifyGotHTML () signal
Referenced by gotHTML(), and viewPageSource().
openActionUrl
void BrowserMainWindow::openActionUrl (QAction * action) private slot
Definition at line 1536 of file browsermainwindow.cpp.
 {
     int offset = action->data().toInt();
     QWebEngineHistory *history = currentTab()->history();
     if (offset < 0)
         history->goToItem(history->backItems(-1*offset).first()); // back
     else if (offset > 0)
         history->goToItem(history->forwardItems(history->count() - offset + 1).back()); // forward
 }
References currentTab().
Referenced by setupToolBar().
parentWindow()
BrowserMainWindow * BrowserMainWindow::parentWindow (QWidget * widget) static
Definition at line 255 of file browsermainwindow.cpp.
 {
     while (widget) {
         if (BrowserMainWindow *parent = qobject_cast<BrowserMainWindow*>(widget))
             return parent;
         widget = widget->parentWidget();
     }
     qWarning() << "BrowserMainWindow::" << __FUNCTION__ << " used with a widget none of whose parents is a main window.";
     return BrowserApplication::instance()->mainWindow();
 }
References BrowserApplication::instance(), and BrowserApplication::mainWindow().
Referenced by WebView::contextMenuEvent(), TabWidget::makeNewTab(), ToolbarSearch::showEnginesMenu(), and TabWidget::windowCloseRequested().
preferences
void BrowserMainWindow::preferences () private slot
Definition at line 1131 of file browsermainwindow.cpp.
 {
     SettingsDialog settingsDialog(this);
     settingsDialog.exec();
 }
Referenced by setupMenu().
printRequested
void BrowserMainWindow::printRequested (QWebEnginePage * page) private slot
Definition at line 1202 of file browsermainwindow.cpp.
 {
     QPrinter printer;
     QPrintDialog dialog(&printer, this);
     dialog.setWindowTitle(tr("Print Document"));
     if (dialog.exec() != QDialog::Accepted)
         return;
     page->print(&printer, [](bool a) {});
 }
Referenced by BrowserMainWindow(), and filePrint().
privacyChanged
void BrowserMainWindow::privacyChanged (bool isPrivate) slot
Definition at line 1249 of file browsermainwindow.cpp.
 {
     m_filePrivateBrowsingAction->setChecked(isPrivate);
     if (!isPrivate)
         tabWidget()->clear();
 }
References TabWidget::clear(), m_filePrivateBrowsingAction, and tabWidget().
privateBrowsing
void BrowserMainWindow::privateBrowsing () private slot
Definition at line 1212 of file browsermainwindow.cpp.
 {
     if (!BrowserApplication::isPrivate()) {
         QString title = tr("Are you sure you want to turn on private browsing?");
         QString text1 = tr("When private browsing is turned on, some actions concerning your privacy will be disabled:");
         QStringList actions;
         actions.append(tr("Webpages are not added to the history."));
         actions.append(tr("Items are automatically removed from the Downloads window."));
         actions.append(tr("Site icons won't be stored."));
         actions.append(tr("Session won't be saved."));
         actions.append(tr("Searches are not added to the pop-up menu in the search box."));
         actions.append(tr("No new network cache is written to disk."));
         QString text2 = tr("Until you close the window, you can still click the Back and Forward "
                            "buttons to return to the webpages you have opened.");
         QString message = QString(QLatin1String("<b>%1</b><p>%2</p><ul><li>%3</li></ul><p>%4</p>"))
                           .arg(title, text1, actions.join(QLatin1String("</li><li>")), text2);
         QMessageBox::StandardButton button = QMessageBox::question(this, tr("Private Browsing"), message,
                                              QMessageBox::Ok | QMessageBox::Cancel,
                                              QMessageBox::Ok);
         if (button == QMessageBox::Ok)
             BrowserApplication::setPrivate(true);
         else
             m_filePrivateBrowsingAction->setChecked(false);
     } else {
         BrowserApplication::setPrivate(false);
     }
 }
References BrowserApplication::isPrivate(), m_filePrivateBrowsingAction, and BrowserApplication::setPrivate().
Referenced by setupMenu().
restoreState()
bool BrowserMainWindow::restoreState (const QByteArray & state)
Definition at line 334 of file browsermainwindow.cpp.
 {
     QByteArray sd = state;
     QDataStream stream(&sd, QIODevice::ReadOnly);
     if (stream.atEnd())
         return false;
     qint32 marker;
     qint32 version;
     stream >> marker;
     stream >> version;
     if (marker != BrowserMainWindowMagic || !(version == 2 || version == 3))
         return false;
     QSize size;
     bool showToolbarDEAD;
     bool showBookmarksBarDEAD;
     bool showStatusbar;
     QByteArray tabState;
     QByteArray splitterState;
     bool showTabBarWhenOneTab;
     qint32 navigationBarLocation;
     qint32 bookmarkBarLocation;
     bool maximized;
     bool fullScreen;
     bool showMenuBar;
     QByteArray qMainWindowState;
     stream >> size;
     stream >> showToolbarDEAD;
     stream >> showBookmarksBarDEAD;
     stream >> showStatusbar;
     stream >> tabState;
     stream >> splitterState;
     stream >> showTabBarWhenOneTab;
     stream >> navigationBarLocation;
     stream >> bookmarkBarLocation;
     if (version >= 3) {
         stream >> maximized;
         stream >> fullScreen;
         stream >> showMenuBar;
         stream >> showMenuBar; // m_menuBarVisible DEAD
         stream >> m_statusBarVisible;
         stream >> qMainWindowState;
     } else {
         maximized = false;
         fullScreen = false;
         showMenuBar = true;
         m_statusBarVisible = showStatusbar;
     }
     if (size.isValid())
         resize(size);
     if (maximized)
         setWindowState(windowState() | Qt::WindowMaximized);
     if (fullScreen) {
         setWindowState(windowState() | Qt::WindowFullScreen);
         m_viewFullScreenAction->setChecked(true);
     }
     menuBar()->setVisible(showMenuBar);
     m_menuBarVisible = showMenuBar;
     statusBar()->setVisible(showStatusbar);
     m_navigationSplitter->restoreState(splitterState);
     tabWidget()->restoreState(tabState);
     m_tabWidget->tabBar()->setShowTabBarWhenOneTab(showTabBarWhenOneTab);
     if (qMainWindowState.isEmpty()) {
         m_navigationBar->setVisible(showToolbarDEAD);
         m_bookmarksToolbar->setVisible(showBookmarksBarDEAD);
         Qt::ToolBarArea navigationArea = Qt::ToolBarArea(navigationBarLocation);
         if (navigationArea != Qt::TopToolBarArea && navigationArea != Qt::NoToolBarArea)
             addToolBar(navigationArea, m_navigationBar);
         Qt::ToolBarArea bookmarkArea = Qt::ToolBarArea(bookmarkBarLocation);
         if (bookmarkArea != Qt::TopToolBarArea && bookmarkArea != Qt::NoToolBarArea)
             addToolBar(bookmarkArea, m_bookmarksToolbar);
     } else {
         QMainWindow::restoreState(qMainWindowState);
     }
 #if defined(Q_WS_MAC)
     m_bookmarksToolbarFrame->setVisible(m_bookmarksToolbar->isVisible());
 #endif
     return true;
 }
References BrowserMainWindowMagic, m_bookmarksToolbar, m_menuBarVisible, m_navigationBar, m_navigationSplitter, m_statusBarVisible, m_tabWidget, m_viewFullScreenAction, TabWidget::restoreState(), TabBar::setShowTabBarWhenOneTab(), TabWidget::tabBar(), and tabWidget().
Referenced by loadDefaultState(), and BrowserApplication::restoreLastSession().
retranslate()
void BrowserMainWindow::retranslate () private
Definition at line 906 of file browsermainwindow.cpp.
 {
     m_fileMenu->setTitle(tr("&File"));
     m_fileNewWindowAction->setText(tr("&New Window"));
     m_fileOpenFileAction->setText(tr("&Open File..."));
     m_fileOpenLocationAction->setText(tr("Open &Location..."));
     m_fileSaveAsAction->setText(tr("&Save As..."));
     m_fileImportBookmarksAction->setText(tr("&Import Bookmarks..."));
     m_fileExportBookmarksAction->setText(tr("&Export Bookmarks..."));
     m_filePrintPreviewAction->setText(tr("P&rint Preview..."));
     m_filePrintAction->setText(tr("&Print..."));
     m_filePrivateBrowsingAction->setText(tr("Private &Browsing..."));
     m_fileCloseWindow->setText(tr("Close Window"));
     m_fileQuit->setText(tr("&Quit"));
     m_editMenu->setTitle(tr("&Edit"));
     m_editUndoAction->setText(tr("&Undo"));
     m_editRedoAction->setText(tr("&Redo"));
     m_editCutAction->setText(tr("Cu&t"));
     m_editCopyAction->setText(tr("&Copy"));
     m_editPasteAction->setText(tr("&Paste"));
     m_editSelectAllAction->setText(tr("Select &All"));
     m_editFindAction->setText(tr("&Find"));
     m_editFindNextAction->setText(tr("Find Nex&t"));
     m_editFindPreviousAction->setText(tr("Find P&revious"));
     m_viewMenu->setTitle(tr("&View"));
     m_viewToolbarAction->setShortcut(tr("Ctrl+|"));
     m_viewBookmarkBarAction->setShortcut(tr("Alt+Ctrl+B"));
     m_viewStatusbarAction->setShortcut(tr("Ctrl+/"));
     m_viewShowMenuBarAction->setText(tr("Show Menu Bar"));
     m_viewReloadAction->setText(tr("&Reload Page"));
     m_viewStopAction->setText(tr("&Stop"));
     m_viewZoomInAction->setText(tr("Zoom &In"));
     m_viewZoomNormalAction->setText(tr("Zoom &Normal"));
     m_viewZoomOutAction->setText(tr("Zoom &Out"));
     m_viewZoomTextOnlyAction->setText(tr("Zoom &Text Only"));
     m_viewSourceAction->setText(tr("Page S&ource"));
     m_viewSourceAction->setShortcut(tr("Ctrl+Alt+U"));
     m_viewFullScreenAction->setText(tr("&Full Screen"));
     m_viewTextEncodingAction->setText(tr("Text Encoding"));
     m_historyMenu->setTitle(tr("Hi&story"));
     m_historyBackAction->setText(tr("Back"));
     m_historyForwardAction->setText(tr("Forward"));
     m_historyHomeAction->setText(tr("Home"));
     m_historyRestoreLastSessionAction->setText(tr("Restore Last Session"));
     m_bookmarksMenu->setTitle(tr("&Bookmarks"));
     m_bookmarksShowAllAction->setText(tr("Show All Bookmarks..."));
     m_bookmarksAddAction->setText(tr("Add Bookmark..."));
     m_bookmarksAddFolderAction->setText(tr("Add Folder..."));
     m_windowMenu->setTitle(tr("&Window"));
     m_toolsMenu->setTitle(tr("&Tools"));
     m_toolsWebSearchAction->setText(tr("Web &Search"));
     m_toolsWebSearchAction->setShortcut(QKeySequence(tr("Ctrl+K", "Web Search")));
     m_toolsClearPrivateDataAction->setText(tr("&Clear Private Data"));
     m_toolsClearPrivateDataAction->setShortcut(QKeySequence(tr("Ctrl+Shift+Delete", "Clear Private Data")));
     m_toolsPreferencesAction->setText(tr("Options..."));
     m_toolsPreferencesAction->setShortcut(tr("Ctrl+,"));
     m_toolsSearchManagerAction->setText(tr("Configure Search Engines..."));
     m_toolsUserAgentMenu->setTitle(tr("User Agent"));
     m_helpMenu->setTitle(tr("&Help"));
     m_helpChangeLanguageAction->setText(tr("Switch application language "));
     m_helpAboutQtAction->setText(tr("About &Qt"));
     m_helpAboutApplicationAction->setText(tr("About &%1", "About Browser").arg(QApplication::applicationName()));
     // Toolbar
     m_navigationBar->setWindowTitle(tr("Navigation"));
     m_bookmarksToolbar->setWindowTitle(tr("&Bookmarks"));
     m_stopReloadAction->setText(tr("Reload / Stop"));
     updateStopReloadActionText(false);
 }
References m_bookmarksAddAction, m_bookmarksAddFolderAction, m_bookmarksMenu, m_bookmarksShowAllAction, m_bookmarksToolbar, m_editCopyAction, m_editCutAction, m_editFindAction, m_editFindNextAction, m_editFindPreviousAction, m_editMenu, m_editPasteAction, m_editRedoAction, m_editSelectAllAction, m_editUndoAction, m_fileCloseWindow, m_fileExportBookmarksAction, m_fileImportBookmarksAction, m_fileMenu, m_fileNewWindowAction, m_fileOpenFileAction, m_fileOpenLocationAction, m_filePrintAction, m_filePrintPreviewAction, m_filePrivateBrowsingAction, m_fileQuit, m_fileSaveAsAction, m_helpAboutApplicationAction, m_helpAboutQtAction, m_helpChangeLanguageAction, m_helpMenu, m_historyBackAction, m_historyForwardAction, m_historyHomeAction, m_historyMenu, m_historyRestoreLastSessionAction, m_navigationBar, m_stopReloadAction, m_toolsClearPrivateDataAction, m_toolsMenu, m_toolsPreferencesAction, m_toolsSearchManagerAction, m_toolsUserAgentMenu, m_toolsWebSearchAction, m_viewBookmarkBarAction, m_viewFullScreenAction, m_viewMenu, m_viewReloadAction, m_viewShowMenuBarAction, m_viewSourceAction, m_viewStatusbarAction, m_viewStopAction, m_viewTextEncodingAction, m_viewToolbarAction, m_viewZoomInAction, m_viewZoomNormalAction, m_viewZoomOutAction, m_viewZoomTextOnlyAction, m_windowMenu, and updateStopReloadActionText().
Referenced by BrowserMainWindow(), and changeEvent().
runScriptOnOpenViews
void BrowserMainWindow::runScriptOnOpenViews (QString source) slot
Definition at line 1566 of file browsermainwindow.cpp.
 {
     for (int i =0; i < tabWidget()->count(); ++i)
         tabWidget()->webView(i)->page()->runJavaScript(source);
 }
References tabWidget(), and TabWidget::webView().
save
void BrowserMainWindow::save () private slot
Definition at line 285 of file browsermainwindow.cpp.
 {
     BrowserApplication::instance()->saveSession();
     QSettings settings;
     settings.beginGroup(QLatin1String("BrowserMainWindow"));
     QByteArray data = saveState(false);
     settings.setValue(QLatin1String("defaultState"), data);
     settings.endGroup();
 }
References BrowserApplication::instance(), BrowserApplication::saveSession(), and saveState().
saveState()
QByteArray BrowserMainWindow::saveState (bool withTabs = true) const
Definition at line 298 of file browsermainwindow.cpp.
 {
     int version = 3;
     QByteArray data;
     QDataStream stream(&data, QIODevice::WriteOnly);
     stream << qint32(BrowserMainWindowMagic);
     stream << qint32(version);
     // save the normal size so exiting fullscreen/maximize will work reasonably
     stream << normalGeometry().size();
     stream << !m_navigationBar->isHidden(); // DEAD
     stream << !m_bookmarksToolbar->isHidden(); // DEAD
     stream << !statusBar()->isHidden();
     if (withTabs)
         stream << tabWidget()->saveState();
     else
         stream << QByteArray();
     stream << m_navigationSplitter->saveState();
     stream << m_tabWidget->tabBar()->showTabBarWhenOneTab();
     stream << qint32(toolBarArea(m_navigationBar));
     stream << qint32(toolBarArea(m_bookmarksToolbar));
     // version 3
     stream << isMaximized();
     stream << isFullScreen();
     stream << menuBar()->isVisible();
     stream << m_menuBarVisible; // DEAD
     stream << m_statusBarVisible;
     stream << QMainWindow::saveState();
     return data;
 }
References BrowserMainWindowMagic, m_bookmarksToolbar, m_menuBarVisible, m_navigationBar, m_navigationSplitter, m_statusBarVisible, m_tabWidget, TabWidget::saveState(), TabBar::showTabBarWhenOneTab(), TabWidget::tabBar(), and tabWidget().
Referenced by save().
searchManagerAction()
QAction* BrowserMainWindow::searchManagerAction () const inline
Definition at line 104 of file browsermainwindow.h.
{
         return m_toolsSearchManagerAction;
     }
References m_toolsSearchManagerAction.
selectLineEdit
void BrowserMainWindow::selectLineEdit () private slot
Definition at line 1117 of file browsermainwindow.cpp.
 {
     if (m_navigationBar->isHidden())
         m_navigationBar->show();
     m_tabWidget->currentLocationBar()->selectAll();
     m_tabWidget->currentLocationBar()->setFocus();
 }
References TabWidget::currentLocationBar(), m_navigationBar, and m_tabWidget.
Referenced by setupMenu().
setupMenu()
void BrowserMainWindow::setupMenu () private
Definition at line 444 of file browsermainwindow.cpp.
 {
     m_menuBarVisible = true;
     new QShortcut(QKeySequence(Qt::Key_F6), this, SLOT(swapFocus()));
     // File
     m_fileMenu = new QMenu(menuBar());
     menuBar()->addMenu(m_fileMenu);
     m_fileNewWindowAction = new QAction(m_fileMenu);
     m_fileNewWindowAction->setShortcut(QKeySequence::New);
     connect(m_fileNewWindowAction, SIGNAL(triggered()),
             this, SLOT(fileNew()));
     m_fileMenu->addAction(m_fileNewWindowAction);
     m_fileMenu->addAction(m_tabWidget->newTabAction());
     m_fileOpenFileAction = new QAction(m_fileMenu);
     m_fileOpenFileAction->setShortcut(QKeySequence::Open);
     connect(m_fileOpenFileAction, SIGNAL(triggered()),
             this, SLOT(fileOpen()));
     m_fileMenu->addAction(m_fileOpenFileAction);
     m_fileOpenLocationAction = new QAction(m_fileMenu);
     // Add the location bar shortcuts familiar to users from other browsers
     QList<QKeySequence> openLocationShortcuts;
     openLocationShortcuts.append(QKeySequence(Qt::ControlModifier + Qt::Key_L));
     openLocationShortcuts.append(QKeySequence(Qt::AltModifier + Qt::Key_O));
     openLocationShortcuts.append(QKeySequence(Qt::AltModifier + Qt::Key_D));
     m_fileOpenLocationAction->setShortcuts(openLocationShortcuts);
     connect(m_fileOpenLocationAction, SIGNAL(triggered()),
             this, SLOT(selectLineEdit()));
     m_fileMenu->addAction(m_fileOpenLocationAction);
     m_fileMenu->addSeparator();
     m_fileMenu->addAction(m_tabWidget->closeTabAction());
     m_fileMenu->addSeparator();
     m_fileSaveAsAction = new QAction(m_fileMenu);
     m_fileSaveAsAction->setShortcut(QKeySequence::Save);
     connect(m_fileSaveAsAction, SIGNAL(triggered()),
             this, SLOT(fileSaveAs()));
     m_fileMenu->addAction(m_fileSaveAsAction);
     m_fileMenu->addSeparator();
     BookmarksManager *bookmarksManager = BrowserApplication::bookmarksManager();
     m_fileImportBookmarksAction = new QAction(m_fileMenu);
     connect(m_fileImportBookmarksAction, SIGNAL(triggered()),
             bookmarksManager, SLOT(importBookmarks()));
     m_fileMenu->addAction(m_fileImportBookmarksAction);
     m_fileExportBookmarksAction = new QAction(m_fileMenu);
     connect(m_fileExportBookmarksAction, SIGNAL(triggered()),
             bookmarksManager, SLOT(exportBookmarks()));
     m_fileMenu->addAction(m_fileExportBookmarksAction);
     m_fileMenu->addSeparator();
     m_filePrintPreviewAction= new QAction(m_fileMenu);
     connect(m_filePrintPreviewAction, SIGNAL(triggered()),
             this, SLOT(filePrintPreview()));
     m_fileMenu->addAction(m_filePrintPreviewAction);
     m_filePrintAction = new QAction(m_fileMenu);
     m_filePrintAction->setShortcut(QKeySequence::Print);
     connect(m_filePrintAction, SIGNAL(triggered()),
             this, SLOT(filePrint()));
     m_fileMenu->addAction(m_filePrintAction);
     m_fileMenu->addSeparator();
     m_filePrivateBrowsingAction = new QAction(m_fileMenu);
     connect(m_filePrivateBrowsingAction, SIGNAL(triggered()),
             this, SLOT(privateBrowsing()));
     m_filePrivateBrowsingAction->setCheckable(true);
     m_fileMenu->addAction(m_filePrivateBrowsingAction);
     m_fileMenu->addSeparator();
     m_fileCloseWindow = new QAction(m_fileMenu);
     connect(m_fileCloseWindow, SIGNAL(triggered()), this, SLOT(close()));
     m_fileCloseWindow->setShortcut(QKeySequence(Qt::CTRL | Qt::SHIFT | Qt::Key_W));
     m_fileMenu->addAction(m_fileCloseWindow);
     m_fileQuit = new QAction(m_fileMenu);
     int kdeSessionVersion = QString::fromLocal8Bit(qgetenv("KDE_SESSION_VERSION")).toInt();
     if (kdeSessionVersion != 0)
         connect(m_fileQuit, SIGNAL(triggered()), this, SLOT(close()));
     else
         connect(m_fileQuit, SIGNAL(triggered()), BrowserApplication::instance(), SLOT(quitBrowser()));
     m_fileQuit->setShortcut(QKeySequence(Qt::CTRL | Qt::Key_Q));
     m_fileMenu->addAction(m_fileQuit);
 #if defined(Q_WS_X11)
     m_fileNewWindowAction->setIcon(QIcon::fromTheme(QLatin1String("window-new")));
     m_fileOpenFileAction->setIcon(QIcon::fromTheme(QLatin1String("document-open")));
     m_filePrintPreviewAction->setIcon(QIcon::fromTheme(QLatin1String("document-print-preview")));
     m_filePrintAction->setIcon(QIcon::fromTheme(QLatin1String("document-print")));
     m_fileSaveAsAction->setIcon(QIcon::fromTheme(QLatin1String("document-save-as")));
     m_fileCloseWindow->setIcon(QIcon::fromTheme(QLatin1String("window-close")));
     m_fileQuit->setIcon(QIcon::fromTheme(QLatin1String("application-exit")));
 #endif
     // Edit
     m_editMenu = new QMenu(menuBar());
     menuBar()->addMenu(m_editMenu);
     m_editUndoAction = new QAction(m_editMenu);
     m_editUndoAction->setShortcuts(QKeySequence::Undo);
     m_tabWidget->addWebAction(m_editUndoAction, QWebEnginePage::Undo);
     m_editMenu->addAction(m_editUndoAction);
     m_editRedoAction = new QAction(m_editMenu);
     m_editRedoAction->setShortcuts(QKeySequence::Redo);
     m_tabWidget->addWebAction(m_editRedoAction, QWebEnginePage::Redo);
     m_editMenu->addAction(m_editRedoAction);
     m_editMenu->addSeparator();
     m_editCutAction = new QAction(m_editMenu);
     m_editCutAction->setShortcuts(QKeySequence::Cut);
     m_tabWidget->addWebAction(m_editCutAction, QWebEnginePage::Cut);
     m_editMenu->addAction(m_editCutAction);
     m_editCopyAction = new QAction(m_editMenu);
     m_editCopyAction->setShortcuts(QKeySequence::Copy);
     m_tabWidget->addWebAction(m_editCopyAction, QWebEnginePage::Copy);
     m_editMenu->addAction(m_editCopyAction);
     m_editPasteAction = new QAction(m_editMenu);
     m_editPasteAction->setShortcuts(QKeySequence::Paste);
     m_tabWidget->addWebAction(m_editPasteAction, QWebEnginePage::Paste);
     m_editMenu->addAction(m_editPasteAction);
     m_editSelectAllAction = new QAction(m_editMenu);
     m_editSelectAllAction->setShortcuts(QKeySequence::SelectAll);
     m_tabWidget->addWebAction(m_editSelectAllAction, QWebEnginePage::SelectAll);
     m_editMenu->addAction(m_editSelectAllAction);
     m_editMenu->addSeparator();
     m_editFindAction = new QAction(m_editMenu);
     m_editFindAction->setShortcuts(QKeySequence::Find);
     connect(m_editFindAction, SIGNAL(triggered()), this, SLOT(editFind()));
     m_editMenu->addAction(m_editFindAction);
     new QShortcut(QKeySequence(Qt::Key_Slash), this, SLOT(editFind()));
     m_editFindNextAction = new QAction(m_editMenu);
     m_editFindNextAction->setShortcuts(QKeySequence::FindNext);
     connect(m_editFindNextAction, SIGNAL(triggered()), this, SLOT(editFindNext()));
     m_editMenu->addAction(m_editFindNextAction);
     m_editFindPreviousAction = new QAction(m_editMenu);
     m_editFindPreviousAction->setShortcuts(QKeySequence::FindPrevious);
     connect(m_editFindPreviousAction, SIGNAL(triggered()), this, SLOT(editFindPrevious()));
     m_editMenu->addAction(m_editFindPreviousAction);
 #if defined(Q_WS_X11)
     m_editUndoAction->setIcon(QIcon::fromTheme(QLatin1String("edit-undo")));
     m_editRedoAction->setIcon(QIcon::fromTheme(QLatin1String("edit-redo")));
     m_editCutAction->setIcon(QIcon::fromTheme(QLatin1String("edit-cut")));
     m_editCopyAction->setIcon(QIcon::fromTheme(QLatin1String("edit-copy")));
     m_editPasteAction->setIcon(QIcon::fromTheme(QLatin1String("edit-paste")));
     m_editSelectAllAction->setIcon(QIcon::fromTheme(QLatin1String("edit-select-all")));
     m_editFindAction->setIcon(QIcon::fromTheme(QLatin1String("edit-find")));
 #endif
     // View
     m_viewMenu = new QMenu(menuBar());
     connect(m_viewMenu, SIGNAL(aboutToShow()),
             this, SLOT(aboutToShowViewMenu()));
     menuBar()->addMenu(m_viewMenu);
     m_viewShowMenuBarAction = new QAction(m_viewMenu);
     m_viewShowMenuBarAction->setShortcut(QKeySequence(Qt::CTRL | Qt::Key_M));
     connect(m_viewShowMenuBarAction, SIGNAL(triggered()), this, SLOT(viewMenuBar()));
     addAction(m_viewShowMenuBarAction);
     m_viewToolbarAction = new QAction(this);
     connect(m_viewToolbarAction, SIGNAL(triggered()), this, SLOT(viewToolbar()));
     m_viewMenu->addAction(m_viewToolbarAction);
     m_viewBookmarkBarAction = new QAction(m_viewMenu);
     connect(m_viewBookmarkBarAction, SIGNAL(triggered()), this, SLOT(viewBookmarksBar()));
     m_viewMenu->addAction(m_viewBookmarkBarAction);
     QAction *viewTabBarAction = m_tabWidget->tabBar()->viewTabBarAction();
     m_viewMenu->addAction(viewTabBarAction);
     connect(viewTabBarAction, SIGNAL(toggled(bool)),
             m_autoSaver, SLOT(changeOccurred()));
     m_viewStatusbarAction = new QAction(m_viewMenu);
     connect(m_viewStatusbarAction, SIGNAL(triggered()), this, SLOT(viewStatusbar()));
     m_viewMenu->addAction(m_viewStatusbarAction);
     m_viewMenu->addSeparator();
     m_viewStopAction = new QAction(m_viewMenu);
     QList<QKeySequence> shortcuts;
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_Period));
     shortcuts.append(Qt::Key_Escape);
     m_viewStopAction->setShortcuts(shortcuts);
     m_tabWidget->addWebAction(m_viewStopAction, QWebEnginePage::Stop);
     m_viewMenu->addAction(m_viewStopAction);
     m_viewReloadAction = new QAction(m_viewMenu);
     shortcuts.clear();
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_R));
     shortcuts.append(QKeySequence(Qt::Key_F5));
     m_viewReloadAction->setShortcuts(shortcuts);
     m_tabWidget->addWebAction(m_viewReloadAction, QWebEnginePage::Reload);
     m_viewMenu->addAction(m_viewReloadAction);
     m_viewZoomInAction = new QAction(m_viewMenu);
     shortcuts.clear();
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_Plus));
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_Equal));
     m_viewZoomInAction->setShortcuts(shortcuts);
     connect(m_viewZoomInAction, SIGNAL(triggered()),
             this, SLOT(zoomIn()));
     m_viewMenu->addAction(m_viewZoomInAction);
     m_viewZoomNormalAction = new QAction(m_viewMenu);
     m_viewZoomNormalAction->setShortcut(QKeySequence(Qt::CTRL | Qt::Key_0));
     connect(m_viewZoomNormalAction, SIGNAL(triggered()),
             this, SLOT(zoomNormal()));
     m_viewMenu->addAction(m_viewZoomNormalAction);
     m_viewZoomOutAction = new QAction(m_viewMenu);
     shortcuts.clear();
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_Minus));
     shortcuts.append(QKeySequence(Qt::CTRL | Qt::Key_Underscore));
     m_viewZoomOutAction->setShortcuts(shortcuts);
     connect(m_viewZoomOutAction, SIGNAL(triggered()),
             this, SLOT(zoomOut()));
     m_viewMenu->addAction(m_viewZoomOutAction);
     m_viewZoomTextOnlyAction = new QAction(m_viewMenu);
     m_viewZoomTextOnlyAction->setCheckable(true);
     connect(m_viewZoomTextOnlyAction, SIGNAL(toggled(bool)),
             BrowserApplication::instance(), SLOT(setZoomTextOnly(bool)));
     connect(BrowserApplication::instance(), SIGNAL(zoomTextOnlyChanged(bool)),
             this, SLOT(zoomTextOnlyChanged(bool)));
     m_viewMenu->addAction(m_viewZoomTextOnlyAction);
     m_viewFullScreenAction = new QAction(m_viewMenu);
     m_viewFullScreenAction->setShortcut(Qt::Key_F11);
     connect(m_viewFullScreenAction, SIGNAL(triggered(bool)),
             this, SLOT(viewFullScreen(bool)));
     m_viewFullScreenAction->setCheckable(true);
     m_viewMenu->addAction(m_viewFullScreenAction);
     m_viewMenu->addSeparator();
     m_viewSourceAction = new QAction(m_viewMenu);
     connect(m_viewSourceAction, SIGNAL(triggered()),
             this, SLOT(viewPageSource()));
     m_viewMenu->addAction(m_viewSourceAction);
     m_viewMenu->addSeparator();
     m_viewTextEncodingAction = new QAction(m_viewMenu);
     m_viewMenu->addAction(m_viewTextEncodingAction);
     m_viewTextEncodingMenu = new QMenu(m_viewMenu);
     m_viewTextEncodingAction->setMenu(m_viewTextEncodingMenu);
     connect(m_viewTextEncodingMenu, SIGNAL(aboutToShow()),
             this, SLOT(aboutToShowTextEncodingMenu()));
     connect(m_viewTextEncodingMenu, SIGNAL(triggered(QAction *)),
             this, SLOT(viewTextEncoding(QAction *)));
     m_stopIcon = style()->standardIcon(QStyle::SP_BrowserStop);
     m_reloadIcon = style()->standardIcon(QStyle::SP_BrowserReload);
 #if defined(Q_WS_X11)
     m_viewStopAction->setIcon(m_stopIcon);
     m_viewReloadAction->setIcon(m_reloadIcon);
     m_viewZoomInAction->setIcon(QIcon::fromTheme(QLatin1String("zoom-in")));
     m_viewZoomNormalAction->setIcon(QIcon::fromTheme(QLatin1String("zoom-original")));
     m_viewZoomOutAction->setIcon(QIcon::fromTheme(QLatin1String("zoom-out")));
     m_viewFullScreenAction->setIcon(QIcon::fromTheme(QLatin1String("view-fullscreen")));
 #endif
     // History
     m_historyMenu = new HistoryMenu(this);
     connect(m_historyMenu, SIGNAL(openUrl(const QUrl&, const QString&)),
             m_tabWidget, SLOT(loadUrlFromUser(const QUrl&, const QString&)));
     menuBar()->addMenu(m_historyMenu);
     QList<QAction*> historyActions;
     m_historyBackAction = new QAction(this);
     m_tabWidget->addWebAction(m_historyBackAction, QWebEnginePage::Back);
     m_historyBackAction->setShortcuts(QKeySequence::Back);
 #if !defined(Q_WS_X11)
     m_historyBackAction->setIconVisibleInMenu(false);
 #endif
     m_historyForwardAction = new QAction(this);
     m_tabWidget->addWebAction(m_historyForwardAction, QWebEnginePage::Forward);
     m_historyForwardAction->setShortcuts(QKeySequence::Forward);
 #if !defined(Q_WS_X11)
     m_historyForwardAction->setIconVisibleInMenu(false);
 #endif
     m_historyHomeAction = new QAction(this);
     connect(m_historyHomeAction, SIGNAL(triggered()), this, SLOT(goHome()));
     m_historyHomeAction->setShortcut(QKeySequence(Qt::CTRL | Qt::SHIFT | Qt::Key_H));
     m_historyRestoreLastSessionAction = new QAction(this);
     connect(m_historyRestoreLastSessionAction, SIGNAL(triggered()),
             BrowserApplication::instance(), SLOT(restoreLastSession()));
     m_historyRestoreLastSessionAction->setEnabled(BrowserApplication::instance()->canRestoreSession());
     historyActions.append(m_historyBackAction);
     historyActions.append(m_historyForwardAction);
     historyActions.append(m_historyHomeAction);
     historyActions.append(m_tabWidget->recentlyClosedTabsAction());
     historyActions.append(m_historyRestoreLastSessionAction);
     m_historyMenu->setInitialActions(historyActions);
 #if defined(Q_WS_X11)
     m_historyRestoreLastSessionAction->setIcon(QIcon::fromTheme(QLatin1String("document-revert")));
     m_historyHomeAction->setIcon(QIcon::fromTheme(QLatin1String("go-home")));
 #endif
     // Bookmarks
     m_bookmarksMenu = new BookmarksMenuBarMenu(this);
     connect(m_bookmarksMenu, SIGNAL(openUrl(const QUrl&, const QString &)),
             m_tabWidget, SLOT(loadUrlFromUser(const QUrl&, const QString&)));
     connect(m_bookmarksMenu, SIGNAL(openUrl(const QUrl&, TabWidget::OpenUrlIn, const QString&)),
             m_tabWidget, SLOT(loadUrl(const QUrl&, TabWidget::OpenUrlIn, const QString&)));
     menuBar()->addMenu(m_bookmarksMenu);
     m_bookmarksShowAllAction = new QAction(this);
     m_bookmarksShowAllAction->setShortcut(QKeySequence(Qt::CTRL | Qt::SHIFT | Qt::Key_B));
     connect(m_bookmarksShowAllAction, SIGNAL(triggered()),
             this, SLOT(showBookmarksDialog()));
     m_bookmarksAddAction = new QAction(this);
     m_bookmarksAddAction->setIcon(QIcon(QLatin1String(":addbookmark.png")));
 #if !defined(Q_WS_X11)
     m_bookmarksAddAction->setIconVisibleInMenu(false);
 #endif
     connect(m_bookmarksAddAction, SIGNAL(triggered()),
             this, SLOT(addBookmark()));
     m_bookmarksAddAction->setShortcut(QKeySequence(Qt::CTRL | Qt::Key_D));
     m_bookmarksAddFolderAction = new QAction(this);
     connect(m_bookmarksAddFolderAction, SIGNAL(triggered()),
             this, SLOT(addBookmarkFolder()));
     QList<QAction*> bookmarksActions;
     bookmarksActions.append(m_bookmarksShowAllAction);
     bookmarksActions.append(m_bookmarksAddAction);
     bookmarksActions.append(tabWidget()->bookmarkTabsAction());
     bookmarksActions.append(m_bookmarksAddFolderAction);
     m_bookmarksMenu->setInitialActions(bookmarksActions);
     m_bookmarksAddFolderAction->setIcon(QIcon::fromTheme(QLatin1String("folder-new")));
     m_bookmarksShowAllAction->setIcon(QIcon::fromTheme(QLatin1String("user-bookmarks")));
     // Window
     m_windowMenu = new QMenu(menuBar());
     menuBar()->addMenu(m_windowMenu);
     connect(m_windowMenu, SIGNAL(aboutToShow()),
             this, SLOT(aboutToShowWindowMenu()));
     aboutToShowWindowMenu();
     // Tools
     m_toolsMenu = new QMenu(menuBar());
     menuBar()->addMenu(m_toolsMenu);
     m_toolsWebSearchAction = new QAction(m_toolsMenu);
     connect(m_toolsWebSearchAction, SIGNAL(triggered()),
             this, SLOT(webSearch()));
     m_toolsMenu->addAction(m_toolsWebSearchAction);
     m_toolsClearPrivateDataAction = new QAction(m_toolsMenu);
     connect(m_toolsClearPrivateDataAction, SIGNAL(triggered()),
             this, SLOT(clearPrivateData()));
     m_toolsMenu->addAction(m_toolsClearPrivateDataAction);
     m_toolsSearchManagerAction = new QAction(m_toolsMenu);
     m_toolsSearchManagerAction->setMenuRole(QAction::NoRole);
     connect(m_toolsSearchManagerAction, SIGNAL(triggered()),
             this, SLOT(showSearchDialog()));
     m_toolsMenu->addAction(m_toolsSearchManagerAction);
     m_toolsUserAgentMenu = new UserAgentMenu(m_toolsMenu);
     m_toolsMenu->addMenu(m_toolsUserAgentMenu);
     m_toolsMenu->addSeparator();
     m_toolsPreferencesAction = new QAction(m_toolsMenu);
     m_toolsPreferencesAction->setMenuRole(QAction::PreferencesRole);
     connect(m_toolsPreferencesAction, SIGNAL(triggered()),
             this, SLOT(preferences()));
     m_toolsMenu->addAction(m_toolsPreferencesAction);
     // Help
     m_helpMenu = new QMenu(menuBar());
     menuBar()->addMenu(m_helpMenu);
     m_helpChangeLanguageAction = new QAction(m_helpMenu);
     connect(m_helpChangeLanguageAction, SIGNAL(triggered()),
             BrowserApplication::languageManager(), SLOT(chooseNewLanguage()));
     m_helpMenu->addAction(m_helpChangeLanguageAction);
     m_helpMenu->addSeparator();
     m_helpAboutQtAction = new QAction(m_helpMenu);
     connect(m_helpAboutQtAction, SIGNAL(triggered()),
             qApp, SLOT(aboutQt()));
     m_helpMenu->addAction(m_helpAboutQtAction);
     m_helpAboutApplicationAction = new QAction(m_helpMenu);
     connect(m_helpAboutApplicationAction, SIGNAL(triggered()),
             this, SLOT(aboutApplication()));
     m_helpMenu->addAction(m_helpAboutApplicationAction);
 #if defined(Q_WS_X11)
     m_helpChangeLanguageAction->setIcon(QIcon::fromTheme(QLatin1String("preferences-desktop-locale")));
     m_helpAboutQtAction->setIcon(QPixmap(QLatin1String(":/trolltech/qmessagebox/images/qtlogo-64.png")));
     m_helpAboutApplicationAction->setIcon(windowIcon());
 #endif
 }
References aboutApplication(), aboutToShowTextEncodingMenu(), aboutToShowViewMenu(), aboutToShowWindowMenu(), addBookmark(), addBookmarkFolder(), TabWidget::addWebAction(), BrowserApplication::bookmarksManager(), clearPrivateData(), TabWidget::closeTabAction(), editFind(), editFindNext(), editFindPrevious(), fileNew(), fileOpen(), filePrint(), filePrintPreview(), fileSaveAs(), goHome(), BrowserApplication::instance(), BrowserApplication::languageManager(), m_autoSaver, m_bookmarksAddAction, m_bookmarksAddFolderAction, m_bookmarksMenu, m_bookmarksShowAllAction, m_editCopyAction, m_editCutAction, m_editFindAction, m_editFindNextAction, m_editFindPreviousAction, m_editMenu, m_editPasteAction, m_editRedoAction, m_editSelectAllAction, m_editUndoAction, m_fileCloseWindow, m_fileExportBookmarksAction, m_fileImportBookmarksAction, m_fileMenu, m_fileNewWindowAction, m_fileOpenFileAction, m_fileOpenLocationAction, m_filePrintAction, m_filePrintPreviewAction, m_filePrivateBrowsingAction, m_fileQuit, m_fileSaveAsAction, m_helpAboutApplicationAction, m_helpAboutQtAction, m_helpChangeLanguageAction, m_helpMenu, m_historyBackAction, m_historyForwardAction, m_historyHomeAction, m_historyMenu, m_historyRestoreLastSessionAction, m_menuBarVisible, m_reloadIcon, m_stopIcon, m_tabWidget, m_toolsClearPrivateDataAction, m_toolsMenu, m_toolsPreferencesAction, m_toolsSearchManagerAction, m_toolsUserAgentMenu, m_toolsWebSearchAction, m_viewBookmarkBarAction, m_viewFullScreenAction, m_viewMenu, m_viewReloadAction, m_viewShowMenuBarAction, m_viewSourceAction, m_viewStatusbarAction, m_viewStopAction, m_viewTextEncodingAction, m_viewTextEncodingMenu, m_viewToolbarAction, m_viewZoomInAction, m_viewZoomNormalAction, m_viewZoomOutAction, m_viewZoomTextOnlyAction, m_windowMenu, TabWidget::newTabAction(), preferences(), privateBrowsing(), TabWidget::recentlyClosedTabsAction(), selectLineEdit(), BookmarksMenuBarMenu::setInitialActions(), HistoryMenu::setInitialActions(), showBookmarksDialog(), showSearchDialog(), swapFocus(), TabWidget::tabBar(), tabWidget(), viewBookmarksBar(), viewFullScreen(), viewMenuBar(), viewPageSource(), viewStatusbar(), TabBar::viewTabBarAction(), viewTextEncoding(), viewToolbar(), webSearch(), zoomIn(), zoomNormal(), zoomOut(), and zoomTextOnlyChanged().
Referenced by BrowserMainWindow().
setupToolBar()
void BrowserMainWindow::setupToolBar () private
Definition at line 984 of file browsermainwindow.cpp.
 {
     setUnifiedTitleAndToolBarOnMac(true);
     m_navigationBar = new QToolBar(this);
     m_navigationBar->setObjectName(QLatin1String("NavigationToolBar"));
     addToolBar(m_navigationBar);
     m_historyBackAction->setIcon(style()->standardIcon(QStyle::SP_ArrowBack, nullptr, this));
     m_historyBackMenu = new QMenu(this);
     m_historyBackAction->setMenu(m_historyBackMenu);
     connect(m_historyBackMenu, SIGNAL(aboutToShow()),
             this, SLOT(aboutToShowBackMenu()));
     connect(m_historyBackMenu, SIGNAL(triggered(QAction *)),
             this, SLOT(openActionUrl(QAction *)));
     m_navigationBar->addAction(m_historyBackAction);
     m_historyForwardAction->setIcon(style()->standardIcon(QStyle::SP_ArrowForward, nullptr, this));
     m_historyForwardMenu = new QMenu(this);
     connect(m_historyForwardMenu, SIGNAL(aboutToShow()),
             this, SLOT(aboutToShowForwardMenu()));
     connect(m_historyForwardMenu, SIGNAL(triggered(QAction *)),
             this, SLOT(openActionUrl(QAction *)));
     m_historyForwardAction->setMenu(m_historyForwardMenu);
     m_navigationBar->addAction(m_historyForwardAction);
     m_stopReloadAction = new QAction(this);
     m_stopReloadAction->setIcon(m_reloadIcon);
     m_navigationBar->addAction(m_stopReloadAction);
     m_navigationSplitter = new QSplitter(m_navigationBar);
     m_navigationSplitter->addWidget(m_tabWidget->locationBarStack());
     m_toolbarSearch = new ToolbarSearch(m_navigationBar);
     m_navigationSplitter->addWidget(m_toolbarSearch);
     connect(m_toolbarSearch, SIGNAL(search(const QUrl&, TabWidget::OpenUrlIn)),
             m_tabWidget, SLOT(loadUrl(const QUrl&, TabWidget::OpenUrlIn)));
     m_navigationSplitter->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Maximum);
     m_tabWidget->locationBarStack()->setMinimumWidth(120);
     m_navigationSplitter->setCollapsible(0, false);
     m_navigationBar->addWidget(m_navigationSplitter);
     int splitterWidth = m_navigationSplitter->width();
     QList<int> sizes;
     sizes << (int)((double)splitterWidth * .80) << (int)((double)splitterWidth * .20);
     m_navigationSplitter->setSizes(sizes);
 }
References aboutToShowBackMenu(), aboutToShowForwardMenu(), TabWidget::locationBarStack(), m_historyBackAction, m_historyBackMenu, m_historyForwardAction, m_historyForwardMenu, m_navigationBar, m_navigationSplitter, m_reloadIcon, m_stopReloadAction, m_tabWidget, m_toolbarSearch, and openActionUrl().
Referenced by BrowserMainWindow().
showBookmarksDialog
void BrowserMainWindow::showBookmarksDialog () private slot
Definition at line 1030 of file browsermainwindow.cpp.
 {
     BookmarksDialog *dialog = new BookmarksDialog(this);
     dialog->setAttribute(Qt::WA_DeleteOnClose);
     connect(dialog, SIGNAL(openUrl(const QUrl&, TabWidget::OpenUrlIn, const QString &)),
             m_tabWidget, SLOT(loadUrl(const QUrl&, TabWidget::OpenUrlIn, const QString &)));
     dialog->show();
 }
References m_tabWidget.
Referenced by setupMenu().
showMenuBarAction()
QAction * BrowserMainWindow::showMenuBarAction () const
Definition at line 439 of file browsermainwindow.cpp.
 {
     return m_viewShowMenuBarAction;
 }
References m_viewShowMenuBarAction.
Referenced by WebView::contextMenuEvent().
showSearchDialog
void BrowserMainWindow::showSearchDialog () private slot
Definition at line 1458 of file browsermainwindow.cpp.
 {
     OpenSearchDialog dialog(this);
     dialog.exec();
 }
Referenced by setupMenu().
showWindow
void BrowserMainWindow::showWindow () private slot
Definition at line 1522 of file browsermainwindow.cpp.
 {
     if (QAction *action = qobject_cast<QAction*>(sender())) {
         QVariant v = action->data();
         if (v.canConvert<int>()) {
             int offset = qvariant_cast<int>(v);
             QList<BrowserMainWindow*> windows = BrowserApplication::instance()->mainWindows();
             windows.at(offset)->activateWindow();
             windows.at(offset)->raise();
             windows.at(offset)->currentTab()->setFocus();
         }
     }
 }
References BrowserApplication::instance(), and BrowserApplication::mainWindows().
Referenced by aboutToShowWindowMenu().
sizeHint()
QSize BrowserMainWindow::sizeHint () const
Definition at line 277 of file browsermainwindow.cpp.
 {
     const QScreen *primaryScreen = qApp->primaryScreen();
     QRect desktopRect = primaryScreen->geometry();
     QSize size = desktopRect.size() * 0.9;
     return size;
 }
swapFocus
void BrowserMainWindow::swapFocus () private slot
Definition at line 1407 of file browsermainwindow.cpp.
 {
     if (currentTab()->hasFocus()) {
         m_tabWidget->currentLocationBar()->setFocus();
         m_tabWidget->currentLocationBar()->selectAll();
     } else {
         currentTab()->setFocus();
     }
 }
References TabWidget::currentLocationBar(), currentTab(), and m_tabWidget.
Referenced by setupMenu().
tabWidget()
TabWidget * BrowserMainWindow::tabWidget () const
Definition at line 1417 of file browsermainwindow.cpp.
 {
     return m_tabWidget;
 }
References m_tabWidget.
Referenced by editFind(), editFindNext(), editFindPrevious(), fileOpen(), goHome(), BrowserApplication::messageReceived(), BrowserApplication::openUrl(), BrowserApplication::postLaunch(), privacyChanged(), restoreState(), runScriptOnOpenViews(), saveState(), SettingsDialog::saveToSettings(), and setupMenu().
toolbarSearch()
ToolbarSearch * BrowserMainWindow::toolbarSearch () const
Definition at line 1427 of file browsermainwindow.cpp.
 {
     return m_toolbarSearch;
 }
References m_toolbarSearch.
updateStatusbar
void BrowserMainWindow::updateStatusbar (const QString & string) private slot
Definition at line 1137 of file browsermainwindow.cpp.
 {
     statusBar()->showMessage(string, 2000);
 }
updateStopReloadActionText()
void BrowserMainWindow::updateStopReloadActionText (bool loading) private
Definition at line 1432 of file browsermainwindow.cpp.
 {
     if (loading) {
         m_stopReloadAction->setToolTip(tr("Stop loading the current page"));
         m_stopReloadAction->setIconText(tr("Stop"));
     } else {
         m_stopReloadAction->setToolTip(tr("Reload the current page"));
         m_stopReloadAction->setIconText(tr("Reload"));
     }
 }
References m_stopReloadAction.
Referenced by loadProgress(), and retranslate().
updateWindowTitle
void BrowserMainWindow::updateWindowTitle (const QString & title = QString()) private slot
Definition at line 1142 of file browsermainwindow.cpp.
 {
     if (title.isEmpty()) {
         setWindowTitle(QApplication::applicationName());
     } else {
 #if defined(Q_WS_MAC)
         setWindowTitle(title);
 #else
         setWindowTitle(tr("%1 - Endorphin", "Page title and Browser name").arg(title));
 #endif
     }
 }
Referenced by BrowserMainWindow().
viewBookmarksBar
void BrowserMainWindow::viewBookmarksBar () private slot
Definition at line 1083 of file browsermainwindow.cpp.
 {
     if (m_bookmarksToolbar->isVisible()) {
         m_bookmarksToolbar->hide();
 #if defined(Q_WS_MAC)
         m_bookmarksToolbarFrame->hide();
 #endif
     } else {
         m_bookmarksToolbar->show();
 #if defined(Q_WS_MAC)
         m_bookmarksToolbarFrame->show();
 #endif
     }
     m_autoSaver->changeOccurred();
 }
References AutoSaver::changeOccurred(), m_autoSaver, and m_bookmarksToolbar.
Referenced by setupMenu().
viewFullScreen
void BrowserMainWindow::viewFullScreen (bool enable) private slot
Definition at line 1344 of file browsermainwindow.cpp.
 {
     if (makeFullScreen) {
         setUnifiedTitleAndToolBarOnMac(false);
         setWindowState(windowState() | Qt::WindowFullScreen);
         menuBar()->hide();
         statusBar()->hide();
     } else {
         setWindowState(windowState() & ~Qt::WindowFullScreen);
         setUnifiedTitleAndToolBarOnMac(true);
         menuBar()->setVisible(m_menuBarVisible);
         statusBar()->setVisible(m_statusBarVisible);
     }
 }
References m_menuBarVisible, and m_statusBarVisible.
Referenced by setupMenu().
viewMenuBar
void BrowserMainWindow::viewMenuBar () private slot
Definition at line 1065 of file browsermainwindow.cpp.
 {
     menuBar()->setVisible(!menuBar()->isVisible());
     m_menuBarVisible = menuBar()->isVisible();
     m_autoSaver->changeOccurred();
 }
References AutoSaver::changeOccurred(), m_autoSaver, and m_menuBarVisible.
Referenced by setupMenu().
viewPageSource
void BrowserMainWindow::viewPageSource () private slot
Definition at line 1361 of file browsermainwindow.cpp.
 {
     if (!currentTab())
         return;
     QString title = currentTab()->title();
     QEventLoop loop;
     connect(this, SIGNAL(notifyGotHTML()), &loop, SLOT(quit()));
     currentTab()->page()->toHtml([this](const QVariant &v)
     {
         QString tmp = v.toString();
         this->gotHTML(tmp);
     });
     loop.exec();
     QUrl url = currentTab()->url();
     SourceViewer *viewer = new SourceViewer(markup, title, url);
     viewer->setAttribute(Qt::WA_DeleteOnClose);
     viewer->show();
 }
References currentTab(), gotHTML(), markup, notifyGotHTML(), and WebView::url().
Referenced by setupMenu().
viewStatusbar
void BrowserMainWindow::viewStatusbar () private slot
Definition at line 1099 of file browsermainwindow.cpp.
 {
     if (statusBar()->isVisible()) {
         statusBar()->close();
     } else {
         statusBar()->show();
     }
     m_statusBarVisible = statusBar()->isVisible();
     m_autoSaver->changeOccurred();
 }
References AutoSaver::changeOccurred(), m_autoSaver, and m_statusBarVisible.
Referenced by setupMenu().
viewTextEncoding
void BrowserMainWindow::viewTextEncoding (QAction * action) private slot
Definition at line 895 of file browsermainwindow.cpp.
 {
     Q_UNUSED(action);
     Q_ASSERT(action);
     QString codec = action->data().toString();
     if (codec.isEmpty())
         QWebEngineSettings::globalSettings()->setDefaultTextEncoding(QString());
     else
         QWebEngineSettings::globalSettings()->setDefaultTextEncoding(codec);
 }
Referenced by setupMenu().
viewToolbar
void BrowserMainWindow::viewToolbar () private slot
Definition at line 1073 of file browsermainwindow.cpp.
 {
     if (m_navigationBar->isVisible()) {
         m_navigationBar->close();
     } else {
         m_navigationBar->show();
     }
     m_autoSaver->changeOccurred();
 }
References AutoSaver::changeOccurred(), m_autoSaver, and m_navigationBar.
Referenced by setupMenu().
webSearch
void BrowserMainWindow::webSearch () private slot
Definition at line 1395 of file browsermainwindow.cpp.
 {
     m_toolbarSearch->selectAll();
     m_toolbarSearch->setFocus();
 }
References m_toolbarSearch.
Referenced by setupMenu().
zoomIn
void BrowserMainWindow::zoomIn () private slot
Definition at line 1323 of file browsermainwindow.cpp.
 {
     if (!currentTab())
         return;
     currentTab()->zoomIn();
 }
References currentTab(), and WebView::zoomIn().
Referenced by setupMenu().
zoomNormal
void BrowserMainWindow::zoomNormal () private slot
Definition at line 1330 of file browsermainwindow.cpp.
 {
     if (!currentTab())
         return;
     currentTab()->resetZoom();
 }
References currentTab(), and WebView::resetZoom().
Referenced by setupMenu().
zoomOut
void BrowserMainWindow::zoomOut () private slot
Definition at line 1337 of file browsermainwindow.cpp.
 {
     if (!currentTab())
         return;
     currentTab()->zoomOut();
 }
References currentTab(), and WebView::zoomOut().
Referenced by setupMenu().
zoomTextOnlyChanged
void BrowserMainWindow::zoomTextOnlyChanged (bool textOnly) slot
Definition at line 1244 of file browsermainwindow.cpp.
 {
     m_viewZoomTextOnlyAction->setChecked(textOnly);
 }
References m_viewZoomTextOnlyAction.
Referenced by setupMenu().
Friends And Related Function Documentation
BrowserApplication
friend class BrowserApplication friend
Definition at line 275 of file browsermainwindow.h.
Member Data Documentation
m_autoSaver
AutoSaver* BrowserMainWindow::m_autoSaver private
Definition at line 266 of file browsermainwindow.h.
Referenced by BrowserMainWindow(), BrowserApplication::newMainWindow(), setupMenu(), viewBookmarksBar(), viewMenuBar(), viewStatusbar(), viewToolbar(), and ~BrowserMainWindow().
m_bookmarksAddAction
QAction* BrowserMainWindow::m_bookmarksAddAction private
Definition at line 233 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_bookmarksAddFolderAction
QAction* BrowserMainWindow::m_bookmarksAddFolderAction private
Definition at line 234 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_bookmarksMenu
BookmarksMenuBarMenu* BrowserMainWindow::m_bookmarksMenu private
Definition at line 231 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_bookmarksShowAllAction
QAction* BrowserMainWindow::m_bookmarksShowAllAction private
Definition at line 232 of file browsermainwindow.h.
Referenced by keyPressEvent(), retranslate(), and setupMenu().
m_bookmarksToolbar
BookmarksToolBar* BrowserMainWindow::m_bookmarksToolbar private
Definition at line 262 of file browsermainwindow.h.
Referenced by aboutToShowViewMenu(), BrowserMainWindow(), restoreState(), retranslate(), saveState(), and viewBookmarksBar().
m_editCopyAction
QAction* BrowserMainWindow::m_editCopyAction private
Definition at line 202 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_editCutAction
QAction* BrowserMainWindow::m_editCutAction private
Definition at line 201 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_editFindAction
QAction* BrowserMainWindow::m_editFindAction private
Definition at line 205 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_editFindNextAction
QAction* BrowserMainWindow::m_editFindNextAction private
Definition at line 206 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_editFindPreviousAction
QAction* BrowserMainWindow::m_editFindPreviousAction private
Definition at line 207 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_editMenu
QMenu* BrowserMainWindow::m_editMenu private
Definition at line 198 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_editPasteAction
QAction* BrowserMainWindow::m_editPasteAction private
Definition at line 203 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_editRedoAction
QAction* BrowserMainWindow::m_editRedoAction private
Definition at line 200 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_editSelectAllAction
QAction* BrowserMainWindow::m_editSelectAllAction private
Definition at line 204 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_editUndoAction
QAction* BrowserMainWindow::m_editUndoAction private
Definition at line 199 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_fileCloseWindow
QAction* BrowserMainWindow::m_fileCloseWindow private
Definition at line 195 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_fileExportBookmarksAction
QAction* BrowserMainWindow::m_fileExportBookmarksAction private
Definition at line 191 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_fileImportBookmarksAction
QAction* BrowserMainWindow::m_fileImportBookmarksAction private
Definition at line 190 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_fileMenu
QMenu* BrowserMainWindow::m_fileMenu private
Definition at line 185 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_fileNewWindowAction
QAction* BrowserMainWindow::m_fileNewWindowAction private
Definition at line 186 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_fileOpenFileAction
QAction* BrowserMainWindow::m_fileOpenFileAction private
Definition at line 187 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_fileOpenLocationAction
QAction* BrowserMainWindow::m_fileOpenLocationAction private
Definition at line 188 of file browsermainwindow.h.
Referenced by keyPressEvent(), retranslate(), and setupMenu().
m_filePrintAction
QAction* BrowserMainWindow::m_filePrintAction private
Definition at line 193 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_filePrintPreviewAction
QAction* BrowserMainWindow::m_filePrintPreviewAction private
Definition at line 192 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_filePrivateBrowsingAction
QAction* BrowserMainWindow::m_filePrivateBrowsingAction private
Definition at line 194 of file browsermainwindow.h.
Referenced by BrowserMainWindow(), privacyChanged(), privateBrowsing(), retranslate(), and setupMenu().
m_fileQuit
QAction* BrowserMainWindow::m_fileQuit private
Definition at line 196 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_fileSaveAsAction
QAction* BrowserMainWindow::m_fileSaveAsAction private
Definition at line 189 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_helpAboutApplicationAction
QAction* BrowserMainWindow::m_helpAboutApplicationAction private
Definition at line 248 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_helpAboutQtAction
QAction* BrowserMainWindow::m_helpAboutQtAction private
Definition at line 247 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_helpChangeLanguageAction
QAction* BrowserMainWindow::m_helpChangeLanguageAction private
Definition at line 246 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_helpMenu
QMenu* BrowserMainWindow::m_helpMenu private
Definition at line 245 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_historyBackAction
QAction* BrowserMainWindow::m_historyBackAction private
Definition at line 226 of file browsermainwindow.h.
Referenced by mousePressEvent(), retranslate(), setupMenu(), and setupToolBar().
m_historyBackMenu
QMenu* BrowserMainWindow::m_historyBackMenu private
Definition at line 252 of file browsermainwindow.h.
Referenced by aboutToShowBackMenu(), and setupToolBar().
m_historyForwardAction
QAction* BrowserMainWindow::m_historyForwardAction private
Definition at line 227 of file browsermainwindow.h.
Referenced by mousePressEvent(), retranslate(), setupMenu(), and setupToolBar().
m_historyForwardMenu
QMenu* BrowserMainWindow::m_historyForwardMenu private
Definition at line 253 of file browsermainwindow.h.
Referenced by aboutToShowForwardMenu(), and setupToolBar().
m_historyHomeAction
QAction* BrowserMainWindow::m_historyHomeAction private
Definition at line 228 of file browsermainwindow.h.
Referenced by keyPressEvent(), retranslate(), and setupMenu().
m_historyMenu
HistoryMenu* BrowserMainWindow::m_historyMenu private
Definition at line 225 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_historyRestoreLastSessionAction
QAction* BrowserMainWindow::m_historyRestoreLastSessionAction private
Definition at line 229 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_menuBarVisible
bool BrowserMainWindow::m_menuBarVisible private
Definition at line 270 of file browsermainwindow.h.
Referenced by restoreState(), saveState(), setupMenu(), viewFullScreen(), and viewMenuBar().
m_navigationBar
QToolBar* BrowserMainWindow::m_navigationBar private
Definition at line 251 of file browsermainwindow.h.
Referenced by aboutToShowViewMenu(), BrowserMainWindow(), restoreState(), retranslate(), saveState(), selectLineEdit(), setupToolBar(), and viewToolbar().
m_navigationSplitter
QSplitter* BrowserMainWindow::m_navigationSplitter private
Definition at line 257 of file browsermainwindow.h.
Referenced by restoreState(), saveState(), and setupToolBar().
m_reloadIcon
QIcon BrowserMainWindow::m_reloadIcon private
Definition at line 255 of file browsermainwindow.h.
Referenced by loadProgress(), setupMenu(), and setupToolBar().
m_statusBarVisible
bool BrowserMainWindow::m_statusBarVisible private
Definition at line 271 of file browsermainwindow.h.
Referenced by restoreState(), saveState(), viewFullScreen(), and viewStatusbar().
m_stopIcon
QIcon BrowserMainWindow::m_stopIcon private
Definition at line 256 of file browsermainwindow.h.
Referenced by loadProgress(), and setupMenu().
m_stopReloadAction
QAction* BrowserMainWindow::m_stopReloadAction private
Definition at line 254 of file browsermainwindow.h.
Referenced by loadProgress(), retranslate(), setupToolBar(), and updateStopReloadActionText().
m_tabWidget
TabWidget* BrowserMainWindow::m_tabWidget private
Definition at line 264 of file browsermainwindow.h.
Referenced by aboutToShowWindowMenu(), BrowserMainWindow(), closeEvent(), currentTab(), editFind(), editFindNext(), editFindPrevious(), lastTabClosed(), restoreState(), saveState(), selectLineEdit(), setupMenu(), setupToolBar(), showBookmarksDialog(), swapFocus(), and tabWidget().
m_toolbarSearch
ToolbarSearch* BrowserMainWindow::m_toolbarSearch private
Definition at line 258 of file browsermainwindow.h.
Referenced by setupToolBar(), toolbarSearch(), and webSearch().
m_toolsClearPrivateDataAction
QAction* BrowserMainWindow::m_toolsClearPrivateDataAction private
Definition at line 240 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_toolsMenu
QMenu* BrowserMainWindow::m_toolsMenu private
Definition at line 238 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_toolsPreferencesAction
QAction* BrowserMainWindow::m_toolsPreferencesAction private
Definition at line 241 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_toolsSearchManagerAction
QAction* BrowserMainWindow::m_toolsSearchManagerAction private
Definition at line 242 of file browsermainwindow.h.
Referenced by retranslate(), searchManagerAction(), and setupMenu().
m_toolsUserAgentMenu
UserAgentMenu* BrowserMainWindow::m_toolsUserAgentMenu private
Definition at line 243 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_toolsWebSearchAction
QAction* BrowserMainWindow::m_toolsWebSearchAction private
Definition at line 239 of file browsermainwindow.h.
Referenced by keyPressEvent(), retranslate(), and setupMenu().
m_viewBookmarkBarAction
QAction* BrowserMainWindow::m_viewBookmarkBarAction private
Definition at line 212 of file browsermainwindow.h.
Referenced by aboutToShowViewMenu(), retranslate(), and setupMenu().
m_viewFullScreenAction
QAction* BrowserMainWindow::m_viewFullScreenAction private
Definition at line 221 of file browsermainwindow.h.
Referenced by restoreState(), retranslate(), and setupMenu().
m_viewMenu
QMenu* BrowserMainWindow::m_viewMenu private
Definition at line 209 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_viewReloadAction
QAction* BrowserMainWindow::m_viewReloadAction private
Definition at line 215 of file browsermainwindow.h.
Referenced by loadProgress(), retranslate(), and setupMenu().
m_viewShowMenuBarAction
QAction* BrowserMainWindow::m_viewShowMenuBarAction private
Definition at line 210 of file browsermainwindow.h.
Referenced by retranslate(), setupMenu(), and showMenuBarAction().
m_viewSourceAction
QAction* BrowserMainWindow::m_viewSourceAction private
Definition at line 220 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_viewStatusbarAction
QAction* BrowserMainWindow::m_viewStatusbarAction private
Definition at line 213 of file browsermainwindow.h.
Referenced by aboutToShowViewMenu(), retranslate(), and setupMenu().
m_viewStopAction
QAction* BrowserMainWindow::m_viewStopAction private
Definition at line 214 of file browsermainwindow.h.
Referenced by loadProgress(), retranslate(), and setupMenu().
m_viewTextEncodingAction
QAction* BrowserMainWindow::m_viewTextEncodingAction private
Definition at line 222 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_viewTextEncodingMenu
QMenu* BrowserMainWindow::m_viewTextEncodingMenu private
Definition at line 223 of file browsermainwindow.h.
Referenced by aboutToShowTextEncodingMenu(), and setupMenu().
m_viewToolbarAction
QAction* BrowserMainWindow::m_viewToolbarAction private
Definition at line 211 of file browsermainwindow.h.
Referenced by aboutToShowViewMenu(), retranslate(), and setupMenu().
m_viewZoomInAction
QAction* BrowserMainWindow::m_viewZoomInAction private
Definition at line 216 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_viewZoomNormalAction
QAction* BrowserMainWindow::m_viewZoomNormalAction private
Definition at line 217 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_viewZoomOutAction
QAction* BrowserMainWindow::m_viewZoomOutAction private
Definition at line 218 of file browsermainwindow.h.
Referenced by retranslate(), and setupMenu().
m_viewZoomTextOnlyAction
QAction* BrowserMainWindow::m_viewZoomTextOnlyAction private
Definition at line 219 of file browsermainwindow.h.
Referenced by retranslate(), setupMenu(), and zoomTextOnlyChanged().
m_windowMenu
QMenu* BrowserMainWindow::m_windowMenu private
Definition at line 236 of file browsermainwindow.h.
Referenced by aboutToShowWindowMenu(), retranslate(), and setupMenu().
markup
QString BrowserMainWindow::markup private
Definition at line 273 of file browsermainwindow.h.
Referenced by gotHTML(), and viewPageSource().
The documentation for this class was generated from the following files:
src/browsermainwindow.h
src/browsermainwindow.cpp