Endorphin: SearchBar Class Reference
SearchBar Class Reference abstract
#include <searchbar.h>
Public Slots
void animateHide ()
void clear ()
void showFind ()
virtual void findNext ()=0
virtual void findPrevious ()=0
Public Member Functions
SearchBar (QWidget *parent=nullptr)
void setSearchObject (QObject *object)
QObject * searchObject () const
Protected Member Functions
void resizeEvent (QResizeEvent *event)
Protected Attributes
Ui_SearchBanner ui
Private Slots
void frameChanged (int frame)
Private Member Functions
void initializeSearchWidget ()
Private Attributes
QObject * m_object
QWidget * m_widget
QTimeLine * m_timeLine
Detailed Description
Definition at line 31 of file searchbar.h.
Constructor & Destructor Documentation
SearchBar()
SearchBar::SearchBar (QWidget * parent = nullptr)
Definition at line 28 of file searchbar.cpp.
     : QWidget(parent)
     , m_object(nullptr)
     , m_widget(nullptr)
     , m_timeLine(new QTimeLine(150, this))
 {
     initializeSearchWidget();
     // we start off hidden
     setMaximumHeight(0);
     m_widget->setGeometry(0, -1 * m_widget->height(),
                           m_widget->width(), m_widget->height());
     hide();
     connect(ui.nextButton, SIGNAL(clicked()),
             this, SLOT(findNext()));
     connect(ui.previousButton, SIGNAL(clicked()),
             this, SLOT(findPrevious()));
     connect(ui.searchLineEdit, SIGNAL(returnPressed()),
             this, SLOT(findNext()));
     connect(ui.searchLineEdit, SIGNAL(textEdited(const QString &)),
             this, SLOT(findNext()));
     connect(ui.doneButton, SIGNAL(clicked()),
             this, SLOT(animateHide()));
     connect(m_timeLine, SIGNAL(frameChanged(int)),
             this, SLOT(frameChanged(int)));
     new QShortcut(QKeySequence(Qt::Key_Escape), this, SLOT(animateHide()));
 }
References animateHide(), findNext(), findPrevious(), frameChanged(), initializeSearchWidget(), m_timeLine, m_widget, and ui.
Member Function Documentation
animateHide
void SearchBar::animateHide () slot
Definition at line 109 of file searchbar.cpp.
 {
     m_timeLine->setDirection(QTimeLine::Backward);
     m_timeLine->start();
     connect(m_timeLine, SIGNAL(finished()), this, SLOT(hide()));
 }
References m_timeLine.
Referenced by SearchBar().
clear
void SearchBar::clear () slot
Definition at line 83 of file searchbar.cpp.
 {
     ui.searchLineEdit->setText(QString());
 }
References ui.
Referenced by TabWidget::clear().
findNext
virtual void SearchBar::findNext () pure virtual slot
Referenced by SearchBar().
findPrevious
virtual void SearchBar::findPrevious () pure virtual slot
Referenced by SearchBar().
frameChanged
void SearchBar::frameChanged (int frame) private slot
Definition at line 116 of file searchbar.cpp.
 {
     if (!m_widget)
         return;
     m_widget->move(0, frame);
     int height = qMax(0, m_widget->y() + m_widget->height());
     setMinimumHeight(height);
     setMaximumHeight(height);
 }
References m_widget.
Referenced by SearchBar().
initializeSearchWidget()
void SearchBar::initializeSearchWidget () private
Definition at line 58 of file searchbar.cpp.
 {
     m_widget = new QWidget(this);
     m_widget->setContentsMargins(0, 0, 0, 0);
     ui.setupUi(m_widget);
     ui.previousButton->setText(m_widget->layoutDirection()
                                == Qt::LeftToRight? QChar(9664): QChar(9654));
     ui.nextButton->setText(m_widget->layoutDirection()
                            == Qt::LeftToRight? QChar(9654): QChar(9664));
     ui.searchInfo->setText(QString());
     setMinimumWidth(m_widget->minimumWidth());
     setMaximumWidth(m_widget->maximumWidth());
     setMinimumHeight(m_widget->minimumHeight());
 }
References m_widget, and ui.
Referenced by SearchBar().
resizeEvent()
void SearchBar::resizeEvent (QResizeEvent * event) protected
Definition at line 102 of file searchbar.cpp.
 {
     if (event->size().width() != m_widget->width())
         m_widget->resize(event->size().width(), m_widget->height());
     QWidget::resizeEvent(event);
 }
References m_widget.
searchObject()
QObject * SearchBar::searchObject () const
Definition at line 78 of file searchbar.cpp.
 {
     return m_object;
 }
References m_object.
Referenced by WebViewSearch::find(), and WebViewSearch::webView().
setSearchObject()
void SearchBar::setSearchObject (QObject * object)
Definition at line 73 of file searchbar.cpp.
 {
     m_object = object;
 }
References m_object.
Referenced by PlainTextEditSearch::PlainTextEditSearch(), and WebViewSearch::WebViewSearch().
showFind
void SearchBar::showFind () slot
Definition at line 88 of file searchbar.cpp.
 {
     if (!isVisible()) {
         show();
         m_timeLine->setFrameRange(-1 * m_widget->height(), 0);
         m_timeLine->setDirection(QTimeLine::Forward);
         disconnect(m_timeLine, SIGNAL(finished()),
                    this, SLOT(hide()));
         m_timeLine->start();
     }
     ui.searchLineEdit->setFocus();
     ui.searchLineEdit->selectAll();
 }
References m_timeLine, m_widget, and ui.
Referenced by BrowserMainWindow::editFind().
Member Data Documentation
m_object
QObject* SearchBar::m_object private
Definition at line 56 of file searchbar.h.
Referenced by searchObject(), and setSearchObject().
m_timeLine
QTimeLine* SearchBar::m_timeLine private
Definition at line 58 of file searchbar.h.
Referenced by animateHide(), SearchBar(), and showFind().
m_widget
QWidget* SearchBar::m_widget private
Definition at line 57 of file searchbar.h.
Referenced by frameChanged(), initializeSearchWidget(), resizeEvent(), SearchBar(), and showFind().
ui
Ui_SearchBanner SearchBar::ui protected
Definition at line 49 of file searchbar.h.
Referenced by clear(), PlainTextEditSearch::find(), WebViewSearch::find(), initializeSearchWidget(), SearchBar(), showFind(), and WebViewSearch::WebViewSearch().
The documentation for this class was generated from the following files:
src/searchbar.h
src/searchbar.cpp