Endorphin: LanguageManager Class Reference
LanguageManager Class Reference
#include <languagemanager.h>
Public Slots
void loadLanguageFromSettings ()
void chooseNewLanguage ()
Signals
void languageChanged (const QString &language)
Public Member Functions
LanguageManager (QObject *parent=nullptr)
void addLocaleDirectory (const QString &directory)
QStringList localeDirectories () const
QString currentLanguage () const
bool setCurrentLanguage (const QString &language)
QStringList languages () const
bool isLanguageAvailable (const QString &language) const
Properties
QString currentLanguage
Private Member Functions
QString convertStringToLanguageFile (const QString &string) const
void loadAvailableLanguages () const
Private Attributes
QString m_currentLanguage
QTranslator * m_sysTranslator
QTranslator * m_appTranslator
bool m_loaded
QStringList m_languages
QStringList m_localeDirectories
Detailed Description
Definition at line 38 of file languagemanager.h.
Constructor & Destructor Documentation
LanguageManager()
LanguageManager::LanguageManager (QObject * parent = nullptr)
Definition at line 47 of file languagemanager.cpp.
     : QObject(parent)
     , m_sysTranslator(nullptr)
     , m_appTranslator(nullptr)
     , m_loaded(false)
 {
 #ifdef LANGUAGEMANAGER_DEBUG
     qDebug() << "LanguageManager::" << __FUNCTION__;
 #endif
 }
Member Function Documentation
addLocaleDirectory()
void LanguageManager::addLocaleDirectory (const QString & directory)
Definition at line 58 of file languagemanager.cpp.
 {
     m_localeDirectories.append(directory);
 }
References m_localeDirectories.
Referenced by BrowserApplication::languageManager().
chooseNewLanguage
void LanguageManager::chooseNewLanguage () slot
Definition at line 231 of file languagemanager.cpp.
 {
 #ifdef LANGUAGEMANAGER_DEBUG
     qDebug() << "LanguageManager::" << __FUNCTION__;
 #endif
     loadAvailableLanguages();
     if (m_languages.isEmpty()) {
         QMessageBox messageBox;
         QLatin1String separator = QLatin1String(", ");
         messageBox.setText(tr("No translation files are installed at %1.")
                            .arg(m_localeDirectories.join(separator)));
         messageBox.setStandardButtons(QMessageBox::Ok);
         messageBox.exec();
         return;
     }
     QStringList items;
     int defaultItem = -1;
     QString current = currentLanguage();
     foreach (const QString &name, m_languages) {
         QLocale locale(name);
         QString string = QString(QLatin1String("%1, %2 (%3) %4"))
                          .arg(QLocale::languageToString(locale.language()))
                          .arg(QLocale::countryToString(locale.country()))
                          .arg(name)
                          // this is for pretty RTL support
                          .arg(QChar(0x200E)); // LRM = 0x200E
         if (name == current)
             defaultItem = items.count();
         items << string;
     }
     items << QLatin1String("English (en_US)");
     if (defaultItem == -1)
         defaultItem = items.count() - 1;
     bool ok;
     QString item = QInputDialog::getItem(nullptr,
                                          tr("Choose language"),
                                          tr("<p>You can run with a different language than<br>"
                                             "the operating system default.</p>"
                                             "<p>Please choose the language which should be used</p>"),
                                          items, defaultItem, false, &ok);
     if (!ok)
         return;
     int selection = items.indexOf(item);
     setCurrentLanguage(m_languages.value(selection));
 }
References currentLanguage, loadAvailableLanguages(), m_languages, m_localeDirectories, and setCurrentLanguage().
convertStringToLanguageFile()
QString LanguageManager::convertStringToLanguageFile (const QString & string) const private
Definition at line 106 of file languagemanager.cpp.
 {
 #ifdef LANGUAGEMANAGER_DEBUG
     qDebug() << "LanguageManager::" << __FUNCTION__ << string;
 #endif
     loadAvailableLanguages();
     if (m_languages.contains(string))
         return string;
     QLocale locale(string);
     QString fallback = locale.name().split(QLatin1Char('_')).value(0);
     if (!string.contains(fallback))
         return QString();
 #ifdef LANGUAGEMANAGER_DEBUG
     qDebug() << "LanguageManager::" << __FUNCTION__ << "fallback" << fallback;
 #endif
     if (m_languages.contains(fallback)) // fallback to the country
         return fallback;
     // See if any language file matches the country
     foreach (const QString &language, m_languages) {
         QString country = QLocale(language).name().split(QLatin1Char('_')).value(0);
         if (country == fallback)
             return language;
     }
     return QString();
 }
References loadAvailableLanguages(), and m_languages.
Referenced by isLanguageAvailable(), and setCurrentLanguage().
currentLanguage()
QString LanguageManager::currentLanguage () const
Definition at line 68 of file languagemanager.cpp.
 {
 #ifdef LANGUAGEMANAGER_DEBUG
     qDebug() << "LanguageManager::" << __FUNCTION__;
 #endif
     if (!m_currentLanguage.isEmpty())
         return m_currentLanguage;
     const QString sysLanguage = QLocale::system().name();
     if (isLanguageAvailable(sysLanguage))
         return sysLanguage;
     return QString();
 }
References isLanguageAvailable(), and m_currentLanguage.
isLanguageAvailable()
bool LanguageManager::isLanguageAvailable (const QString & language) const
Definition at line 82 of file languagemanager.cpp.
 {
 #ifdef LANGUAGEMANAGER_DEBUG
     qDebug() << "LanguageManager::" << __FUNCTION__ << language;
 #endif
     if (language.isEmpty())
         return true;
     // optimization so we don't have to load all the languages
     if (!m_loaded) {
         foreach (const QString &dir, m_localeDirectories) {
             QString file = dir + QLatin1Char('/') + language + QLatin1String(".qm");
             if (QFile::exists(file))
                 return true;
         }
     }
     return !(convertStringToLanguageFile(language).isEmpty());
 }
References convertStringToLanguageFile(), m_loaded, and m_localeDirectories.
Referenced by currentLanguage(), and setCurrentLanguage().
languageChanged
void LanguageManager::languageChanged (const QString & language) signal
Referenced by setCurrentLanguage().
languages()
QStringList LanguageManager::languages () const
Definition at line 196 of file languagemanager.cpp.
 {
 #ifdef LANGUAGEMANAGER_DEBUG
     qDebug() << "LanguageManager::" << __FUNCTION__;
 #endif
     loadAvailableLanguages();
     return m_languages;
 }
References loadAvailableLanguages(), and m_languages.
loadAvailableLanguages()
void LanguageManager::loadAvailableLanguages () const private
Find all *.qm files in the data directory that have a Qt translation.
Definition at line 283 of file languagemanager.cpp.
 {
     if (m_loaded)
         return;
     m_loaded = true;
 #ifdef LANGUAGEMANAGER_DEBUG
     qDebug() << "LanguageManager::" << __FUNCTION__;
 #endif
     foreach (const QString &dir, m_localeDirectories) {
         QDirIterator it(dir);
         while (it.hasNext()) {
             QString fileName = it.next();
             if (!fileName.endsWith(QLatin1String(".qm")))
                 continue;
             const QFileInfo info = it.fileInfo();
             QString language = info.completeBaseName();
             m_languages.append(language);
         }
     }
 }
References m_languages, m_loaded, and m_localeDirectories.
Referenced by chooseNewLanguage(), convertStringToLanguageFile(), and languages().
loadLanguageFromSettings
void LanguageManager::loadLanguageFromSettings () slot
Definition at line 205 of file languagemanager.cpp.
 {
 #ifdef LANGUAGEMANAGER_DEBUG
     qDebug() << "LanguageManager::" << __FUNCTION__;
 #endif
     QSettings settings;
     settings.beginGroup(QLatin1String("LanguageManager"));
     if (settings.contains(QLatin1String("language"))) {
         QString selectedLanguage = settings.value(QLatin1String("language")).toString();
 #ifdef LANGUAGEMANAGER_DEBUG
         qDebug() << "LanguageManager::" << __FUNCTION__ << "Loading language from settings" << selectedLanguage;
 #endif
         // When a translation fails to load remove it from the settings
         // to prevent it from being loaded every time.
         if (!setCurrentLanguage(selectedLanguage)) {
 #ifdef LANGUAGEMANAGER_DEBUG
             qDebug() << "LanguageManager::" << __FUNCTION__ << "Failed to load language";
 #endif
             settings.remove(QLatin1String("language"));
         }
     } else if (!currentLanguage().isEmpty()) {
         setCurrentLanguage(currentLanguage());
     }
 }
References currentLanguage, and setCurrentLanguage().
Referenced by BrowserApplication::languageManager().
localeDirectories()
QStringList LanguageManager::localeDirectories () const
Definition at line 63 of file languagemanager.cpp.
 {
     return m_localeDirectories;
 }
References m_localeDirectories.
setCurrentLanguage()
bool LanguageManager::setCurrentLanguage (const QString & language)
Definition at line 134 of file languagemanager.cpp.
 {
 #ifdef LANGUAGEMANAGER_DEBUG
     qDebug() << "LanguageManager::" << __FUNCTION__ << language;
 #endif
     if (m_currentLanguage == language
             || !isLanguageAvailable(language))
         return false;
     m_currentLanguage = language;
     QSettings settings;
     settings.beginGroup(QLatin1String("LanguageManager"));
     settings.setValue(QLatin1String("language"), m_currentLanguage);
     if (m_currentLanguage.isEmpty()) {
         delete m_appTranslator;
         delete m_sysTranslator;
         m_appTranslator = nullptr;
         m_sysTranslator = nullptr;
         emit languageChanged(currentLanguage());
         return true;
     }
     QTranslator *newAppTranslator = new QTranslator(this);
     QString resourceDir = QLibraryInfo::location(QLibraryInfo::TranslationsPath);
     QString languageFile = convertStringToLanguageFile(m_currentLanguage);
     bool loaded = false;
     foreach (const QString &dir, m_localeDirectories) {
         loaded = newAppTranslator->load(languageFile, dir);
         if (loaded)
             break;
     }
     QTranslator *newSysTranslator = new QTranslator(this);
     QString translatorFileName = QLatin1String("qt_") + languageFile;
     if (!newSysTranslator->load(translatorFileName, resourceDir)) {
         delete newSysTranslator;
         newSysTranslator = nullptr;
     }
     if (!loaded) {
         qWarning() << "Failed to load translation:" << currentLanguage();
         delete newAppTranslator;
         delete newSysTranslator;
         return false;
     }
     QLocale::setDefault(QLocale(m_currentLanguage));
     // A new language event is sent to all widgets in the application
     // They need to catch it and re-translate
     delete m_appTranslator;
     delete m_sysTranslator;
     qApp->installTranslator(newAppTranslator);
     qApp->installTranslator(newSysTranslator);
     m_appTranslator = newAppTranslator;
     m_sysTranslator = newSysTranslator;
     emit languageChanged(currentLanguage());
     return true;
 }
References convertStringToLanguageFile(), currentLanguage, isLanguageAvailable(), languageChanged(), m_appTranslator, m_currentLanguage, m_localeDirectories, and m_sysTranslator.
Referenced by chooseNewLanguage(), and loadLanguageFromSettings().
Member Data Documentation
m_appTranslator
QTranslator* LanguageManager::m_appTranslator private
Definition at line 68 of file languagemanager.h.
Referenced by setCurrentLanguage().
m_currentLanguage
QString LanguageManager::m_currentLanguage private
Definition at line 66 of file languagemanager.h.
Referenced by currentLanguage(), and setCurrentLanguage().
m_languages
QStringList LanguageManager::m_languages mutable private
Definition at line 70 of file languagemanager.h.
Referenced by chooseNewLanguage(), convertStringToLanguageFile(), languages(), and loadAvailableLanguages().
m_loaded
bool LanguageManager::m_loaded mutable private
Definition at line 69 of file languagemanager.h.
Referenced by isLanguageAvailable(), and loadAvailableLanguages().
m_localeDirectories
QStringList LanguageManager::m_localeDirectories private
Definition at line 71 of file languagemanager.h.
Referenced by addLocaleDirectory(), chooseNewLanguage(), isLanguageAvailable(), loadAvailableLanguages(), localeDirectories(), and setCurrentLanguage().
m_sysTranslator
QTranslator* LanguageManager::m_sysTranslator private
Definition at line 67 of file languagemanager.h.
Referenced by setCurrentLanguage().
Property Documentation
currentLanguage
QString LanguageManager::currentLanguage read write
Definition at line 1 of file languagemanager.h.
Referenced by chooseNewLanguage(), AcceptLanguageDialog::defaultAcceptList(), loadLanguageFromSettings(), and setCurrentLanguage().
The documentation for this class was generated from the following files:
src/utils/languagemanager.h
src/utils/languagemanager.cpp