Endorphin: HistoryModel Class Reference
HistoryModel Class Reference
#include <history.h>
Public Types
enum Roles {
DateRole = Qt::UserRole + 1, DateTimeRole = Qt::UserRole + 2, UrlRole = Qt::UserRole + 3, UrlStringRole = Qt::UserRole + 4,
TitleRole = Qt::UserRole + 5, MaxRole = TitleRole
}
Public Slots
void historyReset ()
void historyGoingToChange ()
void entryAdded ()
void entryUpdated (int offset)
Public Member Functions
HistoryModel (HistoryManager *history, QObject *parent=nullptr)
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
int columnCount (const QModelIndex &parent=QModelIndex()) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
Private Attributes
HistoryManager * m_history
Detailed Description
Definition at line 76 of file history.h.
Member Enumeration Documentation
Roles
enum HistoryModel::Roles
Enumerator
DateRole
DateTimeRole
UrlRole
UrlStringRole
TitleRole
MaxRole
Definition at line 87 of file history.h.
                {
         DateRole = Qt::UserRole + 1,
         DateTimeRole = Qt::UserRole + 2,
         UrlRole = Qt::UserRole + 3,
         UrlStringRole = Qt::UserRole + 4,
         TitleRole = Qt::UserRole + 5,
         MaxRole = TitleRole
     };
Constructor & Destructor Documentation
HistoryModel()
HistoryModel::HistoryModel (HistoryManager * history, QObject * parent = nullptr)
Definition at line 90 of file history.cpp.
     : QAbstractTableModel(parent)
     , m_history(history)
 {
     Q_ASSERT(m_history);
     connect(m_history, SIGNAL(historyGoingToChange()), this, SLOT(historyGoingToChange()));
     connect(m_history, SIGNAL(historyReset()),
             this, SLOT(historyReset()));
     connect(m_history, SIGNAL(entryRemoved(const HistoryEntry &)),
             this, SLOT(historyReset()));
     connect(m_history, SIGNAL(entryAdded(const HistoryEntry &)),
             this, SLOT(entryAdded()));
     connect(m_history, SIGNAL(entryUpdated(int)),
             this, SLOT(entryUpdated(int)));
 }
References entryAdded(), entryUpdated(), historyGoingToChange(), historyReset(), and m_history.
Member Function Documentation
columnCount()
int HistoryModel::columnCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 180 of file history.cpp.
 {
     return (parent.isValid()) ? 0 : 2;
 }
data()
QVariant HistoryModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const
Definition at line 143 of file history.cpp.
 {
     QList<HistoryEntry> lst = m_history->history();
     if (index.row() < 0 || index.row() >= lst.size())
         return QVariant();
     const HistoryEntry &item = lst.at(index.row());
     switch (role) {
     case DateTimeRole:
         return item.dateTime;
     case DateRole:
         return item.dateTime.date();
     case UrlRole:
         return QUrl(item.url);
     case UrlStringRole:
         return item.url;
     case TitleRole:
         return item.userTitle();
     case Qt::DisplayRole:
     case Qt::EditRole: {
         switch (index.column()) {
         case 0:
             return item.userTitle();
         case 1:
             return item.url;
         }
     }
 #ifndef NO_BROWSERAPPLICATION
     case Qt::DecorationRole:
         if (index.column() == 0) {
             return BrowserApplication::instance()->icon(item.url);
         }
 #endif
     }
     return QVariant();
 }
References DateRole, HistoryEntry::dateTime, DateTimeRole, HistoryManager::history(), BrowserApplication::icon(), BrowserApplication::instance(), m_history, TitleRole, HistoryEntry::url, UrlRole, UrlStringRole, and HistoryEntry::userTitle().
entryAdded
void HistoryModel::entryAdded () slot
Definition at line 117 of file history.cpp.
 {
     beginInsertRows(QModelIndex(), 0, 0);
     endInsertRows();
 }
Referenced by HistoryModel().
entryUpdated
void HistoryModel::entryUpdated (int offset) slot
Definition at line 123 of file history.cpp.
 {
     QModelIndex idx = index(offset, 0);
     emit dataChanged(idx, idx);
 }
Referenced by HistoryModel().
headerData()
QVariant HistoryModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const
Definition at line 129 of file history.cpp.
 {
     if (orientation == Qt::Horizontal
             && role == Qt::DisplayRole) {
         switch (section) {
         case 0:
             return tr("Title");
         case 1:
             return tr("Address");
         }
     }
     return QAbstractTableModel::headerData(section, orientation, role);
 }
historyGoingToChange
void HistoryModel::historyGoingToChange () slot
Definition at line 112 of file history.cpp.
 {
     beginResetModel();
 }
Referenced by HistoryModel().
historyReset
void HistoryModel::historyReset () slot
Definition at line 107 of file history.cpp.
 {
     endResetModel();
 }
Referenced by HistoryModel(), and removeRows().
removeRows()
bool HistoryModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex())
Definition at line 190 of file history.cpp.
 {
     if (parent.isValid())
         return false;
     int lastRow = row + count - 1;
     beginRemoveRows(parent, row, lastRow);
     QList<HistoryEntry> lst = m_history->history();
     for (int i = lastRow; i >= row; --i)
         lst.removeAt(i);
     disconnect(m_history, SIGNAL(historyReset()), this, SLOT(historyReset()));
     m_history->setHistory(lst);
     connect(m_history, SIGNAL(historyReset()), this, SLOT(historyReset()));
     endRemoveRows();
     return true;
 }
References HistoryManager::history(), historyReset(), m_history, and HistoryManager::setHistory().
rowCount()
int HistoryModel::rowCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 185 of file history.cpp.
 {
     return (parent.isValid()) ? 0 : m_history->history().count();
 }
References HistoryManager::history(), and m_history.
Member Data Documentation
m_history
HistoryManager* HistoryModel::m_history private
Definition at line 104 of file history.h.
Referenced by data(), HistoryModel(), removeRows(), and rowCount().
The documentation for this class was generated from the following files:
src/history/history.h
src/history/history.cpp