Endorphin: DownloadManager Class Reference
DownloadManager Class Reference
#include <downloadmanager.h>
Public Types
enum RemovePolicy { Never, Exit, SuccessFullDownload }
Public Slots
void download (const QNetworkRequest &request, bool requestFileName=false)
void download (const QUrl &url, bool requestFileName=false)
void handleUnsupportedContent (QNetworkReply *reply, bool requestFileName=false)
void cleanup ()
Public Member Functions
DownloadManager (QWidget *parent=nullptr)
~DownloadManager ()
int activeDownloads () const
bool allowQuit ()
RemovePolicy removePolicy () const
void setRemovePolicy (RemovePolicy policy)
void setDownloadDirectory (const QString &directory)
QString downloadDirectory ()
Static Public Member Functions
static QString timeString (double timeRemaining)
static QString dataString (qint64 size)
Properties
RemovePolicy removePolicy
Private Slots
void save () const
void updateRow (DownloadItem *item)
void updateRow ()
void finished ()
Private Member Functions
void addItem (DownloadItem *item)
void updateItemCount ()
void load ()
bool externalDownload (const QUrl &url)
void updateActiveItemCount ()
Private Attributes
AutoSaver * m_autoSaver
DownloadModel * m_model
QNetworkAccessManager * m_manager
QFileIconProvider * m_iconProvider
QList< DownloadItem * > m_downloads
RemovePolicy m_removePolicy
QString m_downloadDirectory
Friends
class DownloadModel
Detailed Description
Definition at line 137 of file downloadmanager.h.
Member Enumeration Documentation
RemovePolicy
enum DownloadManager::RemovePolicy
Enumerator
Never
Exit
SuccessFullDownload
Definition at line 144 of file downloadmanager.h.
                       {
         Never,
         Exit,
         SuccessFullDownload
     };
Constructor & Destructor Documentation
DownloadManager()
DownloadManager::DownloadManager (QWidget * parent = nullptr)
DownloadManager is a Dialog that contains a list of DownloadItems
It is a basic download manager. It only downloads the file, doesn't do BitTorrent, extract zipped files or anything fancy.
Definition at line 472 of file downloadmanager.cpp.
     : QDialog(parent)
     , m_autoSaver(new AutoSaver(this))
     , m_model(new DownloadModel(this))
     , m_manager(new QNetworkAccessManager())
     , m_iconProvider(nullptr)
     , m_removePolicy(Never)
 {
     setupUi(this);
     QSettings settings;
     settings.beginGroup(QLatin1String("downloadmanager"));
     QString defaultLocation = QStandardPaths::writableLocation(QStandardPaths::DesktopLocation);
     setDownloadDirectory(settings.value(QLatin1String("downloadDirectory"), defaultLocation).toString());
     downloadsView->setShowGrid(false);
     downloadsView->verticalHeader()->hide();
     downloadsView->horizontalHeader()->hide();
     downloadsView->setAlternatingRowColors(true);
     downloadsView->horizontalHeader()->setStretchLastSection(true);
     downloadsView->setModel(m_model);
     connect(cleanupButton, SIGNAL(clicked()), this, SLOT(cleanup()));
     connect(buttonBox, SIGNAL(rejected()), this, SLOT(close()));
     load();
 }
References cleanup(), load(), m_model, and setDownloadDirectory().
~DownloadManager()
DownloadManager::~DownloadManager ()
Definition at line 498 of file downloadmanager.cpp.
 {
     m_autoSaver->changeOccurred();
     m_autoSaver->saveIfNeccessary();
     if (m_iconProvider)
         delete m_iconProvider;
 }
References AutoSaver::changeOccurred(), m_autoSaver, m_iconProvider, and AutoSaver::saveIfNeccessary().
Member Function Documentation
activeDownloads()
int DownloadManager::activeDownloads () const
Definition at line 506 of file downloadmanager.cpp.
 {
     int count = 0;
     for (int i = 0; i < m_downloads.count(); ++i) {
         if (m_downloads.at(i)->stopButton->isEnabled())
             ++count;
     }
     return count;
 }
References m_downloads.
Referenced by allowQuit(), load(), updateActiveItemCount(), and updateRow().
addItem()
void DownloadManager::addItem (DownloadItem * item) private
Definition at line 593 of file downloadmanager.cpp.
 {
     connect(item, SIGNAL(statusChanged()), this, SLOT(updateRow()));
     connect(item, SIGNAL(downloadFinished()), this, SLOT(finished()));
     int row = m_downloads.count();
     m_model->beginInsertRows(QModelIndex(), row, row);
     m_downloads.append(item);
     m_model->endInsertRows();
     updateItemCount();
     downloadsView->setIndexWidget(m_model->index(row, 0), item);
     QIcon icon = style()->standardIcon(QStyle::SP_FileIcon);
     item->fileIcon->setPixmap(icon.pixmap(48, 48));
     downloadsView->setRowHeight(row, item->sizeHint().height());
     updateRow(item); //incase download finishes before the constructor returns
     updateActiveItemCount();
 }
References finished(), m_downloads, m_model, updateActiveItemCount(), updateItemCount(), and updateRow().
Referenced by handleUnsupportedContent(), and load().
allowQuit()
bool DownloadManager::allowQuit ()
Definition at line 516 of file downloadmanager.cpp.
 {
     if (activeDownloads() >= 1) {
         int choice = QMessageBox::warning(this, QString(),
                                           tr("There are %1 downloads in progress\n"
                                              "Do you want to quit anyway?").arg(activeDownloads()),
                                           QMessageBox::Yes | QMessageBox::No,
                                           QMessageBox::No);
         if (choice == QMessageBox::No) {
             show();
             return false;
         }
     }
     return true;
 }
References activeDownloads().
Referenced by BrowserApplication::allowToCloseWindow().
cleanup
void DownloadManager::cleanup () slot
Definition at line 747 of file downloadmanager.cpp.
 {
     if (m_downloads.isEmpty())
         return;
     m_model->removeRows(0, m_downloads.count());
     updateItemCount();
     updateActiveItemCount();
     if (m_downloads.isEmpty() && m_iconProvider) {
         delete m_iconProvider;
         m_iconProvider = nullptr;
     }
     m_autoSaver->changeOccurred();
 }
References AutoSaver::changeOccurred(), m_autoSaver, m_downloads, m_iconProvider, m_model, DownloadModel::removeRows(), updateActiveItemCount(), and updateItemCount().
Referenced by ClearPrivateData::accept(), and DownloadManager().
dataString()
QString DownloadManager::dataString (qint64 size) static
Definition at line 796 of file downloadmanager.cpp.
 {
     QString unit;
     double newSize;
     if (size < 1024) {
         newSize = size;
         unit = tr("bytes");
     } else if (size < 1024 * 1024) {
         newSize = (double)size / (double)1024;
         unit = tr("kB");
     } else if (size < 1024 * 1024 * 1024) {
         newSize = (double)size / (double)(1024 * 1024);
         unit = tr("MB");
     } else {
         newSize = (double)size / (double)(1024 * 1024 * 1024);
         unit = tr("GB");
     }
     return QString(QLatin1String("%1 %2")).arg(newSize, 0, 'f', 1).arg(unit);
 }
Referenced by DownloadItem::updateInfoLabel().
download [1/2]
void DownloadManager::download (const QNetworkRequest & request, bool requestFileName = false) slot
Definition at line 554 of file downloadmanager.cpp.
 {
     if (request.url().isEmpty())
         return;
     if (externalDownload(request.url()))
         return;
     handleUnsupportedContent(m_manager->get(request), requestFileName);
 }
References externalDownload(), handleUnsupportedContent(), and m_manager.
Referenced by WebView::downloadRequested(), and BrowserMainWindow::fileSaveAs().
download [2/2]
void DownloadManager::download (const QUrl & url, bool requestFileName = false) inline slot
Definition at line 166 of file downloadmanager.h.
     {
         download(QNetworkRequest(url), requestFileName);
     }
downloadDirectory()
QString DownloadManager::downloadDirectory ()
Definition at line 774 of file downloadmanager.cpp.
 {
     return m_downloadDirectory;
 }
References m_downloadDirectory.
Referenced by DownloadItem::getFileName().
externalDownload()
bool DownloadManager::externalDownload (const QUrl & url) private
Definition at line 532 of file downloadmanager.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("downloadmanager"));
     if (!settings.value(QLatin1String("external"), false).toBool())
         return false;
     QString program = settings.value(QLatin1String("externalPath")).toString();
     if (program.isEmpty())
         return false;
     // Split program at every space not inside double quotes
     QRegExp regex(QLatin1String("\"([^\"]+)\"|([^ ]+)"));
     QStringList args;
     for (int pos = 0; (pos = regex.indexIn(program, pos)) != -1; pos += regex.matchedLength())
         args << regex.cap(1) + regex.cap(2);
     if (args.isEmpty())
         return false;
     return QProcess::startDetached(args.takeFirst(), args << QString::fromUtf8(url.toEncoded()));
 }
Referenced by download(), and handleUnsupportedContent().
finished
void DownloadManager::finished () private slot
Definition at line 620 of file downloadmanager.cpp.
 {
     updateActiveItemCount();
     if (isVisible()) {
         QApplication::alert(this);
     }
 }
References updateActiveItemCount().
Referenced by addItem().
handleUnsupportedContent
void DownloadManager::handleUnsupportedContent (QNetworkReply * reply, bool requestFileName = false) slot
Definition at line 563 of file downloadmanager.cpp.
 {
     if (!reply || reply->url().isEmpty())
         return;
     if (externalDownload(reply->url()))
         return;
     QVariant header = reply->header(QNetworkRequest::ContentLengthHeader);
     bool ok;
     int size = header.toInt(&ok);
     if (ok && size == 0)
         return;
 #ifdef DOWNLOADMANAGER_DEBUG
     qDebug() << "DownloadManager::" << __FUNCTION__ << reply->url() << "requestFileName" << requestFileName;
 #endif
     DownloadItem *item = new DownloadItem(reply, requestFileName, this);
     addItem(item);
     if (item->m_canceledFileSelect)
         return;
     if (!isVisible())
         show();
     activateWindow();
     raise();
 }
References addItem(), externalDownload(), and DownloadItem::m_canceledFileSelect.
Referenced by download().
load()
void DownloadManager::load () private
Definition at line 710 of file downloadmanager.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("downloadmanager"));
     QSize size = settings.value(QLatin1String("size")).toSize();
     if (size.isValid())
         resize(size);
     QByteArray value = settings.value(QLatin1String("removeDownloadsPolicy"), QLatin1String("Never")).toByteArray();
     QMetaEnum removePolicyEnum = staticMetaObject.enumerator(staticMetaObject.indexOfEnumerator("RemovePolicy"));
     m_removePolicy = removePolicyEnum.keyToValue(value) == -1 ?
                      Never :
                      static_cast<RemovePolicy>(removePolicyEnum.keyToValue(value));
     int i = 0;
     QString key = QString(QLatin1String("download_%1_")).arg(i);
     while (settings.contains(key + QLatin1String("url"))) {
         QUrl url = settings.value(key + QLatin1String("url")).toUrl();
         QString fileName = settings.value(key + QLatin1String("location")).toString();
         bool done = settings.value(key + QLatin1String("done"), true).toBool();
         if (!url.isEmpty() && !fileName.isEmpty()) {
             DownloadItem *item = new DownloadItem(nullptr, this);
             item->m_output.setFileName(fileName);
             item->fileNameLabel->setText(QFileInfo(item->m_output.fileName()).fileName());
             item->m_url = url;
             item->stopButton->setVisible(false);
             item->stopButton->setEnabled(false);
             item->tryAgainButton->setVisible(!done);
             item->tryAgainButton->setEnabled(!done);
             item->progressBar->setVisible(false);
             addItem(item);
         }
         key = QString(QLatin1String("download_%1_")).arg(++i);
     }
     cleanupButton->setEnabled(m_downloads.count() - activeDownloads() > 0);
     updateActiveItemCount();
 }
References activeDownloads(), addItem(), m_downloads, DownloadItem::m_output, m_removePolicy, DownloadItem::m_url, Never, and updateActiveItemCount().
Referenced by DownloadManager().
removePolicy()
DownloadManager::RemovePolicy DownloadManager::removePolicy () const
Definition at line 671 of file downloadmanager.cpp.
 {
     return m_removePolicy;
 }
References m_removePolicy.
save
void DownloadManager::save () const private slot
Definition at line 684 of file downloadmanager.cpp.
 {
     QSettings settings;
     settings.beginGroup(QLatin1String("downloadmanager"));
     QMetaEnum removePolicyEnum = staticMetaObject.enumerator(staticMetaObject.indexOfEnumerator("RemovePolicy"));
     settings.setValue(QLatin1String("removeDownloadsPolicy"), QLatin1String(removePolicyEnum.valueToKey(m_removePolicy)));
     settings.setValue(QLatin1String("size"), size());
     if (m_removePolicy == Exit)
         return;
     for (int i = 0; i < m_downloads.count(); ++i) {
         QString key = QString(QLatin1String("download_%1_")).arg(i);
         settings.setValue(key + QLatin1String("url"), m_downloads[i]->m_url);
         settings.setValue(key + QLatin1String("location"), QFileInfo(m_downloads[i]->m_output).filePath());
         settings.setValue(key + QLatin1String("done"), m_downloads[i]->downloadedSuccessfully());
     }
     int i = m_downloads.count();
     QString key = QString(QLatin1String("download_%1_")).arg(i);
     while (settings.contains(key + QLatin1String("url"))) {
         settings.remove(key + QLatin1String("url"));
         settings.remove(key + QLatin1String("location"));
         settings.remove(key + QLatin1String("done"));
         key = QString(QLatin1String("download_%1_")).arg(++i);
     }
 }
References Exit, m_downloads, and m_removePolicy.
setDownloadDirectory()
void DownloadManager::setDownloadDirectory (const QString & directory)
Definition at line 767 of file downloadmanager.cpp.
 {
     m_downloadDirectory = directory;
     if (!m_downloadDirectory.isEmpty())
         m_downloadDirectory += QLatin1Char('/');
 }
References m_downloadDirectory.
Referenced by DownloadManager(), and DownloadItem::getFileName().
setRemovePolicy()
void DownloadManager::setRemovePolicy (RemovePolicy policy)
Definition at line 676 of file downloadmanager.cpp.
 {
     if (policy == m_removePolicy)
         return;
     m_removePolicy = policy;
     m_autoSaver->changeOccurred();
 }
References AutoSaver::changeOccurred(), m_autoSaver, and m_removePolicy.
timeString()
QString DownloadManager::timeString (double timeRemaining) static
Definition at line 779 of file downloadmanager.cpp.
 {
     QString remaining;
     if (timeRemaining > 60) {
         timeRemaining = timeRemaining / 60;
         timeRemaining = floor(timeRemaining);
         remaining = tr("%n minutes remaining", "", int(timeRemaining));
     }
     else {
         timeRemaining = floor(timeRemaining);
         remaining = tr("%n seconds remaining", "", int(timeRemaining));
     }
     return remaining;
 }
Referenced by DownloadItem::updateInfoLabel().
updateActiveItemCount()
void DownloadManager::updateActiveItemCount () private
Definition at line 610 of file downloadmanager.cpp.
 {
     int acCount = activeDownloads();
     if (acCount > 0) {
         setWindowTitle(QApplication::translate("DownloadDialog", "Downloading %1", 0).arg(acCount));
     } else {
         setWindowTitle(QApplication::translate("DownloadDialog", "Downloads", 0));
     }
 }
References activeDownloads().
Referenced by addItem(), cleanup(), finished(), and load().
updateItemCount()
void DownloadManager::updateItemCount () private
Definition at line 761 of file downloadmanager.cpp.
 {
     int count = m_downloads.count();
     itemCount->setText(tr("%n Download(s)", "", count));
 }
References m_downloads.
Referenced by addItem(), cleanup(), and DownloadModel::removeRows().
updateRow [1/2]
void DownloadManager::updateRow () private slot
Definition at line 629 of file downloadmanager.cpp.
 {
     if (DownloadItem *item = qobject_cast<DownloadItem*>(sender()))
         updateRow(item);
 }
Referenced by addItem().
updateRow [2/2]
void DownloadManager::updateRow (DownloadItem * item) private slot
Definition at line 635 of file downloadmanager.cpp.
 {
     int row = m_downloads.indexOf(item);
     if (-1 == row)
         return;
     if (!m_iconProvider)
         m_iconProvider = new QFileIconProvider();
     QIcon icon = m_iconProvider->icon(item->m_output.fileName());
     if (icon.isNull())
         icon = style()->standardIcon(QStyle::SP_FileIcon);
     item->fileIcon->setPixmap(icon.pixmap(48, 48));
     int oldHeight = downloadsView->rowHeight(row);
     downloadsView->setRowHeight(row, qMax(oldHeight, item->minimumSizeHint().height()));
     bool remove = false;
     /*
     TODO: Fix for Private Browsing
     QWebEngineSettings *globalSettings = QWebEngineSettings::globalSettings();
     if (!item->downloading()
         && globalSettings->testAttribute(QWebEngineSettings::PrivateBrowsingEnabled))
     */
     if (!item->downloading())
         remove = true;
     if (item->downloadedSuccessfully()
             && removePolicy() == DownloadManager::SuccessFullDownload) {
         remove = true;
     }
     if (remove)
         m_model->removeRow(row);
     cleanupButton->setEnabled(m_downloads.count() - activeDownloads() > 0);
 }
References activeDownloads(), DownloadItem::downloadedSuccessfully(), DownloadItem::downloading(), m_downloads, m_iconProvider, m_model, DownloadItem::m_output, removePolicy, and SuccessFullDownload.
Friends And Related Function Documentation
DownloadModel
friend class DownloadModel friend
Definition at line 194 of file downloadmanager.h.
Member Data Documentation
m_autoSaver
AutoSaver* DownloadManager::m_autoSaver private
Definition at line 186 of file downloadmanager.h.
Referenced by cleanup(), DownloadModel::removeRows(), setRemovePolicy(), and ~DownloadManager().
m_downloadDirectory
QString DownloadManager::m_downloadDirectory private
Definition at line 192 of file downloadmanager.h.
Referenced by downloadDirectory(), and setDownloadDirectory().
m_downloads
QList<DownloadItem*> DownloadManager::m_downloads private
Definition at line 190 of file downloadmanager.h.
Referenced by activeDownloads(), addItem(), cleanup(), DownloadModel::data(), DownloadModel::flags(), load(), DownloadModel::mimeData(), DownloadModel::removeRows(), DownloadModel::rowCount(), save(), updateItemCount(), and updateRow().
m_iconProvider
QFileIconProvider* DownloadManager::m_iconProvider private
Definition at line 189 of file downloadmanager.h.
Referenced by cleanup(), updateRow(), and ~DownloadManager().
m_manager
QNetworkAccessManager* DownloadManager::m_manager private
Definition at line 188 of file downloadmanager.h.
Referenced by download().
m_model
DownloadModel* DownloadManager::m_model private
Definition at line 187 of file downloadmanager.h.
Referenced by addItem(), cleanup(), DownloadManager(), and updateRow().
m_removePolicy
RemovePolicy DownloadManager::m_removePolicy private
Definition at line 191 of file downloadmanager.h.
Referenced by load(), removePolicy(), save(), and setRemovePolicy().
Property Documentation
removePolicy
RemovePolicy DownloadManager::removePolicy read write
Definition at line 168 of file downloadmanager.h.
Referenced by updateRow().
The documentation for this class was generated from the following files:
src/downloadmanager.h
src/downloadmanager.cpp