Endorphin: WebViewSearch Class Reference
WebViewSearch Class Reference
#include <webviewsearch.h>
Public Slots
void findNext ()
void findPrevious ()
void highlightAll ()
Public Slots inherited from SearchBar
void animateHide ()
void clear ()
void showFind ()
virtual void findNext ()=0
virtual void findPrevious ()=0
Public Member Functions
WebViewSearch (QWebEngineView *webView, QWidget *parent=nullptr)
Public Member Functions inherited from SearchBar
SearchBar (QWidget *parent=nullptr)
void setSearchObject (QObject *object)
QObject * searchObject () const
Private Member Functions
void find (QWebEnginePage::FindFlags flags)
QWebEngineView * webView () const
Additional Inherited Members
Protected Member Functions inherited from SearchBar
void resizeEvent (QResizeEvent *event)
Protected Attributes inherited from SearchBar
Ui_SearchBanner ui
Detailed Description
Definition at line 31 of file webviewsearch.h.
Constructor & Destructor Documentation
WebViewSearch()
WebViewSearch::WebViewSearch (QWebEngineView * webView, QWidget * parent = nullptr)
Definition at line 30 of file webviewsearch.cpp.
     : SearchBar(parent)
 {
     setSearchObject(webView);
     ui.highlightAllButton->setVisible(true);
     connect(ui.highlightAllButton, SIGNAL(toggled(bool)),
             this, SLOT(highlightAll()));
     connect(ui.searchLineEdit, SIGNAL(textEdited(const QString &)),
             this, SLOT(highlightAll()));
 }
References highlightAll(), SearchBar::setSearchObject(), SearchBar::ui, and webView().
Member Function Documentation
find()
void WebViewSearch::find (QWebEnginePage::FindFlags flags) private
Definition at line 61 of file webviewsearch.cpp.
 {
     QString searchString = ui.searchLineEdit->text();
     if (!searchObject() || searchString.isEmpty())
         return;
     QString infoString;
     //if (!webView()->findText(searchString, flags))
     //infoString = tr("Not Found");
     ui.searchInfo->setText(infoString);
 }
References SearchBar::searchObject(), and SearchBar::ui.
Referenced by findNext(), and findPrevious().
findNext
void WebViewSearch::findNext () slot
Definition at line 41 of file webviewsearch.cpp.
 {
     find(nullptr);
 }
References find().
Referenced by BrowserMainWindow::editFindNext().
findPrevious
void WebViewSearch::findPrevious () slot
Definition at line 46 of file webviewsearch.cpp.
 {
     find(QWebEnginePage::FindBackward);
 }
References find().
Referenced by BrowserMainWindow::editFindPrevious().
highlightAll
void WebViewSearch::highlightAll () slot
Definition at line 51 of file webviewsearch.cpp.
 {
     webView()->findText(QString(), nullptr);
     /*
         if (ui.highlightAllButton->isChecked())
             find(QWebEnginePage::HighlightAllOccurrences);
     */
 }
References webView().
Referenced by WebViewSearch().
webView()
QWebEngineView * WebViewSearch::webView () const private
Definition at line 72 of file webviewsearch.cpp.
 {
     return qobject_cast<QWebEngineView*>(searchObject());
 }
References SearchBar::searchObject().
Referenced by highlightAll(), and WebViewSearch().
The documentation for this class was generated from the following files:
src/webviewsearch.h
src/webviewsearch.cpp