Endorphin: WebActionMapper Class Reference
WebActionMapper Class Reference
#include <webactionmapper.h>
Public Member Functions
WebActionMapper (QAction *root, QWebEnginePage::WebAction webAction, QObject *parent)
QWebEnginePage::WebAction webAction () const
void addChild (QAction *action)
void updateCurrent (QWebEnginePage *currentParent)
Private Slots
void rootTriggered ()
void childChanged ()
void rootDestroyed ()
void currentDestroyed ()
Private Attributes
QWebEnginePage * m_currentParent
QAction * m_root
QWebEnginePage::WebAction m_webAction
Detailed Description
A proxy object that connects a single browser action to one child webpage action at a time.
Example usage: used to keep the main window stop action in sync with the current tabs webview's stop action.
Definition at line 79 of file webactionmapper.h.
Constructor & Destructor Documentation
WebActionMapper()
WebActionMapper::WebActionMapper (QAction * root, QWebEnginePage::WebAction webAction, QObject * parent)
Definition at line 67 of file webactionmapper.cpp.
     : QObject(parent)
     , m_currentParent(nullptr)
     , m_root(root)
     , m_webAction(webAction)
 {
     if (!m_root)
         return;
     connect(m_root, SIGNAL(triggered()), this, SLOT(rootTriggered()));
     connect(root, SIGNAL(destroyed(QObject *)), this, SLOT(rootDestroyed()));
     root->setEnabled(false);
 }
References m_root, rootDestroyed(), and rootTriggered().
Member Function Documentation
addChild()
void WebActionMapper::addChild (QAction * action)
Definition at line 90 of file webactionmapper.cpp.
 {
     if (!action)
         return;
     connect(action, SIGNAL(changed()), this, SLOT(childChanged()));
 }
References childChanged().
Referenced by TabWidget::makeNewTab().
childChanged
void WebActionMapper::childChanged () private slot
Definition at line 110 of file webactionmapper.cpp.
 {
     if (QAction *source = qobject_cast<QAction*>(sender())) {
         if (m_root
                 && m_currentParent
                 && source->parent() == m_currentParent) {
             m_root->setChecked(source->isChecked());
             m_root->setEnabled(source->isEnabled());
         }
     }
 }
References m_currentParent, and m_root.
Referenced by addChild().
currentDestroyed
void WebActionMapper::currentDestroyed () private slot
Definition at line 85 of file webactionmapper.cpp.
 {
     updateCurrent(nullptr);
 }
References updateCurrent().
Referenced by updateCurrent().
rootDestroyed
void WebActionMapper::rootDestroyed () private slot
Definition at line 80 of file webactionmapper.cpp.
 {
     m_root = nullptr;
 }
References m_root.
Referenced by WebActionMapper().
rootTriggered
void WebActionMapper::rootTriggered () private slot
Definition at line 102 of file webactionmapper.cpp.
 {
     if (m_currentParent) {
         QAction *gotoAction = m_currentParent->action(m_webAction);
         gotoAction->trigger();
     }
 }
References m_currentParent, and m_webAction.
Referenced by WebActionMapper().
updateCurrent()
void WebActionMapper::updateCurrent (QWebEnginePage * currentParent)
Definition at line 122 of file webactionmapper.cpp.
 {
     if (m_currentParent)
         disconnect(m_currentParent, SIGNAL(destroyed(QObject *)),
                    this, SLOT(currentDestroyed()));
     m_currentParent = currentParent;
     if (!m_root)
         return;
     if (!m_currentParent) {
         m_root->setEnabled(false);
         m_root->setChecked(false);
         return;
     }
     QAction *source = m_currentParent->action(m_webAction);
     if (!source)
         return;
     m_root->setChecked(source->isChecked());
     m_root->setEnabled(source->isEnabled());
     connect(m_currentParent, SIGNAL(destroyed(QObject *)),
             this, SLOT(currentDestroyed()));
 }
References currentDestroyed(), m_currentParent, m_root, and m_webAction.
Referenced by TabWidget::currentChanged(), and currentDestroyed().
webAction()
QWebEnginePage::WebAction WebActionMapper::webAction () const
Definition at line 97 of file webactionmapper.cpp.
 {
     return m_webAction;
 }
References m_webAction.
Referenced by TabWidget::makeNewTab().
Member Data Documentation
m_currentParent
QWebEnginePage* WebActionMapper::m_currentParent private
Definition at line 96 of file webactionmapper.h.
Referenced by childChanged(), rootTriggered(), and updateCurrent().
m_root
QAction* WebActionMapper::m_root private
Definition at line 97 of file webactionmapper.h.
Referenced by childChanged(), rootDestroyed(), updateCurrent(), and WebActionMapper().
m_webAction
QWebEnginePage::WebAction WebActionMapper::m_webAction private
Definition at line 98 of file webactionmapper.h.
Referenced by rootTriggered(), updateCurrent(), and webAction().
The documentation for this class was generated from the following files:
src/webactionmapper.h
src/webactionmapper.cpp